#include "version_autogenerated.h"
#include "cpu_config.h"
#include "stdio.h"
#include "gxhwlib_registers.h"

static void USB_SetSuspendM(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<26);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) &= ~(1<<26);
}

static void USB_ClrSuspendM(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<26);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) |= (1<<26);
}

static void USB_SetPhyReset(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<12);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<28);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) |= (1<<28);
}

static void USB_ClrPhyReset(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<12);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<28);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) &= ~(1<<28);
}

/* usb.c */
void USB_Init(void)
{

#if 0	//will delete later
	DTO_Config(12, 10845877);

	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<4)|(1<<5);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL2) |= 1 | (1<<1) | (1<<2) | (1<<3) | (1<<4) | (1<<5);

	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB_CONFIG)  |= (1<<25) | (1<<31) | (0x20<<8) | (0x20<<20) | (0x20<<26) | (0xf<<16);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB3_CONFIG) |= (1<<25) | (0x20<<20);
#endif

	// usb
	//DTO_Config(4, 0x091ab875); //108
	//DTO_Config(12, 0x0471C71C);
	DTO_Config(12, 0xe38e38);	//12M
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<0); //usb phy
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<1); //usb mac
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x1<<5); //usb 48M
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) |= (0x1<<5); //usb 48M
	//clock_usb_12m_div_load_en
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x1<<4); //usb 12M
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) |= (0x1<<4); //usb 12M
	//48 source
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<4);
	//12source
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) &= ~(1<<5);	//select vpu clk from xtal

	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB_CONFIG)  |= (1<<25) | (1<<31) | (0x20<<8) | (0x20<<20) | (0x20<<26) | (0xf<<16);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB3_CONFIG) |= (1<<25) | (0x20<<20);

	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();
	USB_ClrSuspendM();
	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();

}

static struct pll_dto {
	unsigned int dto;
	unsigned int div;
	unsigned int value;
} dto_table[] = {
	{1  , 0x06666666 , 1 << 1} ,  //audio i2s
	{2  , 0x06666666 , 1 << 2} ,  //audio spdif
	{7  , 0x08000000 , 1 << 16} ,  // GA		108M
	{6  , 0x0aaaaaaa , 1 << 15} ,  // Audio decoder
#if (defined CONFIG_ENABLE_GX_OTP) && (defined ENABLE_BOOT_TOOL)
	// do nothing
#else
	{8  , 0xcd097B4 , 1 << 17} ,  // DemuxSys
#endif
	{9  , 0x8000000 , 1 << 18} ,  // DemuxStc	108M
	{3  , 0x08000000 , 1 << 12} ,  // Video	108M
	{4  , 0x08000000 , 1 << 13} ,  // JPEG	108M
	{10 , 0x2000000 , 1 << 19} ,  // APB2_0
};

/* only for hardware usb test */
void EHCI_Test(void)
{
#define EHCI_OPBASE	(REG_BASE_USB_EHCI+0x10)

#define EHCI_OPREG_USBCMD		(EHCI_OPBASE+0x0)
#define EHCI_OPREG_USBSTS		(EHCI_OPBASE+0x4)
#define EHCI_OPREG_USBINTR		(EHCI_OPBASE+0x8)
#define EHCI_OPREG_FRINDEX		(EHCI_OPBASE+0xc)
#define EHCI_OPREG_CTRLDSSEGMENT	(EHCI_OPBASE+0x10)
#define EHCI_OPREG_PERIODICLISTBASE	(EHCI_OPBASE+0x14)
#define EHCI_OPREG_ASYNCLISTADDR	(EHCI_OPBASE+0x18)
#define EHCI_OPREG_CONFIGFLAG		(EHCI_OPBASE+0x40)
#define EHCI_OPREG_PORTSC1		(EHCI_OPBASE+0x44)
#define EHCI_OPREG_PORTSC2		(EHCI_OPBASE+0x48)
#define EHCI_OPREG_PORTSC3		(EHCI_OPBASE+0x4c)
	printf("enter echi test, hardware engineer can test after this printf.\n");
	*(volatile unsigned int *)(EHCI_OPREG_USBCMD) &= ~((1<<5)|(1<<4));
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC1) |= (1<<7);
	*(volatile unsigned int *)(EHCI_OPREG_USBCMD) &= ~0x1;	//ehci stop
	while(((*(volatile unsigned int *)(EHCI_OPREG_USBSTS)) & (1<<12)) == 0);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC1) |= (4<<16);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC2) |= (4<<16);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC3) |= (4<<16);
	while(1);
}

void close_macrovision(void)
{
	*(volatile unsigned int*)(MACROVISION_CTRL0) = 0;
	*(volatile unsigned int*)(MACROVISION_CTRL1) = 0;
}

void gx_setup_pll_full_controller(void)
{
	int i;

	//clock auido
	//clock audio clock_audio_lodec
	// even div
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<31);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (1<<31); //rst
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x1f<<24);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (0x8<<24); //div
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (1<<30); //load end
	//   source
	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<0);

	/* module dto init */
	for (i=0; i < sizeof(dto_table) / sizeof(struct pll_dto); i++) {
		if (dto_table[i].dto != 0)
			DTO_Config(dto_table[i].dto, dto_table[i].div);
		*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL) |= dto_table[i].value;
	}

	//*****************ts
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<12);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<13);

	// begin the video piex clok
	//////pixel CLOCK
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<8);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (1<<8); //rst
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x3f<<0);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (0x1e<<0); //div
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<7);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (1<<7); //load en
	// div clock
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x3<<9);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (0x1<<9); //div
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<11);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG) |= (1<<11); //rst

	//video dac power down
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_VPU_DAC_POWER_CTRL) = 0x1f;

	//source
#ifdef CONFIG_24M_XTAL
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<5); //VPU clock from DTO
#else
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) &= ~(1<<5); //VPU clock from xtal
#endif
	//clock da
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<6);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<6);

	// dvbc clock
	//div15 clock
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0xff<<8); //ratio
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) |= (0xe7<<8); //ratio  e7
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x1<<16); //rst
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) |= (0x1<<16); //rst clr
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<27); //dvbc clk sel, 0:test clk  1:DTO
	 //adc clock select
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<17);// ADC clk,div2
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) &= ~(1<<18);//ADC clok sel, 0:DTO  1: xtal
//	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<18); //ADC clok sel, 0:DTO  1: xtal
	//set adc cfig
	*(volatile unsigned int *)(CONFIG_BASE+CONFIG_ADC) = (4<<8)|(3<<11)|(1<<4)|(1<<6)|(1<<5)|(0<<14);
	*(volatile unsigned int *)(CONFIG_BASE+CONFIG_ADC) = (4<<8)|(3<<11)|(1<<4)|(1<<6)|(1<<5)|(0<<14)|3;

	close_macrovision();
	USB_Init();
#ifdef CONFIG_USB_EYE_DIAGRAM_TEST
	EHCI_Test();
#endif
}

