#include "version_autogenerated.h"
#include "cpu_config.h"
#include "databahn.h"

/* denali_config.c / h5tq2g63bfr_h9.c */
extern unsigned int DENALI_CONFIG_CTL[155];
extern unsigned int DENALI_CONFIG_PHY[26];
extern unsigned char DENALI_PHASE_ADJUST[6];
extern void ddr_config_patch(void);
extern void serial_put_no_mmu(char);

#define DATABAHN_REG_FULL(i, name, addr, offset, width, v) \
	{DATABAHN_REG_AXI##i##name##addr,  DATABAHN_REG_AXI##i##name##offset,  DATABAHN_REG_AXI##i##name##width, v}

#define DATABAHN_REG(i, name, v) \
	DATABAHN_REG_FULL(i, name, _ADDR, _OFFSET, _WIDTH, v)

static struct reg_param param_table[] = {
	DATABAHN_REG(0 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(1 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(2 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(3 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(4 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(5 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(6 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(7 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(8 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(9 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(10, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(11, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(12, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(13, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(14, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(15, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),

	DATABAHN_REG(0 , _R_PRIORITY, 0x9),	//cpu
	DATABAHN_REG(1 , _R_PRIORITY, 0x6),	//pp
	DATABAHN_REG(2 , _R_PRIORITY, 0x9),	//ga/jpeg
	DATABAHN_REG(3 , _R_PRIORITY, 0x8),
	DATABAHN_REG(4 , _R_PRIORITY, 0x8),
	DATABAHN_REG(5 , _R_PRIORITY, 0x4),	//vpu
	DATABAHN_REG(6 , _R_PRIORITY, 0x3),	//demux
	DATABAHN_REG(7 , _R_PRIORITY, 0x8),
	DATABAHN_REG(8 , _R_PRIORITY, 0x3),	//audio
	DATABAHN_REG(9 , _R_PRIORITY, 0x5),	//video
	DATABAHN_REG(10, _R_PRIORITY, 0x3),	//apu
	DATABAHN_REG(11, _R_PRIORITY, 0x8),	//nfc/mac/secure
	DATABAHN_REG(12, _R_PRIORITY, 0x8),
	DATABAHN_REG(13, _R_PRIORITY, 0x8),
	DATABAHN_REG(14, _R_PRIORITY, 0x8),	//usb
	DATABAHN_REG(15, _R_PRIORITY, 0x8),

	DATABAHN_REG(0 , _W_PRIORITY, 0x9),
	DATABAHN_REG(1 , _W_PRIORITY, 0x6),
	DATABAHN_REG(2 , _W_PRIORITY, 0x9),
	DATABAHN_REG(3 , _W_PRIORITY, 0x8),
	DATABAHN_REG(4 , _W_PRIORITY, 0x8),
	DATABAHN_REG(5 , _W_PRIORITY, 0x4),	//vpu
	DATABAHN_REG(6 , _W_PRIORITY, 0x3),
	DATABAHN_REG(7 , _W_PRIORITY, 0x8),
	DATABAHN_REG(8 , _W_PRIORITY, 0x3),
	DATABAHN_REG(9 , _W_PRIORITY, 0x5),
	DATABAHN_REG(10, _W_PRIORITY, 0x3),
	DATABAHN_REG(11, _W_PRIORITY, 0x8),
	DATABAHN_REG(12, _W_PRIORITY, 0x8),
	DATABAHN_REG(13, _W_PRIORITY, 0x8),
	DATABAHN_REG(14, _W_PRIORITY, 0x8),
	DATABAHN_REG(15, _W_PRIORITY, 0x8),

	{DATABAHN_REG_SWAP_EN_ADDR, DATABAHN_REG_SWAP_EN_OFFSET, DATABAHN_REG_SWAP_EN_WIDTH, 0x0},

	// Lvl
	{DATABAHN_REG_WRLVL_REG_EN_ADDR, DATABAHN_REG_WRLVL_REG_EN_OFFSET, DATABAHN_REG_WRLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_REG_EN_ADDR, DATABAHN_REG_RDLVL_REG_EN_OFFSET, DATABAHN_REG_RDLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_GATE_EN_ADDR, DATABAHN_REG_RDLVL_GATE_EN_OFFSET, DATABAHN_REG_RDLVL_GATE_EN_WIDTH, 1},
	
	// Databahn start enable
	//{DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1}
};

/* routine.c */
void SetRegisterField(unsigned int reg, unsigned int offset, unsigned int width, unsigned int value)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int value_masked;

	original = *(volatile unsigned int *)reg;

	if (width == 32)
		mask = 0xffffffff;
	else
		mask = (1 << width) - 1;
	value_masked = value & mask;
	result = (original & (~(mask << offset))) | (value_masked << offset);

	*(volatile unsigned int *)reg = result;
}

unsigned int GetRegisterField(unsigned int reg, unsigned int offset, unsigned int width)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int mask_shifted;

	original = *(volatile unsigned int *)reg;
	if(width==32)
		mask = 0xffffffff;
	else
		mask = (1 << width)-1;
	mask_shifted = mask << offset;
	result = (original & mask_shifted) >> offset;

	return result;
}

/* databahn.c */
void Databahn_Init(void)
{
	volatile unsigned int i;

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<25);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT_NORM) &= ~((1<<27)|(1<<28));
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DENALI_CONFIG0)=0xffffffff;

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) |= (0x1);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) &= ~(0x1);

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(1<<15); //for pad_oe_e.low power
	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(1<<15);

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x3<<27);//calicalue mode is set vlaue
        *(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(0x2<<27);//calicalue mode is set vlaue
        *(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x1);//calicalue mode is set vlaue
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x1F<<1);//pdovrd
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(0x0f<<1);//pdovrd
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x1F<<6);//ndovrd
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(0x0f<<6);//ndovrd

	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0xF<<11);//PWD14:11
	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(0xF<<11);//PWD14:11

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(0x3<<16);//ODTEN17:16


	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x7<<21);//RON26:21
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x7<<24);//RON26:21

	ddr_config_patch();

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)&=~(0x1<<31);//LPDDR2
	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)|=(0x1<<31);//LPDDR2

#ifdef CONFIG_DDR3
	*(volatile unsigned int*)(0x30a124)|=(0x1<<22);//LPDDR2
#endif

	for(i = 0;i < sizeof(DENALI_CONFIG_CTL)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg(i) = DENALI_CONFIG_CTL[i];

	for(i = 0; i < sizeof(DENALI_CONFIG_PHY)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg((i + 256)) = DENALI_CONFIG_PHY[i];

	Databahn_Config();

	while(!Databahn_isReady());
}

void Databahn_SetParameters(struct reg_param *regs, int count) {
	int i;

	for (i=0; i < count; i++)
		SetRegisterField(Databahn_Reg(regs[i].reg), regs[i].offset, regs[i].width, regs[i].value);
}

void Databahn_Config(void)
{

	Databahn_SetParameters(param_table, sizeof(param_table) / sizeof(struct reg_param));

	// Databahn start enable
	SetRegisterField(Databahn_Reg(DATABAHN_REG_START_ADDR), DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1);
}

unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width)
{
	return GetRegisterField(Databahn_Reg(reg), offset, width);
}

unsigned int Databahn_GetIntStatus(void)
{
	return Databahn_GetParameter(DATABAHN_REG_INT_STATUS_ADDR, DATABAHN_REG_INT_STATUS_OFFSET, DATABAHN_REG_INT_STATUS_WIDTH);
}

unsigned int Databahn_isReady(void)
{
	return (Databahn_GetIntStatus() & 0x20) ? 1 : 0;
}

void Databahn_Init_Patch(void)
{
	unsigned char best_madj;
	unsigned char best_adj;
	
	best_madj = DENALI_PHASE_ADJUST[0];
	best_adj = DENALI_PHASE_ADJUST[1];
	*(volatile unsigned int *)Databahn_Reg((3+256)) = (unsigned int)best_madj;
	*(volatile unsigned int *)Databahn_Reg(81) = (DENALI_CONFIG_CTL[81]&0xffff0000)|(best_adj<<8)|best_adj;	// Slice0
	best_madj = DENALI_PHASE_ADJUST[2];
	best_adj = DENALI_PHASE_ADJUST[3];
	*(volatile unsigned int *)Databahn_Reg((9+256)) = (unsigned int)best_madj;
	*(volatile unsigned int *)Databahn_Reg(84) = (DENALI_CONFIG_CTL[81]&0xff0000ff)|(best_adj<<16)|(best_adj<<8);// Slice1

	*(volatile unsigned int *)Databahn_Reg(74) &= 0xff0000ff;
	*(volatile unsigned int *)Databahn_Reg(74) |= (DENALI_PHASE_ADJUST[4]<<8);
	*(volatile unsigned int *)Databahn_Reg(75) &= 0xffff0000;
	*(volatile unsigned int *)Databahn_Reg(75) |= DENALI_PHASE_ADJUST[5];
}

/* gx3201_sdram.c */
void gx_setup_sdram_controller(void)
{
	Databahn_Init();

	//if it will be configed by users, open it & config it from board-init.c
	//Databahn_Init_Patch();
	serial_put_no_mmu('N');
}

