#ifndef __CONFIG_H__
#define __CONFIG_H__

#ifdef NO_OS
#include "version_autogenerated.h"
#endif

#undef CONFIG_ENABLE_MINIFS

#include "autoconf.h"

#ifdef NO_OS

#ifdef CONFIG_GX3113C
#define CHIP gx3113c
#endif

#ifdef CONFIG_GX3211
#define CHIP gx3211
#endif

#ifdef CONFIG_GX3201
#define CHIP gx3201
#endif

#ifdef CONFIG_GX6605S
#define CHIP gx6605s
#endif

#ifdef CONFIG_SIRIUS
#define CHIP sirius
#endif

#ifdef CONFIG_TAURUS
#define CHIP taurus
#endif

#ifdef CONFIG_GEMINI
#define CHIP gemini
#endif

#ifdef CONFIG_CYGNUS
#define CHIP cygnus
#endif

#ifdef CONFIG_CANOPUS
#define CHIP canopus
#endif

#ifdef CONFIG_VEGA
#define CHIP vega
#endif

#ifdef CONFIG_SCORPIO
#define CHIP scorpio
#endif

#ifdef CONFIG_SCORPIO_TAURUS
#define CHIP scorpio_taurus
#endif

#endif /* NO_OS */

#endif

