#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__

#define CANOPUS

#define THEME_CLASSIC_BLUE 1
#define THEME_CLASSIC_DARK 0
#define THEME_CLASSIC_PURPLE 0
#define THEME_GRID_PURPLE 0
#define THEME_SKY_BLUE 0
#define APP_XRES  1280
#define APP_YRES  720
#define MINI_MEM_SUPPORT 0
#define FM_SUPPORT 0
#define LNB_SHORT_DETECT_SUPPORT 0
#define LEARN_RCU_SUPPORT 0
#define FM_FREQ_NAME_SUPPORT 0
#define SHUTDOWN_MODE_SUPPORT 0
#define START_CHANNEL_SUPPORT 0
#ifndef APP_LOG_LEVEL
#define APP_LOG_LEVEL APP_LOG_ERROR
#endif

//XTAL Configure
//Demod DVBS
#define DEMOD_DVB_S 1
#define DOUBLE_S2_SUPPORT 1

//Demod DVBT
#define DEMOD_DVB_T 0

//Demod DVBC
#define DEMOD_DVB_C 0

//Demod DTMB
#define DEMOD_DTMB 0

//Demod ISDBT
#define DEMOD_ISDBT 0

//Demod COMBO
#define DEMOD_DVB_COMBO 0

#define DEMOD_AUTO_ADAPT_SUPPORT 0
#define NDEMOD_WITH_1TUNER 0

#define OTT_SUPPORT 0

#define TUNER_AUTO_ADAPT_SUPPORT 0
/***** DVBS/S2 Tuner *****/
#define TUNER_AV2018_SUPPORT 0
#define TUNER_RDA5815M_SUPPORT 1
#define TUNER_AV2020_SUPPORT 0
#define TUNER_RT720_SUPPORT 0
#define TUNER_R848_DVBS_SUPPORT 0
#define TUNER_SHARP7306_SUPPORT 0
#define UART_SUPPORT 0
/***** DVBT/T2 Tuner *****/
#define TUNER_MXL608_DVBT_SUPPORT 0
#define TUNER_R836_DVBT_SUPPORT 0
#define TUNER_R848_DVBT_SUPPORT 0
#define TUNER_R910_DVBT_SUPPORT 0
#define TUNER_SI2141_DVBT_SUPPORT 0
#define TUNER_ATBM253_DVBT_SUPPORT 0
#define TUNER_RDA5160_DVBT_SUPPORT 0
/***** DVBC Tuner *****/
#define TUNER_MXL608_DVBC_SUPPORT 0
#define TUNER_TDA18250_SUPPORT 0
#define TUNER_TDA18250A_SUPPORT 0
#define TUNER_TDA18273_DVBC_SUPPORT 0
#define TUNER_R836_DVBC_SUPPORT 0
#define TUNER_R848_DVBC_SUPPORT 0
#define TUNER_R910_DVBC_SUPPORT 0
#define TUNER_SI2141_DVBC_SUPPORT 0
#define TUNER_ATBM2040_DVBC_SUPPORT 0
#define TUNER_ATBM253_DVBC_SUPPORT 0
#define TUNER_RDA5160_DVBC_SUPPORT 0
/***** DTMB Tuner *****/
#define TUNER_MXL608_DTMB_SUPPORT 0
#define TUNER_TDA18273_DTMB_SUPPORT 0
#define TUNER_R836_DTMB_SUPPORT 0
#define TUNER_R848_DTMB_SUPPORT 0
#define TUNER_SI2141_DTMB_SUPPORT 0
#define TUNER_ATBM2030_DTMB_SUPPORT 0
#define TUNER_ATBM2040_DTMB_SUPPORT 0
#define TUNER_ATBM253_DTMB_SUPPORT 0
#define TUNER_RDA5160_DTMB_SUPPORT 0
/***** ISDBT Tuner *****/
#define TUNER_MXL608_ISDBT_SUPPORT 0
#define TUNER_MXL683_ISDBT_SUPPORT 0
#define TUNER_TS6011_SUPPORT 0
#define TUNER_M3031_SUPPORT 0
#define TUNER_R858_DVBC_1ST_SUPPORT 0
#define TUNER_R858_DVBC_2ND_SUPPORT 0

/***** Secure Module *****/
#define SECURE_PVR_SUPPORT 0
#define SECURE_FULL_SUPPORT 1
#define SECURE_RNG_SUPPORT 0
#define SECURE_FIREWALL_SUPPORT 0
#define SECURE_DGST_SUPPORT 0
#define SECURE_SCI_SUPPORT 0
#define SECURE_TEE_SUPPORT 0
#define SECURE_IRDETO_SUPPORT 0
#define SECURE_ACPU_SUPPORT 0
#define SECURE_SCPU_SUPPORT 0
#define SECURE_DMA_SUPPORT 0

#define WORK_PATH "/dvb/"
#define VOICE_CONTROL_SUPPORT 0
#define SMART_VOLUME_SUPPORT 0
#define SMART_VOLUME_TEST_SUPPORT 0
#define ADVANCED_PRINT_SUPPORT 0
#define USB_TO_SERIAL_SUPPORT 0
#define USB_TEST_SUPPORT 0
#define RICHEPG_SUPPORT 0
#define PVR_RECORDING_LIST_STYLE 1
#define PVR_RECORDING_POSTER_STYLE 0
#define NETWORK_SUPPORT 1
#define ETH_SUPPORT 0
#define GPRS_SUPPORT 0
#define COMMON_VIEW_V2_SUPPORT 0
#define IPTV_EPG_PLAYBACK_SUPPORT 0
#define SAT2IP_SERVER_SUPPORT 0
#define SAT2IP_CONFIGURE_SUPPORT 0
#define DVB2IP_SERVER_SUPPORT 0
#define DVB2IP_SERVER_USE_STATIC_SCREEN 0
#define WIFI_SUPPORT 1
#define WIFI_SUPER_AP_SUPPORT 0
#define RNDIS_SUPPORT 0
#define MOD_3G_SUPPORT 1
#define PPPOE_SUPPORT 0
#define BLUETOOTH_SUPPORT 0
#define NETAPPS_SUPPORT 1
#define SOCKS5_SUPPORT 0
#define GET_NET_TIME_SUPPORT 0
#define PROGRAM_NETUP_SUPPORT 0
#define NET_AUDIO_SUPPORT 0
#define PLUGINSTORE_SUPPORT 0
#define PLUGINONLINE_SUPPORT 0
#define WEBLET_SUPPORT 0
#define WEBAPI_SUPPORT 0
#define NET_UPGRADE_SUPPORT 0
#define TRANSMISSION_SUPPORT 0
#define NET_SEARCH_SUPPORT 0
#define DVB_FILE_SEARCH_SUPPORT 0
#define DVB_SERVER_SEARCH_SUPPORT 0
#define SAT_FINDER_SUPPORT 0
#define DVB_CLOUD_SUPPORT 0
#define IPTV_LITE_SUPPORT 0
#define DLNADMR_SUPPORT 1
#define DLNADMP_SUPPORT 1
#define DLNASAT2IP_SUPPORT 1
#define DLNADMS_SUPPORT 1
#define MIRACAST_SUPPORT 0
#define SAMBA_SUPPORT 0
#define APPLETS_SUPPORT 0
#define APPLETS_AUTO_UPDATE_LIST_SUPPORT 0
#define APPLETS_BUILTIN_SUPPORT 0
#define APPLETS_FAV_SUPPORT 0
#define APPLETS_INSTALL_SUPPORT 0
#define APPLETS_RECENT_SUPPORT 0
#define VPN_SUPPORT 0

#define USB_ETH_SUPPORT 0
#define RECALL_LIST_SUPPORT 0
#define MULTIFEED_LIST_SUPPORT 0
#define AUTO_STANDBY_SUPPORT 0
#define NO_SIGNAL_AUTO_STANDBY_SUPPORT 0
#define UNICABLE_SUPPORT 0
#define NO_AVPROG_SAVE_SUPPORT 0
#define RESERVED_SERVICE_NOSAVE_SUPPORT 0
#define MULTISTREAM_SUPPORT 1
#define LNBF_SUPPORT 0
#define PDMX_SUPPORT 1
#define SUPER_BLIND_SUPPORT 1
#define FACTORY_TEST_SUPPORT 0
#define CVBS_TEST_SUPPORT 0
#define SYS_SETTING_SAVE_DIRECT 1
#define KEY_SCANCODE_SUPPORT 0
#define TMLIST_EPG_SUPPORT 1
#define LVLIST_EPG_SUPPORT 0
#define EPG_REALTIMER_GET_DETAIL_SUPPORT 0
#define USB_SAFELY_REMOVE_SUPPORT 0
#define QUICK_SWITCH_SUPPORT 0
#define UI_MIRROR_SUPPORT 0
#define APP_SHARPNESS_SUPPORT 0
#define APP_HUE_SUPPORT 0
#define APP_DEINTERLACE_SUPPORT 0
#define NO_SIGNAL_ALERT_TIP_SUPPORT 0
#define MERGE_DB_SUPPORT 0
#define TKGS_SUPPORT 0
#define CVBS_SCALE_SUPPORT 0
#define MTP_SUPPORT 0
#define PANEL_SETTING_SUPPORT 0
#define STANDBY_SHOW_TIME_SHPPORT 0
#define LONG_PASSWORD_SUPPORT 0
#define PSI_MODULE_SUPPORT 0
#define BOUQUET_SUPPORT 0
#define BAT_MISMATCH_TSID_SUPPORT 0
#define NIT_SUPPORT 0
#define SDT_SUPPORT 0
#define PAT_SUPPORT 0
#define PMT_UPDATE_SUPPORT 0
#define AUTO_UPDATE_SUPPORT 0
#define AUTO_UPDATE_ALL_VERSION_SUPPORT 0
#define AUTO_UPDATE_MISMATCH_TSID_SUPPORT 0
#define AUTO_UPDATE_PROPMT_SUPPORT 0
#define LCN_AUTO_UPDATE 0
#define OTHER_TS_UPDATE_SUPPORT 0
#define HDMI_HDCP_SUPPORT 0
#define MEDIA_SUBTITLE_SUPPORT 1
#define OSD_SUBTITLE_SUPPORT 0
#define SUBTITLE_DELAY_TIME 10

#define PVR_RECORD_TP_SUPPORT 1
#define INDEPEND_RECORD 0
#define NAND_FLASH_SUPPORT 0
#define SPI_NAND_SUPPORT 0
#define P_NAND_SUPPORT 0
#define NAND_YAFS_SUPPORT 0
#define NAND_UBIFS_SUPPORT 0
#define MULTIMEDIA_PREVIEW_SUPPORT 0
#define USB_MICROPHONE_SUPPORT 0
#define PLAYBACK_SPEED_SUPPORT 0
#define QR_POP_SUPPORT 0
#define RF_MODULATOR_SUPPORT 0
#define RF_RT500 0
#define RF_RT534 0
#define MENCENT_FREEE_SPACE 0
#define BOOT_AD_SUPPORT 0
#define BOOT_AD_USER_CONTROL_SUPPORT 0
#define AUDIO_DESCRIPTOR_SUPPORT 0
#define AUDIO_DESCRIPTOR_VOLUME_SET_SUPPORT 0
#define HDMI_CEC_SUPPORT 0
#define DOLBY_SUPPORT 0
#define AUDIO_LANG_QAA2OST_SUPPORT 0
#define HIGH_DYNAMIC_RANGE_SUPPORT 1
#define PVR_STANDBY_SUPPORT 0
#define PVR_STANDBY_TIP_SUPPORT 0
#define POWER_ON_CONTROL_SUPPORT 0
#define SEARCH_AUTO_SAVE_SUPPORT 0
#define SW_FILTER_SUPPORT 0
#define DVBC_TUNE_AUTO_SUPPORT 0
#define LCN_SUPPORT 0
#define LCN_CONFLICT_HANDLE_SUPPORT 0
#define SEARCH_SHOW_LCN_SUPPORT 0
#define LCN_VISIBLE_FLAG_SUPPORT 0
#define PRESET_PROG_INFO_CORRECT_SUPPORT 0
#define ADVANCE_BOOK_TIME 30

#define PARENTAL_LOCK_SUPPORT 0
#define GAME_ENABLE 0
#define SAT_LIST_MOVE_SORT_SUPPORT 0
#define TP_LIST_MOVE_SORT_SUPPORT 0
#define TTX_PRE_PROCESS_ENABLE 0
#define COLOR_16BIT_TTX_SUPPORT
#define AUTO_TEST_ENABLE 0
#define PCDEMO_TEST_ENABLE 0
#define DEMOD_INFO_SUPPORT 0
#define FLAC_SUPPORT 0
#define OGG_SUPPORT 0
#define FACE_DETECT_SUPPORT 0
#define PVR_PREVIEW_SUPPORT 0
#define OTA_SUPPORT 0
#define UPDATE_SUPPORT_FLAG 0
#define APP_MAIN_MENU_OBJ_SUPPORT 0
#define SKIN_SUPPORT 0
#define SKUSB_SUPPORT 0
#define OTA_BACKEND_POLL 0
#define KERNEL_SUPPORT_FLAG 1
#define CASCAM_SUPPORT 0

#define ARIBCC_SUPPORT 0
#define ATSCCC_SUPPORT 0

#define TURN_OVER_MODE 0
#define FONT_GB2312_TO_UTF8 0
#define LANG_ENGLISH "English",
#define OSD_LANG_ARABIC "Arabic",
#define OSD_LANG_RUSSIAN "Russian",
#define OSD_LANG_TURKISH "Turkish",
#define LANG_MAX 4

extern char *g_LangName[];

#define KB_LANG_ENGLISH "English",
#define KB_LANG_ARABIC "Arabic",
#define KB_LANG_RUSSIAN "Russian",
#define KB_LANG_TURKISH "Turkish",
#define KB_LANG_MAX 4

extern char *g_KB_LangName[];

enum TIME_SET_LANG_NAME {
  ITEM_ENGLISH = 0,
  ITEM_ARABIC,
  ITEM_RUSSIAN,
  ITEM_TURKISH,
  ITEM_BULGARAIN,
  ITEM_FARSI,
  ITEM_POLSKI,
  ITEM_PORTUGUESE,
  ITEM_SPANISH,
  ITEM_THAI,
  ITEM_UKRAINIAN,
  ITEM_VIETNAMESE,
  ITEM_LANGUAGE_TOTAL
};

#define BOOT_OTA_VER "V1.2.0.0"
#define LINUX_KERNEL_VER "V4.9"
#define PLATFORM_LIB_VER "V3.10.0"
#define HARDWARE_VER "GX6607H1_DUAL_GX1137_RDA5815M"
#define APP_VER "ORIGIN_6EA86B59B"
#define NETAPPS_VER "V1.2.0"
#define SOFEWARE_TIME "2026-06-05 18:01:26"
#define CA_SUPPORT 0
#define DUAL_CHANNEL_DESCRAMBLE_SUPPORT 0
#define ECM_SUPPORT 0
#define EMM_SUPPORT 0
#define EX_SHIFT_SUPPORT 0
#define CMM_SUPPORT 0

#define CI_SUPPORT 0

#define POP_DLG_POS_X 320
#define POP_DLG_POS_Y 150
#define POP_PASSWD_POS_X 400
#define POP_PASSWD_POS_Y 190
#define WND_TOP_USB_PRO_POS_X 1210
#define WND_TOP_USB_PRO_POS_Y 600
#define MM_BOOK_POS_X 0
#define MM_BOOK_POS_Y 0
#define MM_EDIT_BOOK_X 295
#define MM_EDIT_BOOK_Y 190
#define WND_CH_EDIT_POPDLG_POS_X 215
#define WND_CH_EDIT_POPDLG_POS_Y 220
#define WND_SORT_POS_X 390
#define WND_SORT_POS_Y 120
#define WND_FIND_KB_POS_X 410
#define WND_FIND_KB_POS_Y 100
#define WND_EPG_POP_POS_X 215
#define WND_EPG_POP_POS_Y 220
#define WND_VOL_POS_X 290
#define WND_VOL_POS_Y 400
#define WND_FREQ_POP_LIST_POS_X 0
#define WND_FREQ_POP_LIST_POS_Y 0
#define WND_DMR_POP_DLG_X 425
#define WND_DMR_POP_DLG_Y 220
#define WND_CH_LIST_PASSWD_POS_X 660
#define WND_CH_LIST_PASSWD_POS_Y 220
#define WND_OTA_POP_POS_X 400
#define WND_OTA_POP_POS_Y 190
#define WND_TKGS_UPGD_POP_POS_X 400
#define WND_TKGS_UPGD_POP_POS_Y 190
#define WND_KB_SET_POS_X 410
#define WND_KB_IN_POS_X 410
#define WND_KB_IN_POS_Y 108
#define WND_POP_OP_LIST_POS_X 458
#define WND_POP_OP_LIST_POS_Y 130
#define MAINMENU_POP_LIST_X 458
#define MAINMENU_POP_LIST_Y 130
#define WND_POP_TIP_POS_X 400
#define WND_POP_TIP_POS_Y 150
#define WND_FILE_LIST_POS_X 0
#define WND_FILE_LIST_POS_Y 0
#define WND_MV_OSD_SUBT_W 1180
#define WND_MV_OSD_SUBT_H 42
#define WND_MV_OSD_SUBT_MAX_H 42
#define WND_MV_OSD_SUBT_PIXEL_W 1280
#define WND_MV_OSD_SUBT_PIXEL_H 176
#define WND_MERGE_POP_POS_X 400
#define WND_MERGE_POP_POS_Y 190
#define NETAPP_SETTING_POP_LIST_X 460
#define NETAPP_SETTING_POP_LIST_Y 155
#define WND_SYSTEM_SETTING_POS_Y 0
#define WND_SUBSET_FILE_LIST_POS_X 458
#define WND_POP_QR_POS_X 880
#define WND_POP_QR_POS_Y 188
#define WND_NET_ASPECT_POS_X 950
#define WND_NET_ASPECT_POS_Y 500
#define WND_FACE_PROMPT_POS_X 1110
#define WND_FACE_PROMPT_POS_Y 200
/*color define*/
#define UI_OSD_TRANS (0x00ff00)
#define UI_GUI_TRANS (0xff00ff)
#define UI_SUBT_BG (0x0c0c0c)
#define UI_THEME_BPP (16)
#define XTREAM_SUPPORT
#define XTREAM_SERIES_SUPPORT
#define STALKER_SUPPORT
#define STALKER_SERIES_SUPPORT
#define IPTV_SUPPORT
#define FREEIPTV_SUPPORT

#endif
