#ifndef APP_MAIN_MENU_EX_API_H_20241230
#define APP_MAIN_MENU_EX_API_H_20241230

typedef enum
{
	APPUI_ENTRY_TV_CHANNEL    = 0,
	APPUI_ENTRY_RADIO_CHANNEL ,
	APPUI_ENTRY_DELETE_ALL    ,

	APPUI_ENTRY_TIME_SETTING  ,
	APPUI_ENTRY_TIMER_SETTING ,
	APPUI_ENTRY_LANGUAGE      ,
	APPUI_ENTRY_AV_SETTING    ,
	APPUI_ENTRY_LOCK_CONTROL  ,
	APPUI_ENTRY_OSD_SETTING   ,
	APPUI_ENTRY_COLOR_SETTING ,
	APPUI_ENTRY_NETWORK_SETTING ,
	APPUI_ENTRY_NETWORK ,
	APPUI_ENTRY_ADVANCED_SETTING ,

	APPUI_ENTRY_ANTENNA ,
	APPUI_ENTRY_POSITIONER ,
	APPUI_ENTRY_SAT_LIST ,
	APPUI_ENTRY_TP_LIST ,
	APPUI_ENTRY_DVBFINDER ,

	APPUI_ENTRY_SYSTEM_INFO ,
	APPUI_ENTRY_SOFTINFO ,
	APPUI_ENTRY_FACTORY_RESET ,
	APPUI_ENTRY_SOFTWARE_UPGRADE ,
	APPUI_ENTRY_SOFTUPGRADE ,
	APPUI_ENTRY_UPGRADE_BY_NET ,
	APPUI_ENTRY_SKIN ,
	APPUI_ENTRY_APPLETS ,
	APPUI_ENTRY_XTREAM ,
	APPUI_ENTRY_IPTV ,
	APPUI_ENTRY_STALKER ,

	APPUI_ENTRY_MEDIA_FILE ,
	APPUI_ENTRY_MEDIA_VIDEO ,
	APPUI_ENTRY_MEDIA_MUSIC ,
	APPUI_ENTRY_MEDIA_PIC ,
	APPUI_ENTRY_PVR_MEDIA ,
	APPUI_ENTRY_PVR_MANAGEMENT ,
	APPUI_ENTRY_MEDIA_PLAYER ,

	APPUI_ENTRY_POWER_ON_OFF ,
	APPUI_ENTRY_INTERNET ,
	APPUI_ENTRY_CHANNEL_EDIT ,
	APPUI_ENTRY_RPOGRAM_GUIDE ,
	APPUI_ENTRY_T2_TIME_SETTING ,
	APPUI_ENTRY_SLEEP ,
	APPUI_ENTRY_PLAY_TIMER_SETTING ,
	APPUI_ENTRY_RM_MODULATOR_SETTING ,
	APPUI_ENTRY_DVBT_LOCK_CONTROL ,
	APPUI_ENTRY_PARENTAL_GUIDANCE ,
	APPUI_ENTRY_DVBT_PARENTAL_GUIDANCE ,
	APPUI_ENTRY_T2_OSD_SETTING ,
	APPUI_ENTRY_SAT2IP_SETTING ,
	APPUI_ENTRY_DVB2IP_SETTING ,
	APPUI_ENTRY_VPN ,
	APPUI_ENTRY_PANEL_SETTING ,
	APPUI_ENTRY_T2_PANEL_SETTING ,
	APPUI_ENTRY_LCN_SETTING ,
	APPUI_ENTRY_CEC_SETTING ,
	APPUI_ENTRY_NET_SEARCH ,
	APPUI_ENTRY_TKGS ,

	APPUI_ENTRY_BLUETOOTH_SETTING ,
	APPUI_ENTRY_SINK ,

	APPUI_ENTRY_DVBT ,
	APPUI_ENTRY_ISDBT ,
	APPUI_ENTRY_DVBC ,
	APPUI_ENTRY_DVBC_AUTOSCAN ,
	APPUI_ENTRY_DVBC_MANUALSCAN ,
	APPUI_ENTRY_DVBC_FULLSCAN ,
	APPUI_ENTRY_DVBC_SETFRE ,
	APPUI_ENTRY_DVBT_AUTOSCAN ,
	APPUI_ENTRY_DVBT_MANUALSCAN ,
	APPUI_ENTRY_DVBT_MEDIA_CENTRE ,
	APPUI_ENTRY_MEDIA_CENTRE ,
	APPUI_ENTRY_DVBT_PVR_MANAGEMENT ,
	APPUI_ENTRY_DTMB ,
	APPUI_ENTRY_DTMB_AUTOSCAN ,
	APPUI_ENTRY_DTMB_MANUALSCAN ,
	APPUI_ENTRY_DTMB_FULLSCAN ,
	APPUI_ENTRY_DTMB_SETFRE ,

	APPUI_ENTRY_PRINT_SETTING ,
	APPUI_ENTRY_CVBS_TEST_SETTING ,
	APPUI_ENTRY_GAME_CENTRE ,
	APPUI_ENTRY_T2_SOFTWARE_UPGRADE ,

	APPUI_ENTRY_OTA ,
	APPUI_ENTRY_DVB_CI ,
	APPUI_ENTRY_CA_SETTING ,
	APPUI_ENTRY_CASCAM_SETTING ,
	APPUI_ENTRY_POWERONCONTROL ,

	APPUI_ENTRY_DVBT_FM ,
	APPUI_ENTRY_FM_SETTING ,
	APPUI_ENTRY_FM_AUTOSCAN ,
	APPUI_ENTRY_FM_PLAY ,

	APPUI_ENTRY_USB_TEST ,
	APPUI_ENTRY_DVBT_USB_TEST ,
	APPUI_ENTRY_USB_REMOVE ,

	APPUI_ENTRY_WEBLET ,
	APPUI_ENTRY_PLUGIN_PORTAL ,
	APPUI_ENTRY_SAMBA ,
	APPUI_ENTRY_TRANSMISSION ,
	APPUI_ENTRY_FREEIPTV ,
	APPUI_ENTRY_DLNA_DMR ,
	APPUI_ENTRY_DLNA_DMP ,
	APPUI_ENTRY_DLNA_SAT2IP ,
	APPUI_ENTRY_DLNA_DMS    ,
	APPUI_ENTRY_DVBT_DLNA ,
	APPUI_ENTRY_SUPERCAST ,
	APPUI_ENTRY_CER_YOUTUBE ,

	APPUI_ENTRY_LEARN_RCU ,
	APPUI_ENTRY_INSTALLATION ,
	APPUI_ENTRY_SETTING ,
	APPUI_ENTRY_UTILITY ,

	APPUI_ENTRY_APPLET_WEATHER,
    APPUI_ENTRY_SOCKS5,
    APPUI_ENTRY_RSS,

	APPUI_ENTRY_MAX
} MainMenu_Sub_Entry_ID;

typedef enum
{
	APPUI_SETTING_SORT    = APPUI_ENTRY_MAX+1,
	APPUI_SETTING_LCN,
	APPUI_SETTING_ACU,
	APPUI_SETTING_VOLUM_SCOPE,
	APPUI_SETTING_ASPECT_RATIO,
	APPUI_SETTING_RESOLUTION,
	APPUI_SETTING_TV_FORMAT,
	APPUI_SETTING_SCART,
	APPUI_SETTING_HDR_MODE,
	APPUI_SETTING_SEARCH_MODE,
	APPUI_SETTING_FTA_ONLY,
	APPUI_SETTING_COUNTRY,
	APPUI_SETTING_ANT_POWER,
	APPUI_SETTING_SLEEP,
	APPUI_SETTING_POWERONCONTROL,
	APPUI_SETTING_OSD_LAN,
	APPUI_SETTING_EPG_LAN,
	APPUI_SETTING_SUB_LAN,
	APPUI_SETTING_HOH_SUB,
	APPUI_SETTING_TTX_LAN,
	APPUI_SETTING_FIRST_AUDIO_LAN,
	APPUI_SETTING_SECOND_AUDIO_LAN,
	APPUI_SETTING_DIGITAL_AUDIO,
	APPUI_SETTING_AUDIO_REME,
	APPUI_SETTING_NO_SIGNAL_AUTO_STANDBY,
	APPUI_SETTING_AUDIO_DESC,
	APPUI_SETTING_AD_VOL_OFFSET,
	APPUI_SETTING_POWERON_PLAY,
	APPUI_SETTING_PVR_END_STANDBY,
	APPUI_SETTING_NO_SIGNAL_ALERT_TIP,
	APPUI_SETTING_CEC,
	APPUI_SETTING_MAX
} MainMenu_Sub_Setting_ID;

int   gxapp_exapi_mainmenu_destory(void);
int   gxapp_exapi_mainmenu_check_end(void);
int   gxapp_exapi_mainmenu_exit(void);
int   gxapp_exapi_mainmenu_event_key_check(int key);
int   gxapp_exapi_mainmenu_net_connect_check(void);
int   gxapp_exapi_mainmenu_media_entry(void);

int   gxapp_exapi_mainmenu_sub_create(int id);
int   gxapp_exapi_mainmenu_sub_check(int id);
int   gxapp_exapi_mainmenu_keypress(int id,int key);
char* gxapp_exapi_mainmenu_get_content(int id);

int   gxapp_exapi_passwd_dlg_create(unsigned int handle);
int   gxapp_exapi_passwd_dlg_offset_x_get(void);
int   gxapp_exapi_passwd_dlg_offset_y_get(void);

int*  gxapp_exapi_config_get_int(const char *key, int *buf, int dvalue);

void  gxapp_exapi_timer_str_get(char *tm_str, unsigned int str_len);


void  gxapp_exapi_set_entry_uiid(int id);
int   gxapp_exapi_get_entry_uiid(void);

void  gxapp_exapi_set_proc_uiid(int id);
int   gxapp_exapi_get_proc_uiid(void);

#endif
