#ifndef __CONFIG_H__
#define __CONFIG_H__

#ifdef NO_OS
#include "version_autogenerated.h"

#define OTA_STACK_SIZE 0x100000
#ifndef IRQ_STACK_SIZE
#define IRQ_STACK_SIZE 0x1000
#endif
#endif

//选择支持的芯片,可以都选这样一个工程支持多款芯片
//#define GX3113C
//#define GX3211
//#define GX3201
//#define GX6605S
//#define SIRIUS
#define TAURUS

//#define ENABLE_UPGRADE_LOGO
//使能showlogo功能
#define ENABLE_LOGO
//使能升级功能
#define ENABLE_UPGRADE
//使能GUI
//#define ENABLE_GUI
//使能GDI
#define ENABLE_GDI
//是否使能USB升级功能
//#define ENABLE_USB
//是否使能OTA升级功能
#define ENABLE_OTA
//是否使能NET升级功能
//#define ENABLE_NET

//是否使能面板
#define ENABLE_PANEL

//启动进入交互时间的配置单位毫秒,配置为0不交互
#define CHECK_TIME 500

//是否使能IRR功能
//#define ENABLE_IRR

//#define ENABLE_MINIFS

/* the format of partition path of dlp and backup_dlp is not include "/", like "OEM"
 * oppositely, the format of minifs path of dlp and backup_dlp_path is include "/" and must be prefixed with "/home/gx", like "/home/gx/oem.ini"
 * using different path format to determine how to read and write dlp and backup_dlp file
 * NOTE: path name length not longer than 40 bytes */
#define DLP_PATH "OEM"
#define BACKUP_DLP_PATH "BACKOEM"

#endif

