[variable_oem]
version=0.0.1
[system]
hardware_version=00.00.00.00
manufacture_id = 00.00
[software]
application_version=00.00.00.00
application_update_version=00.00.00.00
[update]
type=OTA_DDTEX
upgrade_patch_file_name=update.bin
fe_tuner_type=TUNER_RDA5815M
fe_demod_type=DEMOD_Taurus_DVBS
dmx_id=0
dmx_pid=2003
dmx_source=0
dmx_timeout=60
fe_type=DVB_S
fe_modulation=DVBC_16QAM
fe_symbolrate=27500
fe_frequency=1150000
fe_polar_invert=0
fe_polar=13V
fe_22k=ON
fe_diseqc10_port=0
fe_diseqc11_port=0
fe_repeat_times=10
ota_repeat_times=3
force_upgrade_flag=0
partition_status=0

#=================================================
#	个字段说明如下：
#=================================================

# varianle_oem段
	version: varianle_oem(可配)
# system段
	hardware_version：硬件版本号（16进制必配）
	manufacture_id：厂商标识 （16进制必配）
	platform_Id：平台id（有需求可配）
	serial_number：串口号（有需求可配）
	chip_id：芯片型号ID（有需求可配）
# software段
	application_version：软件版本号（16进制必配）
	application_update_version：软件更新版本号（字段必须有，版本号随意）
	language：语言（可配） { "Chinese" , "English", "Uygur"}
# update段
	type：升级类型（必配） {"BOOT", "OTA_FAILED", "OTA_DDT", "OTA_DDTEX", "USB", "NET", "UART"}
	upgrade_patch_file_name（必配，升级文件的源文件名，做升级流的源文件必须为本文件名）
	dmx_id：从哪路demux获取数据(必配)
	dmx_source：ts_id(必配) {"DEMUX_TS1", "DEMUX_TS2", "DEMUX_TS3"}
	dmx_pid：升级数据的pid（10进制必配）
	fe_tuner_type：tuner类型（必配） {"TUNER_AV2018","TUNER_AV2020","TUNER_MXL608_DTMB","TUNER_MXL608_T","TUNER_MXL608_C","TUNER_TDA18250","TUNER_TDA18250A","TUNER_TDA18273_DTMB","TUNER_TDA18273_DVBC","TUNER_R836_T","TUNER_R836_C","TUNER_R910_T","TUNER_R910_C","TUNER_SI2141_T","TUNER_SI2141_C","TUNER_R848_S","TUNER_R848_C","TUNER_R848_T","TUNER_R848_DTMB", "TUNER_RDA5815M","TUNER_ATBM2040", "TUNER_ATBM2030","TUNER_SHARP7306","TUNER_R836_DTMB"}
	fe_demod_type：demod类型（必配） {"DEMOD_GX1121D","DEMOD_GX1503B_DTMB","DEMOD_GX113X","DEMOD_GX3211","DEMOD_GX1001","DEMOD_GX1503_DVBC","DEMOD_GX1503_DTMB","DEMOD_GX1801","DEMOD_ATBM78X","DEMOD_ATBM888X_DVBC","DEMOD_ATBM888X_DTMB","DEMOD_ATBM783X_DVBC","DEMOD_ATBM783X_DVBS","DEMOD_GX1133","DEMOD_Sirius_DVBS","DEMOD_Sirius_DVBC","DEMOD_MXL683","DEMOD_Taurus_DVBS","DEMOD_Taurus_DVBC"};
	fe_type：前端类型（必配） {"DVB_S","DVB_S2","DVB_C","DVB_C2","DVB_T","DVB_T2","DTMB","ATSC_T","ATSC_C","ABS_S","DIRECTV","TSDB_T","J83B"}
	partition_status: 升级状态（必配）
	dmx_timeout：demux读书据超时配置（10进制可配）
	ota_repeat_times：升级不成功重复升级的次数（10进制可配）默认为1次
	fe_repeat_times：锁频重复次数（可配）默认为1次
	partition_name：分区名（可配）
	force_upgrade_flag：强制升级标志位（可配）
	=====================
	DVBS工程配置：
	fe_symbolrate：TP符号率（必配10进制）单位: Kbps
	fe_frequency：TP频率（必配19进制） 单位: KHz
	fe_polar：TP LNB power（必配） {"13V","18V"，"OFF"}
	fe_22k: 22K开关（必配） {"ON", "OFF"}
	fe_diseqc10_port：diseqc1.0（必配10进制0～4）
	fe_diseqc11_port：diseqc1.1（必配10进制0～16）
	fe_bandwidth：带宽（可配） {"BANDWIDTH_8_MHZ", "BANDWIDTH_7_MHZ", "BANDWIDTH_6_MHZ"}
	=====================
	DVBC工程配置：
	fe_symbolrate：TP符号率（必配）单位: Kbps
	fe_frequency：TP频率（必配）单位: KHz
	fe_modulation：调制（必配） {"DVBC_16QAM","DVBC_32QAM""DVBC_64QAM","DVBC_128QAM"，"DVBC_256QAM"}
