#include "version_autogenerated.h"
#include "gxhwlib_registers.h"
#include <stdio.h>
#include <gx_flash_common.h>
#include <flash.h>
#include "gx_flash.h"
#include "nand/gx_nand.h"

int nand_init(int cs)
{
#ifdef ENABLE_BOOT_TOOL
#if defined(CONFIG_ARCH_ARM_CANOPUS) || defined(CONFIG_ARCH_ARM_VEGA)
	return gx_nand_init_v1(REG_BASE_NANDFLASH, 1);
#else
	return gx_nand_init_v0(REG_BASE_NANDFLASH, 1);
#endif
#else
#if defined(CONFIG_ARCH_ARM_CANOPUS) || defined(CONFIG_ARCH_ARM_VEGA)
	return gx_nand_init_v1(REG_BASE_NANDFLASH, 0);
#else
	return gx_nand_init_v0(REG_BASE_NANDFLASH, 0);
#endif
#endif
}



struct flash_op gxflash_nand_ops =
{
	.init                = nand_init,
	.readdata            = gx_nand_readdata,
	.gettype             = gx_nand_gettype,
	.getinfo             = gx_nand_getinfo,
	.write_protect_mode  = NULL,
	.write_protect_status= NULL,
	.write_protect_lock  = gx_nand_write_protect_lock,
	.write_protect_unlock= gx_nand_write_protect_unlock,

#ifdef CONFIG_ENABLE_FLASH_FULLFUNCTION
	.chiperase           = gx_nand_chiperase,
	.scruberase          = gx_nand_scruberase,
	.erasedata           = gx_nand_blockerase,
	.erasedata_nospread  = gx_nand_blockerase_nospread,
	.pageprogram         = gx_nand_pageprogram,
	.sync                = gx_nand_sync,
	.test                = NULL,
	.calcblockrange      = gx_nand_calcblockrange,
	.badinfo             = gx_nand_badinfo,
	.pageprogram_yaffs2  = gx_nand_pageprogram_yaffs2,
	.readoob             = gx_nand_readoob,
	.writeoob            = gx_nand_writeoob,
	.otp_lock            = NULL,
	.otp_status          = NULL,
	.otp_erase           = NULL,
	.otp_read            = NULL,
	.otp_write           = NULL,
	.otp_get_regions     = NULL,
	.otp_set_region      = NULL,
#endif

#ifdef CONFIG_ENABLE_FLASH_TEST
	.readdata_noskip     = gx_nand_readdata_noskip,
	.erasedata_noskip    = gx_nand_blockerase_noskip,
	.pageprogram_noskip  = gx_nand_pageprogram_noskip,
	.pageprogram_noecc   = gx_nand_writedata_noecc,
	.block_bbt_isbad     = gx_nand_block_bbt_isbad,
	.readdata_direct     = gx_nand_readdata_direct,
	.read_data_and_oob   = gx_nand_read_data_and_oob,
	.write_data_and_oob  = gx_nand_write_data_and_oob,
#endif
	.block_isbad         = gx_nand_block_isbad,
	.block_markbad       = gx_nand_block_markbad,
	.calc_phy_offset     = gx_nand_calc_phy_offset,
};
