#include "version_autogenerated.h"
#include "gxhwlib_registers.h"
#include "sys/types.h"
#include "cpu/cpu.h"


#if defined(CONFIG_ENABLE_INTC_GIC)
#include "include/intc_gic.h"
#elif defined(CONFIG_ENABLE_INTC_NC)
#include "include/intc_nc.h"
#else
#endif

void gx_interrupt_init(void)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_init(REG_INTC_BASE);
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_init(REG_INTC_BASE);
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void gx_request_interrupt(uint32_t interrupt, enum interrupt_type type,
		interrupt_handler_t handler, void *data)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_request(interrupt, type, handler, data);
	gic_op_enable(interrupt);
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_request(interrupt, type, handler, data);
	nc_op_enable(interrupt);
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void gx_enable_irq(void)
{
	irq_enable();
}

void gx_enable_fiq(void)
{
	fiq_enable();
}

void gx_disable_irq(void)
{
	irq_disable();
}

void gx_disable_fiq(void)
{
	fiq_disable();
}

void gx_free_interrupt(int interrupt)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_free(interrupt);
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_free(interrupt);
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void gx_mask_interrupt(unsigned int interrupt)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_disable(interrupt);
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_mask(interrupt);
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void gx_unmask_interrupt(unsigned int interrupt)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_enable(interrupt);
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_unmask(interrupt);
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void __attribute__((section(".irq_text"))) gx_irq_handler(void)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_irq_handle();
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_irq_handle();
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void __attribute__((section(".fiq_text"))) gx_fiq_handler(void)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_fiq_handle();
#elif defined(CONFIG_ENABLE_INTC_NC)
	nc_op_fiq_handle();
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
}

void gx_disable_all_interrupt(void)
{
#if defined(CONFIG_ENABLE_INTC_GIC)
	gic_op_all_disable();
#elif defined(CONFIG_ENABLE_INTC_NC)
#else
	printf("error : %s %d\n", __func__, __LINE__);
#endif
	irq_disable();
	fiq_disable();
}
