#include "version_autogenerated.h"
#include "cpu_config.h"
#include "databahn.h"

/* denali_config.c / h5tq2g63bfr_h9.c */
extern unsigned int DENALI_CONFIG_CTL[155];
extern unsigned int DENALI_CONFIG_PHY[26];
extern void ddr_config_patch(void);
extern void serial_put_no_mmu(char);

static void Databahn_Init(void);
static void Databahn_SetParameters(struct reg_param *regs, int count);
static unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width);
static unsigned int Databahn_GetIntStatus(void);
static unsigned int Databahn_isReady(void);
static void Databahn_Config(void);

#define DATABAHN_REG_FULL(i, name, addr, offset, width, v) \
	{DATABAHN_REG_AXI##i##name##addr,  DATABAHN_REG_AXI##i##name##offset,  DATABAHN_REG_AXI##i##name##width, v}

#define DATABAHN_REG(i, name, v) \
	DATABAHN_REG_FULL(i, name, _ADDR, _OFFSET, _WIDTH, v)

static struct reg_param param_table[] = {
	// Lvl
	{DATABAHN_REG_WRLVL_REG_EN_ADDR, DATABAHN_REG_WRLVL_REG_EN_OFFSET, DATABAHN_REG_WRLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_REG_EN_ADDR, DATABAHN_REG_RDLVL_REG_EN_OFFSET, DATABAHN_REG_RDLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_GATE_EN_ADDR, DATABAHN_REG_RDLVL_GATE_EN_OFFSET, DATABAHN_REG_RDLVL_GATE_EN_WIDTH, 1},

	DATABAHN_REG(0 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(1 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(2 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(3 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(4 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(5 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(6 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(7 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(8 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(9 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(10, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(11, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(12, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(13, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(14, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(15, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),

	DATABAHN_REG(0 , _R_PRIORITY, 0x6),  // gp/gse/jpeg/vpu
	DATABAHN_REG(1 , _R_PRIORITY, 0x6),  // apu/filter/ga/pp/usb
	DATABAHN_REG(2 , _R_PRIORITY, 0x6),  // audio/gmac/nfc/vedio_decoder
	DATABAHN_REG(3 , _R_PRIORITY, 0x7),  // cortexA7/secure_ctrl/secure_hash
	DATABAHN_REG(4 , _R_PRIORITY, 0x6),  // demux/secure_m2m

	DATABAHN_REG(0 , _W_PRIORITY, 0x6),
	DATABAHN_REG(1 , _W_PRIORITY, 0x6),
	DATABAHN_REG(2 , _W_PRIORITY, 0x6),
	DATABAHN_REG(3 , _W_PRIORITY, 0x7),
	DATABAHN_REG(4 , _W_PRIORITY, 0x6),

	{DATABAHN_REG_SWAP_EN_ADDR, DATABAHN_REG_SWAP_EN_OFFSET, DATABAHN_REG_SWAP_EN_WIDTH, 0x0},

	// Databahn start enable
	//{DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1}
};

/* routine.c */
static void SetRegisterField(unsigned int reg, unsigned int offset, unsigned int width, unsigned int value)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int value_masked;

	original = *(volatile unsigned int *)reg;

	if (width == 32)
		mask = 0xffffffff;
	else
		mask = (1 << width) - 1;
	value_masked = value & mask;
	result = (original & (~(mask << offset))) | (value_masked << offset);

	*(volatile unsigned int *)reg = result;
}

static unsigned int GetRegisterField(unsigned int reg, unsigned int offset, unsigned int width)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int mask_shifted;

	original = *(volatile unsigned int *)reg;
	if(width==32)
		mask = 0xffffffff;
	else
		mask = (1 << width)-1;
	mask_shifted = mask << offset;
	result = (original & mask_shifted) >> offset;

	return result;
}

/* databahn.c */
void Databahn_Init(void)
{
	unsigned int i;
	unsigned int ddr_version;
	unsigned int tsel_feed;
	unsigned int data_e_sel;
	unsigned int ocd_pu;
	unsigned int ocd_pd;
	unsigned int dfi_cmd_control;
	unsigned int vref_set;
	unsigned int encry_delay;

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<25);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT1_NORM) &= ~((1<<27)|(1<<28));
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DENALI_CONFIG0)=0xffffffff;

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) |= (0x1);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) &= ~(0x1);

	//============set dram_config0-3: begin===================
	//clear config0-2
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3)=0x0;

	//#1: config1[30], select dram class
#ifdef CONFIG_DDR3
	ddr_version = 0x2;
#elif defined(CONFIG_DDR2)
	ddr_version = 0x0;
#endif
	//#2: config0[2:0], tsel_feed
	tsel_feed = 0x1;
	//#3: config0[15], data_e_sel, choose the switch of the receiver in DDRIO
	// data_e_sel=0 means switch is controlled by DRAM_CONFIG0[14:11]
	data_e_sel = 0x0;

	//#4: ocd_pu&ocd_pd
#ifdef CONFIG_LQFP_176
	ocd_pu=0xc;
	ocd_pd=0xc;
#else
	ocd_pu=0x8;
	ocd_pd=0x8;
#endif

	//#5: set output driver_strength of DDRIO in board_init.c
	ddr_config_patch();

	//#6: config0[31], dfi_cmd_control
	dfi_cmd_control = 0x1;

	//#7: config2[19:16], set Vref
	vref_set = 0x0;

	//#8: config3[1:0], set encry_delay
	if (DDR_PARAM_FREQUENCY == DDR_FREQUENCY_400M)
		encry_delay = 0;
	else if (DDR_PARAM_FREQUENCY == DDR_FREQUENCY_533M)
		encry_delay = 1;
	else if (DDR_PARAM_FREQUENCY == DDR_FREQUENCY_800M)
		encry_delay = 2;
	else
		encry_delay = 0;

	//set_dram_config
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0) |= (tsel_feed<<0) | (data_e_sel<<15) | (ocd_pu<<16) | (ocd_pd<<20) | (dfi_cmd_control<<31);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1) |= (ddr_version<<29) | (ocd_pu<<3) | (ocd_pd<<7) | (ocd_pu<<14) | (ocd_pd<<18);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2) |= (ocd_pu<<3) | (ocd_pd<<7) | (vref_set<<16);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3) |= (encry_delay<<0);

	//============set dram_config0-3: end===========

	for(i = 0;i < sizeof(DENALI_CONFIG_CTL)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg(i) = DENALI_CONFIG_CTL[i];

	for(i = 0; i < sizeof(DENALI_CONFIG_PHY)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg((i + 256)) = DENALI_CONFIG_PHY[i];

	Databahn_Config();

	while(!Databahn_isReady());
}

void Databahn_SetParameters(struct reg_param *regs, int count) {
	int i;

	for (i=0; i < count; i++)
		SetRegisterField(Databahn_Reg(regs[i].reg), regs[i].offset, regs[i].width, regs[i].value);
}

void Databahn_Config(void)
{
	Databahn_SetParameters(param_table, sizeof(param_table) / sizeof(struct reg_param));
	// Databahn start enable
	SetRegisterField(Databahn_Reg(DATABAHN_REG_START_ADDR), DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1);
}

unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width)
{
	return GetRegisterField(Databahn_Reg(reg), offset, width);
}

unsigned int Databahn_GetIntStatus(void)
{
	return Databahn_GetParameter(DATABAHN_REG_INT_STATUS_ADDR, DATABAHN_REG_INT_STATUS_OFFSET, DATABAHN_REG_INT_STATUS_WIDTH);
}

unsigned int Databahn_isReady(void)
{
	return (Databahn_GetIntStatus() & 0x20) ? 1 : 0;
}

static void wait_rng_ready(void)
{
	*(volatile unsigned int*)(CONFIG_BASE + CONFIG_RNG_CTRL) |= 1;
	while (!((*(volatile unsigned int*)(CONFIG_BASE + CONFIG_RNG_CTRL)) & 0x2));
	*(volatile unsigned int*)(CONFIG_BASE + CONFIG_RNG_CTRL) &= ~1;
}
/* gx3211_sdram.c */
void gx_setup_sdram_controller(void)
{
	Databahn_Init();
	serial_put_no_mmu('N');

	if ((*(volatile unsigned int*)(REG_BASE_OTP+0x0C)) & (0x1 << 10))//bit 10 to indicate ddr_content_scramble_enable
		wait_rng_ready();
}

