#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Makefile
 *
 */

//
// Automatically generated file; DO NOT EDIT.
// NationalChip GxCas Configuration
//
// CONFIG_NONE is not set
// CONFIG_CD is not set
// CONFIG_CTI is not set
// CONFIG_ABV is not set
// CONFIG_DVT is not set
// CONFIG_IRDETO is not set
// CONFIG_RS is not set
// CONFIG_UTI is not set
#define CONFIG_CPG
// CONFIG_DIVIG is not set
// CONFIG_TR is not set
// CONFIG_DESAI is not set
// CONFIG_CONAX is not set
// CONFIG_GOS is not set
// CONFIG_VMX is not set
// CONFIG_TELECAST is not set
// CONFIG_NAGRA is not set
// CONFIG_RELEASE is not set
#define CONFIG_DEBUG
// CONFIG_CSKY is not set
#define CONFIG_ARM
#define CONFIG_ECOS
// CONFIG_LINUX is not set
#define CONFIG_CARD
// CONFIG_NOCARD is not set
// CONFIG_MTC is not set
// CONFIG_SCPU is not set
// CONFIG_TFM is not set
// CONFIG_TFM_USER_DEFINE is not set
#define CONFIG_ACPU
// CONFIG_SCI_OLD is not set
#define CONFIG_SCI_NEW
// CONFIG_DMX_OLD is not set
#define CONFIG_DMX_NEW
// CONFIG_CGHS is not set
#define CONFIG_CGCS
#define CONFIG_HARD_FLOAT

#endif
