#ifndef _GX_RCC_H_
#define _GX_RCC_H_
#include <version_autogenerated.h>

#ifdef CONFIG_RCC_GX_V1
struct rcc_reg_s {
	unsigned int RCC_CTRL_REG;           //0x00
	unsigned int RCC_STA_REG;            //0x04
	unsigned int RCC_INTERVAL;           //0x08
	unsigned int Reserved0;              //0x0c
	unsigned int RCC0_START_ADDR;        //0x10
	unsigned int RCC0_SIZE;              //0x14
	unsigned int RCC1_START_ADDR;        //0x18
	unsigned int RCC1_SIZE;              //0x1c
	unsigned int RCC2_START_ADDR;        //0x20
	unsigned int RCC2_SIZE;              //0x24
	unsigned int RCC3_START_ADDR;        //0x28
	unsigned int RCC3_SIZE;              //0x2c
	unsigned int Reserved1[4];           //0x30~0x3c
	unsigned int HASH_START_ADDR;        //0x40
	unsigned int HASH_SIZE;              //0x44
	unsigned int Reserved2[2];           //0x48~0x4c
	unsigned int RCC_HASH_A;             //0x50
	unsigned int RCC_HASH_B;             //0x54
	unsigned int RCC_HASH_C;             //0x58
	unsigned int RCC_HASH_D;             //0x5c
	unsigned int RCC_HASH_E;             //0x60
	unsigned int RCC_HASH_F;             //0x64
	unsigned int RCC_HASH_G;             //0x68
	unsigned int RCC_HASH_H;             //0x6c
};
#elif defined(CONFIG_RCC_GX_V2)
struct rcc_reg_s {
	unsigned int RCC_CTRL_REG;           //0x00
	unsigned int RCC_STA_REG;            //0x04
	unsigned int RCC_INTERVAL;           //0x08
	unsigned int RCC0_START_ADDR;        //0x0c
	unsigned int RCC0_SIZE;              //0x10
	unsigned int RCC1_START_ADDR;        //0x14
	unsigned int RCC1_SIZE;              //0x18
	unsigned int RCC2_START_ADDR;        //0x1c
	unsigned int RCC2_SIZE;              //0x20
	unsigned int RCC3_START_ADDR;        //0x24
	unsigned int RCC3_SIZE;              //0x28
	unsigned int HASH_START_ADDR;        //0x2c
	unsigned int HASH_SIZE;              //0x30
	unsigned int RCC_HASH_A;             //0x34
	unsigned int RCC_HASH_B;             //0x38
	unsigned int RCC_HASH_C;             //0x3c
	unsigned int RCC_HASH_D;             //0x40
	unsigned int RCC_HASH_E;             //0x44
	unsigned int RCC_HASH_F;             //0x48
	unsigned int RCC_HASH_G;             //0x4c
	unsigned int RCC_HASH_H;             //0x50
};
#endif

#define RCC_SET_BUS_ACC_CONTROL(base, value)    do { \
							base->RCC_CTRL_REG &= ~(0xfff << 16); \
							base->RCC_CTRL_REG |= ((value & 0xfff) << 16); \
						} while(0)

#define RCC_SET_INTERVAL(base, value)           (base->RCC_INTERVAL = value)

#define RCC_SET_RCC0_START_ADDR(base, value)    (base->RCC0_START_ADDR = (value) & 0x1fffffff)
#define RCC_SET_RCC0_SIZE(base, value)          (base->RCC0_SIZE = value)
#define RCC_SET_RCC1_START_ADDR(base, value)    (base->RCC1_START_ADDR = (value) & 0x1fffffff)
#define RCC_SET_RCC1_SIZE(base, value)          (base->RCC1_SIZE = value)
#define RCC_SET_RCC2_START_ADDR(base, value)    (base->RCC2_START_ADDR = (value) & 0x1fffffff)
#define RCC_SET_RCC2_SIZE(base, value)          (base->RCC2_SIZE = value)
#define RCC_SET_RCC3_START_ADDR(base, value)    (base->RCC3_START_ADDR = (value) & 0x1fffffff)
#define RCC_SET_RCC3_SIZE(base, value)          (base->RCC3_SIZE = value)

#define RCC_SECTION0_START(base)                (base->RCC_CTRL_REG |= (1 << 0))
#define RCC_SECTION1_START(base)                (base->RCC_CTRL_REG |= (1 << 1))
#define RCC_SECTION2_START(base)                (base->RCC_CTRL_REG |= (1 << 2))
#define RCC_SECTION3_START(base)                (base->RCC_CTRL_REG |= (1 << 3))

#define RCC_SECTION0_STATUS(base)               ((base->RCC_STA_REG >> 8) & 1)
#define RCC_SECTION1_STATUS(base)               ((base->RCC_STA_REG >> 9) & 1)
#define RCC_SECTION2_STATUS(base)               ((base->RCC_STA_REG >> 10) & 1)
#define RCC_SECTION3_STATUS(base)               ((base->RCC_STA_REG >> 11) & 1)

struct gx_rcc_section {
	int used_flag;
	unsigned int start_addr;
	unsigned int size;
};

#define GX_RCC_SECTION_MAX	4
struct gx_rcc_data_s {
	unsigned int reg_base;
	struct gx_rcc_section gx_rcc_section[GX_RCC_SECTION_MAX];
};

#endif
