#ifndef __APP_STR_ID__
#define __APP_STR_ID__
#include "app_config.h"


#if 1   //basic common words
#define STR_ID_EPG  "Program Guide"
#define STR_ID_INSTALLATION    "Installation"
#define STR_ID_ATNE_SET    "Antenna Setting"
#define STR_ID_CH_EDIT    "Channel Edit"
#define STR_ID_CH_ADD    "Channel Add"
#define STR_ID_CH_LIST    "Channel List"
#define STR_ID_NAMEAZ    "Name(A-Z)"
#define STR_ID_NAMEZA    "Name(Z-A)"
#define STR_ID_POSI_SET    "Positioner Setup"
#define STR_ID_SAT_LIST    "Satellite List"
#define STR_ID_TP_LIST    "TP List"
#define STR_ID_TV_CH    "TV Channel"
#define STR_ID_RADIO_CH    "Radio Channel"
#define STR_ID_DEL_ALL    "Delete All"
#define STR_ID_SYS_SET    "System Setting"
#define STR_ID_TIME_SET    "Time Setting"
#define STR_ID_TIMER_SET    "Timer Setting"
#define STR_ID_TIMER_EDIT    "Timer Edit"
#define STR_ID_LANG    "Language"
#define STR_ID_AV_SET    "AV Setting"
#define STR_ID_LOCK_CTRL    "Lock Control"
#define STR_ID_OSD_SET    "OSD Setting"
#define STR_ID_COLOR_SET    "Color Setting"
#define STR_ID_ADVANCED_SET "Advanced Setting"
#define STR_ID_AUDIO_REMEMBER "Audio Remember"
#define STR_ID_UTILITY    "Utility"
#define STR_ID_VIDEO    "Video"
#define STR_ID_VIDEO_    "Video:"
#define STR_ID_VISIBLITY    "Visibility"
#define STR_ID_TITLE_    "Title:"
#define STR_ID_INVALID    "Invalid!"
#define STR_ID_INVALID_TP    "Invalid TP!"
#define STR_ID_LAST_DAY    "Day-"
#define STR_ID_NEXT_DAY    "Day+"
#define STR_ID_FIRMWARE_UPGRADE    "Software Upgrade"
#define STR_ID_NOWRITE_PERMISSIONS  "Device has no write permissions"
#define STR_ID_FACTORY_RESET    "Factory Reset"
#define STR_ID_SYSTEM_INFO    "System Information"
#define STR_ID_MEDIA_CENTER    "Media Centre"
#define STR_ID_MEDIA_PLAYER    "Media Player"
#define STR_ID_PVR_MANAGE    "PVR Management"
#define STR_ID_PVR_MEDIA    "PVR Media"
#define STR_ID_SATELLITE    "Satellite"
#define STR_ID_LNB_POWER    "LNB Power"
#define STR_ID_LNB_FREQ    "LNB Frequency"
#define STR_ID_SUPER_TP_SEARCH "Super TP Search"
#define STR_ID_SUPER_SEARCH    "Super Search"
#define STR_ID_NORMAL_SEARCH   "Normal Search"
#define STR_ID_ON    "On"
#define STR_ID_OFF   "Off"
#define STR_ID_AUTO    "Auto"
#define STR_ID_MOTOR_TYPE    "Motor Type"
#define STR_ID_SAVE    "Save"
#define STR_ID_BLIND_SEARCH    "Blind Search"
#define STR_ID_BLIND "Blind"
#define STR_ID_TV_RADIO    "TV/Radio"
#define STR_ID_ALL    "All"
#define STR_ID_TV    "TV:"
#define STR_ID_RADIO    "Radio:"
#define STR_ID_NO    "No"
#define STR_ID_YES    "Yes"
#define STR_ID_NIT_SEARCH    "Nit Search"
#define STR_ID_SEARCH    "Search"
#define STR_ID_STRENGTH    "Strength"
#define STR_ID_QUALITY    "Quality"
#define STR_ID_PROGRESS    "Progress"
#define STR_ID_TIPS    "Tips"
#define STR_ID_PRESS_OK    "Press OK"
#define STR_ID_SAT_NAME    "SAT Name"
#define STR_ID_LONGITUDE    "Longitude"
#define STR_ID_DIRECTION    "Direction"
#define STR_ID_DELETE    "Delete"
#define STR_ID_SELECT    "Select"
#define STR_ID_ADD    "Add"
#define STR_ID_EDIT    "Edit"
#define STR_ID_FREQ    "Frequency"
#define STR_ID_POLAR    "Polar"
#define STR_ID_SYM_RATE    "Symbol Rate"
#define STR_ID_MOVE    "Move"
#define STR_ID_SWAP    "Swap"
#define STR_ID_SKIP    "Skip"
#define STR_ID_LOCK    "Lock"
#define STR_ID_FAV    "Fav"
#define STR_ID_UNFAV    "UnFav"
#define STR_ID_HD   "HD"
#define STR_ID_SORT    "Sort"
#define STR_ID_SOURCE "Source"
#define STR_ID_RENAME    "Rename"
#define STR_ID_FREE_SCRAMBLE    "Free/Scramble"
#define STR_ID_FAV_UNFAV    "Fav/UnFav"
#define STR_ID_LOCK_UNLOCK    "Lock/Unlock"
#define STR_ID_KEYBOARF    "Keyboard"
#define STR_ID_MODE    "Mode"
#define STR_ID_DATE    "Date"
#define STR_ID_TIME    "time"
#define STR_ID_DATE_OR_TIME    "Date/Time"
#define STR_ID_TIME_ZONE    "Timezone"
#define STR_ID_TIME_SUMMER    "Summertime"
#define STR_ID_START_TIME    "Start Time"
#define STR_ID_EVENT    "Event"
#define STR_ID_DURATION    "Duration"
#define STR_ID_POWER_ON    "Power On"
#define STR_ID_POWER_OFF    "Power Off"
#define STR_ID_POWER_ON_OFF "Power On/Off"
#define STR_ID_POWER_OFF_TIP    "Shutdown countdown:"
#define STR_ID_TYPE    "Type"
#define STR_ID_ONCE    "Once"
#define STR_ID_DAILY    "Daily"
#define STR_ID_START_DATE    "Start Date"
#define STR_ID_CHANNEL    "Channel"
#define STR_ID_MENU_LANG    "Menu Language"
#define STR_ID_AUDIO_LANG_1   "First Audio Language"
#define STR_ID_AUDIO_LANG_2    "Second Audio Language"
#define STR_ID_SUB_LANG    "Subtitle Language"
#define STR_ID_HOH_SUB    "HOH Subtitles"
#define STR_ID_TTX_LANG     "TTX Language"
#define STR_ID_EPG_LANG    "EPG Language"
#define STR_ID_TV_STANDARD    "TV Standard"
#define STR_ID_TV_RATIO    "TV Ratio"
#define STR_ID_ASPECT_MODE    "Aspect Mode"
#define STR_ID_LETTER_BOX    "Letter Box"
#define STR_ID_VIDEO_OUTPUT "Video Output"
#define STR_ID_STEREO    "Stereo"
#define STR_ID_LEFT    "Left"
#define STR_ID_RIGHT    "Right"
#define STR_ID_MENU_LOCK    "Menu Lock"
#define STR_ID_CH_LOCK    "Channel Lock"
#define STR_ID_CHANGE_PASSWD    "Change Password"
#define STR_ID_OLD_PASSWD    "Old Password"
#define STR_ID_NEW_PASSWD    "New Password"
#define STR_ID_CON_PASSWD    "Confirm Password"
#define STR_ID_DIGITAL_AUDIO        "Digital Audio"
#define STR_ID_TRAN    "Transparency"
#define STR_ID_OSD_TIMEOUT    "OSD timeout"
#define STR_ID_BRIGHT    "Brightness"
#define STR_ID_CHROMA    "Chroma"
#define STR_ID_CONTRAST    "Contrast"
#define STR_ID_SHARPNESS    "Sharpness"
#define STR_ID_HUE          "Hue"
#define STR_ID_UPGRADE_TYPE    "Upgrade Type"
#define STR_ID_SECTION    "Section"
#define STR_ID_FILE_PATH    "File Path"
#define STR_ID_USB_UPGRADE    "USB Upgrade"
#define STR_ID_DUMP    "Dump"
#define STR_ID_FILE_LIST    "File List"
#define STR_ID_LOADER_VER    "Loader"
#define STR_ID_HARDWARE_VER    "Hardware Version"
#define STR_ID_SOFLTWARE_VER    "Software Version"
#define STR_ID_BUILD_TIME    "Build Time"
#define STR_ID_CHIP_SN    "Chip S/N"
#define STR_ID_APPLICATION_VER         "Application"
#define STR_ID_SPD_LIB_VER         "Lib"
#define STR_ID_HARDWARE_INFO        "Hardware Info"
#define STR_ID_FILE    "File"
#define STR_ID_MUSIC    "Music"
#define STR_ID_PICTURE    "Picture"
#define STR_ID_TEXT    "Text"
#define STR_ID_WAITING    "Waiting..."
#define STR_ID_SEQUENCE    "Sequence"
#define STR_ID_RANDOM    "Random"
#define STR_ID_DELAY    "Delay"
#define STR_ID_ONLY_ONCE    "Only once"
#define STR_ID_REPEAT_ONE    "Repeat one"
#define STR_ID_REPEAT_ALL    "Repeat all"
#define STR_ID_VIEW_MODE    "View mode"
#define STR_ID_LRC    "Lyric"
#define STR_ID_NO_LRC    "No lyric!"
#define STR_ID_CONTINUE_VIEW "Continue to watch?"
#define STR_ID_SPECTRUM    "Spectrum"
#define STR_ID_TMS    "Timeshift"
#define STR_ID_REC_DURA    "Record Duration"
#define STR_ID_DISK_INFO    "Disk Information"
#define STR_ID_USB_REMOVE  "USB Remove"
#define STR_ID_REMOVE  "Remove"
#define STR_ID_BOOK    "Book"
#define STR_ID_AUDIO    "Audio"
#define STR_ID_MODUL_PARAM    "Modulation Parameters:"
#define STR_ID_UNKNOW   "Unknown"
#define STR_ID_FIND    "Find"
#define STR_ID_SUBTITLING    "Subtitle"
#define STR_ID_PLAY    "Play"
#define STR_ID_PAUSE    "Pause"
#define STR_ID_SAVE_INFO    "Do you want to save?"
#define STR_ID_ERR_PASSWD    "Invalid Password!"
#define STR_ID_INVALID_SYMBOLS    "Invalid special symbols!"
#define STR_ID_ERR_FILELARGE    "The file is too large!"
#define STR_ID_STOP_REC_INFO    "Sure to stop recording?"
#define STR_ID_STOP_TMS_INFO    "Sure to Stop Timeshift?"
#define STR_ID_STOP_TMS_AND_REC_INFO    "Sure to stop timeshift and record?"
#define STR_ID_STOP_PVR_FIRST    "Stop PVR/TMS first please!"
#define STR_ID_NO_PROGRAM    "Program Not Exist!"
#define STR_ID_VIDEO_UNSUPPORT    "Video decode Failed!"
#define STR_ID_NO_DEVICE    "Device is not available.Please check!"
#define STR_ID_INSERT_USB    "Please insert USB device!"
#define STR_ID_ERR_PATH    "Invalid file path!"
#define STR_ID_NO_SPACE    "No Enough Space!"
#define STR_ID_USB_IN    "USB plug in!"
#define STR_ID_USB_OUT    "USB plug out!"
#define STR_ID_ERR_TIMER     "Invalid Timer!"
#define STR_ID_TIMER_FULL     "Timer Full!"
#define STR_ID_BOOK_ARRIVE_INFO    "Booking arrived, continue?"
#define STR_ID_MAX_SAT    "Max Satellite!"
#define STR_ID_MAX_TP    "Max TP!"
#define STR_ID_NO_TELTEXT    "No Teletext"
#define STR_ID_ERR_LONGITUDE    "Invalid Longitude!"
#define STR_ID_ERR_POSITION    "Invalid Position!"
#define STR_ID_SAVING    "Saving..."
#define STR_ID_DISH_MOVING    "Dish moving..."
#define STR_ID_OUT_RANGE    "Out of range"
#define STR_ID_POS_FULL    "Position Full!"
#define STR_ID_SUCCESS    "Success!"
#define STR_ID_ERR_DATE    "Invalid date!"
#define STR_ID_FORMAT_INFO    "Sure to format?"
#define STR_ID_FORMATING    "Formating! Please wait! No plug!"
#define STR_ID_ERR_OCCUR    "Error occur!"
#define STR_ID_NO_FAV    "No FAV!"
#define STR_ID_SAVING_WAIT    "Saving, please wait..."
#define STR_ID_MAX_CHANNEL    "Max Channel!"
#define STR_ID_NO_NEW_CH    "No new channel is found!"
#define STR_ID_DEL_ALL_CH    "Delete all channels?"
#define STR_ID_NO_CH    "No channel!"
#define STR_ID_INSTALL_FIRST    "Please install first!"
#define STR_ID_NO_SAT    "No sat!"
#define STR_ID_NO_SIGNAL    "No signal"
#define STR_ID_SCRAMBLE    "Scrambled"
#define STR_ID_LOCKED    "Locked"
#define STR_ID_CANCEL    "Cancel"
#define STR_ID_PASSWD    "Password"
#define STR_ID_INPUT_PASSWD    "Please input password!"
#define STR_ID_DONT_CUT_PWER    "Don't cut off the power!"
#define STR_ID_UPGRADE    "Upgrade"
#define STR_ID_PRESENT    "Preset"
#define STR_ID_SAT_SEARCH     "Satellite Search"
#define STR_ID_SUPER_SAT_SEARCH "Super Satellite Search"
#define STR_ID_FTA_ONLY    "FTA Only"
#define STR_ID_NO_PVR_FILE    "No PVR File!"
#define STR_ID_DLE_ONE_TP_FIRST   "Delete one tp first please!"
#define STR_ID_DLE_SAT    "Delete the selected SAT?"
#define STR_ID_SAT_NOT_EXIST    "SAT Not Exist!"
#define STR_ID_DLE_TP "Delete the selected TP?"
#define STR_ID_TP_NOT_EXIST "TP Not Exist!"
#define STR_ID_RECALC    "Recalculation"
#define STR_ID_GOTO    "Goto"
#define STR_ID_SAVE_POSITION    "Save Position"
#define STR_ID_LIMIT    "Limit"
#define STR_ID_FINE_DRIVE    "Fine Drive"
#define STR_ID_LOCAL_LONGITUDE    "Local Longitude"
#define STR_ID_LOCAL_LATITUDE    "Local Latitude"
#define STR_ID_SAT_LONGITUDE    "Sat Longitude"
#define STR_ID_POSITION    "Position"
#define STR_ID_PLAY_MODE    "Play Mode"
#define STR_ID_DELETING "Deleting, please wait..."
#define STR_ID_DEL_FAIL "Delete failed!"
#define STR_ID_TP_EXIST "TP already exist!"
#define STR_ID_FILE_NOT_SUPPORT    "The file type is not supported!"
#define STR_ID_ERR_FILE_OPEN    "Can't open the file!"
#define STR_ID_VOLUME   "Volume"
#define STR_ID_NO_DATA  "No data"
#define STR_ID_NORMAL   "Normal"
#define STR_ID_CANT_PVR "PVR is not supported!"
#define STR_ID_SURE_RESET    "Sure to Factory Reset?"
#define STR_ID_NAME_EXIST   "The name exist!"
#define STR_ID_DISK_SELECT        "Disk Select"
#define STR_ID_INVALID_PID      "Invalid PID value! Please reenter another number!"
#define STR_ID_SAT_EXIT "Satellite already exist!"
#define STR_ID_UPDATE   "Update"
#define STR_ID_NO_INFO      "No Information"
#define STR_ID_FILE_NOT_EXIST   "File does not exist!"
#define STR_ID_DIR_EXISTS   "Directory already exists!"
#define STR_ID_SURE_DELETE      "Are you sure to delete it?"
#define STR_ID_SURE_DELETE_ALL      "Are you sure to delete all?"
#define STR_ID_DETAIL   "Detail"
#define STR_ID_SCANTP_INFO      "Scanning TP..."
#define STR_ID_SELECT_GROUP_CHANNELS    "Select Group Channels"
#define STR_ID_VOLUME_SCOPE    "Volume Scope"
#define STR_ID_GLOBAL        "Global"
#define STR_ID_END_TIME_ERR "End time error."
#define STR_ID_UTC_0000    "Reykjavik,Casablanca,Lisbon,Dublin,London."
#define STR_ID_UTC_0100    "Algiers,Lagos,Madrid,Barcelona,Paris,Amsterdam,Frankfurt,Rome,Berlin,Stockholm."
#define STR_ID_UTC_0200    "Ankara,Cairo,Harare,Sofia,Athens,Bucharest,Minsk,Kyiv,Khartou,Beirut."
#define STR_ID_UTC_0300     "Riyadh,Jeddah,Mecca,Aden,Moscow,Baghdad,Odesa."
#define STR_ID_UTC_0400     "Abu Dhabi,Dubai."
#define STR_ID_UTC_0500     "Tashkent,Lahore,Antananarivo."
#define STR_ID_UTC_0600    "Dhaka."
#define STR_ID_UTC_0700    "Bangkok,Hanoi,jakarta."
#define STR_ID_UTC_0800    "Kuala Lumpur,Singapore,Hong Kong,Beijing,Manila,Shanghai,Taipei."
#define STR_ID_UTC_0900    "Seoul,Tokyo."
#define STR_ID_UTC_1000    "Melbourne,Canberra,Sydney,Brisbane,Vladivostok."
#define STR_ID_UTC_1100    ""
#define STR_ID_UTC_1200    "Auckland,Wellington,Suva,Kamchatka,Anadyr,Kiritimati."
#define STR_ID_UTC_1000_   "Honolulu."
#define STR_ID_UTC_0900_   "Anchorage."
#define STR_ID_UTC_0800_   "Vancouver,San Francisco,Seattle,Los Angeles."
#define STR_ID_UTC_0700_   "Phoenix,Edmonton,Denver."
#define STR_ID_UTC_0600_   "San Salvador,Mexico City,Minneapolis,St. Paul,New Orleans,Managua."
#define STR_ID_UTC_0500_   "Lima,Kingston,Atlanta,Havana,Miami,Toronto,Washington DC,Ottawa,New York"
#define STR_ID_UTC_0400_   "Santiago,La Paz,Caracas,Asuncion,Halifax."
#define STR_ID_UTC_0300_   "Buenos Aires,Brasilia,Sao Paulo,Rio de Janeiro."
#define STR_ID_UTC_0200_   ""
#define STR_ID_UTC_0100_   ""
#define STR_ID_MULTIFEED "Multifeed"
#define STR_ID_MODE_NOT_SUPPORT "The current mode is not supported!"
#define STR_ID_INPUT_EMPTY_TIP      "Input can not be empty!"
#define STR_ID_INPUT_ONLY_SPACE_TIP      "None of the inputs should be space!"
#define STR_ID_MEDIA_DEVICE_NO_EXIST                     "Media device does not exist!"
#define STR_ID_AC3_DECODE   "AC3 Decode"
#define STR_ID_AC3_BYPASS   "AC3 Bypass"
#define STR_ID_AC3_AUTO   "AC3 Auto"
#define STR_ID_ALBUM   "Album:"
#define STR_ID_ARTIST   "Artist:"
#define STR_ID_BIT_RATE   "Bit rate:"
#define STR_ID_CHANNEL_SWITCH "Channel Switch"
#define STR_ID_EXPOSURE_TIME   "Exposure time:"
#define STR_ID_FILE_NAME   "File name:"
#define STR_ID_FILE_SIZE   "File size:"
#define STR_ID_FORMAT   "Format"
#define STR_ID_FORMAT_FAIL   "Format failed!"
#define STR_ID_FRAME_RATE   "Frame rate:"
#define STR_ID_FREE   "Free"
#define STR_ID_FREEZE   "Freeze"
#define STR_ID_MODE_MON "Mon."
#define STR_ID_MODE_TUES "Tues."
#define STR_ID_MODE_WED "Wed."
#define STR_ID_MODE_THURS "Thurs."
#define STR_ID_MODE_FRI "Fri."
#define STR_ID_MODE_SAT "Sat."
#define STR_ID_MODE_SUN "Sun."
#define STR_ID_FULL_SCREEN   "Full screen"
#define STR_ID_GENRE   "Genre:"
#define STR_ID_INSIDE   "Inside"
#define STR_ID_JUMP_TO_EXIST_TP   "Jump to the exist tp?"
#define STR_ID_NONE   "None"
#define STR_ID_ORIG   "Original"
#define STR_ID_ORIG_SIZE   "Original size"
#define STR_ID_OUTSIZE   "Outside"
#define STR_ID_PAN_AND_SCAN   "Pan & Scan"
#define STR_ID_RE_ENTER_PASSWD   "Password same please reenter."
#define STR_ID_PRESS_E_W   "Press East / West"
#define STR_ID_PVR_SET  "PVR Set"
#define STR_ID_RESOLUTION_   "Resolution:"
#define STR_ID_SECTION_RECORD "Section Record"
#define STR_ID_SEEKING   "Seeking..."
#define STR_ID_SEEK_TIME_ERR   "Seek time error"
#define STR_ID_SIGNAL_INDICATOR   "Signal Indicator"
#define STR_ID_SLEEP   "Sleep(HOUR)"
#define STR_ID_SUPER_SAT   "Super Satellite"
#define STR_ID_SUPER_TP   "Super Tp"
#define STR_ID_SYSTEM   "System"
#define STR_ID_THEME   "Theme"
#define STR_ID_TOTAL   "Total"
#define STR_ID_TP_SEARCH   "TP Search"
#define STR_ID_USB_LARGE   "USB too large to format"
#define STR_ID_USED   "Used"
#define STR_ID_USER   "User"
#define STR_ID_VIDEO_PID   "Video PID:"
#define STR_ID_VIDEO_TYPE   "Video Type"
#define STR_ID_YEAR   "Year:"
#define STR_ID_TRACK   "Track:"
#define STR_ID_QUICK_SEEK   "Quick seek"
#define STR_ID_UPGRADE_SUCCESS  "Upgrade successfully!"
#define STR_ID_DLE_ONE_SAT_FIRST    "Delete one satellite first please!"
#define STR_ID_PLZ_WAIT    "Please wait!"
#define STR_ID_SPECIAL  "CA Setting"
#define STR_ID_PVR_END "PVR End!"
#define STR_ID_BLACK   "Black"
#define STR_ID_CAMERA_MAKE   "Camera make:"
#define STR_ID_CAMERA_MODE   "Camera model:"
#define STR_ID_CAN_NOT_PLAY_FILE   "Can't play the file!"
#define STR_ID_CAN_NOT_PLAY_AUDIO   "Can't play audio."
#define STR_ID_CAN_NOT_PLAY_VIDEO   "Can't play video."
#define STR_ID_CODE_FORMAT   "Code format:"
#define STR_ID_COMPLETE_FORMAT   "Complete format!"
#define STR_ID_NAME    "Name"
#define STR_ID_START   "Start"
#define STR_ID_STOP    "Stop"
#define STR_ID_TIMEOUT "Timeout!"
#define STR_ID_DUMP_SUCCESS "Dump successfully!"
#define STR_ID_REBOOT_NOW "Reboot now"
#define STR_ID_AUDIO_PID "Audio PID:"
#define STR_ID_AUDIO_TYPE "Audio Type"
#define STR_ID_AUDIO_CH "Audio Channel"
#define STR_ID_CHINESE  "Chinese"
#define STR_ID_DATE_TIME "Date time:"
#define STR_ID_INFO "Info"
#define STR_ID_MANUAL "Manual"
#define STR_ID_MONO "Mono"
#define STR_ID_OK "OK"
#define STR_ID_COMFIRM "Comfirm"
#define STR_ID_ZERO "Zero"
#define STR_ID_INTERNET     "Internet"
#define STR_ID_TV_FORMAT    "TV Format"
#define STR_ID_RESOLUTION "Resolution"
#define STR_ID_SET_PASSWD   "Set Password"
#define STR_ID_NO_TV_CH    "No TV channel!"
#define STR_ID_NO_RADIO_CH    "No Radio channel!"
#define STR_ID_LCN              "LCN"
#define STR_ID_ACU			"ACU"
#define STR_ID_ASPECT_RATIO "Aspect Ratio"
#define STR_ID_INFORMATION  "Information"
#define STR_ID_AUDIO_BYPASS "Bypass"
#define STR_ID_OSD_LANGUAGE "OSD Language"
#define STR_ID_SEARCH_MODE  "Search Mode"
#define STR_ID_COUNTRY           "Country"

#define STR_ID_SORT_BY_ID   "By Service ID"
#define STR_ID_SORT_BY_NAME "By Service Name"
#define STR_ID_SORT_BY_TP   "By TP"
#define STR_ID_POWER_ON_TIME    "Power On Time"
#define STR_ID_POWER_OFF_TIME   "Power Off Time"
#define STR_ID_BOOK_LIST    "Book List"
#define STR_ID_REGION_TIME "Region and Time"
#define STR_ID_FRE_ERROR    "Frequency set error!"
#define STR_ID_START_SEARCH "Start Search"
#define STR_ID_UPDATE_SUCCESS   "Update success!"
#define STR_ID_ENCOD   "Encoding"
#define STR_ID_AUTO_ROLL   "Auto roll"
#define STR_ID_DISABLE      "Disable"
#define STR_ID_ENABLE      "Enable"

#define STR_ID_RECORD_FILTER        "Record Filter"
#define STR_ID_FREE_SCAN_TAG        "Freescan"
#define STR_ID_FREE_SCAN_RECORD     "Free Scan Recording"

#endif

#if PVR_RECORDING_POSTER_STYLE
#define STR_ID_NO_EPG_EVENT "No EPG Event"
#if PVR_PREVIEW_SUPPORT
#define STR_ID_PREVIEW_FAILED "Preview failed"
#endif
#endif

#if THEME_CLASSIC_PURPLE || THEME_SKY_BLUE || THEME_CLASSIC_DARK || THEME_GRID_PURPLE
#define STR_ID_PROGRAM  "Program"
#define STR_ID_OPTION   "Option"
#define STR_ID_USB  "USB"
#endif

#if (THEME_CLASSIC_BLUE > 0)
#define STR_ID_ROLL_LINES "Roll lines"
#define STR_ID_KEY_PRESS "Key Press"
#define STR_ID_PRESS_L_TO_R "Press Left / Right"
#define STR_ID_USB_SPEED "USB Speed"
#define STR_ID_USB_SPEED_TEST "USB Speed Test"
#endif



#if (DEMOD_DVB_S > 0)
#define STR_ID_SUPER_BLIND_SEARCH "Super Blind Search"
#endif

#if (DEMOD_DVB_C || DEMOD_DTMB || DEMOD_ISDBT || DEMOD_DVB_T)
#define STR_ID_DVBC_SEARCH      "DVBC Search"
#define STR_ID_SYMBOL_RATE      "Symbol Rate(KS/s)"
#define STR_ID_TO_FULL_SEARCH    "Delete all channels to full search?"
#define STR_ID_DTMB_SEARCH      "DTMB Search"
#define STR_ID_ISDBT_SEARCH "ISDBT Search"
#define STR_ID_DVBT_SEARCH      "DVB T2 Search"
#define STR_ID_ANTENNA_POWER     "Antenna Power"
#define STR_ID_MAIN_FREQ        "Main Frequency"
#define STR_ID_MAIN_FREQUENCY   "Main Frequency(MHz)"
#define STR_ID_FULL_SEARCH      "Full Search"
#define STR_ID_LOCK_FAILED      "Lock Failed!"
#define STR_ID_START_FREQ       "Start Frequency(MHz)"
#define STR_ID_END_FREQ         "End Frequency(MHz)"
#define STR_ID_FREQUENCY        "Frequency(MHz)"
#define STR_ID_CHANNEL_SEARCH   "Channel Search"
#define STR_ID_AUTO_SEARCH      "Auto Search"
#define STR_ID_MANUAL_SEARCH    "Manual Search"
#define STR_ID_SEARCH_SETTING    "Search Setting"
#define STR_ID_DEL_ALLCHANNEL   "Delete all channels to auto search?"
#define STR_ID_DEL_ALL_CHANNEL  "Delete all channels to search?"
#define STR_ID_BANDWIDTH        "Bandwidth(M)"
#define STR_ID_SHORT_CIRCUIT     "Antenna Short Circuit!"
#define STR_ID_FREQ_LESS_THAN        "Frequency error, should not less than"
#define STR_ID_FREQ_LARGER_THAN        "Frequency error, should not larger than"
#define STR_ID_SYM_LARGER_THAN        "Symbol rate error, symbol should not larger than"
#define STR_ID_SYM_LESS_THAN        "Symbol rate error, symbol should not less than"
#endif

#if (AUDIO_DESCRIPTOR_SUPPORT >0)
#define STR_ID_AUDIO_DESCRIPTION    "Audio Description"
#if (AUDIO_DESCRIPTOR_VOLUME_SET_SUPPORT >0)
#define STR_ID_AD_VOL_OFFSET    "AD Volume Offset"
#endif
#endif

#if USB_SAFELY_REMOVE_SUPPORT
#define STR_ID_USB_BUSY "USB is busy,please wait..."
#endif
#if (SHUTDOWN_MODE_SUPPORT > 0)
#define STR_ID_SHUTDOWN_MODE "Shutdown Mode"
#define STR_ID_SHUTDOWN_REBOOT_INFO "Press the OK to execute Reboot, and press the Cancel to execute shutdown."
#endif
#if (START_CHANNEL_SUPPORT > 0)
#define STR_ID_START_CHANNEL "Start Channel"
#endif
#if (NETWORK_SUPPORT > 0)
#define STR_ID_WIRED        "Wired"
#define STR_ID_INVALID_IP        "Invalid IP!"
#define STR_ID_DNS1_ERROR    "Invalid DNS1!"
#define STR_ID_DNS2_ERROR    "Invalid DNS2!"
#define STR_ID_SCAN        "Scan"
#define STR_ID_NETWORK  "Network Setting"
#define STR_ID_NO_CONNECT       "No Connection!"
#define STR_ID_CONNECTTING      "Connecting..."
#define STR_ID_CONNECTED        "Connected!"
#define STR_ID_CONNECT  "Connect"
#define STR_ID_CONNECT_TIP "Please connect network!"
#define STR_ID_DISCONNECT   "Disconnect"
#define STR_ID_SERVER_FAIL  "Network error!"
#define STR_ID_STATIC_IP    "Static IP"
#define STR_ID_DEVICE   "Device"
#define STR_ID_IPADDR           "IP Address"
#define STR_ID_SUB_MASK         "Subnet Mask"
#define STR_ID_GATE_WAY         "Gate Way"
#define STR_ID_SETUP    "Setup"
#define STR_ID_USERNAME "Username"
#define STR_ID_SUB_ERROE    "Invalid Subnet Mask!"
#define STR_ID_GATE_WAY_ERROR "Invalid Gate Way!"
#define STR_ID_DNS_COMMON    "DNS1 and DNS2 can not be the same!"
#define STR_ID_NET_ADDR_ERROR    "Network address is wrong"
#define STR_ID_STATE    "Status"
#define STR_ID_LINK_NETWORK     "Please link to wired network or Wi-Fi."
#define STR_ID_HIGH "High"
#define STR_ID_LOW "Low"
#define STR_ID_TUNER "Tuner"
#endif

#if (NETAPPS_SUPPORT > 0)
#define STR_ID_PLAY_ERROR          "Play error!"
#define STR_ID_PLAY_END            "Play end!"
#define STR_ID_PLEASE_LOGIN     "Please login first!"
#define STR_ID_RELOGIN       "Save Success! Are you sure to relogin?"
#define STR_ID_CLOUD   "Cloud"
#define STR_ID_LOCAL   "Local"
#define STR_ID_IMPORT        "Import"
#define STR_ID_INTER_ERROR   "Internal error!"
#define STR_ID_UNKNOWN_ERROR    "Unknown error!"
#define STR_ID_AUTH_ERROR    "Authentication error!"
#define STR_ID_NO_RESULTS   "No results!"
#define STR_ID_SERVER_URL   "Server URL"
#define STR_ID_SOCKS5       "SOCKS5 Setting"
#define STR_ID_SETTING   "Setting"
#define STR_ID_SYSTEM_BUSY_WAIT   "System Busy, Please Wait!"
#define STR_ID_BUSY_TRY_AGAIN   "System busy, please try again!"
#define STR_ID_UPDATING   "Updating..."
#define STR_ID_LOGIN_WAIT   "Login, please wait..."
#define STR_ID_UPDATE_FAILED    "Update failed!"
#define STR_ID_SELECT_PLAY   "Select/Play"
#define STR_ID_NET_CREATE_TIME "Create Time"
#define STR_ID_NET_EXPIRE_TIME "Expire Time"
#define STR_ID_FAVORITES    "Fav List"
#define STR_ID_ED_CH_OK         "Edit Channel Success!"
#define STR_ID_AD_CH_OK         "Add Channel Success!"
#define STR_ID_DEL_CH_OK         "Del Channel Success!"
#endif

#if HDMI_CEC_SUPPORT
#define STR_ID_HDMI_CEC  "HDMI CEC"
#define STR_ID_USE_TV_REMOTE_CONTROL  "Use TV Remote Control"
#define STR_ID_TV_ON_STB_ACTIVITY  "TV On -> STB Activity"
#define STR_ID_STB_STANDBY_TV_ACTIVITY  "STB Standby -> TV Activity"
#define STR_ID_CEC_SYSTEM_AUDIO  "CEC System Audio"
#endif

#if (GAME_ENABLE > 0)
#define STR_ID_SNAKE    "Snake"
#define STR_ID_TETRIS    "Tetris"
#define STR_ID_GAME_CENTER    "Game Centre"
#define STR_ID_LINE   "Line"
#define STR_ID_LEVEL   "Level"
#define STR_ID_READY   "Ready"
#define STR_ID_GAMEOVER "Game Over!"
#define STR_ID_SCORE   "Score"
#endif

#if LCN_SUPPORT
#define STR_ID_LCN_SETTING        "LCN Setting"
#define STR_ID_SORT_BY_LCN        "By LCN"
#define STR_ID_SORT_BY_LCN_MOVE   "Can't move"
#endif
#if ((NET_UPGRADE_SUPPORT > 0) || (OTA_SUPPORT > 0))
#define STR_ID_UPDATE_NEW_VER "Are you sure to upgrade to new version"
#endif
#if (NET_UPGRADE_SUPPORT > 0)
#define STR_ID_NET_UPGRADE "Upgrade By Net"
#define STR_ID_PROTOCOL   "Protocol"
#define STR_ID_GET_UP_INFO "Get upgrade information..."
#define STR_ID_FAIL_GET_UPGRADE_SETTING "Failed to get upgrade setting!"
#define STR_ID_FILE_PARSE_ERROR "Upgrade setting file parse error!"
#define STR_ID_SETTING_FILE_ERROR "Upgrade setting file info error!"
#define STR_ID_RECOVERY_PARTITION_INVALID "Recovery partition invalid!"
#define STR_ID_HARDWARE_VERSION_MISMATCH "Hardware version mismatch!"
#define STR_ID_MANUFACTURE_ID_MISMATCH "Manufacture ID mismatch!"
#define STR_ID_MODEL_SN_MISMATCH "Model SN mismatch!"
#define STR_ID_FIREWARE_NEWEST "Current firmware is the newest!"
#define STR_ID_INVALID_URL "Invalid URL!"
#define STR_ID_STB_INFO_PARSE_ERROR "STB information file parse error!"
#define STR_ID_USER_CANCEL "User cancelled!"
#define STR_ID_NOT_SUPPORT_SAFE_UPGRADE "Chip doesn't support safe upgrade!"
#define STR_ID_SOFTWARE_ERROR "Upgrade failed, please check!"
#define STR_ID_DL_FW "Downloading firmware..."
#define STR_ID_FIRMWARE_FAILED "Firmware error occur!"
#define STR_ID_DL_RECOVERY_OS "Downloading Recovery OS..."
#define STR_ID_RECOVERY_OS_FAILED "Recovery OS error occur!"
#define STR_ID_RECOVERY_OS_SUCC "Recovery OS is ready!"
#endif

#if (PARENTAL_LOCK_SUPPORT > 0)
#define STR_ID_PARENT_GUID    "Parental Guidance"
#define STR_ID_PARENTAL_LOCK    "Parental Lock"
#endif

#if (OTA_SUPPORT > 0)
#define STR_ID_OTA_UPGRADE  "OTA Upgrade"
#define STR_ID_OTA_UPDATE_FAILD            "OTA upgrade failed!"
#define STR_ID_CHECK_OTA               "Please wait while checking software..."
#define STR_ID_CHECK_FAILED            "Could not found upgrade software!"
#define STR_ID_VERSION_INVAILD         "It is the latest software!"
#define STR_ID_FLUSH_FLASH             "Waiting...Please don't power off while upgrading!"
#define STR_ID_RECEIVE_DATA            "Receiving data, please wait... "
#define STR_ID_UPGRADE_SOFTWARE        "Do you want to upgrade software?"
#endif

#if AUTO_UPDATE_SUPPORT || PROGRAM_NETUP_SUPPORT
#define AUTO_UPDATE_SHOW_INFO "Program is updating..."
#define STR_ID_ACU_CLOSE "Please close ACU first."
#endif

#if PROGRAM_NETUP_SUPPORT
#define STR_ID_PROGRAM_NETUP_TITLE "Program net update"
#define STR_ID_PROGRAM_NETUP_CLOSE "Please close Program net update first."
#define STR_ID_CYCLE_TIME "Cycle time"
#endif

#if PLAYBACK_SPEED_SUPPORT
#define STR_ID_AUDIO_SPEEDMODE "Audio Speed Mode"
#define STR_ID_PLAYBACK_SPEED "Playback Speed"
#endif

#if (SAMBA_SUPPORT > 0)
#define STR_ID_MAX_DIR    "Achieve maximum directory!"
#define STR_ID_SAMBA    "Samba"
#define STR_ID_LOGIN "Login"
#endif

#if (POWER_ON_CONTROL_SUPPORT > 0)
#define STR_ID_POWERONCONTROL "Power On Control"
#endif

#if (VPN_SUPPORT > 0)
#define STR_ID_VPN_SETTING "VPN Setting"
#endif

#if (NETAPPS_SUPPORT > 0)
#define STR_ID_RETURN   "Return"
#define STR_ID_REFRESH  "Refresh"
#define STR_ID_LOGIN_OK   "Login success!"
#define STR_ID_LOGIN_FAIL   "Login failed!"
#define STR_ID_NET_IPTV "IPTV"
#define STR_ID_IPTV_LISTVIEW    "List View"
#define STR_ID_IPTV_FAV    "Favorites"
#define STR_ID_IPTV_ENTER_LINK    "Enter Link"
#define STR_ID_IPTV_IMPORT_LINK    "Import Link"
#define STR_ID_IPTV_ADD_LINK    "Add Link"
#define STR_ID_IPTV_ED_LINK    "Edit Link"
#define STR_ID_POWERON_PLAY "Power On Play"
#define STR_ID_IPTV_LOCAL_LIST   "IPTV Cloud List"
#define STR_ID_IPTV_NO_FIND_SER_XML   "Not find iptv_server.xml"
#define STR_ID_IPTV_BANDWIDTH "Bandwidth"
#define STR_ID_WAITING_CONNECTION "Waiting for connection"
#endif

#if (KERNEL_SUPPORT_FLAG > 0)
#define STR_ID_KERNEL_VER         "Kernel"
#endif

#if (DLNADMR_SUPPORT > 0)
#define STR_ID_STOP_DMR_INFO    "Sure to Stop DMR?"
#define STR_ID_DMR_START_ERR          "DLNA render error! Please try again."
#endif

#if (DLNADMP_SUPPORT > 0 || DLNASAT2IP_SUPPORT > 0)
#define STR_ID_SERVER_ERROR "Internal server error"
#define STR_ID_NO_DATA_IN_SUBDIR "No data in subdirectories"
#define STR_ID_FILTER_EMPTY "The result of filtration is empty"
#endif

#if (DLNADMS_SUPPORT > 0)
#define STR_ID_DMS_START          "DLNA DMS Running!"
#define STR_ID_DMS_START_ERR          "DLNA DMS error! Please try again."
#define STR_ID_STOP_DMS_INFO    "Sure to Stop DMS?"
#define STR_ID_DMS_USB_ERR    "No usb devices"
#define STR_ID_DMS_FILE_ERR    "U Disk get files error"
#endif

#if (PLUGINSTORE_SUPPORT > 0)
#define STR_ID_NET_PLUGIN_PORTAL  "Plugin Portal"
#define STR_ID_NET_PLUGIN_STORE  "Plugin Store"
#define STR_ID_NET_PLUGIN_INSTALL_TIP  "Install update or uninstall plugins"
#define STR_ID_NO_RESOURCE "No more system resources"
#define STR_ID_PLUGIN_ERR          "Plugin error! Please try again or check network and setting."
#define STR_ID_PLUGIN_GET_DATA_SLOW "Getting data is slow, please wait or try again!"
#define STR_ID_PLAY_URL_NULL       "Play url is NULL!"
#define STR_ID_LIST_VIEW_TITLE            "Categories"
#define STR_ID_INSTALL "Install"
#define STR_ID_INSTALLED "Installed"
#define STR_ID_UNINSTALL "Uninstall"
#define STR_ID_NOT_INSTALLED "Not Installed"
#define STR_ID_PLUGIN_ONLINE_TV "Online TV"
#define STR_ID_PLUGIN_INSTALING_TIP "Installing,Wait please"
#define STR_ID_PLUGIN_UNINSTALL_FIN "Uninstall finished!"
#endif

#if (WIFI_SUPPORT > 0)
#define STR_ID_WIFI_SET "Wifi Setting"
#define STR_ID_NO_WIFI  "No Wifi device!"
#define STR_ID_OPEN_WIFI        "Please open wifi!"
#define STR_ID_NO_AP    "AP Not Found!"
#define STR_ID_ENCRYPTION   "Encryption"
#define STR_INPUT_ESSID    "Please input ESSID!"
#define STR_ID_SCANNING_HIDDEN_AP "Scanning hidden AP"
#endif

#if MIRACAST_SUPPORT
#define STR_ID_CANT_MIRACAST "Miracast is not supported!"
#define STR_ID_WIFI_SELECT "Wi-Fi Select"
#define STR_ID_MIRACAST_EXIT "Sure to exit miracast?"
#endif
#if (BLUETOOTH_SUPPORT > 0)
#define STR_ID_BLUETOOTH "Bluetooth Setting"
#define STR_ID_BLUETOOTH_DO_NOT_INIT  "Bluetooth do not init,please wait!"
#define STR_ID_SINK      "Sink"
#define STR_ID_NO_BLUETOOTH     "No bluetooth device!"
#define STR_ID_BT_NO_SUPPORTED  "Bluetooth device is not supported!"
#define STR_ID_OPEN_BLUETOOTH   "Please open bluetooth!"

#define STR_ID_LINK_BLUETOOTH          "Please use other bluetooth connect to this device"
#define STR_ID_BLUETOOTH_CONNECT_FAILER     "Bluetooth connect failer as slave device!"
#define STR_ID_BLUETOOTH_SOURCE_CONNECT_ING     "Bluetooth is just connecting,please wait!"
#define STR_ID_BLUETOOTH_CONNECT_ING        "Bluetooth is connecting as slave device!"
#define STR_ID_BLUETOOTH_CONNECT_DIS        "Bluetooth is connected as master device,please disconnect!"
#endif

#if (MOD_3G_SUPPORT > 0)
#define STR_ID_AREA "Area"
#define STR_ID_OPERATOR "Operator"
#define STR_ID_DIAL_NUMBER "Dial Number"
#endif

#if (UNICABLE_SUPPORT > 0)
#define STR_ID_UNICABLE_SET    "Unicable Setting"
#endif

#if (FACTORY_TEST_SUPPORT > 0)
#define STR_ID_FACTORY_TEST "Factory Test"
#define STR_ID_RS232_SHORT  "RS232 Short"
#define STR_ID_22K_CONTROL "22K Control"
#define STR_ID_LNB_SHORT    "LNB Short"
#define STR_ID_LNB_VOLTAGE  "LNB Voltage"
#define STR_ID_OUTPUT_MODE  "OutPut Mode"
#define STR_ID_SCART_VOLRAGE    "Scart Voltage"
#define STR_ID_IP_STATE "IP Status"
#define STR_ID_USB_STATE    "USB Status"
#endif

#ifdef SUPPORT_SCART
#define STR_ID_SCART                 "TV-Scart"
#endif

#if (HIGH_DYNAMIC_RANGE_SUPPORT > 0)
#define STR_ID_HDR_MODE              "HDR Setting"
#endif

#if (TKGS_SUPPORT > 0)
#define STR_ID_TKGS_UPGRATE              "TKGS Upgrade"
#define STR_ID_OPERATE_MODE             "Change Operating Mode"
#define STR_ID_VISIABLE_LOCATION     "Set Update Frequency"
#define STR_ID_PREFERRED_LIST           "Set Preferred List"
#define STR_ID_START_UPDATE             "Start Update"
#define STR_ID_TKGS_VERSION             "TKGS Version"
#define STR_ID_HIDDEN_LOCATION             "Hidden Locations"
#define STR_ID_CUSTOMER                     "Customer"
#define STR_ID_TKGS_CHECK_VERSION  "Checking version.please wait ..."
#define STR_ID_TKGS_UPGRADE_WAIT  "Tkgs upgrading,Please wait ..."
#define STR_ID_TKGS_SAVE_WAIT   "Save data,Please wait ..."
#define STR_ID_TKGS_ENSURE_EXIT      "Are you sure exit upgrade?"
#define STR_ID_TKGS_UPGRADE_FAIL        "TKGS Upgrade Failure!"
#define STR_ID_TKGS_SAME_Version        "Local version is same as Service Version.Do you want countinue?"
#define STR_ID_TKGS_SET_LOCATION "Please set update frequency first!"
#define STR_ID_TKGS_CANT_WORK             "Can't work! Pls check TKGS profile!"
#define STR_ID_LOCATION_EXIST           "Location already exist!"
#endif

#if (SAT2IP_SERVER_SUPPORT > 0)
#define STR_ID_SAT2IP_SETTING      "Sat2IP Setting"
#define STR_ID_SAT2IP_MODE      "Sat2IP Mode"
#define STR_ID_SAT2IP_PRI      "Sat2IP Priority"
#define STR_ID_SAT2IP_PLAY         "Start Sat2IP play!"
#define STR_ID_SAT2IP_STOP_TIP1    "Please set \"Sat2IP Mode\" off or set \"Conflicting Operation\" enable first!"
#define STR_ID_SAT2IP_STOP_TIP2    "Please stop Sat2IP service first, eg: set \"Sat2IP Mode\" off!"
#define STR_ID_SAT2IP_CANNOT_BOOK  "Sat2IP is playing, ignore book!"
#endif

#if (SAT2IP_CONFIGURE_SUPPORT > 0)
#define STR_ID_SAT2IP_DMS_RTSP_SUP      "DMS RTSP Support"
#define STR_ID_SAT2IP_SAME_IP_CLIENT      "Same IP Clients"
#define STR_ID_SAT2IP_SIMPLE      "Simple"
#define STR_ID_SAT2IP_MULT      "Multiple"
#endif

#if (DVB2IP_SERVER_SUPPORT > 0 || SAT2IP_CONFIGURE_SUPPORT > 0)
#define STR_ID_SAT2IP_CONFLICT_OPERAT      "Conflicting Operation"
#endif

#if (DVB2IP_SERVER_SUPPORT > 0)
#define STR_ID_DVB2IP_SETTING           "DVB2IP Setting"
#define STR_ID_DVB2IP_PLAY              "Start DVB2IP play!"
#define STR_ID_DVB2IP_STOP_TIP          "Please stop DVB2IP service first!"
#define STR_ID_DVB2IP_START_FAILED      "Start DVB2IP server failed!"
#define STR_ID_DVB2IP_SERVER            "DVB2IP Server"
#define STR_ID_DVB2IP_CLIENT            "Connected Clients:"
#define STR_ID_DVB2IP_EXIT_TIP          "Exit this window will stop DVB2IP server!"
#define STR_ID_DVB2IP_SURE_STOP         "Sure to stop DVB2IP server?"
#define STR_ID_INDEPENDENT              "Independent"
#define STR_ID_FOLLOWING                "Following"
#define STR_ID_MASTER                   "Master"
#define STR_ID_DVB2IP_MODE              "DVB2IP Mode"
#define STR_ID_DVB2IP_PRIORITY          "DVB2IP Priority"
#define STR_ID_CLIENT_CONTROL           "Client Control"
#define STR_ID_DVB2IP_START             "Start DVB2IP Server"
#define STR_ID_DVB2IP_CANNOT_BOOK       "DVB2IP is playing, ignore book!"
#endif
#if DVB_CLOUD_SUPPORT
#define STR_ID_CLOUD_SELECTED_SATELLITES "Do you want to save selected satellites?"
#endif
#if (CA_SUPPORT > 0)
#define STR_ID_EXSHIFT_SET  "EX-Shift Setting"
#endif

#if (AUTO_STANDBY_SUPPORT > 0)
#define STR_ID_AUTO_STANDBY    "Default AutoStandby"
#define STR_ID_SLEEP_SET       "Sleep Setting"
#endif

#if (NO_SIGNAL_AUTO_STANDBY_SUPPORT > 0)
#define STR_ID_NO_SIGNAL_AUTO_STANDBY "No Signal Auto Standby"
#endif

#if (UART_SUPPORT > 0)
# define STR_ID_BAUD_RATE_ADJUST "Baud Rate Adjust"
#endif




#if (CI_SUPPORT > 0)
#define STR_ID_CI_INFO "CI Information"
#define STR_ID_SLOT1_NO_CARD "Slot 1: No Card"
#endif

#if (RF_MODULATOR_SUPPORT > 0)
#define STR_ID_RF_SEARCH		"RF Output"
#if (RF_RT500 > 0)
#define STR_ID_CHANNEL_STEP		"Band Width"
#define STR_ID_CHANNEL_NO		"Channel NO"
#define STR_ID_SOUND_MOD		"Sound Mode"
#endif
#if (RF_RT534 > 0)
#define STR_ID_RF_ON_OFF		"Rf Power"
#define STR_ID_RF_CH3_CH4		"Rf Mode"
#endif
#endif

#if (NET_SEARCH_SUPPORT)
#define STR_ID_NET_SEARCH			"Net Search Setting"
#define STR_ID_NET_SERVER_NAME  	"Server Name"
#define STR_ID_NET_SERVER_URL   	"Server Url"
#define STR_ID_NET_STREAM_URL   	"Stream Url"
#define STR_ID_NET_STREAM_LIST		"Stream List"
#define STR_ID_NET_SERVER_LIST		"Server List"
#define STR_ID_NET_START_SEARCH 	"Net Start Search"
#define STR_ID_SERVER_SERACH		"Server Search"
#define STR_ID_STREAM_SERACH		"Stream Search"
#define STR_ID_PRESET_SEARCH    	"Preset Search"
#define STR_ID_IMPORT_SUCCESS		"Import Successfully!"
#define STR_ID_IMPORT_ERROR			"Import Error!Plase Check Json Format!"
#define STR_ID_IMPORT_FILE_ERROR	"Import Error!"
#define STR_URL_TOO_LONG			"The Url Too Long! Cat't edit!"
#endif

#if (WEBLET_SUPPORT > 0)
#define STR_ID_WEBLET "Weblet"
#define STR_ID_WEB_FINDER   "Web Finder"
#define STR_ID_WEB_REMOTE   "Web Remote"
#define STR_ID_WEB_LOGIN_TIP "Please scan the QR code"
#endif

#ifdef TRANSMISSION_SUPPORT
#define STR_ID_DELETE_TORRENT_FILE "Do you want to delete torrent file only?"
#endif

#if (BOOT_AD_SUPPORT > 0)
#define STR_ID_BOOT_VIDEO_AD "Video Boot"
#define STR_ID_BOOT_LOGO_AD  "Logo Boot"
#endif

#if (SAT_FINDER_SUPPORT > 0)
#define STR_ID_DVBFINDER   "DVB Finder"
#define STR_ID_DVBFINDER_TIP   "First you need to download APP and install it on your phone, then scan dvbfinder."
#define STR_ID_FIND_SAT   "Find Satellite"
#endif

#if (CI_SUPPORT > 0)
#define STR_CI_INDORMATION "CI Information"
#endif

#if (MERGE_DB_SUPPORT > 0)
#define STR_ID_MERGE_DB_BY_NET "Merge DB By Net"
#endif

#if (PANEL_SETTING_SUPPORT > 0)
#define STR_ID_PANEL_SET            "Panel Setting"
#define STR_ID_LED_BRIGHTNESS       "LED Brightness"
#define STR_ID_LED_DISPLAY          "LED Display"
#define STR_ID_LED_STANDBY          "Standby Show Time"
#endif

#if (BOUQUET_SUPPORT > 0)
#define STR_ID_BOUQUET    "Bouquet"
#define STR_ID_NO_BOUQUET    "No Bouquet!"
#endif

#if (PVR_STANDBY_TIP_SUPPORT > 0)
#define STR_ID_PVR_END_STANDBY "PVR End Goto Standby"
#define STR_ID_PVR_END_STANDBY_TIP "Automatic going to standby in:"
#endif

#if (NO_SIGNAL_ALERT_TIP_SUPPORT > 0)
#define STR_ID_NO_SIGNAL_ALERT_TIP "No Signal Alert Tip"
#define STR_ID_RECEPTION "Reception trouble"
#define STR_ID_SIGNAL_WARNNING "Check the antenna cable connection. If the antenna cable is well connected, perform one of the two operations below by pressing the key of the remote control."
#define STR_ID_SIGNAL_CLEAR "Clear and find all channels"
#define STR_ID_SIGNAL_FIND "Only find again all channels"
#endif

#if (FM_SUPPORT > 0)
#define STR_ID_FM_SETTING      "FM Setting"
#define STR_ID_FM_BAND         "Band"
#define STR_ID_FM_ANT_GAIN     "ANT.Gain"
#define STR_ID_FM_AUTO_SEARCH  "FM Auto Search"
#define STR_ID_FM_PLAY         "FM Play"
#define STR_ID_FM_NO_FIND_FREQ "No find this frequency"
#define STR_ID_FM_NO_FIND      "No find frequency"
#define STR_ID_FM_STOR_MODE    "Storage mode"
#define STR_ID_FM_FREQ_MODE    "Frequency mode"
#define STR_ID_FM_FREQ_OUT     "Frequency out of range"
#define STR_ID_FM_NO_FREQ      "FM radio not exist"
#define STR_ID_FM_EXIST        "FM radio exist"
#define STR_ID_FM_SEARCH_ERROR "FM search error"
#define STR_ID_FM_CHANGE_MODE  "This is frequency mode, please change to storage mode!"
#define STR_ID_FM_EXIT_DEL     "Exit Delete"
#define STR_ID_FM_STOP_REC     "Please stop client play first"
#define STR_ID_FM_PRE_FOR_DVB2IP     "Go back mainmenu first!"
#define STR_ID_FM_NOT_FOLLOWING_MODE    "FM only support following mode, please change!"
#define STR_ID_STOP_DVB2IP_FM           "The client is using,exit this window will stop DVB2IP server,are you sure?"
#endif
#if (APPLETS_SUPPORT > 0)
#define STR_ID_INSTALL "Install"
#define STR_ID_INSTALLED "Installed"
#define STR_ID_UNINSTALL "Uninstall"
#define STR_ID_BUILTIN  "Builtin"
#define STR_ID_APPLETS_RUN_ERROR  "Applet run error!"
#define STR_ID_APPLETS_UNINSTALL_TIP  "Do you want to uninstall?"
#define STR_ID_APPLETS_INSTALL_TIP  "Do you want to install?"
#define STR_ID_NET_APPLETS "Applets"
#define STR_ID_APPLETS_AUTH_ERROR   "Authorization error,please try again later!"
#define STR_ID_APPLETS_SET_SERVER   "Set applets server successfully!"
#define STR_ID_APPLETS_CLOSE_TIP   "Please close the applet first!"
#define STR_ID_APPLETS_GET_LIST_TIP   "Please get list first!"
#define STR_ID_APPLETS_UNEXIST   "The applet is unexist!"
#define STR_ID_APPLETS_OPEN_FAIL   "Open failed!"
#define STR_ID_APPLETS_LIMIT_TIP  "The size is too small"
#define STR_ID_APPLETS_FAV_TIP  "Do you want to fav it?"
#define STR_ID_APPLETS_UNFAV_TIP  "Do you want to unfav it?"
#define STR_ID_APPLETS_UPDATE_TIP  "Do you want to update?"
#define STR_ID_APPLETS_DOWNLOAD_ERROR  "Download error!"
#define STR_ID_APPLETS_CRC_ERROR  "CRC error!"
#define STR_ID_APPLETS_FILE_ERROR  "Open file error!"
#define STR_ID_APPLETS_MKDIR_ERROR  "Mkdir error!"
#define STR_ID_APPLETS_UNZIP_ERROR  "Unzip error!"
#define STR_ID_APPLETS_OBJ_OPEN_ERROR  "Obj open error!"
#define STR_ID_APPLETS_DECRYPT_ERROR  "Decrypt error!"
#endif

#ifdef SUBTTRANS_SUPPORT
#define STR_ID_ST_ENABLE_SUBT_STR "Please Enable Subtitle First."
#define STR_ID_ST_ENABLE_ST_STR "Enable Subtitle Translation?"
#define STR_ID_ST_DISABLE_ST_STR "Disable Subtitle Translation?"
#define STR_ID_ST_ACT_ST_STR "Please Activate Subtitle Translation First."
#define STR_ID_ST_WAIT_START   "Waiting To Enable Subtitle Translation Function ..."
#define STR_ID_ST_TRANS "Translation"
#define STR_ID_SUBTTRANS_SWITCH_ON  "Translation::On"
#define STR_ID_SUBTTRANS_SWITCH_OFF "Translation::Off"
#define STR_ID_SUBTTRANS_NOT_SUPPORT "Only Support DVB Subtitle Mode"
#define STR_ID_ST_AUTO_OFF  "The selected subtitle does not support translation, translation function has been automatically turned off."
#endif

//Not translated
#define STR_ID_BLANK " "
#define STR_ID_TP "TP"
#define STR_ID_WIFI "WIFI"
#define STR_ID_RNDIS "RNDIS"
#define STR_ID_FARSI    "Farsi"
#define STR_ID_DNS1 "DNS1"
#define STR_ID_DNS2 "DNS2"
#define STR_ID_PID   "PID"
#define STR_ID_PPPOE   "PPPoE"
#define STR_ID_3G   "3G"
#define STR_ID_DVBS "DVB-S"
#define STR_ID_DVBS2 "DVB-S2"
#define STR_ID_FTA      "FTA"
#define STR_ID_CAS      "CAS"
#define STR_ID_C        "DVB-C"
#define STR_ID_T2       "DVB-T2"
#define STR_ID_QAM              "QAM"
#define STR_ID_PCM  "PCM"
#define STR_ID_DLNA             "DLNA"

#define STR_ID_ARABIC   "Arabic"
#define STR_ID_ENGLISH   "English"
#define STR_ID_FRENCH   "French"
#define STR_ID_GERMAN   "German"
#define STR_ID_ITALIAN   "Italian"
#define STR_ID_PORTUGUESE   "Portuguese"
#define STR_ID_RUSSIAN   "Russian"
#define STR_ID_SPAIN   "Spain"
#define STR_ID_TURKISH   "Turkish"
#define STR_ID_VIETNAMESE   "Vietnamese"
#define STR_ID_CZECH    "Czech"
#define STR_ID_UKRAINIAN    "Ukrainian"
#define STR_ID_BULGARIAN     "Bulgarian"
#define STR_ID_THAI   "Thai"
#define STR_ID_POLISH    "Polish"
#define STR_ID_POLSKI    "Polski"
#define STR_ID_CHINESES    "Chinese"
#define STR_ID_POLSKI    "Polski"
#define STR_ID_SERBIAN    "Serbian"
#define STR_ID_ROMANIAN    "Romanian"
#define STR_ID_MACEDONIAN    "Macedonian"
#define STR_ID_GREECE    "Greece"
#define STR_ID_TURKEY    "Turkey"
#define STR_ID_ARMENIAN    "Armenian"
#define STR_ID_GEORGIAN  "Georgian"
#define STR_ID_KAZAHSTAN "Kazahstan"
#define STR_ID_KOREAN    "Korean"
#define STR_ID_KYRGYZ    "Kyrgyz"
#define STR_ID_LATVIAN   "Latvian"
#define STR_ID_LITHUANIAN "Lithuanian"
#define STR_ID_MYANMAR    "Myanmar"
#define STR_ID_UZBEK      "Uzbek"
#define STR_ID_INDONESIAN    "Indonesian"
#define STR_ID_ESTONIAN    "Estonian"
#endif
