#ifndef __APP_EUTEL_WINDOWS_H__
#define __APP_EUTEL_WINDOWS_H__

#ifdef  __cplusplus
extern "C" {
#endif /* __cplusplus */

//sattv ftaepg 20230629

#define WND_EUTEL_INFORMATION     "wnd_eutel_information"
#define WND_EUTEL_CHINFO          "wnd_eutel_chinfo"
#define WND_EUTEL_CHMORE          "wnd_eutel_chmore"
#define WND_EUTEL_CHLIST          "wnd_eutel_chlist"
#define WND_EUTEL_EPG             "wnd_eutel_epg"
#define WND_EUTEL_EPG2            "wnd_eutel_show"
#define WND_EUTEL_RECORDINFO      "wnd_eutel_recordinfo"
#define WND_EUTEL_LINEUP          "wnd_eutel_lineup"
#define WND_EUTEL_ANTENNA         "wnd_eutel_antenna"
#define WND_EUTEL_MAINTENANCE     "wnd_eutel_maintenance"
#define WND_EUTEL_COLLECT         "wnd_eutel_collect"
#define WND_EUTEL_SAT_LIST        "wnd_eutel_sat_list"
#define WND_EUTEL_SEARCH          "wnd_eutel_search"


#define STR_ID_TP_FRE               "TP Frequency"
#define STR_ID_TP_POLAR             "TP Polar"
#define STR_ID_TP_SYMBOL            "TP Symbol"

#define STR_ID_Transport_C          "Transport:"
#define STR_ID_MODULATION_C         "Modulation:"
#define STR_ID_FORMAT_C             "Format:"

#define STR_ID_LINEUP_C             "Lineup:"
#define STR_ID_CHANNEL_GENRES_C     "Channel Genres:"
#define STR_ID_MORE                 "More..."
#define STR_ID_CHANNL_FILTER        "Channel Filter"
#define STR_ID_CONTENT_FILTER       "Content Filter"
#define STR_ID_MARK_TIP             "Mark+/Mark-"
#define STR_ID_MARK_LIST            "Mark List"
#define STR_ID_MORE_INFO            "More Information"
#define STR_ID_CHANNEL_INFO         "Channel Information"
#define STR_ID_EVENT_INFO           "Event Information"
#define STR_ID_CUR_EVENT            "Current Event"
#define STR_ID_NEXT_EVENT           "Next Event"
#define STR_ID_NO_EVENT             "No Event!"
#define STR_ID_NO_EPG_INFO          "For complete program descriptions and thumbnail images, please insert USB stick!"
#define STR_ID_PARENTAL_LOCK        "Parental Lock"
#define STR_ID_START_INSTALL_LINEUP "Start Install Lineup"
#define STR_ID_SATTV_VER            "Sat.tv Version"
#define STR_ID_FTAEPG_ANT           "Sat.tv Antenna"
#define STR_ID_FTAEPG_SET           "Sat.tv Setting & Info"
#define STR_ID_VIEW_SET             "View Setting"
#define STR_ID_EPG_KEEP_SEC         "Keep Program View EPG"
#define STR_ID_NUM_PRESS_TIMEOUT    "Number Input Timeout"
#define STR_ID_FTAEPG_INFO          "Sat.tv Information"
#define STR_ID_FTAEPG_LOGS          "Sat.tv Updates"
#define STR_ID_FTAEPG_NO_LOGS       "No update record exists"
#define STR_ID_LINEUP_SWITCH        "Lineup Switch"
#define STR_ID_LINEUP_SELECT        "Lineup Select"
#define STR_ID_ALWAYS               "Always"
#define STR_ID_MAINT_SATS           "Maintenance Sats"

#define STR_ID_MAINT                "Maintenance"
#define STR_ID_NORMAL_MAINT         "Normal Maintenance"
#define STR_ID_MANUAL_MAINT         "Manual Maintenance"
#define STR_ID_AUTO_MAINT           "Auto Maintenance"
#define STR_ID_FORCE_MAINT          "Force Maintenance"
#define STR_ID_USB_MAINT            "USB Maintenance"
#define STR_ID_EPG_MAINT            "EPG Maintenance"
#define STR_ID_MAINT_OK             "Maintenance successed!"
#define STR_ID_MAINT_FAIL           "Maintenance failed!"
#define STR_ID_LINEUP_SWITCH_OK     "Lineup switch completed!"
#define STR_ID_LINEUP_SWITCH_FAIL   "Lineup switch failed!"
#define STR_ID_HOMETS_FAIL          "Home TS identify failed!"
#define STR_ID_LINEUP_NOT_FIND      "Lineup datas not find!"
#define STR_ID_NOT_ENHANCED_MODE    "Not Enhanced Mode!"
#define STR_ID_CONTINUE_EPG_MAINT   "Install successed, Continue to EPG maintenance?"
#define STR_ID_TOTAL_INSTALL_CH     "Total selected channels:"
#define STR_ID_TOTAL_SELECT_CH      "Total installed channels:"

#define STR_ID_MAINT_IDENTIFY_TS    "Identifing TS..."
#define STR_ID_MAINT_UPDATE_CAROUSEL "Updating carousels..."
#define STR_ID_MAINT_PROCESS_LINEUP "Processing lineups..."
#define STR_ID_MAINT_PROCESS_CHANNEL "Processing channels..."
#define STR_ID_MAINT_PROCESS_EPG    "Processing EPG..."
#define STR_ID_MAINT_MIGRATE_TS     "Checking Migration..."
#define STR_ID_MAINT_BLIND_SCAN     "Blind scanning..."
#define STR_ID_MAINT_LINEUP_SELECT  "Lineup selecting..."
#define STR_ID_RECEIVING_PROCESS    "Receiving Data..."
#define STR_ID_PARSING_PROCESS      "Parsing Data..."
#define STR_ID_WRITING_PROCESS      "Saving files..."

#define STR_ID_CH_GENERATING_TIP    "Channel is generating, please wait..."
#define STR_ID_EPG_GENERATING_TIP   "EPG is generating, please wait..."
#define STR_ID_EPG_EMPTY_TIP        "EPG is empty, sure to perform maintenance?"
#define STR_ID_EPG_OUT_DATE_TIP     "EPG is out of date, sure to perform maintenance?"
#define STR_ID_NORMAL_MAINT_TIP     "Do you want to start normal maintenance?"
#define STR_ID_MANUAL_MAINT_TIP     "Do you want to start manual maintenance?"
#define STR_ID_AUTO_MAINT_TIP       "Do you want to start auto maintenance?"
#define STR_ID_FORCE_MAINT_TIP      "Do you want to start force maintenance?"
#define STR_ID_ENHANCED_MAINT_TIP1  "Tips: Leave your receiver in standby during the night for automatic update!"
#define STR_ID_ENHANCED_MAINT_TIP2  "Tips: Please do not plug out USB stick!"

#define STR_ID_TIMERS               "TIMERS"
#define STR_ID_DAY                  "Day"
#define STR_ID_PAGE                 "Page"
#define STR_ID_PAGE_SUB             "Page-"
#define STR_ID_PAGE_PLUS            "Page+"
#define STR_ID_NOW                  "Now"
#define STR_ID_SOON                 "Soon"
#define STR_ID_EVENING              "Evening"
#define STR_ID_TODAY                "Today"
#define STR_ID_TOMORROW             "Tomorrow"
#define STR_ID_DAY_P1               "Day +1"
#define STR_ID_DAY_P2               "Day +2"
#define STR_ID_DAY_P3               "Day +3"
#define STR_ID_DAY_P4               "Day +4"
#define STR_ID_DAY_P5               "Day +5"
#define STR_ID_DAY_P6               "Day +6"
#define STR_ID_DAY_P7               "Day +7"
#define STR_ID_EPG_PROGRAM_VIEW     "Program View"
#define STR_ID_EPG_CHANNEL_VIEW     "Channel View"
#define STR_ID_EPG_VIEW_STYLE       "EPG View Style"
#define STR_ID_EPG_VIEW_DAYS        "EPG View Days"
#define STR_ID_EPG_EVENING_START    "EPG Evening Start"
#define STR_ID_KEEP_CHANNEL_FILTER  "Keep Channel Filter"

#define STR_ID_ENABLE_CERTIFICATION "Are you sure to factory reset to enable satellite with name of Certification?"
#define STR_ID_DISABLE_CERTIFICATION "Are you sure to factory reset to disable satellite with name of Certification?"

#define STR_ID_SWITCH_OTHER_SAT_TIP "Switch to Sat.tv other Satellite, please wait..."
#define STR_ID_SWITCH_FTA_EPG_TIP   "Switch to Sat.tv, please wait..."
#define STR_ID_SWITCH_FREE_SCAN_TIP "Switch to Free Scan, please wait..."

#define STR_ID_USB_STORAGE          "USB Storage"
#define STR_ID_MAINT_INFO           "Maintenance Information"
#define STR_ID_START_MAINT          "Maintenance started"
#define STR_ID_FINISH_MAINT         "Maintenance finished"
#define STR_ID_FAIL_MAINT           "Maintenance failed"
#define STR_ID_NEW_CH_ADDED         "New channel added"
#define STR_ID_NEW_CH_INSTALLED     "New channel installed"
#define STR_ID_CH_DATA_UPDATED      "Channel data updated"
#define STR_ID_EPG_DATA_UPDATED     "EPG data updated"
#define STR_ID_CH_INSTALLED         "Channels installed"
#define STR_ID_UPDATES              "Updates"
#define STR_ID_SUPER_ACCURACY       "Super Accuracy"

#define STR_ID_ZERO_DURATION        "00:00 - 00:00"

#define STR_ID_MEMORY_FREE          "Memory Free"
#define STR_ID_EXIT                 "Exit"

#ifdef  __cplusplus
}
#endif /* __cplusplus */

#endif
