#!/bin/bash
##############################################################################
# Blacker, liujh@nationalchip.com
# Copyright(C) 2013-2020, HangZhou NationalChip Science and Technology Corp.
# Generate Config.in file for theme
##############################################################################


BUILD_DIR=$(pwd)
config_theme_conf=${BUILD_DIR}/system/configin/Config.in.theme
config_theme_path=${BUILD_DIR}/theme/

config_lang_conf=${BUILD_DIR}/system/configin/Config.in.lang

##############################################################################
# Output Theme Config
##############################################################################
config_theme_list=`ls -l $config_theme_path |awk '/^d/{print $NF}'`

if [[ ${config_theme_list} == "" ]]; then
	echo -e "\033[031Cannot find any theme .\033[0m"
	exit 1
fi

echo "Theme List:" $config_theme_list

# output theme config
echo "#This File is generated by script tools, please not modify by hands." > $config_theme_conf
echo "" >> $config_theme_conf

echo "choice" >> $config_theme_conf
echo "    prompt \"Theme Config\"" >> $config_theme_conf
echo "" >> $config_theme_conf

for each_theme in $config_theme_list
do
	echo "config BR2_THEME_${each_theme}" >> $config_theme_conf
	echo "    bool \"${each_theme}\"" >> $config_theme_conf
	echo "" >> $config_theme_conf
done

echo "endchoice" >> $config_theme_conf
echo "" >> $config_theme_conf

echo "config BR2_THEME_TEMPLATE_NAME" >> $config_theme_conf
echo "    string" >> $config_theme_conf
for each_theme in $config_theme_list
do
	echo "    default \"${each_theme}\" if BR2_THEME_${each_theme}" >> $config_theme_conf
done

echo "" >> $config_theme_conf

# output lang config entry
echo "#This File is generated by script tools, please not modify by hands." > $config_lang_conf
echo "" >> $config_lang_conf

echo "menu \"Language Config\"" >>$config_lang_conf
for each_theme in $config_theme_list
do
    echo ${each_theme}
        echo "if BR2_THEME_${each_theme}" >> $config_lang_conf
        echo "source system/configin/Config.in.osd_lang.${each_theme}" >> $config_lang_conf
        echo "source system/configin/Config.in.kb_lang.${each_theme}" >> $config_lang_conf
        echo "endif" >> $config_lang_conf
        echo "" >> $config_lang_conf
done
echo "endmenu" >>$config_lang_conf

echo "" >> $config_lang_conf

if [[ -f .config ]]; then
    source .config
fi

for each_theme in $config_theme_list
do
    echo -e "\033[032mGenerate Language XML for ${each_theme}\033[0m"
    if [ ! -e ${BUILD_DIR}/theme/${each_theme}/language/i18n.xls ];then
        echo -e "\033[031mError: cannot find theme/${each_theme}/language/i18n.xls\033[0m"
        exit 1
    fi

    echo "Process theme: ${each_theme}/language "
    cd ${BUILD_DIR}/theme/${each_theme}/language
    python ${BUILD_DIR}/tools/language/i18n_multi.py ${BUILD_DIR}/theme/${each_theme}/language
    cd - 1> /dev/null
    echo ""

    # generate lang config for selected theme
    echo -e "\033[032mGenerate Language Config for ${each_theme}\033[0m"
    source ${BUILD_DIR}/scripts/factory_config_lang.sh ${each_theme}
done

