#!/bin/bash
##############################################################################
# Blacker, liujh@nationalchip.com
# Copyright(C) 2013-2020, HangZhou NationalChip Science and Technology Corp.
# Generate makefile for library which linker needs staticly
##############################################################################
compile_prefix=$1

if [[ $compile_prefix == "" ]];then
	echo -e "\033[031mWarning: Cannot find any library\033[0m"
	exit 1
fi

echo -e "\033[032mGenerate makefile for including header and library\033[0m"
#compile_prefix=`echo $compile_prefix | sed 's/ecos/elf/g'`
echo "CROSS-COMPILE:" $compile_prefix

BUILD_PATH=`pwd`

APP_PATH=${BUILD_PATH}/app
HEAD_PATH=include
LIB_PATH=lib/${compile_prefix}

#echo $LIB_PATH
#echo $HEAD_PATH

makefile_lib=${APP_PATH}/Makefile.a
rm -f $makefile_lib
echo "#This makefile is generated by bash script tool. " > $makefile_lib
echo "#Please do not edit it by yourself." >> $makefile_lib
echo "#Ref: scripts/factory_makefile_lib.sh" >> $makefile_lib
echo "" >> $makefile_lib

#echo "#Header file path to be included" >> $makefile_lib
#HEAD_LIST=`find ${HEAD_PATH} -name "*.h" | awk '{cmdstr="dirname "$0;system(cmdstr);}' | sort | uniq`
#HEAD_LIST=`find ${HEAD_PATH} -mindepth 1 -maxdepth 2| awk '{cmdstr="dirname "$0;system(cmdstr);}' | sort | uniq`
#HEAD_LIST=`echo "$HEAD_PATH $HEAD_LIST" | sed 's/ /\n/g' | sort | uniq`
#echo "Head Path:" $HEAD_LIST

#for each_head in $HEAD_LIST
#do
#	echo "CFLAGS  += -I\$(GXSRC_PATH)/${each_head}" >> $makefile_lib
#done
#echo "" >> $makefile_lib

#echo "#Library file path to be included" >> $makefile_lib
#LIB_LIST=`find ${LIB_PATH} -name "lib*.a" | awk '{cmdstr="dirname "$0;system(cmdstr);}' | sort | uniq`
#LIB_LIST=`echo "$LIB_PATH $LIB_LIST" | sed 's/ /\n/g' | sort | uniq`
#echo "LIB Path:" $LIB_LIST

#for each_lib in $LIB_LIST
#do
#	echo "LDFLAGS += -L\$(GXSRC_PATH)/${each_lib} " >> $makefile_lib
#done
#echo "" >> $makefile_lib

echo "#Library file to be linked" >> $makefile_lib
LIB_LIST=`find ${LIB_PATH} -name "lib*.a" -type f ! -name libpluginstore.a | awk -F"/" '{print $NF}'`
echo "LIB List:" $LIB_LIST

for each_lib in $LIB_LIST
do
	ldflag_lib_name=`echo $each_lib | sed -e 's/^lib//' -e 's/.a$//' `
	echo "LDFLAGS += -l${ldflag_lib_name}" >> $makefile_lib
done
echo "" >> $makefile_lib

# repeat once for avoiding error of static link algorithm
echo "#repeat once for avoiding link error" >> $makefile_lib
for each_lib in $LIB_LIST
do
	ldflag_lib_name=`echo $each_lib | sed -e 's/^lib//' -e 's/.a$//' `
	echo "LDFLAGS += -l${ldflag_lib_name}" >> $makefile_lib
done
echo "" >> $makefile_lib

echo "#PnP file to be linked" >> $makefile_lib
LIB_DOLBY="libdolby.a"
find_lib=`echo $LIB_LIST | grep -c $LIB_DOLBY `
if [[ $find_lib > 0 ]];then
	echo "CFLAGS +=  -DHAVE_LIB_DOLBY" >> $makefile_lib
fi
LIB_CI="libcim.a"
find_lib=`echo $LIB_LIST | grep -c $LIB_CI `
if [[ $find_lib > 0 ]];then
		    echo "CFLAGS +=  -DHAVE_LIB_CIM" >> $makefile_lib
fi
echo "" >> $makefile_lib

