CROSS_COMPILE=
CC     = $(CROSS_COMPILE)gcc
CPP    = $(CROSS_COMPILE)g++
LD     = $(CROSS_COMPILE)gcc
AR     = $(CROSS_COMPILE)ar
RANLIB = $(CROSS_COMPILE)ranlib
STRIP  = $(CROSS_COMPILE)strip

CFLAGS     += -DLINUX_OS -DLITTLE_ENDIAN -DI386_LINUX
LIBS       += -lpthread -lgxcore -lm
