#!/usr/bin/env python2
#-*- coding:utf-8 -*-

################################################################################
# Copyright © 2019-2029 NationalChip Corporation, All Rights Reserved
# This script is used to analyze frontend config in frontend_config dir,
# and generate macro define to app_frontend_board_config.h.
# This script is based on Python 2.7.12 or 3.5.2, and there is no dependency.
################################################################################

import sys, os, re
reload(sys)
sys.setdefaultencoding('utf-8')

SOLUTION_PATH = sys.argv[1]
SOLUTION_HEAD_FILE_PATH = sys.argv[2]
INPUT_CONFIG_FILE = SOLUTION_PATH + '/.config'
INPUT_FRONTEND_CONFIG_PATH = SOLUTION_PATH + '/frontend_config/'
INPUT_FRONTEND_INIT_H_PATH = SOLUTION_HEAD_FILE_PATH + '/module/app_frontend_init.h'
OUTPUT_FILE = SOLUTION_HEAD_FILE_PATH + '/module/app_frontend_board_config.h'
FRONTEND_CONFIG_LIST = [
    ['DEMOD_I2C_ID', '0xF'],
    ['DEMOD_I2C_CHIP_ADDR', '0x00'],
    ['DEMOD_ATTACH', '0'],
    ['TUNER_I2C_ID', '0xF'],
    ['TUNER_I2C_CHIP_ADDR', '0x00'],
    ['IQ', '0xFF'],
    ['LNB_POWER_GPIO', '0x100'],
    ['LNB_INVERT', '0xFF'],
    ['LNB_CTRL_ENABLE', '0xFF'],
    ['POL_CTRL_ENABLE', '0xFF'],
    ['POLAR_INVERT', '0xFF'],
    ['TS_PIN_CONFIG_00', 'ERRS'],
    ['TS_PIN_CONFIG_01', 'ERRS'],
    ['TS_PIN_CONFIG_02', 'ERRS'],
    ['TS_PIN_CONFIG_03', 'ERRS'],
    ['TS_PIN_CONFIG_04', 'ERRS'],
    ['TS_PIN_CONFIG_05', 'ERRS'],
    ['TS_PIN_CONFIG_06', 'ERRS'],
    ['TS_PIN_CONFIG_07', 'ERRS'],
    ['TS_PIN_CONFIG_08', 'ERRS'],
    ['TS_PIN_CONFIG_09', 'ERRS'],
    ['TS_PIN_CONFIG_10', 'ERRS'],
    ['TS_PIN_CONFIG_11', 'ERRS'],
    ['TS_MODE', '0xF'],
    ['IF_FREQ', '0'],
    ['TUNER_CRYSTAL', '0'],
    ['TUNER_XTAL_CAP', '0xFFFF'],
    ['TUNER_CLOCK_OUT', '0xFFFF'],
    ['TUNER_LOOP_OUT', '0xFFFF'],
    ['IS_OSCILLATOR', '0xF'],
    ['TUNER_CONNECTION', '0xFF'],
    ['DEMUX_TS_SRC', '0xFF'],
    ['AGC_GPIO', '0xFF'],
    ['HV_SEL_GPIO', '0xFF'],
    ['DISEQC_OUT_GPIO', '0xFF'],
    ['DISEQC_IN_GPIO', '0xFF']]

TUNER_ADAPT_CONFIG_LIST = [
    ['I2C_ID', '0xF'],
    ['ATTACH', 'NULL'],
    ['ADDR', '0x00'],
    ['IQ', '0xFF'],
    ['CRYSTAL', '0'],
    ['IF_FREQ', '0'],
    ['XTAL_CAP', '0xFFFF'],
    ['CLOCK_OUT', '0xFFFF'],
    ['LOOP_OUT', '0xFFFF'],
    ['TUNER_CONNECTION', '0xFF'],
    ]
DEMOD_ADAPT_CONFIG_LIST = [
    ['I2C_ID', '0xF'],
    ['CHIP_ADDR', '0x00'],
    ['ATTACH', '0'],
    ]
LNB_ADAPT_CONFIG_LIST = [
    ['LNB_POWER_GPIO', '0x100'],
    ['LNB_INVERT', '0xFF'],
    ['LNB_CTRL_ENABLE', '0xFF'],
    ['POL_CTRL_ENABLE', '0xFF'],
    ['POLAR_INVERT', '0xFF'],
    ['AGC_GPIO', '0xFF'],
    ['HV_SEL_GPIO', '0xFF'],
    ['DISEQC_OUT_GPIO', '0xFF'],
    ['DISEQC_IN_GPIO', '0xFF'],
    ]
TS_ADAPT_CONFIG_LIST = [
    ['TS_PIN_CONFIG_00', 'ERRS'],
    ['TS_PIN_CONFIG_01', 'ERRS'],
    ['TS_PIN_CONFIG_02', 'ERRS'],
    ['TS_PIN_CONFIG_03', 'ERRS'],
    ['TS_PIN_CONFIG_04', 'ERRS'],
    ['TS_PIN_CONFIG_05', 'ERRS'],
    ['TS_PIN_CONFIG_06', 'ERRS'],
    ['TS_PIN_CONFIG_07', 'ERRS'],
    ['TS_PIN_CONFIG_08', 'ERRS'],
    ['TS_PIN_CONFIG_09', 'ERRS'],
    ['TS_PIN_CONFIG_10', 'ERRS'],
    ['TS_PIN_CONFIG_11', 'ERRS'],
    ['TS_MODE', '0xF'],
    ['IS_OSCILLATOR', '0xF'],
    ['DEMUX_TS_SRC', '0xFF'],
    ]

TS_SRC_LIST = []
FRONTEND_MODE_LIST = []
demod_count = 0
demod_adapt_flag = 0
tuner_adapt_flag = 0
last_ts_src = 0
combo_flag = 0
fe_adapt_type = ['demod', 'tuner', 'lnb', 'ts']


def parse_frontend_config():
    head_line = '#ifndef __APP_FRONTEND_BOARD_CONFIG_H__\n\
#define __APP_FRONTEND_BOARD_CONFIG_H__\n\
\n/*\n * DO NOT MODIFY.\n\
 * This file was generated by parse_frontend_config.py\n */\n\n'
    end_line = '\n#endif'
    config_file = open(INPUT_CONFIG_FILE, 'r')
    config_lines = config_file.readlines()
    config_file.close()
    output_fd = open(OUTPUT_FILE, 'w+')
    output_fd.write(head_line)
    _find_tuner_config(config_lines, output_fd)
    _find_demod_adapt_config(config_lines, output_fd)
    _find_fe_config(config_lines, output_fd)
    output_fd.write(end_line)
    output_fd.close()

def _find_demod_adapt_config(config_lines, output_fd):
    global demod_count
    global demod_adapt_flag
    demod_adapt_flag_list = _get_demod_adapt_flag_enum_list()
    temp_demod_count = 1
    if demod_count > 0:
        output_fd.write('#define APP_FRONTEND_DEMOD_CONFIG_TYPE_LIST {\\\n')
        for each_config in  config_lines:
            if each_config.strip().find('#') < 0:#filter valid config
                config_offset = each_config.strip().rstrip().find('BR2_DEMOD%d_'%temp_demod_count)
                if config_offset >= 0:
                    auto_adapt_offset = each_config.lower().rstrip().find('auto_adapt')
                    if auto_adapt_offset >= 0:
                        demod_adapt_flag = 1
                        for temp_list in demod_adapt_flag_list:
                            temp_demod_adapt_offset = temp_list.lower().rstrip().find('auto_adapt')
                            if temp_demod_adapt_offset >= 0:
                                output_fd.write('    %s,\\\n'%temp_list)
                            else:
                                continue
                    else:
                        for temp_list in demod_adapt_flag_list:
                            temp_demod_adapt_offset = temp_list.lower().rstrip().find('auto_adapt')
                            if temp_demod_adapt_offset < 0:
                                output_fd.write('    %s,\\\n'%temp_list)
                            else:
                                continue
                    if temp_demod_count >= demod_count:
                        output_fd.write('    }\n')
                    temp_demod_count += 1

def _find_tuner_config(config_lines, output_fd):
    global demod_count
    global tuner_adapt_flag
    tuner_enum_list = _get_tuner_enum_list()
    tuner_count = 1
    for each_config in config_lines:
        if each_config.strip().find('#') < 0:#filter valid config
            if demod_count == 0:#get demod count first
                config_offset = each_config.strip().find('BR2_DEMOD_MULTY_DEMOD')
                if config_offset >= 0:
                    demod_count = int(each_config.split('=')[1].strip().rstrip())
                    output_fd.write('#define APP_MULTI_DEMOD_NUM %d\n'%demod_count)
                    output_fd.write('#define APP_FRONTEND_TUNER_LIST {\\\n')
            else:
                config_offset = each_config.strip().rstrip().find('BR2_TUNER%d_'%tuner_count)
                if config_offset >= 0:
                    tuner_find_flag = 0
                    tuner_name = each_config.split('=')[0].strip().rstrip()[config_offset+len('BR2_TUNER%d_'%tuner_count):]
                    auto_string = 'auto_adapt'
                    auto_adapt_offset = tuner_name.lower().find(auto_string)
                    if auto_adapt_offset >= 0:
                        tuner_adapt_flag = 1
                        tuner_name = tuner_name[:auto_adapt_offset+len(auto_string)]
                    for temp_list in tuner_enum_list:
                        if tuner_name == temp_list[0]:
                            #output_fd.write('#define APP_TUNER%d_ATTACH %s\n'%(tuner_count, temp_list[1]))
                            output_fd.write('    %s,\\\n'%temp_list[1])
                            tuner_find_flag = 1
                            break
                    if tuner_find_flag == 0:
                        output_fd.close()
                        raise IOError('Cannot match %s in app_frontend_init.h'%tuner_name)
                    if tuner_count == demod_count:
                        output_fd.write('    }\n')
                        break
                    tuner_count += 1
    if demod_count == 0:
        output_fd.close()
        raise IOError('Cannot find BR2_DEMOD_MULTY_DEMOD! Please check!')

def _get_demod_adapt_flag_enum_list():
    fd = open(INPUT_FRONTEND_INIT_H_PATH, 'r')
    file_lines = fd.readlines()
    fd.close()
    enum_list = []
    enum_flag = 0
    for string in file_lines:
        if len(string) < 8:
            continue
        if string.strip()[0] == '#' or string.strip()[:2] == '//' or string.strip()[:2] == '/*':
            continue
        if string.find('enum') > 0:
            enum_flag = 1
            continue
        if enum_flag > 0:
            pos1 = string.find('APP_DEMOD_ADAPT_TYPE')
            if pos1 > 0:
                break
            pos1 = string.find(';')
            if pos1 > 0:
                enum_flag = 0;
                continue
            pos1 = string.find('DEMOD_')
            if pos1 >= 0:
                pos2 = string.rstrip('//').rstrip('/*').find(',')
                if pos2 > 0:
                    enum_list.append(string[pos1:pos2])
    return enum_list

def _get_tuner_enum_list():
    fd = open(INPUT_FRONTEND_INIT_H_PATH, 'r')
    file_lines = fd.readlines()
    fd.close()
    enum_list = []
    enum_flag = 0
    for string in file_lines:
        if len(string) < 8:
            continue
        if string.strip()[0] == '#' or string.strip()[:2] == '//' or string.strip()[:2] == '/*':
            continue
        if string.find('enum') > 0:
            enum_flag = 1
            continue
        if enum_flag > 0:
            pos1 = string.find('APP_TUNER_TYPE')
            if pos1 >= 0 and enum_flag == 2:
                break
            pos1 = string.find('TUNER_')
            if pos1 >= 0:
                enum_flag = 2
                pos2 = string.rstrip('//').rstrip('/*').find(',')
                if pos2 > 0:
                    pos2 = string.find(',')
                    enum_list.append([string[pos1+len('TUNER_'):pos2].rstrip(), string[pos1:pos2]])
            else:
                enum_flag = 0
    return enum_list

def _find_fe_config(config_lines, output_fd):
    global FRONTEND_MODE_LIST, TS_SRC_LIST
    config_file_name = ''
    combo_flag = 0
    for each_config in config_lines:
        if each_config.strip().find('#') < 0:#filter valid config
            demod_config = re.findall('BR2_DEMOD\d_', each_config.strip())
            if len(demod_config) > 0:
                _find_demux_config(each_config.strip())
            config_offset = each_config.strip().find('BR2_FE_CONFIG_')
            if config_offset >= 0:
                config_file_name = each_config.split('=')[0].rstrip()[config_offset + len('BR2_FE_CONFIG_'):].lower()
                break

    if len(config_file_name) == 0:
        output_fd.close()
        raise IOError('Cannot find frontend config, please match the config in frontend_config dir and config in make menuconfig')

    config_list = os.listdir(INPUT_FRONTEND_CONFIG_PATH)
    find_config_flag = 0
    for each_config in config_list:
        if config_file_name == each_config.lower():
            find_config_flag = 1
            try:
                _analyze_config(INPUT_FRONTEND_CONFIG_PATH + each_config, output_fd)
            except Exception as msg:
                output_fd.close()
                raise IOError(msg)
            break
    if find_config_flag == 0:
        output_fd.close()
        raise IOError('Cannot find frontend config in %s'%INPUT_FRONTEND_CONFIG_PATH)

    #write frontend_mode to config file, which configured in app_system_init()
    if len(FRONTEND_MODE_LIST) > 0 and len(TS_SRC_LIST) > 0:
        output_fd.write('#define APP_FRONTEND_MODE_CONFIG {\\\n')
        for info in FRONTEND_MODE_LIST:
            output_fd.write('    %s,\\\n'%info)
        output_fd.write('    }\n\n')


def _find_demux_config(config_string):
    global FRONTEND_MODE_LIST, TS_SRC_LIST, last_ts_src, combo_flag
    demod_index = config_string.index('DEMOD')+len('DEMOD')
    config_string = config_string[demod_index:]
    if config_string.find('COMBO') >= 0:
        if config_string.split('_')[-1].find('S') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBS')
        elif config_string.split('_')[-1].find('T') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBT')
        elif config_string.split('_')[-1].find('C') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBC')
        elif config_string.split('_')[-1].find('ISDBT') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBT')
        TS_SRC_LIST.append(str(last_ts_src))
        combo_flag = 1
    else:
        if config_string.split('_')[-1].find('S2') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBS')
        elif config_string.split('_')[-1].find('T2') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBT')
        elif config_string.split('_')[-1].find('C') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBC')
        elif config_string.split('_')[-1].find('DTMB') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DTMB')
        elif config_string.split('_')[-1].find('ISDBT') >= 0:
            FRONTEND_MODE_LIST.append('DEMOD_TYPE_DVBT')
        if combo_flag == 1:
            last_ts_src += 1
            TS_SRC_LIST.append(str(last_ts_src))
        else:
            TS_SRC_LIST.append(str(last_ts_src))
            last_ts_src += 1

def _parse_note_string(input_string):
    pos_list = []
    input_string = input_string.strip().rstrip()
    #strip end of line, include '//' '/*' '#'
    pos = input_string.find('//')
    if pos >= 0: pos_list.append(pos)
    pos = input_string.find('/*')
    if pos >= 0: pos_list.append(pos)
    pos = input_string.find('#')
    if pos >= 0: pos_list.append(pos)
    if len(pos_list) > 0:
        pos_list.sort()
        input_string = input_string[:pos_list[0]]
    return input_string

def _is_list_of_empty_elements(lst):
    for element in lst:
        if element != '':
            return False
    return True

def _analyze_demod_tuner_adapt_param(config_lines, output_fd, adapt_type):
    global demod_count
    define_params_title_str = ''
    type_str = 'demod'
    type_substr_list = ['']
    type_config_list = ['']
    if adapt_type == 'tuner':
        define_params_title_str = '#define APP_FRONTEND_TUNER_ADAPT_PARAMETERS {\\\n'
        type_str = 'tuner'
        type_config_list = TUNER_ADAPT_CONFIG_LIST
    elif adapt_type == 'demod':
        define_params_title_str = '#define APP_FRONTEND_DEMOD_ADAPT_PARAMETERS {\\\n'
        type_config_list = DEMOD_ADAPT_CONFIG_LIST
    elif adapt_type == 'lnb':
        define_params_title_str = '#define APP_FRONTEND_LNB_ADAPT_PARAMETERS {\\\n'
        type_substr_list = ['lnb', 'pol','polar', 'agc', 'hv', 'diseqc']
        type_config_list = LNB_ADAPT_CONFIG_LIST
    elif adapt_type == 'ts':
        define_params_title_str = '#define APP_FRONTEND_TS_DAPT_PARAMETERS {\\\n'
        type_substr_list = ['ts_pin', 'ts_src', 'ts_mode', 'is_oscillator']
        type_config_list = TS_ADAPT_CONFIG_LIST

    output_fd.write(define_params_title_str)
    for count in range(1, demod_count+1):
        for adapt_count in range(1, 10):# only support 10 adapt, you can change this if you want to support more
            adapt_flag_true = 0
            adapt_params = ['']*len(type_config_list)
            for each_config in config_lines:
                #valid config, filter '#' and '//' and '/*' and length<=2 and cannot find '='
                if each_config.strip()[:1] != '#' and each_config.strip()[:2] != '//' \
                        and len(each_config) > 2 and each_config.find('=') > 0 \
                        and each_config.strip()[:2] != '/*':
                    find_str_flag = 0
                    for type_substr in type_substr_list:
                        if each_config.lower().find('frontend%d_%s%d_adapt_%s'%(count, type_str,adapt_count, type_substr)) >= 0:
                            find_str_flag = 1
                            break
                    if each_config.lower().find('frontend%d_%s%d_adapt'%(count, type_str,adapt_count)) >= 0:
                        adapt_flag_true = 1
                    if find_str_flag == 0:
                        continue
                    configs = each_config.split('=')
                    if len(configs) == 2:
                        configs[0] = configs[0].rstrip()
                        configs[1] = _parse_note_string(configs[1])
                        if len(configs[1]) > 0:
                            temp_count = 0
                            for temp_adapt_params in type_config_list:
                                if configs[0].find(temp_adapt_params[0].lower()) >= 0:
                                    break
                                temp_count += 1
                            if temp_count < len(type_config_list):
                                configs[1] = configs[1].strip().rstrip().rstrip('\n')
                                adapt_params[temp_count] = configs[1]
            if _is_list_of_empty_elements(adapt_params) == False:
                write_data = '    {%d, '%(count-1)
                temp_count = 0
                max_chip_addr = 4 #define max tuner address adapt number
                for i in adapt_params:
                    if len(i):
                        if type_config_list[temp_count][0].lower().find('addr') >= 0:# i2c addr must be list
                            addr_count = len(i.split(','))
                            write_data += '{' + i + ',' + '0x00,'*(max_chip_addr-addr_count) +'}'
                        else:
                            write_data += i
                    else:
                        if type_config_list[temp_count][0].lower().find('addr') >= 0:# i2c addr must be list
                            write_data += '{' + (type_config_list[temp_count][1] + ',')*max_chip_addr + '}'
                        else:
                            write_data += type_config_list[temp_count][1]
                    if temp_count != (len(type_config_list)-1):
                        write_data += ','
                    temp_count += 1
                write_data += '},\\\n'
                #print write_data
                output_fd.write(write_data)
            else:
                if adapt_flag_true > 0:
                    write_data = '    {%d, '%(count-1)
                    temp_count = 0
                    for default_adapt_params in type_config_list:
                        write_data += default_adapt_params[1] + ','
                    write_data += '},\\\n'
                    output_fd.write(write_data)
    output_fd.write('    }\n')

def _analyze_demod_adapt_ts4pin_param(output_fd, adapt_ts4pin_switch_flag, pin_switch_count, ts4pin_switch_list):
    global demod_count
    ts4pin_switch_count = 0
    if len(ts4pin_switch_list) > 0:
        output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_TS4PIN_SWITCH {\\\n')
        if adapt_ts4pin_switch_flag > 0:
            for data in ts4pin_switch_list:
                #output_fd.write('    {%d, %d, {'%(adapt_demod_num, len(data)))
                if len(data) > ts4pin_switch_count:
                    ts4pin_switch_count = len(data) - 1
                output_fd.write('    {%d, %d, {'%(int(data[0]), len(data)-1))
                if len(data) == 1:
                    output_fd.write('0')
                for dat in data[1:]:
                    try:
                        frontend_id = int(dat.split(',')[0])
                        ts_control = int(dat.split(',')[1])
                    except:
                        raise IOError('frontend ID and ts control in frontend_ts4pin_switch must be a number!please check frontend config file!')
                    if frontend_id <= 0 or frontend_id > demod_count:
                        raise IOError('frontend ID in frontend_ts4pin_switch must greater than 0!please check frontend config file!')
                    elif ts_control != 0 and ts_control != 1:
                        raise IOError('ts control in frontend_ts4pin_switch must be 0 or 1!please check frontend config file!')
                    output_fd.write('{' + dat + '},')
                output_fd.write('}},\\\n')
            output_fd.write('    }\n')
    output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_PIN_SWITCH_COUNT  %d\n'%pin_switch_count)
    output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_TS4PIN_SWITCH_COUNT  %d\n'%ts4pin_switch_count)

def _analyze_ts4pin_param(output_fd, ts4pin_switch_list, pin_switch_count, pin_switch_count_list):
    global demod_count
    if len(ts4pin_switch_list) == 0:
        raise IOError('Cannot find ts4pin_switch config in frontend_config')
    output_fd.write('#define APP_FRONTEND_TS4PIN_SWITCH {\\\n')
    ts4pin_switch_count = 0
    ts4pin_switch_count_list = []
    for data in ts4pin_switch_list:
        output_fd.write('    {')
        if len(data) > ts4pin_switch_count:
            ts4pin_switch_count = len(data)
        ts4pin_switch_count_list.append(len(data))
        for dat in data:
            try:
                frontend_id = int(dat.split(',')[0])
                ts_control = int(dat.split(',')[1])
            except:
                raise IOError('frontend ID and ts control in frontend_ts4pin_switch must be a number!please check frontend config file!')
            if frontend_id <= 0 or frontend_id > demod_count:
                raise IOError('frontend ID in frontend_ts4pin_switch must greater than 0!please check frontend config file!')
            elif ts_control != 0 and ts_control != 1:
                raise IOError('ts control in frontend_ts4pin_switch must be 0 or 1!please check frontend config file!')
            output_fd.write('{' + dat + '},')
        output_fd.write('},\\\n')
    output_fd.write('    }\n')
    output_fd.write('#define APP_FRONTEND_PIN_SWITCH_COUNT  %d\n'%pin_switch_count)
    output_fd.write('#define APP_FRONTEND_PIN_SWITCH_COUNT_LIST {\\\n')
    pin_count_list =['0']*demod_count
    wt_buff = ''
    i = 0
    for data in pin_switch_count_list:
        pin_count_list[i] = str(data)
        i += 1
    for count in range(0, demod_count):
        wt_buff += pin_count_list[count] + ','
    output_fd.write('    ' + wt_buff + '\\\n')
    output_fd.write('    }\n')
    output_fd.write('#define APP_FRONTEND_TS4PIN_SWITCH_COUNT  %d\n'%ts4pin_switch_count)
    output_fd.write('#define APP_FRONTEND_TS4PIN_SWITCH_COUNT_LIST {\\\n')
    ts4pin_count_list =['0']*demod_count
    wt_buff = ''
    i = 0
    for data in ts4pin_switch_count_list:
        ts4pin_count_list[i] = str(data)
        i += 1
    for count in range(0, demod_count):
        wt_buff += ts4pin_count_list[count] + ','
    output_fd.write('    ' + wt_buff + '\\\n')
    output_fd.write('    }\n')

def _analyze_pin_switch_param(config_lines, find_pin_switch_config, output_fd, auto_adapt_flag):
    # get pin switch parameters, only for combo solution
    global demod_count
    adapt_count = 1
    if find_pin_switch_config == 1:
        pin_switch_count = 0
        adapt_ts4pin_switch_flag = 0
        pin_switch_count_list = []
        ts4pin_switch_list = []
        if auto_adapt_flag == 1:
            adapt_count = 10
            output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_PIN_SWITCH_PARAMETERS {\\\n')
        else:
            output_fd.write('#define APP_FRONTEND_PIN_SWITCH_PARAMETERS {\\\n')
        for count in range(1, demod_count+1):
            pin_config_list = []
            for pin_adapt_count in range(1, adapt_count+1):
                pin_config_list = []
                adapt_flag_true = 0
                ts4pin_not_empty_flag = 0
                adapt_pin_switch_count = 0
                if auto_adapt_flag == 1:
                    find_ts4pin_str = 'demod%d_adapt_ts4pin_switch'%pin_adapt_count
                    find_pin_switch_str = 'demod%d_adapt_'%pin_adapt_count
                else:
                    find_ts4pin_str = 'ts4pin_switch'
                    find_pin_switch_str = ''
                for pin_count in range(1, 12):# only support 12 pins, you can change this if you want to support more
                    for each_config in config_lines:
                        #valid config, filter '#' and '//' and '/*' and length<=2 and cannot find '='
                        if each_config.strip()[:1] != '#' and each_config.strip()[:2] != '//' \
                                and len(each_config) > 2 and each_config.find('=') > 0 \
                                and each_config.strip()[:2] != '/*':
                            if each_config.lower().find('frontend%d_%s'%(count,find_ts4pin_str)) >= 0:
                                if pin_count == 1:#just need to check first time
                                    configs = each_config.split('=')
                                    if len(configs) == 2:
                                        configs[1] = _parse_note_string(configs[1])
                                        if auto_adapt_flag == 1:
                                            configs[1] = '%d;'%(count-1) + configs[1]
                                        parameters = configs[1].split(';')
                                        ts4pin_switch_list.append(parameters)
                                        adapt_ts4pin_switch_flag = 1
                                        ts4pin_not_empty_flag = 1
                                continue
                            if each_config.lower().find('frontend%d_demod%d_adapt'%(count,pin_adapt_count)) >= 0:
                                if ts4pin_not_empty_flag == 0:
                                    adapt_flag_true = 1
                            if each_config.lower().find('frontend%d_%spin%d_switch'%(count, find_pin_switch_str, pin_count)) < 0:
                                continue
                            adapt_pin_switch_count += 1
                            configs = each_config.split('=')
                            if len(configs) == 2:
                                configs[1] = _parse_note_string(configs[1])
                                if len(configs[1]) > 0:
                                    pin_config_list.append(configs[1])
                if auto_adapt_flag == 1:
                    if ts4pin_not_empty_flag == 0 and adapt_flag_true == 1:
                        ts4pin_switch_list.append(['%d'%(count-1)])
                if len(pin_config_list) > 0:
                    if auto_adapt_flag == 1:
                        output_fd.write('    {%d, %d, {'%(count-1,adapt_pin_switch_count))
                    else:
                        output_fd.write('    {')
                    for pin_config in pin_config_list:
                        temp_pin_config = pin_config.split(',')
                        for parameters in temp_pin_config:
                            try:
                                dat = int(parameters)
                            except:
                                dat = int(parameters, 16)
                            if dat > 0xFF or dat < 0:
                                raise IOError('pin_config parameters error!please check frontend config file!')
                        output_fd.write('{' + pin_config + '},')
                    if auto_adapt_flag == 1:
                        output_fd.write('}},\\\n')
                    else:
                        output_fd.write('},\\\n')
                    if len(pin_config_list) > pin_switch_count:
                        pin_switch_count = len(pin_config_list)
                    pin_switch_count_list.append(len(pin_config_list))
                else:
                    if auto_adapt_flag == 1 and adapt_flag_true == 1:
                        output_fd.write('    {%d, %d, {0'%(count-1,adapt_pin_switch_count))
                        output_fd.write('}},\\\n')
        output_fd.write('    }\n')
        if auto_adapt_flag == 1:
            _analyze_demod_adapt_ts4pin_param(output_fd, adapt_ts4pin_switch_flag, pin_switch_count, ts4pin_switch_list)
        else:
            _analyze_ts4pin_param(output_fd, ts4pin_switch_list, pin_switch_count, pin_switch_count_list)
    else:
        if auto_adapt_flag == 1:
            output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_PIN_SWITCH_COUNT  0\n')
            output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_TS4PIN_SWITCH_COUNT  0\n')
        else:
            output_fd.write('#define APP_FRONTEND_PIN_SWITCH_COUNT  0\n')

def _analyze_config(config_path, output_fd):
    config_file = open(config_path, 'r')
    config_lines = config_file.readlines()
    config_file.close()
    global demod_count
    global demod_adapt_flag
    global tuner_adapt_flag
    find_ts_src_config = 1
    find_pin_switch_config = 0
    find_adapt_pin_switch_config = 0
    for config_item in FRONTEND_CONFIG_LIST:
        output_fd.write('#define APP_FRONTEND_%s {\\\n'%config_item[0].upper())
        for count in range(1, demod_count+1):
            item_find_flag = 0
            for each_config in config_lines:
                #valid config, filter '#' and '//' and '/*' and length<=2 and cannot find '='
                if each_config.strip()[:1] != '#' and each_config.strip()[:2] != '//' \
                        and len(each_config) > 2 and each_config.find('=') > 0 \
                        and each_config.strip()[:2] != '/*':
                    if each_config.lower().find('frontend%d_pin'%count) >= 0 and each_config.lower().find('_switch') > 0:
                        find_pin_switch_config = 1
                        continue
                    if each_config.lower().find('_adapt_pin') >= 0 and each_config.lower().find('_switch') > 0:
                        find_adapt_pin_switch_config = 1
                        continue

                    if each_config.lower().find('frontend%d_'%count + config_item[0].lower()) < 0:
                        continue
                    configs = each_config.split('=')
                    if len(configs) == 2:
                        configs[1] = _parse_note_string(configs[1])
                        if len(configs[1]) > 0:
                            item_find_flag = 1
                            configs[1] = configs[1].strip().rstrip().rstrip('\n')
                            output_fd.write('    %s,\\\n'%configs[1])
                            break
            if item_find_flag == 0:
                if config_item[0] == 'DEMUX_TS_SRC':
                    find_ts_src_config = 0
                else:
                    output_fd.write('    %s,/*this item will not be configed*/\\\n'%config_item[1])
        if config_item[0] == 'DEMUX_TS_SRC' and find_ts_src_config == 0:#cannot find ts_src config in frontend_config file
            #write ts_src to config file, which configured in app_system_init()
            if len(FRONTEND_MODE_LIST) > 0 and len(TS_SRC_LIST) > 0:
                for info in TS_SRC_LIST:
                    output_fd.write('    %s,\\\n'%info)
            else:
                output_fd.close()
                raise IOError('Cannot find BR2_DEMOD configs')
        output_fd.write('    }\n')

    for adapt_type in fe_adapt_type:
        if adapt_type == 'tuner':
            if tuner_adapt_flag == 1:
                _analyze_demod_tuner_adapt_param(config_lines, output_fd, adapt_type)
            continue
        if demod_adapt_flag == 1:
            _analyze_demod_tuner_adapt_param(config_lines, output_fd, adapt_type)

    if demod_adapt_flag == 1:
        _analyze_pin_switch_param(config_lines, find_adapt_pin_switch_config, output_fd, 1)
    else:
        output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_PIN_SWITCH_COUNT  0\n')
        output_fd.write('#define APP_FRONTEND_DEMOD_ADAPT_TS4PIN_SWITCH_COUNT  0\n')

    _analyze_pin_switch_param(config_lines, find_pin_switch_config, output_fd, 0)


if __name__ == '__main__':
    parse_frontend_config()

