# Rules
# vendor_name:os_name:theme_name
# * stands for anyone except above
public:linux:classic_blue
public:linux:classic_dark
public:linux:classic_purple
public:linux:grid_purple
public:ecos:classic_blue
public:ecos:classic_dark
public:ecos:classic_purple
public:ecos:grid_purple
mini:linux:classic_dark
mini:linux:classic_blue
mini:ecos:classic_dark
mini:ecos:classic_blue
mini:ecos:classic_purple
mini:ecos:grid_purple
mini:ecos:sky_blue
