#ifndef __GX_SPI_H__
#define __GX_SPI_H__

#include <version_autogenerated.h>
#include <linux/list.h>

#define SFLASH_CONTROL_VALUE	0x8420c002

struct spi_regs {
	volatile unsigned int SPI_CR;
	volatile unsigned int SPI_SR;
	volatile unsigned int SPI_TX_DATA;
	volatile unsigned int SPI_RX_DATA;
};

//about spi_cr
#define CR_DUAL_TX          (0x1 << 23)
#define CR_DUAL_RX          (0x1 << 22)
#define CR_NO_INTER_DELAY   (0x1 << 21)
#define CR_LSB              (0x1 << 20)
#define CR_POS_RX           (0x1 << 19)
#define CR_CSEN             (1 << 17)
#define CR_CSFORCE          (0x1 << 16)
#define CR_CSVALID          (0x3 << 16)
#define CR_ICNT_2           (0x1 << 14)
#define CR_ICNT_3           (0x2 << 14)
#define CR_ICNT_4           (0x3 << 14)
#define CR_SPIE             (0x1 << 13)
#define CR_SPGO             (0x1 << 12)
#define CR_CS_SEL           (0x1 << 10)
#define CR_CSPOL_H          (0x1 << 10)
#define CR_CPOL_H           (0x1 << 9)
#define CR_CPHA_H           (0x1 << 8)
#define CR_CSDL(x)          ((x) << 5)
#define CR_SPBR(x)          ((x) << 0)

//about spi_sr
#define SR_BUSY             (0x1 << 1)
#define SR_OPE_RDY          (0x1 << 0)

#define SPI_SIZE            16
#define SZ_MULT             0x10

#endif
