SET(BUILD_CAS $ENV{BUILD_CAS})
IF (BUILD_CAS STREQUAL cd)
	INCLUDE(cas/cdhs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL cti)
	INCLUDE(cas/ctihs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL dvt)
	INCLUDE(cas/dvths/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL rs)
	INCLUDE(cas/rshs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL irdeto)
	INCLUDE(cas/irdeto/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL abv)
	INCLUDE(cas/abvhs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL uti)
	INCLUDE(cas/utihs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL cryptoguard)
	INCLUDE(cas/cryptoguard/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL divig)
	INCLUDE(cas/DiviGuard/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL tr)
	INCLUDE(cas/trhs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL desai)
	INCLUDE(cas/desai/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL conax)
	INCLUDE(cas/conax/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL gospell)
	INCLUDE(cas/gospell/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL vmx)
	INCLUDE(cas/vmxhs/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL telecast)
	INCLUDE(cas/telecasths/ca.cmake)
ELSEIF (BUILD_CAS STREQUAL nagra)
	INCLUDE(cas/nagra/ca.cmake)
ELSE()
	MESSAGE(STATUS "BUILD_CAS   : ${BUILD_CAS}")
ENDIF()
