SET(ARCH_OS $ENV{ARCH_OS})
SET(BUG $ENV{BUG})
SET(GX_EXT_CFLAGS $ENV{GX_EXT_CFLAGS})

SET(CMAKE_C_COMPILER_FORCED TRUE)
SET(CMAKE_CXX_COMPILER_FORCED TRUE)

#ADD_DEFINITIONS(-D$ENV{ARCH} -D$ENV{ARCH}-$ENV{OS})
IF (ARCH_OS STREQUAL arm-ecos)
	SET(ARCH arm)
	SET(OS   ECOS)
	SET(TOOLCHAIN_PREFIX arm-none-eabi-)
ELSEIF (ARCH_OS STREQUAL arm-linux)
	SET(ARCH arm)
	SET(OS   LINUX)
	SET(TOOLCHAIN_PREFIX arm-linux-uclibcgnueabihf-)
ELSEIF (ARCH_OS STREQUAL csky-ecos)
	SET(ARCH csky)
	SET(OS   ECOS)
	SET(TOOLCHAIN_PREFIX csky-elf-)
ELSEIF (ARCH_OS STREQUAL csky-linux)
	SET(ARCH csky)
	SET(OS   LINUX)
	SET(TOOLCHAIN_PREFIX csky-linux-)
ELSE()
	SET(ARCH i386)
	SET(OS   LINUX)
	SET(GOXCEED_PATH /usr/local/)
ENDIF()

SET(GOXCEED_PATH       $ENV{GX_PREFIX}/${ARCH_OS})

EXECUTE_PROCESS(COMMAND which ${TOOLCHAIN_PREFIX}gcc
	OUTPUT_VARIABLE COMPILER_FULL_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
SET(CMAKE_C_COMPILER   ${COMPILER_FULL_PATH})

EXECUTE_PROCESS(COMMAND which ${TOOLCHAIN_PREFIX}g++
	OUTPUT_VARIABLE COMPILER_FULL_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
SET(CMAKE_CXX_COMPILER   ${COMPILER_FULL_PATH})

ADD_DEFINITIONS(-D${ARCH} -D${OS}_OS)
ADD_DEFINITIONS(-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64)

# adjust the default behaviour of hte FIND_XXX() NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODULE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_INCLUDE ONLY)

SET(GXSRC_PATH ${CMAKE_CURRENT_SOURCE_DIR})
SET(CMAKE_INSTALL_PREFIX ${GOXCEED_PATH} )
MESSAGE(STATUS "INSTALL_DIR   : ${CMAKE_INSTALL_PREFIX}")

SET(EXTRA_CFLAGS "${EXTRA_CFLAGS} -Werror ${GX_EXT_CFLAGS}")
SET(EXTRA_CXXFLAGS "${EXTRA_CXXFLAGS} -Werror ${GX_EXT_CFLAGS}")

IF (BUG STREQUAL patch)
	SET(CKSY_LINUX_BUG "-mkstq2")
ELSE()
	SET(CKSY_LINUX_BUG "")
ENDIF()

SET(CMAKE_C_FLAGS           "${CKSY_LINUX_BUG} ${CMAKE_C_FLAGS} ${GXCFLAGS} ${GX_EXT_CFLAGS} -Wall -Wundef -D_GNU_SOURCE")
SET(CMAKE_CXX_FLAGS_DEBUG   "${CKSY_LINUX_BUG} $ENV{CXXFLAGS} ${GX_EXT_CFLAGS} -O0 -Wall -g -ggdb -DGXDBG")
SET(CMAKE_CXX_FLAGS_RELEASE "${CKSY_LINUX_BUG} $ENV{CXXFLAGS} ${GX_EXT_CFLAGS} -O2 -Wall -fdata-sections -ffunction-sections")

SET(CMAKE_C_FLAGS_DEBUG     "${CMAKE_CXX_FLAGS_DEBUG}" )
SET(CMAKE_C_FLAGS_RELEASE   "${CMAKE_CXX_FLAGS_RELEASE} ${CMAKE_C_FLAGS}" )

INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/    )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/bus )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/av  )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/gxsecure  )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/dvbhal  )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/devapi  )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/gxbus  )
INCLUDE_DIRECTORIES( ${GOXCEED_PATH}/include/libteec  )
INCLUDE_DIRECTORIES( ${CMAKE_BINARY_DIR}         )

FUNCTION(ADD_GX_LIBRARY name)
	ADD_LIBRARY( ${name} ${ARGN} )
	INSTALL(TARGETS ${name}
		ARCHIVE DESTINATION ${GOXCEED_PATH}/lib)

ENDFUNCTION(ADD_GX_LIBRARY name)
