#include "stdio.h"
#include "io.h"
#include "string.h"
#include "time.h"
#include "serial.h"
#include "gxhwlib_registers.h"
#include "version_autogenerated.h"

#ifdef CONFIG_ARCH_ARM_SIRIUS

#define BUF_MAX_LEN 33
#define REG_ARM_JTAG_PASSWD_LL   (REG_BASE_CHIPCONFIG + 0x00000360)
#define REG_ARM_JTAG_PASSWD_LH   (REG_BASE_CHIPCONFIG + 0x00000364)
#define REG_ARM_JTAG_PASSWD_HL   (REG_BASE_CHIPCONFIG + 0x00000368)
#define REG_ARM_JTAG_PASSWD_HH   (REG_BASE_CHIPCONFIG + 0x0000036c)
#define REG_ARM_JTAG_PASSWD_EN   (REG_BASE_CHIPCONFIG + 0x00000370)

static int get_string(char *buf)
{
	int ret = 0;
	char c;
	char *addr = buf;

	while (1) {
		if (uart_try_getc(&c, CONFIG_UART_PORT)) {
			continue;
		}
		if ((c == '\r') || (c == '\n')) {//回车键
			break;
		} else if (c == 0x08) { //回退键
			if (buf > addr) {
				printf("\b");
				printf(" ");
				printf("\b");
				*(--buf) = '\0';
			}
			continue;
		} else if (buf - addr > (BUF_MAX_LEN-2)) //防止数组超出出错
			continue;
		else
			printf("*");
		*buf++ = c;
		*buf = '\0';
	}
	printf("\n");

	if (buf == addr && (buf[0] == '\0' || buf[0] == '0')) //not have input
		ret = -1;

	return ret;
}

static void write_passwd(char *buf)
{
	unsigned int tmp = 0;
	int i;
	for (i = 0; i < 4; i++) {
		tmp |= (*buf++ << 24);
		tmp |= (*buf++ << 16);
		tmp |= (*buf++ << 8);
		tmp |= (*buf++ << 0);
		__raw_writel(tmp, (REG_ARM_JTAG_PASSWD_HH-i*4));
		tmp = 0;
	}
	__raw_writel(1, REG_ARM_JTAG_PASSWD_EN);
}

int jtag_init(void)
{
	int timeout_flag = 1;
	int ret = 0;
	unsigned int time_st;
	unsigned char *d_buf = NULL;
	char *buf = NULL;
	char ch;

	gx_time_init();

	printf(" please enter 'j' or 'J' into jtag mode within 3s ...\n");
	time_st = gx_time_get_s();
	while ((gx_time_get_s() - time_st) <= 3) {
		if (uart_try_getc(&ch, CONFIG_UART_PORT)) {
			continue;
		} else {
			timeout_flag = 0;
			break;
		}
	}

	if (timeout_flag)
		return -1;

	if (ch == 'J' || ch == 'j') {
		buf = (char *)malloc(BUF_MAX_LEN);
		memset(buf, 0, BUF_MAX_LEN);
		printf("input passwd:\n");
		printf(">");
		if (!get_string(buf)) {
			d_buf = string_to_hex(buf, NULL);
			if (!d_buf) {
				printf("error: bad hex digits string !!!\n");
				ret = -1;
				goto err;
			}
			write_passwd(d_buf);
			free(d_buf);
		}
err:
		free(buf);
	}

	return ret;
}
#endif
