SET(SRC_MUXER muxer/muxer.c
	)

IF (CONFIG_FFMPEG_ENABLE)
	SET(SRC_MUXER ${SRC_MUXER}
	muxer/muxer_ffmpeg.c
	)
ENDIF (CONFIG_FFMPEG_ENABLE)

IF (CONFIG_MUX_MPEGTS)
	SET(SRC_MUXER ${SRC_MUXER}
		avformat/file.c)
ENDIF (CONFIG_MUX_MPEGTS)

IF (CONFIG_MUX_RAWVIDEO)
	SET(SRC_MUXER ${SRC_MUXER}
		avformat/rawenc.c
		)
ENDIF (CONFIG_MUX_RAWVIDEO)

