#include "version_autogenerated.h"
#include "cpu_config.h"
#include "databahn.h"
#include "io.h"
#ifdef DDR_PAR_PATCH_INCLUDE
#include DDR_PAR_PATCH_INCLUDE
#endif

/* denali_config.c  */
extern unsigned int DENALI_CONFIG_CTL[155];
extern unsigned int DENALI_CONFIG_PHY[31];
extern unsigned int DENALI_CONFIG_CTL_2[155];
extern unsigned int DENALI_CONFIG_PHY_2[31];
extern void ddr_config_patch(void);
extern void serial_put_no_mmu(char);
extern unsigned char otp_read_simple(unsigned int address);

static void Databahn_Init(void);
static void Databahn_SetParameters(struct reg_param *regs, int count);
static unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width);
static unsigned int Databahn_GetIntStatus(void);
static unsigned int Databahn_isReady(void);
static void Databahn_Config(void);

#define DATABAHN_REG_FULL(i, name, addr, offset, width, v) \
	{DATABAHN_REG_AXI##i##name##addr,  DATABAHN_REG_AXI##i##name##offset,  DATABAHN_REG_AXI##i##name##width, v}

#define DATABAHN_REG(i, name, v) \
	DATABAHN_REG_FULL(i, name, _ADDR, _OFFSET, _WIDTH, v)

static struct reg_param param_table[] = {
	// Lvl
	{DATABAHN_REG_WRLVL_REG_EN_ADDR, DATABAHN_REG_WRLVL_REG_EN_OFFSET, DATABAHN_REG_WRLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_REG_EN_ADDR, DATABAHN_REG_RDLVL_REG_EN_OFFSET, DATABAHN_REG_RDLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_GATE_EN_ADDR, DATABAHN_REG_RDLVL_GATE_EN_OFFSET, DATABAHN_REG_RDLVL_GATE_EN_WIDTH, 1},

	DATABAHN_REG(0 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(1 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(2 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(3 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(4 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(5 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(6 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(7 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(8 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(9 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(10, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(11, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(12, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(13, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(14, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(15, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),

	DATABAHN_REG(0 , _R_PRIORITY, 0x4),    //cpu
	DATABAHN_REG(1 , _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(2 , _R_PRIORITY, 0xa),    //pp/ga/jpeg
	DATABAHN_REG(3 , _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(4 , _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(5 , _R_PRIORITY, 0x1),    //vpu
	DATABAHN_REG(6 , _R_PRIORITY, 0x3),    //demux/filter
	DATABAHN_REG(7 , _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(8 , _R_PRIORITY, 0x3),    //audio_dec
	DATABAHN_REG(9 , _R_PRIORITY, 0x5),    //video_dec
	DATABAHN_REG(10, _R_PRIORITY, 0x2),    //apu/hdcp
	DATABAHN_REG(11, _R_PRIORITY, 0x8),    //secure/scpu/usb
	DATABAHN_REG(12, _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(13, _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(14, _R_PRIORITY, 0x8),    //unused
	DATABAHN_REG(15, _R_PRIORITY, 0x8),    //unused

	DATABAHN_REG(0 , _W_PRIORITY, 0x6),    //cpu
	DATABAHN_REG(1 , _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(2 , _W_PRIORITY, 0xa),    //pp/ga/jpeg
	DATABAHN_REG(3 , _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(4 , _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(5 , _W_PRIORITY, 0x1),    //vpu
	DATABAHN_REG(6 , _W_PRIORITY, 0x3),    //demux/filter
	DATABAHN_REG(7 , _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(8 , _W_PRIORITY, 0x3),    //audio_dec
	DATABAHN_REG(9 , _W_PRIORITY, 0x5),    //video_dec
	DATABAHN_REG(10, _W_PRIORITY, 0x2),    //apu/hdmi
	DATABAHN_REG(11, _W_PRIORITY, 0x8),    //secure/scpu/usb
	DATABAHN_REG(12, _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(13, _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(14, _W_PRIORITY, 0x8),    //unused
	DATABAHN_REG(15, _W_PRIORITY, 0x8),    //unused

	{DATABAHN_REG_SWAP_EN_ADDR, DATABAHN_REG_SWAP_EN_OFFSET, DATABAHN_REG_SWAP_EN_WIDTH, 0x0},

	// Databahn start enable
	//{DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1}
};

/* routine.c */
static void SetRegisterField(unsigned int reg, unsigned int offset, unsigned int width, unsigned int value)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int value_masked;

	original = *(volatile unsigned int *)reg;

	if (width == 32)
		mask = 0xffffffff;
	else
		mask = (1 << width) - 1;
	value_masked = value & mask;
	result = (original & (~(mask << offset))) | (value_masked << offset);

	*(volatile unsigned int *)reg = result;
}

static unsigned int GetRegisterField(unsigned int reg, unsigned int offset, unsigned int width)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int mask_shifted;

	original = *(volatile unsigned int *)reg;
	if(width==32)
		mask = 0xffffffff;
	else
		mask = (1 << width)-1;
	mask_shifted = mask << offset;
	result = (original & mask_shifted) >> offset;

	return result;
}
#ifdef CONFIG_FPGA_BOARD

void Databahn_SetParameter(unsigned int reg, unsigned int offset, unsigned int width, unsigned int value)
{
	SetRegisterField(Databahn_Reg(reg), offset, width, value);
}

unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width)
{
	return GetRegisterField(Databahn_Reg(reg), offset, width);
}

void Databahn_StartEnable(void)
{
	Databahn_SetParameter(DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1);
}

void Databahn_StartDisable(void)
{
	Databahn_SetParameter(DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 0);
}

unsigned int Databahn_GetIntStatus(void)
{
	return Databahn_GetParameter(DATABAHN_REG_INT_STATUS_ADDR, DATABAHN_REG_INT_STATUS_OFFSET, DATABAHN_REG_INT_STATUS_WIDTH);
}

unsigned int Databahn_isReady(void)
{
	return (Databahn_GetIntStatus()&0x20)?1:0;
}

unsigned int Databahn_GetAltMemPhyParamter(void)
{
	unsigned int dat;

	dat = *(volatile unsigned int *)0xa030a158;
	return dat;
}

unsigned int Databahn_isAltMemPhyReady(void)
{
	if(Databahn_GetAltMemPhyParamter()&(1<<16))
		return 1;
	else
		return 0;
}

void Databahn_Init(void)
{
	volatile unsigned int i;

	ddr_config_patch();

	for(i=0;i<155;i++)
	{
		*(volatile unsigned int *)Databahn_Reg(i) = DENALI_CONFIG_CTL[i];
	}
	for(i=0;i<26;i++)
	{
		*(volatile unsigned int *)Databahn_Reg(i+256) = DENALI_CONFIG_PHY[i];
	}

	Databahn_StartEnable();
#ifdef CONFIG_ACCELERATOR
	while(!Databahn_isReady());
#endif

}


#else
/* databahn.c */
void Databahn_Init(void)
{
	unsigned int i;
	unsigned int ddr_type;
	unsigned int tsel_feed;
	unsigned int data_e_sel;
	unsigned int ocd_pu_dq;
	unsigned int ocd_pd_dq;
	unsigned int ocd_pu_clk;
	unsigned int ocd_pd_clk;
	unsigned int ocd_pu_cmd;
	unsigned int ocd_pd_cmd;
	unsigned int dfi_cmd_control;
	unsigned int vref_set;
	//unsigned int ddr_vref_en; //not used
	unsigned int cwl;
	unsigned int encry_delay;
	unsigned char ddr_kgd;
	unsigned char ddr_info;
	unsigned int *p_DENALI_CONFIG_CTL;
	unsigned int *p_DENALI_CONFIG_PHY;
#ifdef DDR_PAR_PATCH_INCLUDE
	ddr_kgd = otp_read_simple(0x138) & 0xF; //!!!OTP_addr TBD!!!
	serial_put_no_mmu('k');
	serial_put_no_mmu('g');
	serial_put_no_mmu('d');
	serial_put_no_mmu(':');
	serial_put_no_mmu(ddr_kgd + '0');
	serial_put_no_mmu('\r');
	serial_put_no_mmu('\n');
#endif

	/* set ddrc_clk */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<25);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT_NORM) &= ~((1<<27)|(1<<28));

	/* set ddrc_ports */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DENALI_CONFIG0)=0xffffffff;

	/* reset ddrc */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) |= (0x1);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) &= ~(0x1);

	//============set dram_config0-3: begin===================
	//clear config0-3
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3)=0x0;

	p_DENALI_CONFIG_CTL = DENALI_CONFIG_CTL;
	p_DENALI_CONFIG_PHY = DENALI_CONFIG_PHY;

	//#1: config1[30], set ddr_type

#ifdef CONFIG_DDR3
	ddr_type = 0x1;
#elif defined(CONFIG_DDR2)
	ddr_type = 0x0;
#else
#error "DDR_TYPE error"
#endif

#ifdef CHIP_BOARD_3113XX
	ddr_info = otp_read_simple(0x10D) & 0xf;
	if (ddr_info == 2) {
		p_DENALI_CONFIG_CTL = DENALI_CONFIG_CTL;
		p_DENALI_CONFIG_PHY = DENALI_CONFIG_PHY;
		ddr_type = 0x0;
	} else {
		p_DENALI_CONFIG_CTL = DENALI_CONFIG_CTL_2;
		p_DENALI_CONFIG_PHY = DENALI_CONFIG_PHY_2;
		ddr_type = 0x1;
	}
#endif

	//#2: config0[2:0], tsel_feed
	tsel_feed = 0x1;

	//#3: config0[15], data_e_sel, choose the switch of the receiver in DDRIO
	//data_e_sel=0 means switch is controlled by DRAM_CONFIG0[14:11]
	data_e_sel = 0x0;

	//#4: ocd_pu&ocd_pd
	ocd_pu_dq  = 8; //config0[19:16]
	ocd_pd_dq  = 8; //config0[23:20]
	ocd_pu_clk = 8; //pu_clk: config1[17:14], pd_dqs: config1[6:3]
	ocd_pd_clk = 8; //pu_clk: config1[21:18], pd_dqs: config1[10:7]
	ocd_pu_cmd = 8; //config2[6:3]
	ocd_pd_cmd = 8; //config2[10:7]

	//#5: set output driver_strength of DDRIO in board_init.c
	ddr_config_patch();

	//#6: config0[31], dfi_cmd_control
	dfi_cmd_control = 0x1;

	//#7: config2[19:16], set Vref
	vref_set = 0x0;

	//#8: config3[1:0], set encry_delay
	cwl = (p_DENALI_CONFIG_CTL[5] >> 16) & 0x1F;
	encry_delay = (cwl - 4) / 2;

	////#9: config3[19], ddr_vref_en
	//ddr_vref_en=0x0;

	//set DRAM_CONFIG
#ifndef CONFIG_ACCELERATOR
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0) |= (tsel_feed<<0) | (data_e_sel<<15) | (ocd_pu_dq<<16) | (ocd_pd_dq<<20) | (dfi_cmd_control<<31);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1) |= (ocd_pu_clk<<3) | (ocd_pd_clk<<7) | (ocd_pu_clk<<14) | (ocd_pd_clk<<18) | (ddr_type<<30);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2) |= (ocd_pu_cmd<<3) | (ocd_pd_cmd<<7) | (vref_set<<16);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3) |= (encry_delay<<0);
#endif
	//============set dram_config0-3: end===========

	for(i = 0;i < sizeof(DENALI_CONFIG_CTL)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg(i) = p_DENALI_CONFIG_CTL[i];

	for(i = 0; i < sizeof(DENALI_CONFIG_PHY)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg((i + 256)) = p_DENALI_CONFIG_PHY[i];

#ifdef DDR_PAR_PATCH_INCLUDE
	if (ddr_kgd > 0) {
		for (i = 0; i < sizeof(DDR_PAR_PATCH_ARRAY)/sizeof(struct ddr_patch); i++) {
			if (ddr_kgd == DDR_PAR_PATCH_ARRAY[i].kgd_type)
				*(volatile unsigned int *)DDR_PAR_PATCH_ARRAY[i].addr = DDR_PAR_PATCH_ARRAY[i].value;
		}
	}
#endif

	Databahn_Config();

	while(!Databahn_isReady());
}

void Databahn_SetParameters(struct reg_param *regs, int count)
{
	int i;

	for (i=0; i < count; i++)
		SetRegisterField(Databahn_Reg(regs[i].reg), regs[i].offset, regs[i].width, regs[i].value);
}

void Databahn_Config(void)
{
	Databahn_SetParameters(param_table, sizeof(param_table) / sizeof(struct reg_param));

	// Databahn start enable
	SetRegisterField(Databahn_Reg(DATABAHN_REG_START_ADDR), DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1);
}

unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width)
{
	return GetRegisterField(Databahn_Reg(reg), offset, width);
}

unsigned int Databahn_GetIntStatus(void)
{
	return Databahn_GetParameter(DATABAHN_REG_INT_STATUS_ADDR, DATABAHN_REG_INT_STATUS_OFFSET, DATABAHN_REG_INT_STATUS_WIDTH);
}

unsigned int Databahn_isReady(void)
{
	return (Databahn_GetIntStatus() & 0x20) ? 1 : 0;
}

#endif

void gx_setup_sdram_controller(void)
{
	Databahn_Init();
	serial_put_no_mmu('N');

	/* used for scorpio secure align */
#ifdef ENABLE_SECURE_ALIGN
	volatile unsigned int i = 0x10000;
	*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_CTRL) = 1;
	while(*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_CTRL) != 0x02);
	*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_DATA);
	while (i--) //delay 30 ms
		__asm__ volatile ("nop");
#endif
}

