PROJECT(gxcas C CXX)
INCLUDE(scripts/toolchain.cmake)
INCLUDE(scripts/config.cmake)
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

SET(CMAKE_BUILD_TYPE $ENV{BUILD_MODE})
IF (CMAKE_BUILD_TYPE STREQUAL release)
	MESSAGE(STATUS "BUILD_FLAGS : ${CMAKE_C_FLAGS_RELEASE}")
ELSEIF (CMAKE_BUILD_TYPE STREQUAL debug)
	MESSAGE(STATUS "BUILD_FLAGS : ${CMAKE_C_FLAGS_DEBUG}")
ENDIF()

INCLUDE_DIRECTORIES(include)
AUX_SOURCE_DIRECTORY(module MODULE)

ADD_GX_LIBRARY(gxmodule
	${MODULE}
	)
ADD_GX_LIBRARY(gxcas
	${CAS}
	)

INSTALL(DIRECTORY include/ DESTINATION ${GOXCEED_PATH}/include/gxcas/)
