#include <stdio.h>
#include <string.h>
#include <config.h>
#include <version_autogenerated.h>
#include <gx_mem_info.h>

extern char *bootloader_tags;
extern unsigned long memparse(char *ptr, char **retptr);
extern char * get_cmdline(void);
extern void cmdline_init(const char *cmd);

__attribute__((weak)) char *bootloader_tags;
int parse_tag_cmdline(void)
{
	if (*(unsigned int *)(bootloader_tags + 4) == 0x54410003){
		cmdline_init(bootloader_tags+8);
#ifdef CONFIG_ARCH_CKMMU_GX6605S
		cmdline_add("chipid=0x6605");
#endif
		return 0;
	}
	printf("bootloader_tags err!: %s %d\n", __func__, __LINE__);
	return -1;
}

static char *tmp_cmdline = NULL;

static char *cmdline_alloc(void)
{
	tmp_cmdline = malloc(COMMAND_LINE_SIZE);
	if (!tmp_cmdline) {
		printf("error: %s %d, malloc failed\n", __func__, __LINE__);
		return NULL;
	}
	memset(tmp_cmdline, 0x0, COMMAND_LINE_SIZE);
	strncpy(tmp_cmdline, get_cmdline(), COMMAND_LINE_SIZE);
	return tmp_cmdline;
}

static void cmdline_free(void)
{
	if (tmp_cmdline) {
		free(tmp_cmdline);
		tmp_cmdline = NULL;
	}
}

int gx_mem_info_get(char *name, struct gx_mem_info *info)
{
	int ret = 0;
	char *args = NULL;
	char *param = NULL;
	char *val = NULL;

	if (!info) {
		printf("error: %s %d\n", __func__, __LINE__);
		return -1;
	}

	if ((args = cmdline_alloc()) == NULL)
		return -1;

	while (*args) {
		val = NULL;
		param = NULL;
		args = next_arg(args, &param, &val);
		if (!(param && val))
			continue;

		if (!strcmp(name, param)) {
			info->size = memparse(val, &val);
			if (*(val++) != '@') {
				printf("error: %s %d, <%s> param error\n", __func__, __LINE__, name);
				ret = -1;
				goto exit;
			}
			info->start = memparse(val, &val);
#ifdef GX_MEM_DEBUG
			printf("name : %-10s, start : 0x%08x, size : 0x%08x\n", name, info->start, info->size);
#endif

			ret = 0;
			goto exit;
		}
	}

	ret = -1;

exit:
	cmdline_free();
	return ret;
}

int gx_mem_get_int32_value(char *name, int *value)
{
	int ret = -1;
	char *args = NULL;
	char *param = NULL;
	char *val = NULL;

	if (!value)
		return -1;

	if ((args = cmdline_alloc()) == NULL)
		return -1;

	while (*args) {
		val = NULL;
		param = NULL;
		args = next_arg(args, &param, &val);
		if (!(param && val))
			continue;

		if (!strcmp(name, param)) {
			*value = memparse(val, NULL);
			ret = 0;
			break;
		}
	}

exit:
	cmdline_free();
	return ret;
}

int gx_mem_protect_type_get(int *type)
{
	static int protect_flag = -1;
	*type = 0;
	if (protect_flag != -1) {
		*type = protect_flag;
		return 0;
	}

	if (gx_mem_get_int32_value("protect_flag", type) < 0)
		return -1;

	protect_flag = *type;
	return 0;
}

int gx_mem_secure_align(void)
{
    if (strstr((const char*)get_cmdline(),"secure_align"))
        return 1;
    return 0;
}
