#include <stdio.h>
#include <version_autogenerated.h>
#include <get_mem_info.h>
#include <gx_mem_info.h>
#include <gx_otp.h>

int get_mem_info(struct mem_info *info)
{
	if (!info)
		return -1;

	if (info->type == SPP_BUF) {
		info->addr = SPP_BUF_START_ADDR;
		info->len = SPP_BUF_END_ADDR - SPP_BUF_START_ADDR;
	} else if (info->type == SVPU_BUF) {
		info->addr = SVPU_BUF_START_ADDR;
		info->len = SVPU_BUF_END_ADDR - SVPU_BUF_START_ADDR;
	} else if (info->type == OSD_BUF) {
		info->addr = OSD_BUF_START_ADDR;
		info->len = OSD_BUF_END_ADDR - OSD_BUF_START_ADDR;
	} else {
		printf("get mem failed, error mem type : 0x%x\n", info->type);
		return -1;
	}

	return 0;
}

int protect_flag_probe(void)
{
#if !defined ENABLE_LIB && defined CONFIG_ENABLE_GX_OTP
	unsigned int flag = 0;

	// main switch
	if (gx_otp_query_flag(OTP_FLAG_DDR_CONTENT_LIMIT) == false)
		return 0;

	// DEMUX TS buff switch
	if (gx_otp_query_flag(OTP_FLAG_TS_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_DEMUX_TSW | GXMEM_FLAG_DEMUX_TSR;

	// DEMUX ES buff switch
	if (gx_otp_query_flag(OTP_FLAG_ES_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_DEMUX_ES;

	// VIDEO/AUDIO FIRMWARE buff switch
	if (gx_otp_query_flag(OTP_FLAG_FW_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_VIDEO_FIRMWARE | GXMEM_FLAG_AUDIO_FIRMWARE;

	// VIDEO frame / VPU buff switch
	if (gx_otp_query_flag(OTP_FLAG_VOUT_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_VIDEO_FRAME | GXMEM_FLAG_VPU_CAP;

	// Audio frame buff switch
	if (gx_otp_query_flag(OTP_FLAG_AOUT_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_AUDIO_FRAME;

	// GP buff switch
	if (gx_otp_query_flag(OTP_FLAG_GP_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_GP_ES;

	// SCPU buff switch
	if (gx_otp_query_flag(OTP_FLAG_SCPU_BUF_PROTECT) == true)
		flag |= GXMEM_FLAG_SCPU;

	return flag;
#else
	return 0;
#endif
}
