#include "common/sec_rw.h"
#include "version_autogenerated.h"

void sec_write(unsigned int addr, unsigned int value, unsigned int delay)
{
#if defined(CONFIG_ARCH_CKMMU_GX6605S)
	__asm__ __volatile("  \
	sync                \n\
	br      2f          \n\
	1:                  \n\
	subi    %2, %2, 1   \n\
	2:                  \n\
	cmpnei  %2, 0       \n\
	bt      1b          \n\
	sync                \n\
	st      %1, (%0, 0) \n\
	sync                \n\
	":
	:"r"(addr),"r"(value),"r"(delay)
	:
	);
#else
	*(volatile unsigned int *)addr = value;
#endif
}

unsigned int sec_read(unsigned int addr, unsigned int delay)
{
	unsigned int rdata;
#if defined(CONFIG_ARCH_CKMMU_GX6605S)
	__asm__ __volatile("  \
	sync                \n\
	br      2f          \n\
	1:                  \n\
	subi    %2, %2, 1   \n\
	2:                  \n\
	cmpnei  %2, 0       \n\
	bt      1b          \n\
	sync                \n\
	ld      %0, (%1, 0) \n\
	sync                \n\
	":"=r"(rdata)
	:"r"(addr),"r"(delay)
	:
	);
#else
	rdata = *(volatile unsigned int *)addr;
#endif
	return(rdata);
}

