#include "fat.h"
#include "usb.h"
#include "time.h"
#include "stdio.h"
#include <gx_flash_common.h>
#include "flash.h"
#include "gx3201/gx3201_api.h"
#include "watchdog.h"
#include "partition.h"
#include "version_autogenerated.h"

#if defined(ENABLE_USB_RECOVER)||defined(CONFIG_ENABLE_USB)

#ifdef CONFIG_RECOVERY_IMAGE
#define UPDATE_FILE CONFIG_RECOVERY_IMAGE
#else
#define UPDATE_FILE "/recovery.rcv"
#endif

#ifdef USB_RECOVER_WHOLE_IMAGE
#define UPDATE_SKIP_BLOCK 0
#else
#define UPDATE_SKIP_BLOCK 2
#endif

#define ROOT_HUB_INDEX  0
#define MAX_PORTS 10
#ifdef CONFIG_RECOVERY_IMAGE_SIZE
#define BIN_LENGTH  CONFIG_RECOVERY_IMAGE_SIZE
#else
#define BIN_LENGTH  0x400000
#endif

#define USB_MAX_PROBE_TIME 1375

int au_usb_stor_curr_dev = -1; /* current device */

static void flash_update(unsigned int flash_addr, const unsigned char *buf, unsigned int flash_len)
{
	//printf("Erase flash address: 0x%x, len: %d\n", flash_addr, flash_len);
	gxflash_erasedata(flash_addr, flash_len);
	//printf("Write to flash address: 0x%x, len: %d\n", flash_addr, flash_len);
	gxflash_pageprogram(flash_addr, (uint8_t*)buf, flash_len);
}

extern int gdi_upgrade_guide(void);
extern int gdi_upgrade_waiting(int x,int y,int w,int h);
extern int gdi_upgrade_process(int val);
extern int gdi_upgrade_start(void);
extern void gdi_palette_init(void);
extern int gdi_upgrade_end(void);

extern void irr_poll(void);
extern int irr_read(void *buffer, uint32_t *len);
extern int gx3211_svpu_do_run(void);

/* todo : 还需优化，每读取一次就要初始化一次设备 */
int usb_read(unsigned char *data, int datalen, char *filename)
{
	block_dev_desc_t *stor_dev;
	unsigned int partition = 0;
	unsigned int  start_time;
	int dev_index, dev_num;
	int res = -1;

	/* start USB */
	if (usb_stop() < 0) {
		printf("usb_stop failed\n");
		return -1;
	}

	if (usb_init() < 0) {
		printf("usb_init failed\n");
		return -1;
	}

	/*
	 * check whether a storage device is attached (assume that it's
	 * a USB memory stick, since nothing else should be attached).
	 */
	start_time = get_timer(0);
	do {
		au_usb_stor_curr_dev = usb_stor_scan(0);
		if (au_usb_stor_curr_dev != -1)
			break;
		mdelay(100);
	} while (get_timer(start_time) < USB_MAX_PROBE_TIME);

	dev_num = usb_stor_num_get();
	for (dev_index = 0; dev_index < dev_num; dev_index++) {
		/* check whether it has a partition table */
		stor_dev = usb_stor_get_dev(dev_index);
		if (stor_dev == NULL) {
			printf("the %d device is uknown device type\n", dev_index);
			res = -1;
			continue;
		}

		for(partition = 1; partition <= USB_MAX_PARTITON; partition++) {
			if (fat_register_device(stor_dev, partition) == 0) {
				if((res = file_fat_read(filename, data, datalen)) != -1)
					break;
			}
		}

		if(partition > USB_MAX_PARTITON) {
			res = -1;
			continue;
		}

		break;
	}

	usb_stop();
	return res;
}
static unsigned int ok_key_array[] =
{
	0xbb4457a8,
	0xFF00A758,
};

static unsigned int exit_key_array[] =
{
	0xbb444fb0,
	0xFF005FA0,
};

static int gxirr_poll(void)
{
	unsigned int ret = 1;
	unsigned int len = 4;
	unsigned int code;
	int i = 0;
	mdelay(100);

	irr_poll();

	ret = irr_read(&code, &len);
	if(ret == 0)
	{
		printf("code = %x\n",code);
		for(i = 0; i<(sizeof(ok_key_array)/sizeof(ok_key_array[0]));i++)
		{
			if(code == ok_key_array[i])
			{
				return 0;
			}
		}
		for(i = 0; i<(sizeof(exit_key_array)/sizeof(exit_key_array[0]));i++)
		{
			if(code == exit_key_array[i])
			{
				return 1;
			}
		}
	}

	return -1;
}
int usb_recover_proc(void)
{
	unsigned char *pbuf = NULL;
	block_dev_desc_t *stor_dev;
	int res = 0, ret = 0;
	unsigned int block_num = 0;
	unsigned int i = 0;
	unsigned int partition = 0;
	unsigned int  start_time;
	unsigned int block_size;

	block_size = gxflash_get_info(GX_FLASH_BLOCK_SIZE);

	/* start USB */
	if (usb_stop() < 0) {
		printf("usb_stop failed\n");
		return -1;
	}

	if (usb_init() < 0) {
		printf("usb_init failed\n");
		return -1;
	}

	/*
	 * check whether a storage device is attached (assume that it's
	 * a USB memory stick, since nothing else should be attached).
	 */
	start_time = get_timer(0);
	do {
		au_usb_stor_curr_dev = usb_stor_scan(0);
		if (au_usb_stor_curr_dev != -1)
			break;
		mdelay(100);
	} while (get_timer(start_time) < USB_MAX_PROBE_TIME);

	/* check whether it has a partition table */
	stor_dev = usb_stor_get_dev(0);
	if (stor_dev == NULL) {
		printf("uknown device type\n");
		res = -1;
		goto exit;
	}

	if((pbuf = (unsigned char*)malloc(BIN_LENGTH)) == NULL) {
		printf("malloc failed!\n");
		res = -1;
		goto exit;
	}

	for(partition = 1; partition <= USB_MAX_PARTITON; partition++) {
		if (fat_register_device(stor_dev, partition) == 0) {
			if((file_fat_read(UPDATE_FILE, pbuf, BIN_LENGTH)) != -1)
				break;
		}
	}

	if(partition > USB_MAX_PARTITON) {
		res = -1;
		goto exit;
	}

	block_num = BIN_LENGTH / block_size;
	if((BIN_LENGTH % block_size) > 0)
		block_num++;

	if(block_num > UPDATE_SKIP_BLOCK) {
		struct usb_device *usb_dev = NULL;
		int port_num;
		unsigned char usb_port_save[MAX_PORTS];
		unsigned char usb_port[MAX_PORTS];

		usb_dev = usb_get_dev_index(ROOT_HUB_INDEX);
		port_num = usb_get_port_num(usb_dev);

		for (i = 0; i < port_num; i++)
			usb_port_save[i] = usb_get_port_stat(usb_dev, i+1);

		gdi_palette_init();
		gx3211_svpu_do_run();
		gdi_upgrade_guide();
		gxflash_write_protect_unlock();
		printf("____________usb update____block_num = %d________\n",block_num);
		while(1) {
			ret = gxirr_poll();
			if(ret==0) {
				gdi_upgrade_start();
				gdi_upgrade_process(0);
				for(i = UPDATE_SKIP_BLOCK; i < block_num; i++) {
					flash_update(i * block_size, pbuf + (i * block_size), block_size);
					printf("[%s]%d update proc %d %d%%\n", __func__, __LINE__,i , i*100/block_num);
					gdi_upgrade_process(i*100/block_num);
					//_fd650_show_num(i*100/block_num);
				}
				// _fd650_show_num(100);
				printf("[%s]%d update proc finish\n", __func__, __LINE__);
				gdi_upgrade_process(100);
				gdi_upgrade_end();
				break;
			} else if(ret == 1) {
				gdi_upgrade_waiting(50,140,16,20);
				usb_stop();
				return -1;
			} else
				continue;
		}
		while(1) {
			int detected = 0;
			for (i = 0; i < port_num; i++) {
				usb_port[i] = usb_get_port_stat(usb_dev, i+1);
				if ((usb_port[i] & 0x1) != (usb_port_save[i] & 0x1)) {
					detected = 1;
					break;
				}
			}

			if (detected) {
				printf("restart...\n");
				gx_wdt_reset_soon(10);
			} else
				printf("Update finish, please plug out!!!!!\n");
		}
	} else
		usb_stop();

exit:
	if (usb_stop() < 0) {
		printf("usb_stop failed\n");
		return -1;
	}
	if(pbuf)
		free(pbuf);
	return res;
}
#endif
