#ifndef __GX_PLAYER_CONFIG_H__
#define __GX_PLAYER_CONFIG_H__

/* #undef HAVE_BYTESWAP_H */

#define CONFIG_DVB_FE
#define CONFIG_STREAM_DVB
#define CONFIG_STREAM_FILE
#define CONFIG_STREAM_FFFILE
#define CONFIG_STREAM_HTTP
#define CONFIG_STREAM_FFHTTP
/* #undef CONFIG_STREAM_FFRIST */
#define CONFIG_STREAM_RTSP
#define CONFIG_STREAM_FFRTSP
#define CONFIG_STREAM_RTMP
#define CONFIG_STREAM_FFRTMP
#define CONFIG_STREAM_FFRTMPHTTP
#define CONFIG_STREAM_LIVE555
#define CONFIG_STREAM_MEM
#define CONFIG_STREAM_FIFO
#define CONFIG_STREAM_RINGMEM
/* #undef CONFIG_STREAM_MMS */
/* #undef CONFIG_STREAM_FFMMS */
#define CONFIG_STREAM_M3U8
#define CONFIG_STREAM_FFHLS
#define CONFIG_STREAM_UDP
#define CONFIG_STREAM_FFUDP
#define CONFIG_STREAM_TCP
#define CONFIG_STREAM_RTP
#define CONFIG_STREAM_FFRTP
/* #undef CONFIG_STREAM_FFSRTP */
/* #undef CONFIG_STREAM_FFDATA */
#define CONFIG_STREAM_FFCRYPTO
#define CONFIG_STREAM_FFCONCAT
/* #undef CONFIG_STREAM_WFD */
#define CONFIG_STREAM_CRYPTO
#define CONFIG_STREAM_HWCRYPTO
#define CONFIG_STREAM_MPEGDASH
#define CONFIG_STREAM_FFCOMPOSE
#define CONFIG_STREAM_FM
#define CONFIG_STREAM_FFASSOCIATIONLIBRE
#define CONFIG_STREAM_ASSOCIATIONLIBRE
/* #undef CONFIG_MUX_RAWVIDEO */
/* #undef CONFIG_MUX_MPEGTS */
#define CONFIG_DEMUX_HW
#define CONFIG_DEMUX_MPEG_AUDIO
#define CONFIG_DEMUX_MPEG_PS
#define CONFIG_DEMUX_MPEG_TS
#define CONFIG_DEMUX_MKV
#define CONFIG_DEMUX_AVI
/* #undef CONFIG_DEMUX_RMVB */
#define CONFIG_DEMUX_FLV
#define CONFIG_DEMUX_MOV
#define CONFIG_DEMUX_AAC
#define CONFIG_DEMUX_ES
/* #undef CONFIG_DEMUX_LIVE555 */
/* #undef CONFIG_DEMUX_ASF */
#define CONFIG_DEMUX_OGG
#define CONFIG_DEMUX_APE
/* #undef CONFIG_DEMUX_REAL */
#define CONFIG_DEMUX_TS
#define CONFIG_DEMUX_TLS
#define CONFIG_IPTV_ENABLE
#define CONFIG_DEMUX_MP3
#define CONFIG_DEMUX_SBC
#define CONFIG_DEMUX_AC3
#define CONFIG_DEMUX_DTS
#define CONFIG_DEMUX_FM
#define CONFIG_DEMUX_FLAC
#define CONFIG_DEMUX_WAV
#define CONFIG_FFMPEG_ENABLE
#define CONFIG_DEMUX_ASSOCIATIONLIBRE
#define CONFIG_VD_HW
/* #undef CONFIG_VD_MPEG */
/* #undef CONFIG_VD_DUMMY */
/* #undef CONFIG_VD_MJPEG */
#define CONFIG_AD_HW
#define CONFIG_AD_SW
/* #undef CONFIG_AD_SW_APE */
/* #undef CONFIG_AD_MP3 */
/* #undef CONFIG_AD_DUMMY */
#define CONFIG_VO_HW
/* #undef CONFIG_VO_FBDEV */
/* #undef CONFIG_VO_DUMMY */
#define CONFIG_AO_HW
/* #undef CONFIG_AO_OSS */
/* #undef CONFIG_AO_SDL */
/* #undef CONFIG_AO_DUMMY */
#define CONFIG_MEM_POOL
#define CONFIG_SUBTITLE_DVB
#define CONFIG_SUBTITLE_ARIBCC
#define CONFIG_SUBTITLE_ATSCCC
#define CONFIG_SUBTITLE_SCTE
#define CONFIG_SUBTITLE_TELETEXT
#define CONFIG_SUBTITLE_MEDIA
#define CONFIG_SUBTITLE_TTML
#define CONFIG_AVCODEC_DIVX
#define CONFIG_STREAM_CACHE
/* #undef CONFIG_VOD_SYSTEM */
#define CONFIG_DVB_RECORD
#endif
