#ifndef __USER_H__
#define __USER_H__

#include "stdio.h"
#include "string.h"

#include "util.h"
#include "gx_flash_common.h"
#include "gx_flash.h"
#include "flash.h"
#include "config.h"

#include "boot.h"
#include "gx_api.h"
#include "bootmenu.h"
#include "partition.h"
#include "time.h"
#include "serial.h"
#include "irr.h"
#include "interrupt.h"
#include "gpio.h"
#include "rcc.h"
#include "eeprom.h"
#include <scpu.h>
#include "version_autogenerated.h"
#include <gxhwlib_registers.h>
#include "common/gx_mem_info.h"

#ifdef CONFIG_ENABLE_OTA
#include "gxota.h"
#endif

#ifdef CONFIG_ENABLE_NET
#include <net.h>
#endif

#ifdef CONFIG_ENABLE_CTR
#include  "ctr.h"
#endif

#ifdef CONFIG_ENABLE_IO_FRAMEWORK
#include "../ate/include/io.h"
#endif

#ifdef CONFIG_ENABLE_JTAG_PASSWD
#include "jtagpasswd.h"
#endif

#ifdef CONFIG_ENABLE_FIREWALL
#include "gx_firewall.h"
extern int demux_SMP_config(int mem_type, int id, unsigned int addr, int size);
extern int audio_SMP_config(int mem_type, int id, unsigned int addr, int size);
extern int video_SMP_config(int mem_type, int id, unsigned int addr, int size);
extern int scpu_SMP_config(int mem_type, int id, unsigned int addr, int size);
#endif

#ifdef ENABLE_SECURE_VERIFY
#include "common/verify.h"
#endif

#ifdef CONFIG_ENABLE_TEE
#include "driver/gx_permit.h"
#endif

void canopus_user_firewall_init(void);

#endif
