#ifndef _VOD_IN_TYPEDEF_H_
#define _VOD_IN_TYPEDEF_H_


typedef enum
{
	ERRNO_VOD_NO_ERROR =0,
	ERRNO_VOD_ERROR_RESULT,
	ERRNO_VOD_TIMEOUT ,
	ERRNO_VOD_PARAM ,
	ERRNO_VOD_NOSOCKET ,
	ERRNO_VOD_CONNECT_SERVER ,
	ERRNO_VOD_TUNER_LOCK,
	ERRNO_VOD_NET_FAIL,
	ERRNO_VOD_NOTHISINFO,
	ERRNO_VOD_UNAUTHORIZE,
	ERRNO_VOD_OUTRANGE,
	ERRNO_VOD_SERVER_REFUSE,
	ERRNO_VOD_NO_MEMORY,
	ERRNO_VOD_CONNECT_SER,
	ERRNO_VOD_SERVER_RES,
	ERRNO_VOD_SDP_INFO,
	ERRNO_VOD_SETUP_VID,
	ERRNO_VOD_SETUP_AUD,
	ERRNO_VOD_TRANSTYPE,
	ERRNO_VOD_PLAY,
	ERRNO_VOD_PAUSE,
	ERRNO_VOD_STOP,
	ERRNO_VOD_WAIT_RES,





	ERR_VOD_END 
}ERRNO_VOD_t;


/*以下定义play函数的返回值*/
#define PLAY_OK                    0
#define ERR_DSPDOWNLOAD           -1
#define ERR_NETCONNECT            -2
#define ERR_SEND_PLAYCMD          -3
#define ERR_AUDIOSESSION_CREATE   -4
#define ERR_VIDEOSESSION_CREATE   -5
#define ERR_PREBUFFER_FAIL        -6
#define ERR_DSPSTOPWORK           -7
#define ERR_NET_FAIL              -8
#define ERR_OBJECT_FAIL           -9
#define ERR_MSG_INIT_FAIL           -10


typedef enum
{
	VOD_TRANS_TYPE_NONE = 0X00 ,
	VOD_TRANS_TYPE_ISMA ,
	VOD_TRANS_TYPE_TS,
	VOD_TRANS_TYPE_ASF,
	VOD_TRANS_TYPE_HWTS,

	VOD_TRANS_TYPE_END
	
}VOD_TRANS_TYPE_t;

typedef enum
{
	VOD_RECV_TYPE_NONE = 0X00 ,
	VOD_RECV_TYPE_TCPINTERLEAVE,
	VOD_RECV_TYPE_UDP ,
	VOD_RECV_TYPE_IGMP,
	VOD_RECV_TYPE_QAM,
	VOD_RECV_TYPE_TCP,

	VOD_RECV_TYPE_END
	
}VOD_RECV_TYPE_t;


typedef enum/*此结构定义为vod内部＆外部统一的，如果修改到此结构，需要与vod_common_def.h同步*/
{
	VOD_APP_UNKNOWN = 0,
	VOD_APP_SIHUA_VOD,
	VOD_APP_SIHUA_SHIFT,
	VOD_APP_SIHUA_SINGLE,
	VOD_APP_SIHUA_MP3,
	VOD_APP_IPTV2_VOD,
	VOD_APP_IPTV2_SINGLE,
	VOD_APP_IPTV2_GROUP,
	VOD_APP_IPTV2_MP3,
	VOD_APP_MOTO_LSCP_VOD,
	VOD_APP_MS_MMS_VOD,
	VOD_APP_COSHIP,
	VOD_APP_COSHIP_LIVING,	
	VOD_APP_PVR,
	VOD_APP_WFD,
	VOD_APP_END
}VOD_APP_TYPE_t;

typedef enum/*此结构定义为vod内部＆外部统一的，如果修改到此结构，需要与vod_common_def.h同步*/
{
	VOD_RANGE_TYPE_NONE = 0,
	VOD_RANGE_TYPE_NPT,
	VOD_RANGE_TYPE_CLOCK,
	VOD_RANGE_TYPE_PTS,
	VOD_RANGE_TYPE_STAMP,

	VOD_RANGE_TYPE_END
} VOD_RANGE_TYPE_t;

typedef enum/*此结构定义为vod内部＆外部统一的，如果修改到此结构，需要与vod_common_def.h同步*/
{
	EVENT_NONE = 0,
	EVENT_PLAY_START,
	EVENT_PROGRAM_END,
	EVENT_SERVER_NORESP,
	EVENT_SERVER_CLOSED,
	EVENT_CONNECTION_CLOSED,
	EVENT_BEGINNING_OF_FILE,
	EVENT_END_OF_FILE,
	EVENT_IP_CABLE_IN,
	EVENT_IP_CABLE_OUT,
	EVENT_TS_CABLE_IN,
	EVENT_TS_CABLE_OUT,
	EVENT_RTP_BUFFER_OVERFLOW,
	EVENT_TS_BUFFER_OVERFLOW,
	EVENT_NET_BUSY,
	EVENT_NET_OK,
	EVENT_RANGE_ERROR,
	EVENT_RETURN_CODE_ERROR,

	EVENT_END	
}VOD_EVENT_t;

typedef enum
{
	VOD_SERVER_NONE = 0,
	VOD_SERVER_SIHUA,
	VOD_SERVER_HUAWEI,
	VOD_SERVER_MOTO,
	VOD_SERVER_ZTE,
	VOD_SERVER_TAIDE,
	VOD_SERVER_UT,
	VOD_SERVER_ASB,

	VOD_SERVER_END
} VOD_SERVER_TYPE_t;

#define IO_TCP					1
#define IO_UDP					2
#define IO_CABLE				3

#endif

