#!/bin/sh

ver="v0.1 -- 20150812"

help()
{

cat << HELP
Usages: ./create_board <chip_core> <src chip_board> <create chip_board>
eg.	./create_board gx3201 3201e-dvbc 3201e-guangxi
	./create_board gx3201 3201-dvbc 3201-anhui
HELP
	exit 0
}

error()
{
	echo "$1"
	exit 1
}

echo_exec()
{
	echo $1
	$1
}

par_check()
{
	if [ $# -lt 3 ]; then
		echo "parameters not enough."
		help
	fi
}

main()
{
	par_check $@

	if [ -d ../gxloader ]; then
		pre_dir=./
	elif [ -d ../../gxloader ]; then
		pre_dir=../
	else
		echo "error: you must put create_board in directory gxloader or gxloader/tools."
		exit 1
	fi

	conf_src_dir="${pre_dir}conf/${1}/${2}"
	conf_dst_dir="${pre_dir}conf/${1}/${3}"
	board_src_dir="${pre_dir}board/${1}/board-${2}"
	board_dst_dir="${pre_dir}board/${1}/board-${3}"

	if [ -d ${conf_dst_dir} ]; then
		echo "error: ${conf_dst_dir} already exist, please check."
		exit 1
	else
		echo_exec "cp $conf_src_dir $conf_dst_dir -rf"
		echo "find conf/${1}/${3}/ -name \"*.config\" |xargs sed -i \"s/CHIP_BOARD = ${2}/CHIP_BOARD = ${3}/g\""
		find ${conf_dst_dir} -name "*.config" |xargs sed -i "s/CHIP_BOARD = ${2}/CHIP_BOARD = ${3}/g"
	fi

	if [ -d ${board_dst_dir} ]; then
		echo "error: ${board_dst_dir} already exist, please check."
		exit 1
	else
		echo_exec "cp ${board_src_dir} ${board_dst_dir} -rf"
	fi

	echo "finish operate, please confirm directory & config."
}

main $@
