flash_size    0x800000
block_size    0x010000
write_protect true
crc32         true

# 1) NAME field:
#	"BOOT"   : gxloader
#	"TABLE"  : partition table
#	"LOGO"   : gxloader show logo
#	"KERNEL" : application program
#	"ROOT"   : root file system
#
# 2) The FS field have these types:
#           "RAW": self definition file system type;
#           "CRAMFS":  cram_file_system type;
#           "MINIFS":  mini_file_system type;
# 3) The partition have 2 mode "ro" and "rw":
#           "ro": means that this partition could not been modified at runtime;
#           "rw": means that this partition could modify at runtime
# 4) The size of "auto" means the size of partition is determined by source file size, but for
#    the final partition (example "DATA") it means the size is last to the end of flash.
#
## NOTE:
#
# 1) The size of source file could not exceed the max size of partition.
# 2) The start addr of "BOOT" and "LOGO" should never be modified whenever you are
#    modifying this file (configure file) or running a program.
# 3) The 1K bytes blank befor the "LOGO" partition is reserved for partition table,
#    so do not use these space.
# 4)
# name   source file           CRC        file_system_type mode    update   version 	start addr   size
#---------------------------------------------------------------------------------------------------------
BOOT    loader-sflash.bin    true        RAW     	   ro	  0	    0       0x000000     auto
OTA     ota.img              false       RAW               ro     0         0       0x020000     auto
TABLE   NULL                 true        RAW               ro     0         0       0x070000     auto
LOGO    logo.bin             false       RAW     	   ro	  0	    0       0x080000     auto
KERNEL  ecos_romfs.img       true        RAW     	   ro     0	    0       0x090000     auto
ROOT    root_cramfs.img      false       CRAMFS            ro     0	    0       0x550000     auto
#THEME   theme_cramfs.img       false        CRAMFS           ro     0     0         0x560000     auto
OEM     variable_oem.ini     true        RAW     	   rw	  0	    0       0x6e0000     auto
BACKOEM      NULL            true        RAW               rw     0         0       0x6f0000     64K
DATA    minifs.img           false       MINIFS            rw 	  0	    0       0x700000     auto
