#include "stdio.h"
#include "string.h"
#include "gxota.h"
#include "version_autogenerated.h"
#include "boot.h"
#include "load_kernel.h"
#include <gx_flash_common.h>
#include "flash.h"
#include "libini.h"
#include "simple_gxdlp_api.h"

#define MAX_OTA_FLASH_SECTION 10
struct ota_storage_flash_region {
	unsigned int base;
	unsigned int size;
};

struct ota_storage_info {
	unsigned int cnt;
	unsigned int total_size;
	struct ota_storage_flash_region region[MAX_OTA_FLASH_SECTION];
};

extern int gxirr_start(void);

#ifdef OTA_FORCE_MULTI_SECTION_FLASH
static int gxota_storage_info_get(struct ota_storage_info *ota_storage)
{
	char *args = NULL;
	char *param = NULL;
	char *val = NULL;
	char *ota_bin_cmdline = NULL;
	int ota_bin_cmdline_len = strlen(OTA_FORCE_MULTI_SECTION_FLASH) + 1;
	int ret = 0;

	if (!ota_storage) {
		printf("error: %s %d\n", __func__, __LINE__);
		return -1;
	}

	ota_bin_cmdline = args = malloc(ota_bin_cmdline_len);
	if (!args) {
		printf("error: %s %d, malloc failed\n", __func__, __LINE__);
		ret = -1;
		goto exit;
	}
	memset(args, 0x0, ota_bin_cmdline_len);

	strncpy(args, OTA_FORCE_MULTI_SECTION_FLASH, ota_bin_cmdline_len);

	ota_storage->cnt = 0;
	ota_storage->total_size = 0;

	/* ota_bin_cmdline like kernel cmdline param "mem="
	 * for example,"ota_sec1=64K@0x10000 ota_sec2=384K@0x60000",
	 * The ota file is divided into two segments and stored at
	 * different addresses in the flash
	 **/
	while (*args && ota_storage->cnt < MAX_OTA_FLASH_SECTION) {
		val = NULL;
		param = NULL;
		args = next_arg(args, &param, &val);
		if (!(param && val))
			continue;

		ota_storage->region[ota_storage->cnt].size = memparse(val, &val);
		if (*(val++) != '@')
			goto exit;
		ota_storage->region[ota_storage->cnt].base = memparse(val, &val);

		ota_storage->total_size += ota_storage->region[ota_storage->cnt].size;
		ota_storage->cnt++;
	}

exit:
	if (*args && ota_storage->cnt == MAX_OTA_FLASH_SECTION) {
		printf("error: only support 10 section");
		ret = -1;
	}

	if (ota_bin_cmdline) {
		free(ota_bin_cmdline);
		ota_bin_cmdline = NULL;
	}
	return ret;
}

int gxota_get_bin_size(void)
{
	struct ota_storage_info ota_storage;

	gxota_storage_info_get(&ota_storage);

	return ota_storage.total_size;
}

int gxota_load(uint8_t *ota_bin_buf, uint32_t ota_bin_size)
{
	struct ota_storage_info ota_storage;
	int i = 0;
	int offset = 0;

	if (ota_bin_buf == NULL) {
		printf("error: param ota_bin_buf is NULL\n");
		return -1;
	}

	gxota_storage_info_get(&ota_storage);

	if (ota_storage.total_size > ota_bin_size) {
		printf("error: ota_bin_size %d < ota bin size %d\n", ota_storage.total_size, ota_bin_size);
		return -1;
	}

	for (i = 0; i < ota_storage.cnt; i++) {
		if ((offset + ota_storage.region[i].size) > ota_bin_size)
			return -1;
		gxflash_readdata(ota_storage.region[i].base, ota_bin_buf + offset, ota_storage.region[i].size);
		offset += ota_storage.region[i].size;
	}

	return 0;
}
#endif


void gxota_entry(void)
{
	struct partition_info* partition_ota;
	GxDLP_Download_Type type;

	printf("try to enter ota to update \n");
#if (defined(OTA_FORCE_FLASH_ADDR) && (defined(OTA_FORCE_FLASH_SIZE)))
#ifdef CONFIG_SIMPLE_DLP_SUPPORT
	GxDLP_Init(CONFIG_DLP_PATH, CONFIG_BACKUP_DLP_PATH);
	GxDLP_Get_UpdateType(&type);
	GxDLP_Close();
	if (type == GXDLP_NONE_DOWNLOAD
		|| type == GXDLP_OTA_FAILED) {
		printf("not need enter ota to update\n");
		return;
	}
#endif
	printf("enter ota to update\n");
	partition_ota = malloc(sizeof(struct partition_info));
	if (partition_ota) {
		memset(partition_ota, 0, sizeof(struct partition_info));
		strcpy(partition_ota->name, "OTA");
		partition_ota->total_size = OTA_FORCE_FLASH_SIZE;
		partition_ota->partition_size = partition_ota->total_size;
		partition_ota->start_addr = OTA_FORCE_FLASH_ADDR;
		doboot_kernel(partition_ota);
		free(partition_ota);
		partition_ota = NULL;
	}
#else
#error "OTA_FORCE_FLASH_ADDR and OTA_FORCE_FLASH_SIZE must be defined"
#endif
}

