//This .c is generated by python  script tool.
//Please do not edit it by yourself.
//sources: netappsmenu-config.json, allconfig.json
//process: app_netapps_common_ex.c

#include "app.h"
#include "app_main_menu.h"
#include "app_netapps_init.h"
void app_netapps_event_init_ex(void)
{
}
