#include "version_autogenerated.h"
#include "cpu_config.h"
#include "stdio.h"
#include "board-common.h"

//#define CONFIG_ETH_PHY_CLOCK_USE_PLL

static void __dto_config(struct dto_param *param, unsigned char mmu_flag, unsigned char sec_flag)
{
	unsigned int data;
	unsigned int config_base;
	unsigned int dto_cfg_addr;

	unsigned int value_cfg_addr;
	unsigned int dto;
	unsigned int source_sel;
	unsigned int div;
	unsigned int source_sel_bit;

	if ((!param) || !(param->dto))
		return;

	dto		= param->dto;
	source_sel	= param->source_sel;
	div		= param->div;
	source_sel_bit	= param->source_sel_bit;

	config_base = CONFIG_CLOCK_BASE;

	if (sec_flag == 0) {
		dto_cfg_addr = config_base + CONFIG_DTO1_CONFIG + 4 * (dto - 1);

		if (param->source_sel == 1)
			value_cfg_addr = config_base + CONFIG_CLOCK_SOURCE1;
		else if (param->source_sel == 2)
			value_cfg_addr = config_base + CONFIG_CLOCK_SOURCE2;
	} else {
		dto_cfg_addr = config_base + CONFIG_DTO1_CONFIG_SEC + 4 * (dto - 1);

		value_cfg_addr = config_base + CONFIG_CLOCK_SOURCE_SEC;
	}

	__raw_writel((0<<31 | 1<<30 | div), dto_cfg_addr);
	__raw_writel((1<<31 | 1<<30 | div), dto_cfg_addr);

	data = __raw_readl(value_cfg_addr);
	__raw_writel((data | source_sel_bit), value_cfg_addr);
}

// fo = fi*div/2^30
// div = fo*2^30/fi
// dto select the bus, fi is dto's pll fre, fo is bus fre (output fre), here fi is 1188000000
void DTO_Config(struct dto_param *param, unsigned char mmu_flag)
{
	__dto_config(param, mmu_flag, 0);
}

// fo = fi*div/2^30
// div = fo*2^30/fi
// dto select the bus, fi is dto's pll fre, fo is bus fre (output fre), here fi is 1188000000
void DTO_Sec_Config(struct dto_param *param, unsigned char mmu_flag)
{
	__dto_config(param, mmu_flag, 1);
}

static void __div_config(struct div_param *param, unsigned char mmu_flag, unsigned char sec_flag)
{
	int i ;
	int data ;

	unsigned int div_cfg_addr;
	unsigned int value_cfg_addr;
	unsigned int config_base;

	unsigned int div_cfg_id;
	unsigned int value_cfg_id;
	unsigned int bit_width;
	unsigned int rstn;
	unsigned int load;
	unsigned int ratio;
	unsigned int value;

	if (!param)
		return;

	config_base = CONFIG_CLOCK_BASE;

	div_cfg_id   = param->div_cfg_id;
	value_cfg_id = param->value_cfg_id;
	bit_width    = param->bit_width;
	rstn         = param->rstn;
	load         = param->load;
	ratio        = param->ratio;
	value        = param->value;

	if (sec_flag == 0) {
		if (div_cfg_id == 1)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG1;
		else if(div_cfg_id == 2)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG2;
		else if (div_cfg_id == 3)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG3;
		else if (div_cfg_id == 4)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG4;
		else
			while(1);

		if (value_cfg_id == 1)
			value_cfg_addr = config_base + CONFIG_CLOCK_SOURCE1;
		else if (value_cfg_id == 2)
			value_cfg_addr = config_base + CONFIG_CLOCK_SOURCE2;
		else
			while(1);
	} else {
		if (div_cfg_id == 0)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG0_SEC;
		else if(div_cfg_id == 1)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG1_SEC;
		else if (div_cfg_id == 2)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG2_SEC;
		else if (div_cfg_id == 3)
			div_cfg_addr = config_base + CONFIG_CLOCK_DIV_CONFIG3_SEC;
		else
			while(1);

		value_cfg_addr = config_base + CONFIG_CLOCK_SOURCE_SEC;
	}

	data = __raw_readl(div_cfg_addr);
	__raw_writel((data & ~(bit_width)) | load | ratio, div_cfg_addr);
	data = __raw_readl(div_cfg_addr);
	__raw_writel((data | rstn), div_cfg_addr);

	data = __raw_readl(value_cfg_addr);
	__raw_writel((data | value), value_cfg_addr);
}

void DIV_Config(struct div_param *param, unsigned char mmu_flag)
{
	__div_config(param, mmu_flag, 0);
}

void DIV_Sec_Config(struct div_param *param, unsigned char mmu_flag)
{
	__div_config(param, mmu_flag, 1);
}

void PLL_Config(unsigned int pll, unsigned int value)
{
	volatile unsigned int j = 100;
	*(volatile unsigned int*)(pll) = (0xf<<27)|value;
	while(j--);
	*(volatile unsigned int*)(pll) = (0x0<<27)|value;
}

void PLL_Config_Power_Down(unsigned int pll)
{
	*(volatile unsigned int*)(pll) |= (0xf<<27);
}

static struct dto_param dto_table_full[] = {
/*      dto  |   source_sel |  div  |  source_sel_bit */
	{1 ,        1,       0x05555555,   1<<1 }, // APU SRL0(I2S0) 99MHz
	{2 ,        1,       0x05555555,   1<<2 }, // APU SPD0       99MHz
	{3 ,        1,       0x05555555,   1<<3 }, // APU SRL1(I2S1) 99MHz
	{4 ,        1,       0x05555555,   1<<4 }, // APU SPD1       99MHz
	{5 ,        1,       0x0ccccccc,   1<<5 }, // Audio play AHB 237.6MHz
	{6 ,        1,       0x10000000,   1<<6 }, // Audio decoder  297MHz
	{7 ,        1,       0x10000000,   1<<15}, // VPU AXI        297MHz
	{8 ,        1,       0x0ccccccc,   1<<17}, // JPEG           237.6MHz
	{9 ,        1,       0x00000000,   1<<18}, // PP clock is depended on JPEG_PP AXI
	{10,        1,       0x0ccccccc,   1<<19}, // JPEG_PP AXI    237.6MHz
	{11,        1,       0x10000000,   1<<20}, // GA             297 MHz
	{16,        1,       0x15555555,   1<<16}, // Video decoder 396MHz
	{17,        1,       0x0aaaaaaa,   1<<11}, // hdmi axi 198MHz
};

static struct dto_param dto_sec_table_full[] = {
/*      dto  |   source_sel(sec) |  div  |  source_sel_bit */
	{1,         1,       0x0ccccccc,   1<<0 }, // Demux sys        237.6MHz
	{2,         1,       0x05d1745d,   1<<1 }, // Demux STC        108MHz
	{3,         1,       0x09249249,   1<<2 }, // pidfilter        169.7MHz
	{4,         1,       0x09249249,   1<<3 }, // GSE              169.7MHz
	{8,         1,       0x0ccccccc,   1<<16}, // APB2_3/smartcard 237.6MHz
	//{9,         1,       0x0aaaaaaa,   1<<21}, // HDCP22           198MHz
};

static struct div_param div_table_full[] = {
	{1, 2, 0xff<<24 , 1<<31 , 1<<30 , 5<<24 , 1<<21}, // SDIO        198MHz
	{1, 2, 0xff<<16 , 1<<23 , 1<<22 , 3<<16 , 1<<4 }, // USB 12M     12MHz
	{1, 2, 0xff<<8  , 1<<15 , 1<<14 , 26<<8 , 1<<5 }, // ETH PHY     50MHz=PLL_ETH/27
	{1, 1, 0xff<<0  , 1<<7  , 1<<6  , 11<<0 , 0<<0 }, // Audio loDAC 99MHz

	{2, 1, 0x3<<21  , 1<<23 , 1<<22 , 3<<21 , 0    }, // SVPU pixel 13.5MHz
	{2, 1, 0xff<<12 , 1<<19 , 1<<18 , 43<<12, 1<<10}, // SVPU pixel double 27MHz
	{2, 1, 0xff<<0  , 1<<7  , 1<<6  , 7<<0  , 1<<9 }, // VPU pixel double clock/HDMI 148.5MHz

#ifdef DVB_CHANNEL_C
	/* 27MHz/24MHz XTAL DVB C PLL_DVB == 1080MHz */
	{3, 1, 0xff<<16 , 1<<23 , 1<<22 , 17<<16 , 1<<24}, // DVB demod_l     60MHz
#elif defined(DVB_CHANNEL_S2)
#if defined(CONFIG_24M_XTAL)
	/* 24MHz XTAL DVB S2 PLL_DVB == 1536MHz */
	{3, 1, 0xff<<16 , 1<<23 , 1<<22 , 7<<16 , 0    }, // adc clk          1536/8=192MHz
	{3, 1, 0xff<<8  , 1<<15 , 1<<14 , 3<<8  , 1<<23}, // DVB fec clk 1536/4/2=192MHz ts_base clk 1536/4=384
	{3, 1, 0xff<<0  , 1<<7  , 1<<6  , 11<<0 , 1<<22}, // DVB demod_h clk  128MHz
#else /* 27MHz XTAL */
	/* 27MHz XTAL DVB S2 PLL_DVB == 756MHz */
	{3, 1, 0xff<<16 , 1<<23 , 1<<22 , 3<<16 , 0    }, // adc clk          756/4=189MHz
	{3, 1, 0xff<<8  , 1<<15 , 1<<14 , 1<<8  , 1<<23}, // DVB fec clk 756/2/2=189MHz ts_base clk 756/2=378
	{3, 1, 0xff<<0  , 1<<7  , 1<<6  , 5<<0  , 1<<22}, // DVB demod_h clk  126MHz
#endif /* CONFIG_24M_XTAL */
#endif /* DVB_CHANNEL_C */
};

static struct div_param div_sec_table_full[] = {
	{0, 1, 0xff<<8  , 1<<15 , 1<<14 , 7<<8  , 1<<7 }, // IFCP/SCPU  148.5MHz
	{0, 1, 0xff<<16 , 1<<23 , 1<<22 , 5<<16 , 1<<18}, // TSIO sys   198MHz
};

static void USB_SetSuspendM(void)
{
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) &= ~(1<<10);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) &= ~(1<<26);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB2_CONFIG) &= ~(1<<26);
}

static void USB_ClrSuspendM(void)
{
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) |= (1<<10);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) |= (1<<26);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB2_CONFIG) |= (1<<26);
}

static void USB_SetPhyReset(void)
{
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) |= (1<<12);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) |= (1<<28);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB2_CONFIG) |= (1<<28);
}

static void USB_ClrPhyReset(void)
{
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) &= ~(1<<12);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB1_CONFIG) &= ~(1<<28);
	*(volatile unsigned int *)(USB_CONFIG_BASE + CONFIG_USB2_CONFIG) &= ~(1<<28);
}

static void USB_Init(void)
{
	unsigned int usb_clock_source_cfg = 0;

	/* USB PHY clock source from xtal to 12MHz clock*/
	usb_clock_source_cfg |= (1<<0);
	/* USB UTMI clock source from xtal to USB PHY clock*/
	usb_clock_source_cfg |= (1<<1);
	/* USB UTMI1 clock source from xtal to USB PHY clock*/
	usb_clock_source_cfg |= (1<<2);
	/* USB 48m clock source from xtal to USB PHY clock*/
	usb_clock_source_cfg |= (1<<3);
	/* USB 12m clock source please see div_table_full */
	usb_clock_source_cfg |= (1<<4);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE+CONFIG_CLOCK_SOURCE2) |= usb_clock_source_cfg;

	/*                      usb phy                      */
	*(volatile unsigned int*)(USB_PHY_PORT1 + 0x00) = 0x1f;
	*(volatile unsigned int*)(USB_PHY_PORT1 + 0x08) = 0x5c;
	*(volatile unsigned int*)(USB_PHY_PORT1 + 0x18) = 0x05;

	*(volatile unsigned int*)(USB_PHY_PORT2 + 0x00) = 0x1f;
	*(volatile unsigned int*)(USB_PHY_PORT2 + 0x08) = 0x5c;
	*(volatile unsigned int*)(USB_PHY_PORT2 + 0x18) = 0x05;

	/* usb phy port */
	*(volatile unsigned int*)(USB_CONFIG_BASE + CONFIG_USB_CONFIG)  |= (1<<25) | (1<<31) | (0x20<<8) | (0x20<<20) | (0x20<<26) | (0xf<<16);
	*(volatile unsigned int*)(USB_CONFIG_BASE + CONFIG_USB3_CONFIG) |= (1<<25) | (0x20<<20);
	*(volatile unsigned int*)(USB_CONFIG_BASE + CONFIG_USB6_CONFIG) |= (1<<0); // config phy clock 12M, 0 : 24M, 1 : 12M

	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();
	USB_ClrSuspendM();
	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();
}

static void hdmi_disable (void)
{
	//TODO
}

static void hdmi_enable(void)
{
	//TODO
}

static void eth_disable (void)
{
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE2) &= ~(1<<5);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE2) &= ~((1<<6)|(1<<7)|(1<<8)); //set eth rm|mtx|mrx clock source to xtal
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG1) |= (1<<4)|(1<<5)|(1<<6);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (1<<15);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG0) |= (1<<28);
}

static void eth_enable(void)
{
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE+CONFIG_CLOCK_SOURCE2) |= (1<<6)|(1<<7)|(1<<8); //set eth rm|mtx|mrx clock source to pll
}

static void dvb_disable(void)
{
	/* switch DVB related clock from PLL to xtal */
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE1) &= ~((1<<22)|(1<<23)|(1<<24)|(1<<26)|(1<<28)|(1<<31));
	/* Disable DVB related clock */
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG0) |= (1<<21)|(1<<22)|(1<<23)|(1<<27)|(1<<30);
}

static void dvb_enable(void)
{
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE1) |= 1 << 26; // ADC clock source from xtal to PLL
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE1) |= 1 << 31; // ts_base clock source from xtal to pll
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_GLB) |= 1 << 2; // IQADC to DVB clock source
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE1) |= 1 << 28; // DVB ADC clock source from xtal to ADC clock or PLL
	*(volatile unsigned int *)(CONFIG_BASE + CONFIG_DVB_SELECT)    &= ~(1 << 0);

#ifdef DVB_CHANNEL_S2
	/* Disable DVB demod_l clk */
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG0) |= (1<<23);
#else /* DVB_CHANNEL_C */
	/* Disable DVB fec clk and demod_h clk */
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG0) |= (1<<21)|(1<<22);
#endif
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_ADC_CONFIG_0) |=  0x3;
}

void __gx_setup_pll_full_controller(void)
{
	int i;
#ifdef DVB_CHANNEL_S2
#ifdef CONFIG_24M_XTAL
	unsigned int dvb_clk = 1536000000;
#else /* 27MHz XTAL */
	unsigned int dvb_clk = 756000000;
#endif
#elif defined(DVB_CHANNEL_C)
	unsigned int dvb_clk = 1080000000;
#endif
	unsigned int ts_clock_source_cfg = 0;
	unsigned int hdmi_clock_source_cfg = 0;

#if defined(DVB_CHANNEL_S2) || defined(DVB_CHANNEL_C)
	PLL_Config(CONFIG_CLOCK_BASE + CONFIG_DVB_PLL_CONFIG, get_pll_config(dvb_clk));    // PLL_DVB
	while ((*(volatile unsigned int*)(CONFIG_CLOCK_BASE+CONFIG_PLL_CONFIG_IN) & (1 << 3)) != (1 << 3)); // wait pll dvb
#endif
	PLL_Config(CONFIG_CLOCK_BASE + CONFIG_TSIO_PLL_CONFIG, get_pll_config(1593000000)); // PLL TSIO
	while ((*(volatile unsigned int*)(CONFIG_CLOCK_BASE+CONFIG_PLL_CONFIG_IN) & (1 << 4)) != (1 << 4)); // wait pll tsio lock
	PLL_Config(CONFIG_CLOCK_BASE + CONFIG_ETH_PLL_CONFIG, get_pll_config(1350000000)); // PLL ETH
	while ((*(volatile unsigned int*)(CONFIG_CLOCK_BASE+CONFIG_PLL_CONFIG_IN) & (1 << 5)) != (1 << 5)); // wait pll eth lock

	/* TSIO PHY PLL select from TSIO PLL */
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_GLB) |= 1 << 4;
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1 << 20);
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) |= 1 << 19;
	*(volatile unsigned int *)0x8ac00118 = 0x47;
	*(volatile unsigned int *)0x8ac0011c = 0x45555533;

	/* select PP from JPEG_PP AXI or JPEG_PP AIX div 2 */
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_DTO9_CONFIG) |= 1 << 31;

	// DTO config
	for (i = 0; i < sizeof(dto_table_full)/sizeof(struct dto_param); i++) {
		DTO_Config(&dto_table_full[i], 1);
	}
	for (i = 0; i < sizeof(dto_sec_table_full)/sizeof(struct dto_param); i++) {
		DTO_Sec_Config(&dto_sec_table_full[i], 1);
	}

	// DIV config
	for (i = 0; i < sizeof(div_table_full)/sizeof(struct div_param); i++)
		DIV_Config(&div_table_full[i], 1);
	for (i = 0; i < sizeof(div_sec_table_full)/sizeof(struct div_param); i++)
		DIV_Sec_Config(&div_sec_table_full[i], 1);

	/* HDMI TMDS clk */
	hdmi_clock_source_cfg |= 1 << 25;
	/* HDMI pre clk */
	hdmi_clock_source_cfg |= 1 << 26;
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE2) |= hdmi_clock_source_cfg;

	eth_enable();
#if defined(DVB_CHANNEL_S2) || defined(DVB_CHANNEL_C)
	dvb_enable();
#else
	dvb_disable();
#endif

	USB_Init();

	// select VDAC clock source 0: VPU VDAC clock 1: SVPU VDAC clock
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE1) |= (1<<14);

	/************** TS clock ****************/
	ts_clock_source_cfg |= (1<<10);//ts serial channel1
	ts_clock_source_cfg |= (1<<11);//ts parallel channel1
	ts_clock_source_cfg |= (1<<12);//ts parallel channel2
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE2) |= ts_clock_source_cfg;

	//release AKL reset
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_AKL_RESET_RELEASE) |= 0x1;

	//close hdcp22 clock
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= 1 << 22;
}

void gx_setup_pll_full_controller(void)
{
#ifdef ENABLE_BOOT_TOOL
	/* .boot or .jboot always runs in the REE. If the permissions for the secure clock are set to be
	 * inaccessible from the REE in the permit, then CONFIG_ETH_PLL_CONFIG will also be inaccessible.
	 * In this case, there is no need to wait for the PLL ETH lock.  */
	PLL_Config(CONFIG_CLOCK_BASE + CONFIG_ETH_PLL_CONFIG, get_pll_config(1350000000)); // PLL ETH
	DIV_Config(&div_table_full[2], 1); //config ETH PHY DIV
	USB_Init();
	eth_enable();
#else
#ifdef CONFIG_REE_LOADER
	gxteeloader_setup_pll();
#else
	__gx_setup_pll_full_controller();
#endif
#endif
}

void __gx_power_reduction(void)
{
        /* close vdec clock */
        *(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE1) &= ~(1<<16);
        *(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG0) |= 1<<15;

#ifdef CONFIG_CLOCK_TSIO_DISABLE
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_GLB) &= ~(1 << 4);
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) |= (1 << 20);
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1 << 19);
	*(volatile unsigned int *)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1 << 18);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (3<<20);
	PLL_Config_Power_Down(CONFIG_CLOCK_BASE + CONFIG_TSIO_PLL_CONFIG); // PLL TSIO
#endif
#ifndef CONFIG_ETH_PHY_CLOCK_USE_PLL
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE2) &= ~(1<<5);
	PLL_Config_Power_Down(CONFIG_CLOCK_BASE + CONFIG_ETH_PLL_CONFIG); // PLL ETH
#endif
#ifdef CONFIG_CLOCK_ETH_DISABLE
	eth_disable();
	PLL_Config_Power_Down(CONFIG_CLOCK_BASE + CONFIG_ETH_PLL_CONFIG); // PLL ETH
#endif
#ifndef CONFIG_ENABLE_NANDFLASH
#ifdef CONFIG_CLOCK_ETH_DISABLE /* 因为 eth 和 NFC 控制器共用了一个 NOC 总线, 当关闭 NFC 时钟会导致 eth 没法使用 */
	/* close AHB NFC clock */
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (1<<13);
#endif
#endif

#ifdef CONFIG_CLOCK_GSE_DISABLE
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1<<3);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (1<<3);
#endif
#ifdef CONFIG_CLOCK_PIDFILTER_DISABLE
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1<<2);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (1<<2);
#endif
#ifdef CONFIG_CLOCK_SDIO_DISABLE
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE2) &= ~(1<<21);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG1) |= (1<<9)|(1<<10)|(1<<11);
#endif
#ifdef CONFIG_CLOCK_SMARTCARD_DISABLE
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1<<16);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (1<<19);
#endif
#ifdef CONFIG_CLOCK_SCPU_DISABLE
	/* close scpu clock */
	//*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_SOURCE_SEC) &= ~(1<<7);
	*(volatile unsigned int*)(CONFIG_CLOCK_BASE + CONFIG_CLOCK_GATE_REG_SEC) |= (1<<7);
#endif
}

void gx_power_reduction(void)
{
#ifdef ENABLE_BOOT_TOOL
	/* Do nothing, .boot or .jboot no need to do power reduction */
#else
#ifdef CONFIG_REE_LOADER
	gxteeloader_power_reduction();
#else
	__gx_power_reduction();
#endif
#endif
}
