#include "stdio.h"
#include "string.h"

#include "config.h"
#include "io.h"

#include "util.h"
#include "serial.h"

#include <version_autogenerated.h>
#include <gxhwlib_registers.h>
#ifdef CONFIG_ENABLE_FIP
#include "fip.h"
#endif
#include "uart_core.h"

#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
#include "interrupt.h"
#endif

#define UART_SCICR               (0x00)
#define UART_SCISR               (0x04)
#define UART_SCIDR               (0x08)
#define UART_SCIBR               (0x0c)
#define UART_SCICFG              (0x10)

// default configuration
#define DEFAULT_UART_DATABITS   8	// 5 - 8
#define DEFAULT_UART_STOPBITS   1	// 1 - 2
#define DEFAULT_UART_PARITY     UART_PARITY_NONE	// none, even, odd

#if defined(CONFIG_ARCH_ARM_SIRIUS)
#define UART0_ISR_VEC_NUM 36
#define UART1_ISR_VEC_NUM 35
#else
#define UART0_ISR_VEC_NUM 0
#define UART1_ISR_VEC_NUM 1
#endif

struct uart_device uart_dev[] = {
	{0, REG_BASE_UART0, UART0_ISR_VEC_NUM, NULL},
	{1, REG_BASE_UART1, UART1_ISR_VEC_NUM, NULL}
};

struct uart_device *get_uart_dev(int port)
{
	unsigned char i = 0;

	for (i = 0; i < sizeof(uart_dev)/sizeof(struct uart_device); i++) {
		if (uart_dev[i].port == port)
			return &uart_dev[i];
	}

	return &uart_dev[0];
}

#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
static enum interrupt_return uart_interrupt_isr(uint32_t vector, void *pdata)
{
	struct uart_device *p_uart_dev = (struct uart_device *)pdata;
	unsigned char c;
	unsigned int  state;

	if(__raw_readl(p_uart_dev->reg_base + UART_SCISR) & 0x20) {
		c = (__raw_readl(p_uart_dev->reg_base + UART_SCIDR) & 0xff);
		if (p_uart_dev->rx_fifo != NULL)
			kfifo_put(p_uart_dev->rx_fifo, &c, 1);
	}

	return HANDLED;
}
#endif

//
// UART initialization
//

static int uart_getclkdiv(int baudrate)
{
	int clkdiv;
	unsigned int uart_srcclk;

	uart_srcclk = GX_UART_CLOCK;

	clkdiv = uart_srcclk / ((16 * baudrate) /100);

	//uart_printf("speed=%d, clkdiv*10=%d\n", speed, clkdiv);
	if (clkdiv % 100 > 50)
		clkdiv = clkdiv / 100;
	else
		clkdiv = clkdiv / 100 - 1;

	return clkdiv;
}

static void uart_init_port(int baudrate, int port)
{
	int clkdiv;
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;
	static int init = 0;

	uart_set_baudrate(baudrate, port);
	if (init > 0)
		return;
	init = 1;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;

	__raw_writel(0x600, gx_uartbase + UART_SCICR);
#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
	if (p_uart_dev->rx_fifo == NULL) {
		p_uart_dev->rx_fifo = kfifo_alloc(UART_RX_FIFO_LEN);
		if (p_uart_dev->rx_fifo == NULL)
			return;
		__raw_writel(0x9600, gx_uartbase + UART_SCICR);
		gx_request_interrupt(p_uart_dev->isr_vec, IRQ, uart_interrupt_isr, p_uart_dev);
	}
#endif
}

void uart_init(int baudrate, int port)
{
	uart_init_port(baudrate, port);
}

void uart_reset(int baudrate, int port)
{
	uart_init_port(baudrate, port);
}

#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
int uart_close_irq(void)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;
	unsigned int port = 0;
	unsigned char i = 0;

	for (i = 0; i < sizeof(uart_dev)/sizeof(struct uart_device); i++) {
		p_uart_dev = &uart_dev[i];
		port = p_uart_dev->port;
		gx_uartbase = p_uart_dev->reg_base;

		__raw_writel(0x600, gx_uartbase + UART_SCICR);
		gx_free_interrupt(p_uart_dev->isr_vec);
	}
}
#endif

int uart_set_baudrate(int baudrate, int port)
{
	int clkdiv;
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;

	clkdiv = uart_getclkdiv(baudrate);

#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
	gx_disable_irq();
#endif
	__raw_writel(clkdiv, gx_uartbase + UART_SCIBR);
#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
	gx_enable_irq();
#endif

	return 0;
}

#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
int uart_flush_in(int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;

	if (p_uart_dev->rx_fifo != NULL) {
		gx_disable_irq();
		kfifo_reset(p_uart_dev->rx_fifo);
		gx_enable_irq();
	}

	return 0;
}
#endif

static inline void uart_raw_putc(int ch, int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;

	while (!(__raw_readl(gx_uartbase+UART_SCISR) & (0x01 << 7)));
	__raw_writel(ch, gx_uartbase+UART_SCIDR);
}

void uart_compatible_putc(int ch, int port)
{
#ifndef CONFIG_NO_PRINT
	/* If \n, also do \r, In order to compatible with the printf of Windows*/
	if (ch == '\n')
		uart_raw_putc('\r', port);
	uart_raw_putc(ch, port);
#endif
}

void uart_putc(int ch, int port)
{
	uart_raw_putc(ch, port);
}

void uart_putstring(int port, unsigned char *buffer, int len)
{
	while (len--)
		uart_raw_putc(*buffer++, port);
}

int uart_getc(int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;
#ifndef CONFIG_NO_GETC
#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
	unsigned char c = 0;

	if (p_uart_dev->rx_fifo != NULL) {
		while (!kfifo_len(p_uart_dev->rx_fifo));
		kfifo_get(p_uart_dev->rx_fifo, &c, 1);
		return c;
	} else
		return 0;
#else
	while (!(__raw_readl(gx_uartbase + UART_SCISR) & 0x20));
	return (__raw_readl(gx_uartbase + UART_SCIDR) & 0xff);
#endif
#else
	return 0;
#endif
}

int uart_try_getc(char *c, int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;
#ifndef CONFIG_NO_GETC
#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
	if (p_uart_dev->rx_fifo != NULL) {
		if (kfifo_len(p_uart_dev->rx_fifo) > 0) {
			kfifo_get(p_uart_dev->rx_fifo, c, 1);
			return 0;
		} else
			return -1;
	} else
		return -1;
#else
	if(__raw_readl(gx_uartbase + UART_SCISR) & 0x20){
		*c = (__raw_readl(gx_uartbase + UART_SCIDR) & 0xff);
		return 0;
	}else{
		return -1;
	}
#endif
#else
	return -1;
#endif
}

#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
int uart_try_getstring(int port, unsigned char *buffer, int len)
{
	struct uart_device *p_uart_dev = get_uart_dev(port);

	if (p_uart_dev->rx_fifo != NULL)
		return kfifo_get(p_uart_dev->rx_fifo, buffer, len);
	else
		return -1;
}
#endif

int uart_tstc(int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;
#if defined (CONFIG_ENABLE_IRQ) && defined (CONFIG_ENABLE_UART_IRQ)
	if (p_uart_dev->rx_fifo != NULL) {
		if (kfifo_len(p_uart_dev->rx_fifo) > 0)
			return 1;
		else
			return 0;
	} else
		return 0;
#else
	return (__raw_readl(gx_uartbase + UART_SCISR) & 0x20) != 0;
#endif
}

int uart_start_break(int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;
	unsigned int _scicr = 0;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;

	_scicr = __raw_readl(gx_uartbase + UART_SCICR);
	_scicr |= 1 << 10;
	_scicr |= 1 << 3;
	__raw_writel(_scicr, gx_uartbase + UART_SCICR);

	return 0;
}

int uart_end_break(int port)
{
	unsigned int gx_uartbase = 0;
	struct uart_device *p_uart_dev;
	unsigned int _scicr = 0;

	p_uart_dev = get_uart_dev(port);
	gx_uartbase = p_uart_dev->reg_base;

	_scicr = __raw_readl(gx_uartbase + UART_SCICR);
	_scicr &= ~(1 << 3);
	__raw_writel(_scicr, gx_uartbase + UART_SCICR);

	return 0;
}
