#include "version_autogenerated.h"
#include "cpu_config.h"
#include "stdio.h"
#include "board-common.h"

void USB_SetSuspendM(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<26);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) &= ~(1<<26);
}

void USB_ClrSuspendM(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<26);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) |= (1<<26);
}

void USB_SetPhyReset(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<12);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<28);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) |= (1<<28);
}

void USB_ClrPhyReset(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<12);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<28);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) &= ~(1<<28);
}

void USB_Init(void)
{
	/* usb phy */
#ifdef CONFIG_BGA
	/*                         BGA                          */
# if (defined USB_RESISTANCE_2_2)
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x00) = 0x18;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x0c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x10) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x14) = 0x13;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x18) = 0xcf;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x1c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x24) = 0x84;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x28) = 0x03;

	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x40) = 0x18;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x4c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x50) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x54) = 0x13;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x58) = 0xcf;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x5c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x64) = 0x84;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x68) = 0x03;
# elif (defined USB_RESISTANCE_10)
# error "BGA not support 10Ω now"
# elif (defined USB_RESISTANCE_0)
# error "BGA not support 0Ω now"
# endif // #if (defined USB_RESISTANCE_2_2)

#elif (defined CONFIG_LQFP)

	/*                         LQFP                         */
# if (defined USB_RESISTANCE_2_2)

	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x00) = 0x07;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x0c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x10) = 0x0e;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x14) = 0x9f;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x18) = 0xcd;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x1c) = 0x02;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x24) = 0x8c;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x28) = 0x03;

	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x40) = 0x07;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x4c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x50) = 0x0e;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x54) = 0x9f;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x58) = 0xcd;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x5c) = 0x02;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x64) = 0x8c;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x68) = 0x03;

# elif (defined USB_RESISTANCE_10)

	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x00) = 0x07;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x0c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x10) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x14) = 0x9f;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x18) = 0xcd;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x1c) = 0x02;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x24) = 0x8c;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x28) = 0x1b;

	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x40) = 0x07;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x4c) = 0x00;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x50) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x54) = 0x9f;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x58) = 0xcd;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x5c) = 0x02;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x64) = 0x8c;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x68) = 0x1b;

# elif (defined USB_RESISTANCE_0)
# error "LQFP not suuport 0Ω now"
# endif

#elif (defined CONFIG_SIP)
	/*                         SIP                         */
# if (defined USB_RESISTANCE_2_2)
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x00) = 0x07;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x0c) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x10) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x14) = 0x9f;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x18) = 0xcd;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x1c) = 0x02;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x24) = 0x8c;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x28) = 0x03;

	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x40) = 0x07;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x4c) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x50) = 0xe0;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x54) = 0x9f;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x58) = 0xcd;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x5c) = 0x02;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x64) = 0x8c;
	*(volatile unsigned int*)(INNO_CONFIG_BASE + 0x68) = 0x03;
# elif (defined USB_RESISTANCE_10)
# error "SIP not support 10Ω now"
# elif (defined USB_RESISTANCE_0)
# error "SIP not support 0Ω now"
# endif // #if (defined USB_RESISTANCE_2_2)

#else
#error "Package not support, please check .config file"
#endif // CONFIG_BGA


	/* clock */
#if 1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<31);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<31); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(0x3f<<24);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (0x3<<24); //div to 148.5
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<30); //load en
#endif
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= 1|(1<<1)|(1<<2)|(1<<3)|(1<<4);

	/* usb phy port */
#if 0
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_USB_CONFIG) |= (1<<25)|(1<<31);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_USB3_CONFIG) |= (1<<25);
#else
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB_CONFIG)  |= (1<<25) | (1<<31) | (0x20<<8) | (0x20<<20) | (0x20<<26) | (0xf<<16);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB3_CONFIG) |= (1<<25) | (0x20<<20);
#endif

#ifdef ENABLE_SECURE_ALIGN
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB3_CONFIG) |= 1; //set usb port 32 bit align
#endif

	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();
	USB_ClrSuspendM();
	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();

#ifdef CONFIG_USB_EYE_DIAGRAM_TEST
	int i = 0;
	int total_num = 0;
	total_num = 0x68;
	for (i = 0; i <= total_num; i+=4) {
		if ((i % 16) == 0)
			printf("\n0x%x: ", INNO_CONFIG_BASE + i);
		printf("0x%08x ", *(volatile unsigned int *)(INNO_CONFIG_BASE + i));
	}
	printf("\n");
#endif
}

/* only for hardware usb test */
void EHCI_Test(void)
{
#define EHCI_OPBASE	(REG_BASE_USB_EHCI+0x10)

#define EHCI_OPREG_USBCMD		(EHCI_OPBASE+0x0)
#define EHCI_OPREG_USBSTS		(EHCI_OPBASE+0x4)
#define EHCI_OPREG_USBINTR		(EHCI_OPBASE+0x8)
#define EHCI_OPREG_FRINDEX		(EHCI_OPBASE+0xc)
#define EHCI_OPREG_CTRLDSSEGMENT	(EHCI_OPBASE+0x10)
#define EHCI_OPREG_PERIODICLISTBASE	(EHCI_OPBASE+0x14)
#define EHCI_OPREG_ASYNCLISTADDR	(EHCI_OPBASE+0x18)
#define EHCI_OPREG_CONFIGFLAG		(EHCI_OPBASE+0x40)
#define EHCI_OPREG_PORTSC1		(EHCI_OPBASE+0x44)
#define EHCI_OPREG_PORTSC2		(EHCI_OPBASE+0x48)
#define EHCI_OPREG_PORTSC3		(EHCI_OPBASE+0x4c)
	printf("enter echi test, hardware engineer can test after this printf.\n");
	*(volatile unsigned int *)(EHCI_OPREG_USBCMD) &= ~((1<<5)|(1<<4));
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC1) |= (1<<7);
	*(volatile unsigned int *)(EHCI_OPREG_USBCMD) &= ~0x1;	//ehci stop
	while(((*(volatile unsigned int *)(EHCI_OPREG_USBSTS)) & (1<<12)) == 0);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC1) |= (4<<16);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC2) |= (4<<16);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC3) |= (4<<16);
	while(1);
}

void close_macrovision(void)
{
	*(volatile unsigned int*)(GX_REG_VIRTUAL_BASE1 + MACROVISION_CTRL0) = 0;
	*(volatile unsigned int*)(GX_REG_VIRTUAL_BASE1 + MACROVISION_CTRL1) = 0;
	*(volatile unsigned int*)(GX_REG_VIRTUAL_BASE1 + MACROVISION_CTRL2) = 0;
	*(volatile unsigned int*)(GX_REG_VIRTUAL_BASE1 + MACROVISION_CTRL3) = 0;
}

static struct pll_dto {
	unsigned int dto;
	unsigned int div;
	unsigned int value;
} dto_table[] = {
	{0  , 0          , 1 << 26} ,  // Ethernet clock
	{7  , 0x08000000 , 1 << 16} ,  // GA 		148.5MHZ
	{8  , 0x091ab875 , 1 << 17} ,  // DemuxSys 	169MHz
	{9  , 0x05d1745d , 1 << 18} ,  // DemuxStc 	108MHz
	{3  , 0x0a9ce01c , 1 << 12} ,  // Video  	197Mhz
	{4  , 0x08000000 , 1 << 13} ,  // JPEG	 	148.5MHZ
	{6  , 0x0cc48677 , 1 << 15} ,  // Audio decoder 240MHZ
	{1  , 0x04a7904a , 1 << 1} ,   // Audio i2s	86.4MHz
	{2  , 0x04a7904a , 1 << 1} ,   // Audio spdif	86.4MHz
	{5  , 0x08000000 , 1 << 14} ,  // PP		148.5MHZ
};

void gx_setup_pll_full_controller(void)
{
	int i;
	unsigned char cfg;
	unsigned int eth_config;
	//unsigned int adc_rdy;

	for (i=0; i < sizeof(dto_table) / sizeof(struct pll_dto); i++) {
		if (dto_table[i].dto != 0)
			DTO_Config(dto_table[i].dto, dto_table[i].div, 1);
		*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL) |= dto_table[i].value;
	}

//tmp macro, will delete later
#define CPU_FREQ	1
#define UART_CLOCK 1
#define AUDIO_USE_DVB 0
#define PCM_CLOCK_OPEN 0
#define USB_DEFINE   0
#if defined(CHIP_BOARD_3201h) || defined(CHIP_BOARD_3211) || defined(CHIP_BOARD_3212_dvbc) || defined(CHIP_BOARD_6610) ||  \
	defined(CHIP_BOARD_6610g) || defined(CHIP_BOARD_6611_dvbs2) || defined(CHIP_BOARD_6611g) || defined(CHIP_BOARD_6621) || defined(CHIP_BOARD_6622_dvbs2) || defined(CHIP_BOARD_generic)
#define ETH_DEFINE   1
#define ETH_PHY_USE_INTERN 1
#else
#define ETH_DEFINE   0
#define ETH_PHY_USE_INTERN 0
#endif

#if 0
//audio decoder
#if AUDIO_USE_DVB
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_DTO6_CONFIG) &= ~(1<<31);	//DTO 31 set 0, use the DVB clock
#else
	DTO_Config(6, 0x0CC48677);//240M // AUDIO USE DTO, USE 240M
#endif
#endif

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<15);

	//clock auido
	//clock audio clock_audio_lodec
	// div
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<31);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<31); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x3f<<23);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (23<<23); //div//24分频、、1188/24=49.5M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<30); //load end
	//   source
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<0); //sel to pll divm clock

	//DVB DIV
	//clock audio clock_audio_lodec
	// div
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<7);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<7); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(0x3f<<0);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (19<<0); //div//24分频、、999/20=49.95M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<6);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<6); //load end
	//select form PLL_DTO  DTO or from the DVB div
	//*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1<<3); //from PLL_DTO DTO
	//*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<3);  //from PLL_DVB DIV

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<2); // SPD clok xtal to pll

	//PCM clock
#if PCM_CLOCK_OPEN
	//gate the mac
	//*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_MPEG_HOT_RST2_1SET) |= (1<<6);//gate
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_MPEG_HOT_RST2_1CLR) |= (1<<6);//open
#endif
	//end audio set

	// begin the video piex clok
	//////pixel CLOCK div

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_MPEG_CLK_INHIBIT_NORM) |= 1 <<30;
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<6);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<6); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x3f<<0);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (0x7<<0); //div to 148.5
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<7);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<7); //load en

	// even div clock
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<20);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<20); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x3f<<12);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (0x2a<<12); //div to 27
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(1<<19);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<19); //load en
	//source
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<5); //from xtal to pll clock

	//SVPU clock source
#ifdef CONFIG_24M_XTAL
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<6); //SVPU clock from DTO
#else
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1<<6); //SVPU clock from xtal
#endif
	//div the pixel clcok to div2
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x7<<8);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (0x5<<8);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &= ~(0x1<<11);   //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (0x1<<11);


	//div the pixel1 clcok to div2
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(0x3<<26);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x3<<26);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(0x1<<25);   //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<25);

	//HDMI  clock_hdmi_icec clock select
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<5);
	//dcs pixel pixdel double hdmi hdmi phy hdmi icec hdmi sfr
	//end the pixel clcok

	// video dac clock

	// dac clock come from pixel doule or ivnv of double
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(0x1<<6);//use the inv of the pixel doubleclock
	///// *(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<6);  //use the pixel double clcok
	// dac clock come from pixel1 doule or ivnv of double
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(0x1<<6);//use the inv of the pixel doubleclock
	//*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<6);  //use the pixel double clcok
	//dac1 0 from pixel 1 from pixel1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1<<8); // select from not xtal
	//dac2 0 from pixel 1 from pixel1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1<<9); // select from not xtal
	//dac3 0 from pixel 1 from pixel1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1<<10); // select from not xtal
	//dac4 0 from pixel 1 from pixel1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<11); // select from not xtal
	//end the video dac

	//TS
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<11);//ts1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<12);//ts2
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<13);//ts3

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<14);//ts1
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<15);//ts2
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<16);//ts3

#if USB_DEFINE
	//use div 99 to get the clock , not need set
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<0); //usb phy generate //12M
	// usb mac clock
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<1); //usb mac 60M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<2); //usb mac 60M
	// usb 48M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<3); //usb mac 48M
	//usb 12M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<31);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<31); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(0x3f<<24);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (0x3<<24); //div to 148.5
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<30); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<4); //from xtal to phy
#endif

	//ETH clock
#if ETH_DEFINE
	//eth phy div
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<23);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<23); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(0x3f<<16);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (43<<16); //div to 44 27M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<22);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<22); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(1<<22); //xtal to pll div

#if ETH_PHY_USE_INTERN
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1<<28); // 0 from the inter phy
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(1<<23); //mii 1 from the phy
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(1<<24); //mii 1 from phy

	//ETH PHY set
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) |= (0x1<<23); // 0 shut down, fixe en zero
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x3<<0); // 0 shut down, fixe en zero
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x3<<9); // 0 norm mode

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x3<<7); // 0 mode select
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) |=  (0x2<<7); // 10 internal rmii and SMI

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x7<<4); // 0 27M clock
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) |=  (0x5<<4); // 10

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x1f<<11); // 0 phy address
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) |=  (0x1<<11); // 10

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x1<<3); // 0  ephy_led_pol

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0xf<<16); // 0 BGS
	gx_otp_read(0x368,1,&cfg);
	if (cfg&(1<<4))
		cfg &= 0xf;
	else
		cfg = 0x7;
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) |=  (cfg<<16); // 10 BGS set

	//PHY rest
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(1<<2); // select from not xtal
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) |= (1<<2); // select from not xtal
#else
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<28); // 1 from eteral phy

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(1<<23); //mii 0 from rmi clock div
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(1<<24); //mii 0 from rmi clcok div
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_EPHY_CONFIG) &= ~(0x1<<23); // 0 shut down, fixe en zero
#endif

	//rmii_clk
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<26); // select from not xtal
	// mii clcok
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<22); // select from not xtal
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<23); // select from not xtal

	// eth phy interface select
	eth_config = *(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_ETH_CONFIG);
	eth_config |= 0x100;
	eth_config &= ~0xc0;
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_ETH_CONFIG) = eth_config; // RMII
#endif


#if 1	//DVB CONFIG

	//ts base clock

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<15);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<15); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(0x3f<<8);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (3<<8); //div to 44 27M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) &= ~(1<<14);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG3) |= (1<<14); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<21); // select from not xtal
	//end ts base

	// PLL clcok select 0 come from DVB 1, come from the DTO
	//come from the DVB
	//*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(1<<20); // select from not xtal
	// come from the DTO
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<20); // select from DTO

#ifdef DVB_CHANNEL_S2
	// DIV for dvbs 1
	// to 118.8 //dvb 1188 div 118.8
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<12);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<12); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x3f<<4);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (9<<4); //div to 44
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<11);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<11); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<30); // select from not xtal

	//to 132M//DVb 1188 div9  to132
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<21);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<21); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x3f<<13);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (8<<13); //div to 44
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<20);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<20); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<29); // select from not xtal

	//When DVBS use the DAC clock for 237.6
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<30); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x3f<<22);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (4<<22); //div to 44 27M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<29);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<29); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<27); // select from not xtal to div

	//adc clock
	//doube mode[19:18] 00 10 xtal  01 div clock 11 div2 of the div clok
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(0x3<<18); // select from not xtal
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<18); // select 01 doube of dvbs clok

	// dvb module adc clok
	// to adc clock inv
	// *(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<10); // select 00 doube of dvbs clok
	//not inv
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<10); //

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (0x1<<31); // xtal to PLL adc
	//adc set

	//set the  fsctrl
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0xff<<10); // fsctrl 000is 1x 11111111 = 1.996x
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |= (0x80<<10); // fsctrl 000is 1x 11111111 = 1.996x
	//bctrl 00110
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0x1f<<2);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |= (0x6<<2); ///70%

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0x1f<<24); // set i2c address
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x1d<<24); // set i2c address //1d << 2 address is 74
	//set the scl and sda is high
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x7<<29); // set scl and sdi and i2c resetz go high

	// when power down . adc is in power down  mode set opm =00;

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~((0x3<<18) | (0x1<<8) ); // adc in power down mode endacr is 0
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |= (1<<8); // endcr disable the duty cycle restorer

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &=  ~(0x3<<22); // use_prev_f is zero ,powerup need the use_prev_f, startcal set zero, power auto starcal

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0x1<<29); // i2c resetz set low keep at leas 4ns
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x1<<29); // i2c resetz set hihgh no is

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x3<<18); // i2c resetz set hihgh no is
	// set to the normal mode
	//do {
	//	adc_rdy = (*(volatile unsigned int*)(CONFIG_BASE_MMU+STATE_ADC))& 0x2 ; // [1] bit is adcrdy
	//} while (!(adc_rdy & 0x2));
	// set the port
	// DVBS set the duble I and q

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x1<<7) |(0x1<<20) ; // i2c resetz set hihgh no is
	//end

#endif

#ifdef DVB_CHANNEL_C
	//When DVBC use the DAC clock for 29.7, DVBC clock to 59.4 so there is 59.4
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<30); //rst
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(0x3f<<22);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (19<<22); //div 20 to 59.4M
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) &= ~(1<<29);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<29); //load en

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<27); // select from not xtal

	//adc clock
	//doube mode[19:18] 00 10 xtal  01 div clock 11 div2 of the div clok
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &= ~(0x3<<18); // select from not xtal
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x3<<18); // select div 2 of dvbc for adc clock is 29.7M

	// dvb module adc clok
	// to adc clock inv
	// *(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<10); // select 00 doube of dvbs clok
	//not inv
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (0x1<<10); // select 00 doube of dvbs clok

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (0x1<<31); // xtal to PLL adc

	//set the  fsctrl
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0xff<<10); // fsctrl 000is 1x 11111111 = 1.996x
	//bctrl 00110
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0x1f<<2);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |= (0x6<<2); ///70%


	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0x1f<<24); // set i2c address
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x1d<<24); // set i2c address //1d << 2 address is 74
	//set the scl and sda is high
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x7<<29); // set scl and sdi and i2c resetz go high

	// when power down . adc is in power down  mode set opm =00;

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~((0x3<<18) | (0x1<<8) ); // adc in power down mode endacr is 0
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |= (1<<8); // endcr disable the duty cycle restorer

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &=  ~(0x3<<22); // use_prev_f is zero ,powerup need the use_prev_f, startcal set zero, power auto starcal

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~(0x1<<29); // i2c resetz set low keep at leas 4ns
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x1<<29); // i2c resetz set hihgh no is

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) |=  (0x3<<18); // i2c resetz set hihgh no is

	// set to the normal mode
	//do {
	//	adc_rdy = (*(volatile unsigned int*)(CONFIG_BASE_MMU+STATE_ADC))& 0x2 ; // [1] bit is adcrdy
	//} while (!(adc_rdy & 0x2));

	// set the port
	// DVBS set the duble I and q

	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_ADC) &= ~((0x1<<7) |(0x1<<20)) ; // one port
	//end


#endif
	//video adc
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_DAC) &= ~(0x1<<0);	//enextref set zero
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_DAC) |= (0x1<<1);	//envbg set high
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_DAC) &= ~(0x7<<4);	//enctr set zero
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_DAC) &= ~(0xf<<8);	//ensc set zero
#endif

	close_macrovision();
	USB_Init();
#ifdef CONFIG_USB_EYE_DIAGRAM_TEST
	EHCI_Test();
#endif

#ifdef ENABLE_SECURE_ALIGN
	// demux
	*(volatile unsigned int*)(REG_BASE_DEMUX + 0x47F0) &= ~0x3;
	*(volatile unsigned int*)(REG_BASE_DEMUX + 0x47F0) |= 0x3;
	// audio_or
	*(volatile unsigned int*)(REG_BASE_ADEC + 0x1EC) &= ~(0x3 << 1);
	*(volatile unsigned int*)(REG_BASE_ADEC + 0x1EC) |= (0x3 << 1);
	// ga
	*(volatile unsigned int*)(REG_BASE_GA + 0x34) |= 1;
#endif

	//modify spdif driver strength, 0xa030aa04[28:27]: 00-6.6mA, 01-13.3mA, [10-19.9mA], 11-26.5mA
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_IO_DRIVE_CTL2) &= ~(0x3 << 12);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_IO_DRIVE_CTL2) |= 0x2 << 12;
}

