#include <stdio.h>
#include "config.h"
#include "io.h"
#include "tdcxo.h"
#include "version_autogenerated.h"

#define  TDCXO_BASE     (0x89b00000)


int TXC_getAdcParameter(int adcValue) {
    if (adcValue <= 30) {
        return -6;
    } else if (adcValue <= 35) {
        return -9;
    } else if (adcValue <= 40) {
        return -11;
    } else if (adcValue <= 45) {
        return -13;
    } else if (adcValue <= 50) {
        return -14;
    } else if (adcValue <= 55) {
        return -16;
    } else if (adcValue <= 60) {
        return -18;
    } else if (adcValue <= 65) {
        return -19;
    } else if (adcValue <= 70) {
        return -20;
    } else if (adcValue <= 75) {
        return -21;
    } else if (adcValue <= 85) {
        return -22;
    } else if (adcValue <= 90) {
        return -23;
    } else if (adcValue <= 105) {
        return -24;
    } else if (adcValue <= 130) {
        return -25;
    } else if (adcValue <= 185) {
        return -26;
    } else if (adcValue <= 245) {
        return -25;
    } else if (adcValue <= 300) {
        return -24;
    } else if (adcValue <= 335) {
        return -23;
    } else if (adcValue <= 380) {
        return -22;
    } else if (adcValue <= 420) {
        return -21;
    } else if (adcValue <= 455) {
        return -20;
    } else if (adcValue <= 505) {
        return -19;
    } else if (adcValue <= 545) {
        return -18;
    } else if (adcValue <= 600) {
        return -17;
    } else if (adcValue <= 655) {
        return -16;
    } else if (adcValue <= 720) {
        return -15;
    } else if (adcValue <= 810) {
        return -14;
    } else if (adcValue <= 855) {
        return -13;
    } else if (adcValue <= 905) {
        return -14;
    } else if (adcValue <= 930) {
        return -15;
    } else if (adcValue <= 940) {
        return -16;
    } else if (adcValue <= 950) {
        return -17;
    } else if (adcValue <= 960) {
        return -18;
    } else {
        return -19; // 对于adcValue >= 961的情况
    }
}

int TDK7pf_getAdcParameter(int adcValue) {
    if (adcValue < 29) {
        return 0;
    } else if (adcValue <= 35) {
        return -1;
    } else if (adcValue <= 40) {
        return -3;
    } else if (adcValue <= 45) {
        return -5;
    } else if (adcValue <= 50) {
        return -7;
    } else if (adcValue == 51) {
        return -9;
    } else if (adcValue == 52) {
        return -12;
    } else if (adcValue == 53) {
        return -13;
    } else if (adcValue == 54) {
        return -15;
    } else if (adcValue <= 59) {
        return -16;
    } else if (adcValue <= 63) {
        return -17;
    } else if (adcValue <= 66) {
        return -18;
    } else if (adcValue == 67) {
        return -19;
    } else if (adcValue <= 77) {
        return -20;
    } else if (adcValue <= 87) {
        return -21;
    } else if (adcValue <= 104) {
        return -22;
    } else if (adcValue <= 222) {
        return -23;
    } else if (adcValue <= 266) {
        return -22;
    } else if (adcValue <= 311) {
        return -21;
    } else if (adcValue <= 353) {
        return -20;
    } else if (adcValue <= 395) {
        return -19;
    } else if (adcValue <= 434) {
        return -18;
    } else if (adcValue <= 484) {
        return -17;
    } else if (adcValue <= 529) {
        return -16;
    } else if (adcValue <= 584) {
        return -15;
    } else if (adcValue <= 662) {
        return -14;
    } else if (adcValue <= 764) {
        return -13;
    } else if (adcValue <= 816) {
        return -12;
    } else if (adcValue <= 858) {
        return -13;
    } else if (adcValue <= 890) {
        return -14;
    } else if (adcValue <= 907) {
        return -15;
    } else if (adcValue <= 924) {
        return -16;
    } else if (adcValue <= 930) {
        return -17;
    } else if (adcValue <= 942) {
        return -18;
    } else {
        return -19; // 对于adcValue > 942的情况
    }
}

int TDK7pf1_getAdcParameter(int adcValue) {
    if (adcValue <= 30) {
        return -3;
    } else if (adcValue <= 35) {
        return -5;
    } else if (adcValue <= 40) {
        return -7;
    } else if (adcValue <= 45) {
        return -10;
    } else if (adcValue <= 50) {
        return -12;
    } else if (adcValue <= 55) {
        return -14;
    } else if (adcValue <= 60) {
        return -15;
    } else if (adcValue <= 65) {
        return -16;
    } else if (adcValue <= 70) {
        return -17;
    } else if (adcValue <= 75) {
        return -18;
    } else if (adcValue <= 80) {
        return -19;
    } else if (adcValue <= 90) {
        return -20;
    } else if (adcValue <= 100) {
        return -21;
    } else if (adcValue <= 125) {
        return -22;
    } else if (adcValue <= 185) {
        return -23;
    } else if (adcValue <= 255) {
        return -22;
    } else if (adcValue <= 300) {
        return -21;
    } else if (adcValue <= 350) {
        return -20;
    } else if (adcValue <= 395) {
        return -19;
    } else if (adcValue <= 440) {
        return -18;
    } else if (adcValue <= 485) {
        return -17;
    } else if (adcValue <= 530) {
        return -16;
    } else if (adcValue <= 590) {
        return -15;
    } else if (adcValue <= 655) {
        return -14;
    } else if (adcValue <= 740) {
        return -13;
    } else if (adcValue <= 860) {
        return -12;
    } else if (adcValue <= 900) {
        return -13;
    } else if (adcValue <= 920) {
        return -14;
    } else if (adcValue <= 935) {
        return -15;
    } else if (adcValue <= 945) {
        return -16;
    } else if (adcValue <= 950) {
        return -17;
    } else if (adcValue <= 955) {
        return -18;
    } else if (adcValue <= 960) {
        return -19;
    } else {
        return -20; // 对于adcValue >= 961的情况
    }
}

int TDK9pf_getAdcParameter(int adcValue) {
    if (adcValue <= 60) {
        return 9;
    } else if (adcValue <= 65) {
        return 7;
    } else if (adcValue <= 70) {
        return 6;
    } else if (adcValue <= 80) {
        return 5;
    } else if (adcValue <= 85) {
        return 4;
    } else if (adcValue <= 100) {
        return 3;
    } else if (adcValue <= 115) {
        return 2;
    } else if (adcValue <= 240) {
        return 1;
    } else if (adcValue <= 295) {
        return 2;
    } else if (adcValue <= 345) {
        return 3;
    } else if (adcValue <= 390) {
        return 4;
    } else if (adcValue <= 435) {
        return 5;
    } else if (adcValue <= 480) {
        return 6;
    } else if (adcValue <= 530) {
        return 7;
    } else if (adcValue <= 575) {
        return 8;
    } else if (adcValue <= 630) {
        return 9;
    } else if (adcValue <= 700) {
        return 10;
    } else if (adcValue <= 770) {
        return 11;
    } else if (adcValue <= 860) {
        return 12;
    } else if (adcValue <= 900) {
        return 11;
    } else if (adcValue <= 925) {
        return 10;
    } else if (adcValue <= 935) {
        return 9;
    } else if (adcValue <= 945) {
        return 8;
    } else {
        return 7; // 对于adcValue >= 946的情况
    }
}

int HC9pf_getAdcParameter(int adcValue) {
    if (adcValue <= 55) {
        return 3;
    } else if (adcValue <= 60) {
        return 2;
    } else if (adcValue <= 65) {
        return 1;
    } else if (adcValue <= 70) {
        return 0;
    } else if (adcValue <= 75) {
        return -1;
    } else if (adcValue <= 85) {
        return -2;
    } else if (adcValue <= 90) {
        return -3;
    } else if (adcValue <= 95) {
        return -4;
    } else if (adcValue <= 110) {
        return -5;
    } else if (adcValue <= 125) {
        return -6;
    } else if (adcValue <= 165) {
        return -7;
    } else if (adcValue <= 200) {
        return -8;
    } else if (adcValue <= 270) {
        return -7;
    } else if (adcValue <= 325) {
        return -6;
    } else if (adcValue <= 375) {
        return -5;
    } else if (adcValue <= 410) {
        return -4;
    } else if (adcValue <= 460) {
        return -3;
    } else if (adcValue <= 510) {
        return -2;
    } else if (adcValue <= 555) {
        return -1;
    } else if (adcValue <= 635) {
        return 0;
    } else if (adcValue <= 710) {
        return 1;
    } else if (adcValue <= 775) {
        return 2;
    } else if (adcValue <= 890) {
        return 3;
    } else if (adcValue <= 915) {
        return 2;
    } else if (adcValue <= 940) {
        return 1;
    } else if (adcValue <= 950) {
        return 0;
    } else {
        return -2; // 对于adcValue > 950的情况
    }
}

/**
 * 测量校准值
 *
 * \param xtal 选择晶振类型，0 TKD0 7pf; 1 TKD1 7pf; 2 TXC 7pf; 3 Hosonic 9pf; 4 TDK 9pf;
 * \param fine 补偿精度，传0默认值35
 * \param *adjust 测量的 adjust 值，可以是负数
 * \param *ppm 测量的 ppm 值，可以是负数
 * \param timeout 测试超时时间,传0为默认148ms
 *
 * \return 返回函数是否执行成功
 * \retval 0 功能正常
 * \retval -1 超时
 */
int gxtdcxo_measure(u32 xtal,u32 fine, s32 *adjust, s32 *ppm, u32 timeout)
{
    int fine_value = 0;
    int reg_value = 0;
    short signed_reg_value = 0;
    int read_value = 0;
    int adc_value = 0;
    int adc_parameter = 0;

    if (fine == 0)
        fine_value = 35; // 默认值35
    else
        fine_value = fine;
    __raw_writel(0, (TDCXO_BASE + 0x04)); // disable module

    __raw_writel((1 << 31), (0x89400704)); // 晶振起振
    __raw_writel(1, (TDCXO_BASE + 0x04)); // enable module

    if (timeout == 0) {
        __raw_writel(0x3D0900, (TDCXO_BASE + 0x3c)); // 100ms
    } else {
        timeout = timeout * 1000000 / 37;
        __raw_writel(timeout, (TDCXO_BASE + 0x3c)); // user config
    }

    __raw_writel((fine_value << 0), (TDCXO_BASE + 0x14));
    __raw_writel((1 << 16) | (fine_value << 0), (TDCXO_BASE + 0x14));

    __raw_writel(3, (TDCXO_BASE + 0x10)); // measure mode

    read_value = __raw_readl((TDCXO_BASE + 0x28));
    read_value = 0xfff << 16;
    __raw_writel(read_value, (TDCXO_BASE + 0x28)); // start measure

    read_value = __raw_readl((TDCXO_BASE + 0x30)); // soft set mv
    read_value &= (~(0x1 << 30));
    __raw_writel(read_value, (TDCXO_BASE + 0x30));

    read_value = __raw_readl((TDCXO_BASE + 0x10));
    read_value |= 1 << 2;
    __raw_writel(read_value, (TDCXO_BASE + 0x10)); // start measure

    while (1) {
        reg_value = __raw_readl((TDCXO_BASE + 0xc)); // read measure status
        if (reg_value & (0x01 << 4)) {
            __raw_writel(reg_value, (TDCXO_BASE + 0x0c)); // clear measure status
            read_value = __raw_readl(0x89400290); // soft set mv
            // printf("\nbefore reset read_value = 0x%x\n", read_value);
            read_value |= ((0x1 << 8));
            __raw_writel(read_value, 0x89400290);

            read_value = __raw_readl(0x89400290); // soft set mv
            // printf("\nafter reset read_value = 0x%x\n", read_value);
            read_value &= (~(0x1 << 8));
            __raw_writel(read_value, 0x89400290);

            printf("\nmeasure timeout!\n");
            return -1;
        }
        if (reg_value & 0x01) {
            __raw_writel(reg_value, (TDCXO_BASE + 0x0c)); // clear measure status
            break;
        }
    }

    reg_value = __raw_readl((TDCXO_BASE + 0x100)); // read measure reg
    adc_value = ((reg_value >> 16) & 0x3ff);

    if (xtal == 0) {
        adc_parameter = TDK7pf_getAdcParameter(adc_value);
    } else if (xtal == 1) {
        adc_parameter = TDK7pf1_getAdcParameter(adc_value);
    } else if (xtal == 2) {
        adc_parameter = TXC_getAdcParameter(adc_value);
    } else if (xtal == 3) {
        adc_parameter = HC9pf_getAdcParameter(adc_value);
    } else if (xtal == 4) {
        adc_parameter = TDK9pf_getAdcParameter(adc_value);
    }

    read_value = (reg_value & 0x8000);
    signed_reg_value = (reg_value & 0xffff);
    if (read_value == 0x8000) {
        read_value = (~(signed_reg_value) + 1) * 26 / 400;
        printf("ADC = %d , ADC_Parameter = %d , PPM = %d \n", adc_value, adc_parameter, read_value);
        if (xtal == 3) {
            adc_value = (adc_parameter - read_value)/2;
        }else{
            adc_value = adc_parameter - read_value;
        }
        *adjust = adc_value;
        *ppm = read_value;
    } else {
        read_value = (reg_value & 0xffff) * 26 / 400;
        printf("ADC = %d , ADC_Parameter = %d , PPM = -%d \n", adc_value, adc_parameter, read_value);
        if (xtal == 3) {
            adc_value = (adc_parameter - (-read_value))/2;
        }else{
            adc_value = adc_parameter - (-read_value);
        }
        *adjust = adc_value;
        *ppm = -read_value;
    }
    return 0;
}


//txc
int TXC_getCoreValue(int adcValue) {
    if (adcValue <= 30) {
        return 22;
    } else if (adcValue <= 35) {
        return 21;
    } else if (adcValue <= 40) {
        return 19;
    } else if (adcValue <= 45) {
        return 18;
    } else if (adcValue <= 50) {
        return 17;
    } else if (adcValue <= 55) {
        return 15;
    } else if (adcValue <= 60) {
        return 14;
    } else if (adcValue <= 65) {
        return 13;
    } else if (adcValue <= 70) {
        return 12;
    } else if (adcValue <= 75) {
        return 11;
    } else if (adcValue <= 85) {
        return 10;
    } else if (adcValue <= 90) {
        return 9;
    } else if (adcValue <= 105) {
        return 8;
    } else if (adcValue <= 130) {
        return 8;
    } else if (adcValue <= 185) {
        return 7;
    } else if (adcValue <= 245) {
        return 8;
    } else if (adcValue <= 300) {
        return 8;
    } else if (adcValue <= 335) {
        return 9;
    } else if (adcValue <= 380) {
        return 10;
    } else if (adcValue <= 420) {
        return 11;
    } else if (adcValue <= 455) {
        return 12;
    } else if (adcValue <= 505) {
        return 13;
    } else if (adcValue <= 545) {
        return 13;
    } else if (adcValue <= 600) {
        return 14;
    } else if (adcValue <= 655) {
        return 15;
    } else if (adcValue <= 720) {
        return 16;
    } else if (adcValue <= 810) {
        return 17;
    } else if (adcValue <= 855) {
        return 17;
    } else if (adcValue <= 905) {
        return 16;
    } else if (adcValue <= 930) {
        return 16;
    } else if (adcValue <= 940) {
        return 15;
    } else if (adcValue <= 950) {
        return 14;
    } else if (adcValue <= 960) {
        return 14;
    } else {
        return 13; // 对于adcValue >= 961的情况
    }
}

//tkd
int TKD7pf_getCoreValue(int adcValue) {
    if (adcValue < 29) {
        return 31;
    } else if (adcValue <= 35) {
        return 29;
    } else if (adcValue <= 40) {
        return 27;
    } else if (adcValue <= 45) {
        return 25;
    } else if (adcValue <= 50) {
        return 23;
    } else if (adcValue == 51) {
        return 21;
    } else if (adcValue == 52) {
        return 18;
    } else if (adcValue == 53) {
        return 17;
    } else if (adcValue == 54) {
        return 16;
    } else if (adcValue <= 59) {
        return 15;
    } else if (adcValue <= 63) {
        return 14;
    } else if (adcValue <= 66) {
        return 13;
    } else if (adcValue == 67) {
        return 13;
    } else if (adcValue <= 77) {
        return 12;
    } else if (adcValue <= 87) {
        return 11;
    } else if (adcValue <= 104) {
        return 11;
    } else if (adcValue <= 222) {
        return 10;
    } else if (adcValue <= 266) {
        return 10;
    } else if (adcValue <= 311) {
        return 11;
    } else if (adcValue <= 353) {
        return 12;
    } else if (adcValue <= 395) {
        return 12;
    } else if (adcValue <= 434) {
        return 13;
    } else if (adcValue <= 484) {
        return 14;
    } else if (adcValue <= 529) {
        return 15;
    } else if (adcValue <= 584) {
        return 16;
    } else if (adcValue <= 662) {
        return 16;
    } else if (adcValue <= 764) {
        return 17;
    } else if (adcValue <= 816) {
        return 18;
    } else if (adcValue <= 858) {
        return 17;
    } else if (adcValue <= 890) {
        return 17;
    } else if (adcValue <= 907) {
        return 16;
    } else if (adcValue <= 924) {
        return 15;
    } else if (adcValue <= 930) {
        return 14;
    } else if (adcValue <= 942) {
        return 13;
    } else {
        return 12; // 对于adcValue > 942的情况
    }
}

int TKD7pf1_getCoreValue(int adcValue) {
    if (adcValue <= 30) {
        return 27;
    } else if (adcValue <= 35) {
        return 25;
    } else if (adcValue <= 40) {
        return 23;
    } else if (adcValue <= 45) {
        return 20;
    } else if (adcValue <= 50) {
        return 18;
    } else if (adcValue <= 55) {
        return 17;
    } else if (adcValue <= 60) {
        return 16;
    } else if (adcValue <= 65) {
        return 15;
    } else if (adcValue <= 70) {
        return 14;
    } else if (adcValue <= 75) {
        return 13;
    } else if (adcValue <= 80) {
        return 13;
    } else if (adcValue <= 90) {
        return 12;
    } else if (adcValue <= 100) {
        return 12;
    } else if (adcValue <= 125) {
        return 11;
    } else if (adcValue <= 185) {
        return 10;
    } else if (adcValue <= 255) {
        return 11;
    } else if (adcValue <= 300) {
        return 12;
    } else if (adcValue <= 350) {
        return 12;
    } else if (adcValue <= 395) {
        return 13;
    } else if (adcValue <= 440) {
        return 14;
    } else if (adcValue <= 485) {
        return 14;
    } else if (adcValue <= 530) {
        return 15;
    } else if (adcValue <= 590) {
        return 16;
    } else if (adcValue <= 655) {
        return 17;
    } else if (adcValue <= 740) {
        return 17;
    } else if (adcValue <= 860) {
        return 17;
    } else if (adcValue <= 900) {
        return 17;
    } else if (adcValue <= 920) {
        return 17;
    } else if (adcValue <= 935) {
        return 16;
    } else if (adcValue <= 945) {
        return 15;
    } else if (adcValue <= 950) {
        return 14;
    } else if (adcValue <= 955) {
        return 14;
    } else if (adcValue <= 960) {
        return 13;
    } else {
        return 12; // 对于adcValue >= 961的情况
    }
}

int TDK9pf_getCoreValue(int adcValue) {
    if (adcValue <= 60) {
        return 42;
    } else if (adcValue <= 65) {
        return 40;
    } else if (adcValue <= 70) {
        return 38;
    } else if (adcValue <= 80) {
        return 37;
    } else if (adcValue <= 85) {
        return 36;
    } else if (adcValue <= 100) {
        return 35;
    } else if (adcValue <= 115) {
        return 33;
    } else if (adcValue <= 240) {
        return 32;
    } else if (adcValue <= 295) {
        return 33;
    } else if (adcValue <= 345) {
        return 35;
    } else if (adcValue <= 390) {
        return 36;
    } else if (adcValue <= 435) {
        return 37;
    } else if (adcValue <= 480) {
        return 38;
    } else if (adcValue <= 530) {
        return 40;
    } else if (adcValue <= 575) {
        return 41;
    } else if (adcValue <= 630) {
        return 42;
    } else if (adcValue <= 700) {
        return 44;
    } else if (adcValue <= 770) {
        return 46;
    } else if (adcValue <= 860) {
        return 48;
    } else if (adcValue <= 900) {
        return 46;
    } else if (adcValue <= 925) {
        return 44;
    } else if (adcValue <= 935) {
        return 42;
    } else if (adcValue <= 945) {
        return 41;
    } else {
        return 40; // 对于adcValue >= 946的情况
    }
}

int HS9pf_getCoreValue(int adcValue) {//Hosonic
    if (adcValue <= 55) {
        return 33;
    } else if (adcValue <= 60) {
        return 32;
    } else if (adcValue <= 65) {
        return 31;
    } else if (adcValue <= 70) {
        return 31;
    } else if (adcValue <= 75) {
        return 31;
    } else if (adcValue <= 85) {
        return 30;
    } else if (adcValue <= 90) {
        return 30;
    } else if (adcValue <= 95) {
        return 29;
    } else if (adcValue <= 110) {
        return 28;
    } else if (adcValue <= 125) {
        return 27;
    } else if (adcValue <= 165) {
        return 27;
    } else if (adcValue <= 200) {
        return 26;
    } else if (adcValue <= 270) {
        return 26;
    } else if (adcValue <= 325) {
        return 27;
    } else if (adcValue <= 375) {
        return 28;
    } else if (adcValue <= 410) {
        return 29;
    } else if (adcValue <= 460) {
        return 30;
    } else if (adcValue <= 510) {
        return 30;
    } else if (adcValue <= 555) {
        return 31;
    } else if (adcValue <= 635) {
        return 31;
    } else if (adcValue <= 710) {
        return 31;
    } else if (adcValue <= 775) {
        return 32;
    } else if (adcValue <= 890) {
        return 33;
    } else if (adcValue <= 915) {
        return 32;
    } else if (adcValue <= 940) {
        return 31;
    } else if (adcValue <= 950) {
        return 31;
    } else {
        return 30; // 对于adcValue > 950的情况
    }
}


/**
 * 热敏补偿
 *
 * \param xtal 选择晶振类型，0 TKD0 7pf; 1 TKD1 7pf; 2 TXC 7pf; 3 Hosonic 9pf; 4 TDK 9pf;
 * \param fine 补偿精度，传0默认值35
 * \param adjust 补偿校准值,可能是负数
 * \param gate 补偿门限，只有定时补偿的时候需要传递，loader 不需要
 * \param times 补偿间隔时间,传0默认值148ms
 *
 * \return 返回函数是否执行成功
 * \retval 0 执行成功
 * \retval -1 功能出错
 */
int gxtdcxo_compensate(u32 xtal, u32 fine, s32 adjust, u32 gate, u32 times)
{
    int core_value = 0;
    int fine_value = 0;
    int reg_value = 0;
    short signed_reg_value = 0;
    int read_value = 0;
    int adc_value = 0;

    if (gate != 0)
        return -1;

    __raw_writel((1 << 31), (0x89400704)); // 晶振起振
    __raw_writel(1, (TDCXO_BASE + 0x04)); // enable module

    __raw_writel(0x2, (TDCXO_BASE + 0x10)); // 软件补偿
    __raw_writel(0x6, (TDCXO_BASE + 0x10)); // 0x10
    if (times == 0) {
        __raw_writel(0x3D0900, (TDCXO_BASE + 0x24));
    } else {
        times = times * 1000000 / 37;
        __raw_writel(times, (TDCXO_BASE + 0x24)); // user config
    }
    read_value = __raw_readl((TDCXO_BASE + 0x30)); // soft set mv
    read_value &= (~(0x1 << 30));
    __raw_writel(read_value, (TDCXO_BASE + 0x30));
    adc_value = 0;
    while (1) {
        adc_value = __raw_readl((TDCXO_BASE + 0x1c));
        adc_value = adc_value & 0x3ff;
        if (adc_value != 0)
            break;
    }

    if (xtal == 0) {
        core_value = TKD7pf_getCoreValue(adc_value);
    } else if (xtal == 1) {
        core_value = TKD7pf1_getCoreValue(adc_value);
    } else if (xtal == 2) {
        core_value = TXC_getCoreValue(adc_value);
    } else if (xtal == 3) {
        core_value = HS9pf_getCoreValue(adc_value);
    } else if (xtal == 4) {
        core_value = TDK9pf_getCoreValue(adc_value);
    }
    //test
    read_value = __raw_readl((TDCXO_BASE + 0x24)); // soft set mv

    printf("\nadc = %d core = %d adjust = %d, core_adjust = %d, read_value = %d\n", adc_value, core_value, adjust, core_value - adjust,read_value);

    core_value = core_value - adjust;
    if(core_value < 0)
        core_value = 0;

    if (fine == 0)
        fine_value = 35; // 默认值35
    else
        fine_value = fine;

    __raw_writel((core_value << 8) | (fine_value << 0), (TDCXO_BASE + 0x14));
    __raw_writel((1 << 16) | (core_value << 8) | (fine_value << 0), (TDCXO_BASE + 0x14));
    __raw_writel((core_value << 8) | (fine_value << 0), (TDCXO_BASE + 0x14));
    __raw_writel((1 << 17) | (core_value << 8) | (fine_value << 0), (TDCXO_BASE + 0x14));
    return 0;
}

