#ifndef __COPY_CFG_H__
#define __COPY_CFG_H__
#include "version_autogenerated.h"

#define readl(addr) \
	({ unsigned int __v = (*(volatile unsigned int *) (addr)); __v; })
#define writel(val, addr) \
	(void)((*(volatile unsigned int *)(unsigned int)(addr)) = (unsigned int)(val))
#define readw(addr) \
	({ unsigned short __v = (*(volatile unsigned short *) (addr)); __v; })

//配置操作次数或大小
//===========================================================
#define DOWNLOAD_SIZE 		2048
#define WAIT_TIMES 		10000


#define SR_RDRF                (0x1 << 5)
//#define SR_TDRE              (0x1 << 7)


//配置基址
//===========================================================
#define UART_BASE 		0x00400000
#define P_FLASH_BASE 		0x10000000
//===========================================================


//配置操作命令
//===========================================================
#define SPI_FLASH_READ_CMD             0x3
#define SPI_FLASH_FAST_READ_CMD        0x0B
#define SPI_FLASH_QUAD_READ_CMD        0x6B
#define SPI_NANDFLASH_GET_FEATURE      0x0f
#define SPI_NANDFLASH_READ_TO_CACHE    0x13
#define SPI_NANDFLASH_READ_FROM_CACHE  0x03
#define SPI_NANDFLASH_PAGESIZE         2048
#define NAND_FLASH_RESET_CMD           0xff
#define NAND_FLASH_READ_CMD1           0x0
#define NAND_FLASH_READ_CMD2           0x30
#define NAND_FLASH_READID_CMD          0x90
#define NAND_FLASH_READPARAM_CMD       0xec
//===========================================================

//定义三种NAND FLASH类型
//===========================================================
#define NAND_TYPE_3_CYCLE        0x3
#define NAND_TYPE_4_CYCLE_512    0x4
#define NAND_TYPE_4_CYCLE_2K     0x6
#define NAND_TYPE_5_CYCLE        0x5
//===========================================================

//SPI FlASH 寄存器定义相关部分
//===========================================================
struct spi {
	uint32_t spicr;
	uint32_t spisr;
	uint32_t spitx;
	uint32_t spirx;
};

#define SPIFLASH_MAGIC_NUM  (0XAA55AA55)

#define SPICSPOL            (0x1 << 10)
#define SPIGO               (0x1 << 12)
#define SPISR_RX_READY      (0x1 << 0)
#define SPICSFORCE          (0x1 << 16)
#define SPICSEN             (0x1 << 17)
#define SPICR_ICNT_BIT      (14)
//===========================================================

//DESIGNWARE SPI 寄存器定义相关部分
//===========================================================

/* SPI register offsets */
#ifdef CONFIG_ENABLE_DWSPI
#define SPIM_CTRLR0             0x00
#define SPIM_CTRLR1             0x04
#define SPIM_ENR                0x08
#define SPIM_SER                0x10
#define SPIM_BAUDR              0x14
#define SPIM_TXFTLR             0x18
#define SPIM_RXFTLR             0x1c
#define SPIM_TXFLR              0x20
#define SPIM_RXFLR              0x24
#define SPIM_SR                 0x28
#define SPIM_IMR                0x2c
#define SPIM_ISR                0x30
#define SPIM_RISR               0x34
#define DW_SPI_TXOICR           0x38
#define DW_SPI_RXOICR           0x3c
#define DW_SPI_RXUICR           0x40
#define SPIM_ICR                0x48
#define SPIM_DMACR              0x4c
#define SPIM_DMATDLR            0x50
#define SPIM_DMARDLR            0x54
#define SPIM_TXDR               0x60
#define SPIM_RXDR               0x60
#define SPIM_RX_SAMPLE_DLY      0XF0
#define SPIM_SPI_CTRLR0         0xF4


/* Bit fields in SR, 7 bits */
#define SR_MASK                 0x7f            /* cover 7 bits */
#define SR_BUSY                 (1 << 0)
#define SR_TF_NOT_FULL          (1 << 1)
#define SR_TF_EMPT              (1 << 2)
#define SR_RF_NOT_EMPT          (1 << 3)
#define SR_RF_FULL              (1 << 4)
#define SR_TX_ERR               (1 << 5)
#define SR_DCOL                 (1 << 6)

//Bits in CTRL0
#define SPI_DFS_OFFSET          0
#define SPI_DFS_8BIT            0x07
#define SPI_DFS_32BIT           0x1f

#define SPI_FRF2_STANDARD        0x0
#define SPI_FRF2_DUAL            0x1
#define SPI_FRF2_QUAD            0x2
#define SPI_FRF2_OCTAL           0x3

#define SPI_FRF_OFFSET          4    /* Frame Format */
#define SPI_MODE_OFFSET         6     /* SCPH & SCOL */

#define SPI_FRF2_OFFSET          22

#define SPI_TMOD_OFFSET         10
#define SPI_TMOD_TR             0x0   /* xmit & recv */
#define SPI_TMOD_TO             0x1   /* xmit only */
#define SPI_TMOD_RO             0x2   /* recv only */
#define SPI_TMOD_EPROMREAD      0x3   /* eeprom read mode */

// GX series serial flash
#define GX_CMD_WREN           0x06      // write enable
#define GX_CMD_WRDI           0x04      // write disable
#define GX_CMD_RDSR1          0x05      // read status1 register
#define GX_CMD_RDSR2          0x35      // read status2/configure register
#define GX_CMD_RDSR3          0x15      // read status3/configure register
#define GX_CMD_WRSR1          0x01      // write status/configure register
#define GX_CMD_WRSR2          0X31      // write status/configure register
#define GX_CMD_WRSR3          0X11      // write status/configure register
#define GX_CMD_READ           0x03      // read data bytes
#define GX_CMD_FAST_READ      0x0b      // read data bytes at higher speed
#define GX_CMD_DREAD          0x3B      // read data dual output
#define GX_CMD_QREAD          0x6B      // read data quad output
#define GX_CMD_PP             0x02      // page program
#define GX_CMD_QPP            0x32      // quad page program
#define GX_CMD_SE             0x20      // sector erase
#define GX_CMD_BE             0xd8      // block erase
#define GX_CMD_CE             0xc7      // chip erase
#define GX_CMD_DP             0xb9      // deep power down
#define GX_CMD_RES            0xab      // release from deep power down
#define GX_CMD_READID         0x9F      // read ID
#define GX_CMD_READID_BAK     0x90      // read ID for WinBond
#define GX_CMD_WREAR          0xC5      //Write Extended Address Register

// dummy clock
#define FAST_READ_DUMMY_CLOCK 8         //fast read dummy clock size

/* Used for Macronix and Winbond flashes. */
#define GX_CMD_EN4B     0xb7    /* Enter 4-byte mode */
#define GX_CMD_EX4B     0xe9    /* Exit 4-byte mode */
/* Used for Spansion flashes only. */
#define GX_CMD_BRWR     0x17    /* Bank register write */
/* Usec for ISSI flashes only. */
#define GX_CMD_RDFR     0x48    /* Read Function Register */
#define GX_CMD_WRFR     0x42    /* Write Function Register */


// GX25Lxx series status regsiter
#define GX_STAT_WIP           0x01      // write in progress bit
#define GX_STAT_WEL           0x02      // write enable latch
#define GX_STAT_BP0           0x04      // block protect bit 0
#define GX_STAT_BP1           0x08      // block protect bit 1
#define GX_STAT_BP2           0x10      // block protect bit 2
#define GX_STAT_SRWD          0x80      // status register write protect

//clk fre
#ifdef CONFIG_ARCH_ARM_SIRIUS
#define BUS_CLK_FRE             (170*1000*1000)
#else
#define BUS_CLK_FRE             (1024*1024*118)
#endif

//fifo depth
#define TX_FIFO_LEN		        8
#define RX_FIFO_LEN		        0xf

#define SPI_XFER_BEGIN          (0x01 << 0)
#define SPI_XFER_END            (0x01 << 1)
#define SPI_XFER_ONCE           (SPI_XFER_BEGIN | SPI_XFER_END)
#define SPI_XFER_MMAP           (0x01 << 2)
#define SPI_XFER_MMAP_END       (0x01 << 3)
#define SPI_XFER_U_PAGE         (0x01 << 4)

#define dw_readl( regs, off)       readl(regs + off)
#define dw_writel(regs, off, val)  writel(val, regs + off)
#define dw_readw( regs, off)       readw(regs + off)
#endif


#ifdef CONFIG_ENABLE_SPINAND

#define CR_CSVALID                 (0x3 << 16)
#define CR_ICNT_4                  (0x3 << 14)
#define CR_SPGO                    (0x1 << 12)
#define CR_CS_SEL                  (0x1 << 10)
#define CR_CSPOL_H                 (0x1 << 10)

//about spi_sr
#define SR_OPE_RDY                 (0x1 << 0)

#define CMD_READ                   0x13
#define CMD_READ_RDM               0x03
#define CMD_PROG_PAGE_CLRCACHE     0x02
#define CMD_PROG_PAGE              0x84
#define CMD_PROG_PAGE_EXC          0x10
#define CMD_ERASE_BLK              0xd8
#define CMD_WR_ENABLE              0x06
#define CMD_WR_DISABLE             0x04
#define CMD_READ_ID                0x9f
#define CMD_RESET                  0xff
#define CMD_READ_REG               0x0f
#define CMD_WRITE_REG              0x1f

/* feature/ status reg */
#define REG_BLOCK_LOCK             0xa0
#define REG_OTP                    0xb0
#define REG_STATUS                 0xc0
#define REG_ECC                    0x90

/* status */
#define STATUS_OIP_MASK            (0x01  )
#define STATUS_READY               (0 << 0)
#define STATUS_BUSY                (1 << 0)
#define STATUS_E_FAIL_MASK         (0x04  )
#define STATUS_E_FAIL              (1 << 2)
#define STATUS_P_FAIL_MASK         (0x08  )
#define STATUS_P_FAIL              (1 << 3)
#define STATUS_ECC_MASK            (0x30  )
#define STATUS_ECC_1BIT_CORRECTED  (1 << 4)
#define STATUS_ECC_ERROR           (2 << 4)
#define STATUS_ECC_RESERVED        (3 << 4)


/*ECC enable defines*/
#define REG_ECC_MASK               0x10
#define REG_ECC_OFF                0x00
#define REG_ECC_ON                 0x01
#define ECC_DISABLED
#define ECC_IN_NAND
#define ECC_SOFT

#define OTP_PRT                    0x80

/*BUF enable defines*/
#define REG_BUF_MASK               0x08
#define REG_BUF_OFF                0x00
#define REG_BUF_ON                 0x01

/* block lock */
#define BL_ALL_LOCKED              0x38
#define BL_1_2_LOCKED              0x30
#define BL_1_4_LOCKED              0x28
#define BL_1_8_LOCKED              0x20
#define BL_1_16_LOCKED             0x18
#define BL_1_32_LOCKED             0x10
#define BL_1_64_LOCKED             0x08
#define BL_ALL_UNLOCKED            0x00

#endif

//UART 寄存器定义相关部分
//===========================================================
#ifdef CONFIG_UART_TYPE_DW

#define  DSW_RBR                 (0x0)
#define  DSW_DLL                 (0x0)
#define  DSW_THR                 (0x0)
#define  DSW_DLH                 (0x4)
#define  DSW_IER                 (0x4)
#define  DSW_FCR                 (0x8)
#define  DSW_LSR                 (0x14)
#define  DSW_MCR                 (0x10)
#define  DSW_USR                 (0x7c)
#define  DSW_LCR                 (0xc)
#define  DSW_DLF                 (0xc0)

#define  DSW_USR_BUSY            (0x0)
#define  DSW_LSR_TEMT            (0x6)
#define  DSW_LSR_DR              (0x0)
#elif defined(CONFIG_UART_TYPE_GX)
#define UART_SCICR               (0x00)
#define UART_SCISR               (0x04)
#define UART_SCIDR               (0x08)
#define UART_SCIBR               (0x0c)
#define UART_SCICFG              (0x10)
#endif


//NAND FLASH 寄存器定义相关部分
//===========================================================
struct nand {
	volatile u32  cfg_module;
	volatile u32  sel;
	volatile u32  timing_sequence;
	volatile u32  none;
	volatile u32  cfg_ecc; //changed
	volatile u32  ctl_receive;
	volatile u32  status_reg1;
	volatile u32  status_reg2;
	volatile u32  cmd_reg;
	volatile u32  addr_reg;
	volatile u32  wrdata_fifo;
	volatile u32  rddata_fifo;
	volatile u32  ecc_status;
	volatile u32  cfg_dma_trans_startaddr;//new add
	volatile u32  cfg_dma_ctrl;	//changed
	volatile u32  cfg_dma_waittime;//new add
};

#define NAND1_CE_EN             (0x1 << 0)
#define NAND1_GET_READY         (0x1 << 8)
#define NAND1_RX_DATA_DONE      (0x1 << 1)
#define REG_OP_DONE             (0x1 << 7)

#define RECEIVE_DATA_EN         (0x1 << 0)
#define WANT_READ_DATA_COUNT    (0x4 << 16)

#define RX_DATAFIFO_LEVEL       (0x4 << 16)

#define NAND_FLASH_PAGE_SIZE		2048
#define NAND_FLASH_OOB_SIZE		64
//===========================================================

#define		PINMUXA		(*(volatile uint32_t*)0x0050A138)
#define		PINMUXB		(*(volatile uint32_t*)0x0050A134)
#define		PINMUXC		(*(volatile uint32_t*)0x0050A130)

extern void gx_copy_bootloader(void);


/* Canopus */

#define ECC_VERSION             0x0000
#define ECC_ENABLE_STATUS       0x0004
#define ECC_CONFIG              0x0008
#define ECC_DATA                0x0010

#define NAND_FLASH_CTL_VERSION  0x0800
#define ENABLE_STATUS           0x0804
#define CTRL_CONFIG             0x0808
#define BLOCK_SIZE              0x080c
#define XFER_START              0x0810
#define XFER_TOTAL_SIZE         0x0814
#define DMA_START_ADDR          0x0818
#define INT_STATUS              0x0820
#define INT_ENABLE              0x0824
#define SW_CMD_TYPE             0x0828
#define SW_CMD_START            0x082c
#define SW_CMD_ADDR_LO          0x0830
#define SW_CMD_ADDR_HI          0x0834
#define STATUS_RDATA_SW         0x0838
#define TWP_TWH                 0x0840
#define TRP_TREH                0x0844
#define TRP_TREH_FAST           0x0848
#define SMP_DLY_NEG_FAST        0x084c
#define TWB_TRR                 0x0850
#define TRWAD                   0x0854
#define T_BUSY_TIMEOUT          0x0858
#define SPI_CLK_DIV             0x0860
#define SMP_DLY_NEG_SPI         0x0864
#define TCS_TCSHS               0x0868

#define TYPE0_START_ADDR        0x0880
#define TYPE0_LENGTH            0x0884
#define TYPE0_GAP               0x0888
#define TYPE1_START_ADDR        0x0890
#define TYPE1_LENGTH            0x0894
#define TYPE1_GAP               0x0898
#define TYPE2_START_ADDR        0x08a0
#define TYPE2_LENGTH            0x08a4
#define TYPE2_GAP               0x08a8
#define START_ROW_ADDR          0x08b0
#define TYPE3_RELOAD_COL_ADDR   0x08b4
#define END_TYPE012_ADDR        0x08b8
#define END_COL_ADDR            0x08bc
#define BAD_BLOCK_MARK_0        0x08c0
#define BAD_BLOCK_MARK_1        0x08c4
#define SPI_APPEND_PLANE_SEL    0x08d0
#define C3F_ROW_ADDR            0x08d4

#define TASK_CNT_0              0x0a00
#define TASK_CNT_1              0x0a04
#define BKPT_TASK_CNT_0         0x0a08
#define BKPT_TASK_CNT_1         0x0a0c
#define BKPT_CONTINUE           0x0a14
#define BKPT_STATUS             0x0a18
#define BKPT_ENABLE             0x0a1c

#define DATA_REGISTER           0x0c00


#define NAND_SEQ_CMD		0x01
#define NAND_SEQ_ADDR		0x02
#define NAND_SEQ_WB		0x03
#define NAND_SEQ_WRD		0x04
#define NAND_SEQ_RB		0x05
#define NAND_SEQ_CSH		0x06
#define NAND_SEQ_CSL		0x07


#define NAND_READ_REG(x)  ({ unsigned int __v = (*(volatile unsigned int *) ((REG_BASE_NANDFLASH) + x)); __v; })
#define NAND_WRITE_REG(v, x)   do {  \
	(*(volatile unsigned int *)((REG_BASE_NANDFLASH) + x)) = (unsigned int)(v);\
	} while(0)

#endif

