/*
 * =====================================================================================
 *
 *       Filename:  gx_api.h
 *
 *    Description:  common interface for api function
 *
 *        Version:  1.0
 *        Created:  04/28/2011 12:15:29 PM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  charle,
 *        Company:  Hangzhou Nationalchip Science&Technology Co.Ltd.
 *
 * =====================================================================================
 */
#ifndef __BOOTLOADER_GXAPI_H
#define __BOOTLOADER_GXAPI_H

#include "version_autogenerated.h"

#if defined(CONFIG_ARCH_CKMMU_GX3201)
#include "gx3201_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_GX3211)
#include "gx3211_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_GX6605S)
#include "gx6605s_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_GX3113C)
#include "gx3113C_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_ARM_SIRIUS)
#include "sirius_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_TAURUS)
#include "taurus_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_GEMINI)
#include "gemini_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_CYGNUS)
#include "cygnus_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_ARM_CANOPUS)
#include "canopus_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_ARM_VEGA)
#include "vega_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_SCORPIO)
#include "scorpio_api.h"
#include "board-common.h"
#elif defined(CONFIG_ARCH_CKMMU_SCORPIO_TAURUS)
#include "scorpio_taurus_api.h"
#include "board-common.h"
#else
#error "error chip, please select correct chip"
#endif


#define SECTION_SRAM __attribute__((section(".sram")))
void gx_print_allregisters(void);
void gx_print_board_info(void);

void dcache_flush(void);
void hide_logo(void);

enum cvbs_mode_enum {
	G_PAL,
	G_PAL_M,
	G_PAL_N,
	G_PAL_NC,
	G_NTSC_M,
	G_NTSC_443,
};
enum ypbpr_hdmi_mode_enum {
	G_YPBPR_HDMI_480I,
	G_YPBPR_HDMI_480P,
	G_YPBPR_HDMI_576I,
	G_YPBPR_HDMI_576P,
	G_YPBPR_HDMI_720P_50HZ,
	G_YPBPR_HDMI_720P_60HZ,
	G_YPBPR_HDMI_1080I_50HZ,
	G_YPBPR_HDMI_1080I_60HZ,
	G_YPBPR_HDMI_1080P_50HZ,
	G_YPBPR_HDMI_1080P_60HZ,
};

void platform_show_logo(unsigned char *logo_buf, unsigned int logo_size);

#endif

