-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgAjEWoK59C0+2eSaS
HIgNVizh/UOr/ForxAMkIdu+FhShRANCAARPWkgTHiJGLHOXBPOdOiUh6Fr7qNmv
Ko1IHASUNHf/zQpUW9e3wQqU72gTJbAnO549sjU2IxlxUNYEHUywsJYB
-----END PRIVATE KEY-----
