/* linux memtester4.3.0, ported by huangjb 20121022 */
#include <version_autogenerated.h>
#include <stdio.h>

/* ver1.1.0 */


#ifdef CONFIG_MEMORY_TEST_SIZE
#define MEMORY_TEST_BYTES	CONFIG_MEMORY_TEST_SIZE
#else
#define MEMORY_TEST_BYTES	(DDR_SIZE * 1024UL * 1024UL) / 2
#endif
static char *memory_test_buf_a = (char *)DRAMBASE;
static char *memory_test_buf_b = (char *)DRAMBASE+MEMORY_TEST_BYTES;

#define TEST_NARROW_WRITES
extern int printf(const char *fmt, ...);

typedef unsigned long ul;
typedef unsigned long long ull;
typedef unsigned long volatile ulv;
typedef unsigned char volatile u8v;
typedef unsigned short volatile u16v;

#define memtest_printf(fmt, ...) stage1_printf(fmt, ##__VA_ARGS__)

//#ifdef CONFIG_ARCH_ARM
#define RANDOM_MAX 0x7FFFFFFF
static long do_rand(unsigned long *value)
{
	long quotient, remainder, t;
	quotient = *value / 127773L;

	remainder = *value % 127773L;

	t = 16807L * remainder - 2836L * quotient;

	if (t <= 0)
		t += 0x7FFFFFFFL;

	return ((*value = t) % ((unsigned long)RANDOM_MAX + 1));
}

static unsigned long next = 1;

static int rand(void)
{
	return do_rand(&next);
}

static void srand(unsigned int seed)
{
	next = seed;
}

#define rand32() ((unsigned int) rand() | ( (unsigned int) rand() << 16))

#define ULONG_MAX  4294967295UL

#if (ULONG_MAX == 4294967295UL)
    #define rand_ul() rand32()
    #define UL_ONEBITS 0xffffffff
    #define UL_LEN 32
    #define CHECKERBOARD1 0x55555555
    #define CHECKERBOARD2 0xaaaaaaaa
    #define UL_BYTE(x) ((x | x << 8 | x << 16 | x << 24))
#elif (ULONG_MAX == 18446744073709551615ULL)
    #define rand64() (((ul) rand32()) << 32 | ((ul) rand32()))
    #define rand_ul() rand64()
    #define UL_ONEBITS 0xffffffffffffffffUL
    #define UL_LEN 64
    #define CHECKERBOARD1 0x5555555555555555
    #define CHECKERBOARD2 0xaaaaaaaaaaaaaaaa
    #define UL_BYTE(x) (((ul)x | (ul)x<<8 | (ul)x<<16 | (ul)x<<24 | (ul)x<<32 | (ul)x<<40 | (ul)x<<48 | (ul)x<<56))
#else
    #error long on this platform is not 32 or 64 bits
#endif

struct test {
    char *name;
    int (*fp)(ulv* bufa, ulv* bufb, size_t count);
};

union {
    unsigned char bytes[UL_LEN/8];
    ul val;
} mword8;

union {
    unsigned short u16s[UL_LEN/16];
    ul val;
} mword16;

char progress[] = "-\\|/";
#define PROGRESSLEN 4
#define PROGRESSOFTEN 2500
#define ONE 0x00000001L

int err_flag = 1;

int compare_regions(ulv *bufa, ulv *bufb, size_t count) {
    int r = 0;
    int addr_a;
    int col_a;
    int bnk_a;
    int row_a;
    //int diff_h;
    //int diff_l;
    int xor_rst;
    size_t i;
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    off_t physaddr;
    for (i = 0; i < count; i++, p1++, p2++) {
        if (*p1 != *p2) {
		addr_a = ((ul) (i * sizeof(ul))) + DRAMBASE;
#ifdef CONFIG_DDR2
#if DDR_SIZE == 64 //MB
                //row[25-13], bank[12-11], col[10-1], dp[0]
                  row_a = (( (addr_a<<6)>>19  ) &0x1fff);
                  bnk_a = (( (addr_a<<19)>>30 ) &0x3);
                  col_a = (( (addr_a<<21)>>22 ) &0x3ff);
#elif DDR_SIZE == 128 //MB
                //row[26-14], bank[13-11], col[10-1], dp[0]
                  row_a = (( (addr_a<<5)>>19  ) &0x1fff);
                  bnk_a = (( (addr_a<<18)>>29 ) &0x7);
                  col_a = (( (addr_a<<21)>>22 ) &0x3ff);
#endif
#endif
		
#ifdef CONFIG_DDR3
#if DDR_SIZE == 128 //MB
                //row[26-14], bank[13-11], col[10-1], dp[0]
                  row_a = (( (addr_a<<5)>>19  ) &0x1fff);
                  bnk_a = (( (addr_a<<18)>>29 ) &0x7);
                  col_a = (( (addr_a<<21)>>22 ) &0x3ff);
#elif DDR_SIZE == 256 //MB
                //row[27-14], bank[13-11], col[10-1], dp[0]
                  row_a = (( (addr_a<<4)>>18  ) &0x3fff);
                  bnk_a = (( (addr_a<<18)>>29 ) &0x7);
                  col_a = (( (addr_a<<21)>>22 ) &0x3ff);
#elif DDR_SIZE == 512 //MB
                //row[28-14], bank[13-11], col[10-1], dp[0]
                  row_a = (( (addr_a<<3)>>17  ) &0x7fff);
                  bnk_a = (( (addr_a<<18)>>29 ) &0x7);
                  col_a = (( (addr_a<<21)>>22 ) &0x3ff);
#endif
#endif
		memtest_printf("FAILURE: 0x%08x != 0x%08x, xor_result=0x%08x, addr_a: bank=0x%x,row=0x%x,col=0x%x;\n", (ul) *p1, (ul) *p2, ((ul) *p1)^((ul) *p2), bnk_a&0x00000007, row_a&0x0000ffff, col_a&0x00000fff);
	    err_flag = 1;
//            memtest_printf("Skip \n");
            r = -1;
        }
    }
    return r;
}

int test_random_value(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    ul j = 0;
    size_t i;

    for (i = 0; i < count; i++) {
        *p1++ = *p2++ = rand_ul();
    }
    return compare_regions(bufa, bufb, count);
}

int test_xor_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ ^= q;
        *p2++ ^= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_sub_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();
    for (i = 0; i < count; i++) {
        *p1++ -= q;
        *p2++ -= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_mul_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ *= q;
        *p2++ *= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_div_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        if (!q) {
            q++;
        }
        *p1++ /= q;
        *p2++ /= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_or_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ |= q;
        *p2++ |= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_and_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ &= q;
        *p2++ &= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_seqinc_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ = *p2++ = (i + q);
    }
    return compare_regions(bufa, bufb, count);
}

int test_solidbits_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    ul q;
    size_t i;

    for (j = 0; j < 64; j++) {
        q = (j % 2) == 0 ? UL_ONEBITS : 0;
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            *p1++ = *p2++ = (i % 2) == 0 ? q : ~q;
        }
        if (compare_regions(bufa, bufb, count)) {
            memtest_printf("Skip \n");
            return -1;
        }
    }
    return 0;
}

int test_checkerboard_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    ul q;
    size_t i;

    for (j = 0; j < 64; j++) {
        q = (j % 2) == 0 ? CHECKERBOARD1 : CHECKERBOARD2;
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            *p1++ = *p2++ = (i % 2) == 0 ? q : ~q;
        }
        if (compare_regions(bufa, bufb, count)) {
            memtest_printf("Skip \n");
            return -1;
        }
    }
    return 0;
}

int test_blockseq_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < 256; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            *p1++ = *p2++ = (ul) UL_BYTE(j);
        }
        if (compare_regions(bufa, bufb, count)) {
            memtest_printf("Skip \n");
            return -1;
        }
    }
    return 0;
}

int test_walkbits0_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < UL_LEN * 2; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            if (j < UL_LEN) { /* Walk it up. */
                *p1++ = *p2++ = ONE << j;
            } else { /* Walk it back down. */
                *p1++ = *p2++ = ONE << (UL_LEN * 2 - j - 1);
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            memtest_printf("Skip \n");
            return -1;
        }
    }
    return 0;
}

int test_walkbits1_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < UL_LEN * 2; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            if (j < UL_LEN) { /* Walk it up. */
                *p1++ = *p2++ = UL_ONEBITS ^ (ONE << j);
            } else { /* Walk it back down. */
                *p1++ = *p2++ = UL_ONEBITS ^ (ONE << (UL_LEN * 2 - j - 1));
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            memtest_printf("Skip \n");
            return -1;
        }
    }
    return 0;
}

int test_bitspread_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < UL_LEN * 2; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            if (j < UL_LEN) { /* Walk it up. */
                *p1++ = *p2++ = (i % 2 == 0)
                    ? (ONE << j) | (ONE << (j + 2))
                    : UL_ONEBITS ^ ((ONE << j)
                                    | (ONE << (j + 2)));
            } else { /* Walk it back down. */
                *p1++ = *p2++ = (i % 2 == 0)
                    ? (ONE << (UL_LEN * 2 - 1 - j)) | (ONE << (UL_LEN * 2 + 1 - j))
                    : UL_ONEBITS ^ (ONE << (UL_LEN * 2 - 1 - j)
                                    | (ONE << (UL_LEN * 2 + 1 - j)));
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            memtest_printf("Skip \n");
            return -1;
        }
    }
    return 0;
}

int test_bitflip_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j, k;
    ul q;
    size_t i;

    for (k = 0; k < UL_LEN; k++) {
        q = ONE << k;
        for (j = 0; j < 8; j++) {
            q = ~q;
            p1 = (ulv *) bufa;
            p2 = (ulv *) bufb;
            for (i = 0; i < count; i++) {
                *p1++ = *p2++ = (i % 2) == 0 ? q : ~q;
            }
            if (compare_regions(bufa, bufb, count)) {
		memtest_printf("Skip \n");
                return -1;
            }
        }
    }
    return 0;
}

#ifdef TEST_NARROW_WRITES
int test_8bit_wide_random(ulv* bufa, ulv* bufb, size_t count) {
    u8v *p1, *t;
    ulv *p2;
    int attempt;
    unsigned int b, j = 0;
    size_t i;

    for (attempt = 0; attempt < 2;  attempt++) {
        if (attempt & 1) {
            p1 = (u8v *) bufa;
            p2 = bufb;
        } else {
            p1 = (u8v *) bufb;
            p2 = bufa;
        }
        for (i = 0; i < count; i++) {
            t = mword8.bytes;
            *p2++ = mword8.val = rand_ul();
            for (b=0; b < UL_LEN/8; b++) {
                *p1++ = *t++;
            }
            if (!(i % PROGRESSOFTEN)) {
                serial_put('\b');
                serial_put(progress[++j % PROGRESSLEN]);
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_16bit_wide_random(ulv* bufa, ulv* bufb, size_t count) {
    u16v *p1, *t;
    ulv *p2;
    int attempt;
    unsigned int b, j = 0;
    size_t i;

    for (attempt = 0; attempt < 2; attempt++) {
        if (attempt & 1) {
            p1 = (u16v *) bufa;
            p2 = bufb;
        } else {
            p1 = (u16v *) bufb;
            p2 = bufa;
        }
        for (i = 0; i < count; i++) {
            t = mword16.u16s;
            *p2++ = mword16.val = rand_ul();
            for (b = 0; b < UL_LEN/16; b++) {
                *p1++ = *t++;
            }
            if (!(i % PROGRESSOFTEN)) {
                serial_put('\b');
                serial_put(progress[++j % PROGRESSLEN]);
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}
#endif


struct test tests[] = {
    { "Random Value"          , test_random_value }            ,
    { "Compare XOR"           , test_xor_comparison }          ,
    { "Compare SUB"           , test_sub_comparison }          ,
    { "Compare MUL"           , test_mul_comparison }          ,
    { "Compare DIV"           , test_div_comparison }          ,
    { "Compare OR"            , test_or_comparison }           ,
    { "Compare AND"           , test_and_comparison }          ,
    { "Sequential Increment"  , test_seqinc_comparison }       ,
    { "Solid Bits"            , test_solidbits_comparison }    ,
    { "Block Sequential"      , test_blockseq_comparison }     ,
    { "Checkerboard"          , test_checkerboard_comparison } ,
    { "Bit Spread"            , test_bitspread_comparison }    ,
    { "Bit Flip"              , test_bitflip_comparison }      ,
    { "Walking Ones"          , test_walkbits1_comparison }    ,
    { "Walking Zeroes"        , test_walkbits0_comparison }    ,
//    #ifdef TEST_NARROW_WRITES
//    { "8-bit Writes"          , test_8bit_wide_random }        ,
//    { "16-bit Writes"         , test_16bit_wide_random }       ,
//    #endif
//    { NULL, NULL }
};

void memory_test(void)
{
	int i;
	err_flag = 0;
	memtest_printf("%s, %s\n", __FILE__, __func__);
//	while(1)
//	{
		memtest_printf("memory_test:buf_a=0x%x,buf_b=0x%x,test_bytes=0x%x\n", memory_test_buf_a, memory_test_buf_b, MEMORY_TEST_BYTES);
		for(i = 0; i < sizeof(tests)/sizeof(struct test); i++)
		{
			memtest_printf("test%d:%s, err_flag=%d\n", i, tests[i].name, err_flag);
			tests[i].fp((ulv *)memory_test_buf_a, (ulv *)memory_test_buf_b, MEMORY_TEST_BYTES/sizeof(ulv));
		}
//	}
}
