#include "version_autogenerated.h"
#include <stdio.h>
#include "databahn.h"
#include "cpu_config.h"

/* v1.1.1 */

/* need to set test space, which is half of the total test size */
//#define MEMORY_TEST_BYTES	(KERNEL_END_ADDR - KERNEL_START_ADDR)
#define MEMORY_TEST_BYTES	4*1024*1024
static char *memory_test_buf_a = (char *)KERNEL_START_ADDR;
static char *memory_test_buf_b = (char *)KERNEL_START_ADDR+MEMORY_TEST_BYTES;

/* need to set the register address of read/write phase */
//for CK
#if defined(CONFIG_ARCH_CKMMU)
#define READ_PHASE_ADDR		0xa0c00144
#define WRITE_PHASE_ADDR	0xa0c00410
//for ARM
#elif defined(CONFIG_ARCH_ARM)
#define READ_PHASE_ADDR		0x88500144
#define WRITE_PHASE_ADDR	0x88500410
#endif
/* need to set the type of sdram */
#define TEST_NARROW_WRITES

extern int stage1_printf(const char *fmt, ...);
extern unsigned int DENALI_CONFIG_PHY[5];

#define memtest_printf(fmt, ...) stage1_printf(fmt, ##__VA_ARGS__)

typedef unsigned long ul;
typedef unsigned long long ull;
typedef unsigned long volatile ulv;
typedef unsigned char volatile u8v;
typedef unsigned short volatile u16v;
//#ifdef CONFIG_ARCH_ARM
#define RANDOM_MAX 0x7FFFFFFF
static long do_rand(unsigned long *value)
{
	long quotient, remainder, t;
	quotient = *value / 127773L;

	remainder = *value % 127773L;

	t = 16807L * remainder - 2836L * quotient;

	if (t <= 0)
		t += 0x7FFFFFFFL;

	return ((*value = t) % ((unsigned long)RANDOM_MAX + 1));
}

static unsigned long next = 1;

static int rand(void)
{
	return do_rand(&next);
}

static void srand(unsigned int seed)
{
	next = seed;
}

#define rand32() ((unsigned int) rand() | ( (unsigned int) rand() << 16))

#define ULONG_MAX  4294967295UL

#if (ULONG_MAX == 4294967295UL)
    #define rand_ul() rand32()
    #define UL_ONEBITS 0xffffffff
    #define UL_LEN 32
    #define CHECKERBOARD1 0x55555555
    #define CHECKERBOARD2 0xaaaaaaaa
    #define UL_BYTE(x) ((x | x << 8 | x << 16 | x << 24))
#elif (ULONG_MAX == 18446744073709551615ULL)
    #define rand64() (((ul) rand32()) << 32 | ((ul) rand32()))
    #define rand_ul() rand64()
    #define UL_ONEBITS 0xffffffffffffffffUL
    #define UL_LEN 64
    #define CHECKERBOARD1 0x5555555555555555
    #define CHECKERBOARD2 0xaaaaaaaaaaaaaaaa
    #define UL_BYTE(x) (((ul)x | (ul)x<<8 | (ul)x<<16 | (ul)x<<24 | (ul)x<<32 | (ul)x<<40 | (ul)x<<48 | (ul)x<<56))
#else
    #error long on this platform is not 32 or 64 bits
#endif

struct test {
    char *name;
    int (*fp)(ulv* bufa, ulv* bufb, size_t count);
};

union {
    unsigned char bytes[UL_LEN/8];
    ul val;
} mword8;

union {
    unsigned short u16s[UL_LEN/16];
    ul val;
} mword16;

char progress[] = "-\\|/";
#define PROGRESSLEN 4
#define PROGRESSOFTEN 2500
#define ONE 0x00000001L

void set_read_phase(u8 phase)
{
	(*(unsigned int*)(READ_PHASE_ADDR)) = ((*(unsigned int*)(READ_PHASE_ADDR)) & 0xffffff00) | phase;
	stage1_delay_us(16);
}

void set_write_phase(u8 phase)
{
	(*(unsigned int*)(WRITE_PHASE_ADDR)) = ((*(unsigned int*)(WRITE_PHASE_ADDR)) & 0xffff00ff) | (phase<<8);
	stage1_delay_us(16);
}


int compare_regions(ulv *bufa, ulv *bufb, size_t count) {
    int r = 0;
    size_t i;
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    u8 write_phase_default = (DENALI_CONFIG_PHY[4] >> 8) & 0xFF;
    set_write_phase(write_phase_default);
    for (i = 0; i < count; i++, p1++, p2++)
    {
	
        if (*p1 != *p2)
	{
		r = -1;
		return r;
	}
    }
    r = 0;
    return r;
}

int test_random_value(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    ul j = 0;
    size_t i;

    for (i = 0; i < count; i++) {
        *p1++ = *p2++ = rand_ul();
        if (!(i % PROGRESSOFTEN)) {
        }
    }
    return compare_regions(bufa, bufb, count);
}

int test_xor_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ ^= q;
        *p2++ ^= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_sub_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();
    for (i = 0; i < count; i++) {
        *p1++ -= q;
        *p2++ -= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_mul_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ *= q;
        *p2++ *= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_div_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        if (!q) {
            q++;
        }
        *p1++ /= q;
        *p2++ /= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_or_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ |= q;
        *p2++ |= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_and_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ &= q;
        *p2++ &= q;
    }
    return compare_regions(bufa, bufb, count);
}

int test_seqinc_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    size_t i;
    ul q = rand_ul();

    for (i = 0; i < count; i++) {
        *p1++ = *p2++ = (i + q);
    }
    return compare_regions(bufa, bufb, count);
}

int test_solidbits_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    ul q;
    size_t i;

    for (j = 0; j < 64; j++) {
        q = (j % 2) == 0 ? UL_ONEBITS : 0;
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            *p1++ = *p2++ = (i % 2) == 0 ? q : ~q;
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_checkerboard_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    ul q;
    size_t i;

    for (j = 0; j < 64; j++) {
        q = (j % 2) == 0 ? CHECKERBOARD1 : CHECKERBOARD2;
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            *p1++ = *p2++ = (i % 2) == 0 ? q : ~q;
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_blockseq_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < 256; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            *p1++ = *p2++ = (ul) UL_BYTE(j);
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_walkbits0_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < UL_LEN * 2; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            if (j < UL_LEN) { /* Walk it up. */
                *p1++ = *p2++ = ONE << j;
            } else { /* Walk it back down. */
                *p1++ = *p2++ = ONE << (UL_LEN * 2 - j - 1);
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_walkbits1_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < UL_LEN * 2; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            if (j < UL_LEN) { /* Walk it up. */
                *p1++ = *p2++ = UL_ONEBITS ^ (ONE << j);
            } else { /* Walk it back down. */
                *p1++ = *p2++ = UL_ONEBITS ^ (ONE << (UL_LEN * 2 - j - 1));
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_bitspread_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j;
    size_t i;

    for (j = 0; j < UL_LEN * 2; j++) {
        p1 = (ulv *) bufa;
        p2 = (ulv *) bufb;
        for (i = 0; i < count; i++) {
            if (j < UL_LEN) { /* Walk it up. */
                *p1++ = *p2++ = (i % 2 == 0)
                    ? (ONE << j) | (ONE << (j + 2))
                    : UL_ONEBITS ^ ((ONE << j)
                                    | (ONE << (j + 2)));
            } else { /* Walk it back down. */
                *p1++ = *p2++ = (i % 2 == 0)
                    ? (ONE << (UL_LEN * 2 - 1 - j)) | (ONE << (UL_LEN * 2 + 1 - j))
                    : UL_ONEBITS ^ (ONE << (UL_LEN * 2 - 1 - j)
                                    | (ONE << (UL_LEN * 2 + 1 - j)));
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_bitflip_comparison(ulv *bufa, ulv *bufb, size_t count) {
    ulv *p1 = bufa;
    ulv *p2 = bufb;
    unsigned int j, k;
    ul q;
    size_t i;

    for (k = 0; k < UL_LEN; k++) {
        q = ONE << k;
        for (j = 0; j < 8; j++) {
            q = ~q;
            p1 = (ulv *) bufa;
            p2 = (ulv *) bufb;
            for (i = 0; i < count; i++) {
                *p1++ = *p2++ = (i % 2) == 0 ? q : ~q;
            }
            if (compare_regions(bufa, bufb, count)) {
                return -1;
            }
        }
    }
    return 0;
}

#ifdef TEST_NARROW_WRITES
int test_8bit_wide_random(ulv* bufa, ulv* bufb, size_t count) {
    u8v *p1, *t;
    ulv *p2;
    int attempt;
    unsigned int b, j = 0;
    size_t i;

    for (attempt = 0; attempt < 2;  attempt++) {
        if (attempt & 1) {
            p1 = (u8v *) bufa;
            p2 = bufb;
        } else {
            p1 = (u8v *) bufb;
            p2 = bufa;
        }
        for (i = 0; i < count; i++) {
            t = mword8.bytes;
            *p2++ = mword8.val = rand_ul();
            for (b=0; b < UL_LEN/8; b++) {
                *p1++ = *t++;
            }
            if (!(i % PROGRESSOFTEN)) {
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}

int test_16bit_wide_random(ulv* bufa, ulv* bufb, size_t count) {
    u16v *p1, *t;
    ulv *p2;
    int attempt;
    unsigned int b, j = 0;
    size_t i;

//    serial_put(' ');
    for (attempt = 0; attempt < 2; attempt++) {
        if (attempt & 1) {
            p1 = (u16v *) bufa;
            p2 = bufb;
        } else {
            p1 = (u16v *) bufb;
            p2 = bufa;
        }
        for (i = 0; i < count; i++) {
            t = mword16.u16s;
            *p2++ = mword16.val = rand_ul();
            for (b = 0; b < UL_LEN/16; b++) {
                *p1++ = *t++;
            }
            if (!(i % PROGRESSOFTEN)) {
            }
        }
        if (compare_regions(bufa, bufb, count)) {
            return -1;
        }
    }
    return 0;
}
#endif


struct test tests[] = {
    { "Random Value"          , test_random_value }            ,
    { "Compare XOR"           , test_xor_comparison }          ,
    { "Compare SUB"           , test_sub_comparison }          ,
    { "Compare MUL"           , test_mul_comparison }          ,
    { "Compare DIV"           , test_div_comparison }          ,
    { "Compare OR"            , test_or_comparison }           ,
    { "Compare AND"           , test_and_comparison }          ,
//    { "Sequential Increment"  , test_seqinc_comparison }       ,
//    { "Solid Bits"            , test_solidbits_comparison }    ,
//    { "Block Sequential"      , test_blockseq_comparison }     ,
//    { "Checkerboard"          , test_checkerboard_comparison } ,
//    { "Bit Spread"            , test_bitspread_comparison }    ,
//    { "Bit Flip"              , test_bitflip_comparison }      ,
//    { "Walking Ones"          , test_walkbits1_comparison }    ,
//    { "Walking Zeroes"        , test_walkbits0_comparison }    ,
//    #ifdef TEST_NARROW_WRITES
//    { "8-bit Writes"          , test_8bit_wide_random }        ,
//    { "16-bit Writes"         , test_16bit_wide_random }       ,
//    #endif
//    { NULL, NULL }
};


int memory_test_rd(void)
{
	int i;
	int rr = 0;
	int rr_flag = 0;
	for(i = 0; i < sizeof(tests)/sizeof(struct test); i++)
	{
	rr_flag = tests[i].fp((ulv *)memory_test_buf_a, (ulv *)memory_test_buf_b, MEMORY_TEST_BYTES/sizeof(ulv));
	if (rr_flag == -1)
		{
			return 0;
		}
	}
	return 1;
}

int memory_test_wr(u8 phase)
{
	int i;
	int rr = 0;
	int rr_flag = 0;
	for(i = 0; i < sizeof(tests)/sizeof(struct test); i++)
	{
	rr_flag = tests[i].fp((ulv *)memory_test_buf_a, (ulv *)memory_test_buf_b, MEMORY_TEST_BYTES/sizeof(ulv));
	set_write_phase(phase);
	if (rr_flag == -1)
		{
			return 0;
		}
	}
	return 1;
}

short int read_phase_test(void)
{
	u8 phase_start = 0x00;
	u8 phase = phase_start;
	u8 read_phase = 0x00;
	u8 phase_rise = 0x00;
	u8 phase_fall = 0x00;
//	memtest_printf("\nread dqs phase original value is 0x%x \n",(*(unsigned int*)(READ_PHASE_ADDR))&(0x000000ff));
	set_read_phase(phase);
//	memtest_printf("Read phase is reset, which =0x%x \n",(*(unsigned int*)(READ_PHASE_ADDR))&(0x000000ff));
//	memtest_printf("\n Read Phase Test Start\n");
	
	/* detect read data rising window*/
	if (memory_test_rd() == 1)
	{
//		phase_rise = phase;
	}
	else
	{
		phase = phase + 0x04;
		set_read_phase(phase);
//		memtest_printf("Read phase beginning value is testing \n");
		while (memory_test_rd() == 0) //rising windows search forwards
		{
//			memtest_printf("Read phase 0x%x failed, next...\n", phase);
			phase = phase + 0x04;
			set_read_phase(phase);
			if(phase == 0xfc)
			{
				memtest_printf("Warning: read phase test failed\n");
				set_read_phase(0x38);
				return -1;
			}
		}
	}
	phase_rise = phase;
//	memtest_printf("\n Read phase begins @ 0x%x\n", phase_rise); //print read phase rising result
	
	/* detect read data falling window */
	phase = phase_rise + 0x40;
	set_read_phase(phase);
	while (memory_test_rd() == 1) //falling coarse test
	{
		phase = phase + 0x10;
		set_read_phase(phase);
//		memtest_printf("Read phase ending value is testing coarsely\n");
	}
	phase = phase - 0x04;
	set_read_phase(phase);
	while (memory_test_rd() == 0) //falling fine test
	{
//		memtest_printf("current read phase value 0x%x is failed, next...\n", phase);
		phase = phase - 0x04;
		set_read_phase(phase);
	}
	phase_fall = phase;
	if(phase_fall<=phase_rise){
		memtest_printf("Warning: read phase test failed: phase_fall<rise\n");
		set_read_phase(0x38);
		return -1;
	}
//	memtest_printf("\nRead phase ends @ 0x%x\n", phase_fall); //print read phase falling result
	
	memtest_printf("Read phase range is 0x%x-0x%x, width=%ddeg\n", phase_rise, phase_fall, (phase_fall-phase_rise)*360/256);
	read_phase = (phase_rise + phase_fall)/2;
	set_read_phase(read_phase);
	short int read_out;
	read_out = (phase_rise<<8)&0xff00 | phase_fall&0x00ff;
	return read_out;
}

short int write_phase_test(void)
{
	u8 phase_start = 0x00;
	u8 phase = phase_start;
	u8 write_phase = 0x00;
	u8 phase_rise = 0x00;
	u8 phase_fall = 0x00;
//	memtest_printf("\nWrite phase original value is 0x%x \n",(((*(unsigned int*)(WRITE_PHASE_ADDR))&(0x0000ff00))>>8));
	set_write_phase(phase);
//	memtest_printf("Write phase is reset, which =0x%x \n",(((*(unsigned int*)(WRITE_PHASE_ADDR))&(0x0000ff00))>>8));
//	memtest_printf("\n Write Phase Test Start\n");
	short int write_out;
	
	/* detect write data rising window*/
	if (memory_test_wr(phase) == 1)
	{
//		phase_rise = phase;
	}
	else
	{
		phase = phase + 0x04;
		set_write_phase(phase);
//		memtest_printf("Write phase beginning value is testing \n");
		while (memory_test_wr(phase) == 0) //rising windows search forwards
		{
			
//			memtest_printf("Write phase 0x%x failed, next...\n", phase);
			phase = phase + 0x04;
			set_write_phase(phase);
			if(phase == 0xfc)
			{
				memtest_printf("Warning: write phase test failed\n");
				set_write_phase(0x4c);
				return -1;
			}
		}
	}
	phase_rise = phase;
//	memtest_printf("\n Write phase begins @ 0x%x \n", phase_rise); //print write phase rising result

	/* detect write data falling window */
	phase = phase_rise + 0x40;
	set_write_phase(phase);
	while (memory_test_wr(phase) == 1) //falling coarse test
	{
		phase = phase + 0x10;
		set_write_phase(phase);
//		memtest_printf("Write phase ending value is testing coarsely\n");
	}
	phase = phase - 0x04;
	set_write_phase(phase);
	while (memory_test_wr(phase) == 0) //falling fine test
	{
//		memtest_printf("Current write phase value 0x%x is failed, next...\n", phase);
		phase = phase - 0x04;
		set_write_phase(phase);
	}
	phase_fall = phase;
	if(phase_fall<=phase_rise){
		memtest_printf("Warning: write phase test failed: phase_fall<rise\n");
		set_write_phase(0x4c);
		return -1;
	}
//	memtest_printf("\nWrite phase ends @ 0x%x\n", phase_fall); //print read phase falling result
	
	memtest_printf("Write phase range is 0x%x-0x%x, width=%ddeg\n", phase_rise, phase_fall, (phase_fall-phase_rise)*360/256);
	write_phase = (phase_rise + phase_fall)/2;
	set_write_phase(write_phase);
	write_out = ((phase_rise<<8)&0xff00) | (phase_fall&0x00ff);
	return write_out;
}

void memory_phase_test(void)
{
	short int read_phase[3];
	u8 read_rise[3];
	u8 read_fall[3];
	u8 max_read_rise;
	u8 min_read_fall;

	short int write_phase[3];
	u8 write_rise[3];
	u8 write_fall[3];
	u8 max_write_rise;
	u8 min_write_fall;

	unsigned int i = 0;
	memtest_printf("\n");
	memtest_printf("Default read  phase is 0x%x \n",(*(unsigned int*)(READ_PHASE_ADDR))&(0x000000ff));
	memtest_printf("Default Write phase is 0x%x \n",(((*(unsigned int*)(WRITE_PHASE_ADDR))&(0x0000ff00))>>8));
	memtest_printf("\n");
	while(i<=2){
		memtest_printf("---loop%d:---\n",i);
		read_phase[i]  = read_phase_test(); //get the read phase result
		read_rise[i]   = read_phase[i]>>8;
		read_fall[i]   = read_phase[i];
		write_phase[i] = write_phase_test();
		write_rise[i]  = write_phase[i]>>8;
		write_fall[i]  = write_phase[i];
		i++;
	}
	max_read_rise = max3(read_rise[0], read_rise[1], read_rise[2]);
	min_read_fall = min3(read_fall[0], read_fall[1], read_fall[2]);
	max_write_rise = max3(write_rise[0], write_rise[1], write_rise[2]);
	min_write_fall = min3(write_fall[0], write_fall[1], write_fall[2]);
	memtest_printf("\n         <<< Result >>>\n");
//	memtest_printf("<<<Read: range = 0x%x-0x%x, width = %ddeg>>>\n", max_read_rise, min_read_fall, (min_read_fall-max_read_rise)*360/256);
//	memtest_printf("<<<Write: range = 0x%x-0x%x, width = %ddeg>>>\n", max_write_rise, min_write_fall, (min_write_fall-max_write_rise)*360/256);
	memtest_printf("|chip|dll|rd_left|rd_right|center|width|wr_left|wr_right|center|width|\n");
	memtest_printf("|    |0d |0x     |0x      |0x    |deg  |0x     |0x      |0x    |deg  |\n");
	memtest_printf("| 1  |%d |%x     |%x      |%x    |%d   |%x     |%x      |%x    |%d   |\n", (((*(unsigned int*)(CONFIG_BASE_MMU+CONFIG_DRAM_STATUS2))<<8)>>23), max_read_rise, min_read_fall, (min_read_fall+max_read_rise)/2,(min_read_fall-max_read_rise)*360/256, max_write_rise, min_write_fall, (min_write_fall+max_write_rise)/2,(min_write_fall-max_write_rise)*360/256);
}
