#include <string.h>
#include "version_autogenerated.h"
#include "vega_param.h"
#include DDR_PAR_INCLUDE

#define GX_BASE_AHB0_SEC (0x83C00000)
#define GX_BASE_APB0_SEC (0x8200F000)
#define GX_BASE_APB1_SEC (0x8240F000)
#define GX_BASE_APB2_SEC (0x8280F000)
#define GX_BASE_APB3_SEC (0x82C0F000)
#define GX_BASE_AHB1_SEC (0x88F00000)
#define GX_BASE_AHB2_SEC (0x89F00000)
#define GX_BASE_AHB3_SEC (0x8AF00000)

spl_boot_info spl_boot = {BOOTLOADER_BIN_SIZE / 0x20000, LOADER_START_ADDR};
spl_flash_info spl_flash;
security_cfg_t ree_secure_cfg[REE_SECURITY_CFG_SIZE / 12] =
{
#if 1 /* RCC TEST */
	{0x89800000 + 0x008,     0x1000      , 0xffffffff},
	{0x89800000 + 0x000,     1 << 16   , 0x0fff0000},
	{0x89800000 + 0x00C,     LOADER_START_ADDR      , 0x1fffffff},
	{0x89800000 + 0x010,     BOOTLOADER_BIN_SIZE/8      , 0xffffffff},
#endif
};

void ddr_config_patch(void)
{
#define DDR_OUTPUT_DRIVER 0x7
#define DDR_ADDR_OUTPUT_DRIVER 0x4
extern spl_dram_info spl_dram;
	spl_dram.dram_config[0] |= (DDR_OUTPUT_DRIVER<<3) | (DDR_OUTPUT_DRIVER<<6) | (DDR_OUTPUT_DRIVER<<16) | (DDR_OUTPUT_DRIVER<<19) | (DDR_OUTPUT_DRIVER<<22) | (DDR_OUTPUT_DRIVER<<25) | (DDR_OUTPUT_DRIVER<<28); //feed, odt, dm, cmd
	spl_dram.dram_config[1] |= (DDR_OUTPUT_DRIVER<<0) | (DDR_OUTPUT_DRIVER<<11); //dqs and clk
	spl_dram.dram_config[2] |= (DDR_ADDR_OUTPUT_DRIVER<<11); //cmd
	spl_dram.dram_config[3] |= (DDR_OUTPUT_DRIVER<<16) | (DDR_OUTPUT_DRIVER<<20) | (DDR_OUTPUT_DRIVER<<24) |(DDR_OUTPUT_DRIVER<<28); //dq
	spl_dram.dram_config[5] |= (DDR_ADDR_OUTPUT_DRIVER<<0) |(DDR_ADDR_OUTPUT_DRIVER<<3) |(DDR_ADDR_OUTPUT_DRIVER<<6) |(DDR_ADDR_OUTPUT_DRIVER<<9) |(DDR_ADDR_OUTPUT_DRIVER<<12) |(DDR_ADDR_OUTPUT_DRIVER<<15) |(DDR_ADDR_OUTPUT_DRIVER<<18) |(DDR_ADDR_OUTPUT_DRIVER<<21) |(DDR_ADDR_OUTPUT_DRIVER<<24) |(DDR_ADDR_OUTPUT_DRIVER<<27); //addr
	spl_dram.dram_config[6] |= (DDR_ADDR_OUTPUT_DRIVER<<0) |(DDR_ADDR_OUTPUT_DRIVER<<3) |(DDR_ADDR_OUTPUT_DRIVER<<6) |(DDR_ADDR_OUTPUT_DRIVER<<9) |(DDR_ADDR_OUTPUT_DRIVER<<12) |(DDR_ADDR_OUTPUT_DRIVER<<16) |(DDR_ADDR_OUTPUT_DRIVER<<19) |(DDR_ADDR_OUTPUT_DRIVER<<22); //addr, ba
}

void flash_init(void)
{
	spl_flash.nor_flash.clk_div = 2;
	spl_flash.nor_flash.sample_delay = 0;
	spl_flash.nor_flash.addr_cyc = 3;

	spl_flash.snand_flash.clk_div = 2;
	spl_flash.snand_flash.smp_dly_neg_spi = 0;
	spl_flash.snand_flash.page_size = 2048;
	spl_flash.snand_flash.page_num_per_block = 64;
	spl_flash.snand_flash.plane_sel = (0<<24) | (0x0c<<8) | 6,  /* (0<<24) | (0x0c<<8) | 6; DS35Q2GA, DS35Q2GB, F50L2G41XA 需要使用*/
	spl_flash.snand_flash.tsc_tcshs = (10<<16) | 2;
	spl_flash.snand_flash.dummy_before_addr = 0;
	spl_flash.snand_flash.dummy_after_addr = 1;
	spl_flash.snand_flash.addr_cyc = 4;

	spl_flash.nand_flash.page_size = 2048;
	spl_flash.nand_flash.page_num_per_block = 64;
	spl_flash.nand_flash.twp_twh = 0x20002;
	spl_flash.nand_flash.trp_treh = (3<<16) | 3;
	spl_flash.nand_flash.trp_treh_fast = (2<<16) | 1;
	spl_flash.nand_flash.smp_dly_neg_fast = (0<<24) | 0;
	spl_flash.nand_flash.twb_trr = (15<<16) | 8;
	spl_flash.nand_flash.trwad = 12;
	spl_flash.nand_flash.addr_cyc = 4;
}

