#include "version_autogenerated.h"
#include "cpu_config.h"
#include "databahn.h"
#ifdef CONFIG_EXTERN_PARAM
#include "board_param.h"
#endif
#include "io.h"

/* denali_config.c / h5tq2g63bfr_h9.c */
extern unsigned int DENALI_CONFIG_CTL[155];
extern unsigned int DENALI_CONFIG_PHY[26];
#ifdef DDR_SEC_PAR_INCLUDE
extern unsigned int DENALI_CONFIG_CTL_2[155];
extern unsigned int DENALI_CONFIG_PHY_2[26];
#endif
extern void ddr_config_patch(void);
extern void serial_put_no_mmu(char);
extern unsigned char otp_read_simple(unsigned int address);

static void Databahn_Init(void);
static void Databahn_SetParameters(struct reg_param *regs, int count);
static unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width);
static unsigned int Databahn_GetIntStatus(void);
static unsigned int Databahn_isReady(void);
static void Databahn_Config(void);

#define DATABAHN_REG_FULL(i, name, addr, offset, width, v) \
	{DATABAHN_REG_AXI##i##name##addr,  DATABAHN_REG_AXI##i##name##offset,  DATABAHN_REG_AXI##i##name##width, v}

#define DATABAHN_REG(i, name, v) \
	DATABAHN_REG_FULL(i, name, _ADDR, _OFFSET, _WIDTH, v)

/* This param_table is used taurus and gemini, but some params are different
 * between taurus and gemini, so defined gemini_diff_param_table */
static struct reg_param param_table[] = {
	// Lvl
	{DATABAHN_REG_WRLVL_REG_EN_ADDR, DATABAHN_REG_WRLVL_REG_EN_OFFSET, DATABAHN_REG_WRLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_REG_EN_ADDR, DATABAHN_REG_RDLVL_REG_EN_OFFSET, DATABAHN_REG_RDLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_GATE_EN_ADDR, DATABAHN_REG_RDLVL_GATE_EN_OFFSET, DATABAHN_REG_RDLVL_GATE_EN_WIDTH, 1},

	DATABAHN_REG(0 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(1 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(2 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(3 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(4 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(5 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(6 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(7 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(8 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(9 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(10, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(11, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(12, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(13, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(14, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(15, _EN_SIZE_LT_WIDTH_INSTR, 0xffff),

	DATABAHN_REG(0 , _R_PRIORITY, 0x5),	//cpu
	DATABAHN_REG(1 , _R_PRIORITY, 0x6),
	DATABAHN_REG(2 , _R_PRIORITY, 0x9),	//pp/ga/jpeg
	DATABAHN_REG(3 , _R_PRIORITY, 0x8),
	DATABAHN_REG(4 , _R_PRIORITY, 0x8),
	DATABAHN_REG(5 , _R_PRIORITY, 0x4),	//vpu
	DATABAHN_REG(6 , _R_PRIORITY, 0x3),	//demux/filter/gse
	DATABAHN_REG(7 , _R_PRIORITY, 0x8),
	DATABAHN_REG(8 , _R_PRIORITY, 0x3),	//audio_dec
	DATABAHN_REG(9 , _R_PRIORITY, 0x5),	//video_dec
	DATABAHN_REG(10, _R_PRIORITY, 0x3),	//apu
	DATABAHN_REG(11, _R_PRIORITY, 0x8),	//secure/scpu/mac
	DATABAHN_REG(12, _R_PRIORITY, 0x8),
	DATABAHN_REG(13, _R_PRIORITY, 0x8),
	DATABAHN_REG(14, _R_PRIORITY, 0x8),	//usb
	DATABAHN_REG(15, _R_PRIORITY, 0x8),

	DATABAHN_REG(0 , _W_PRIORITY, 0x5),
	DATABAHN_REG(1 , _W_PRIORITY, 0x6),
	DATABAHN_REG(2 , _W_PRIORITY, 0x9),
	DATABAHN_REG(3 , _W_PRIORITY, 0x8),
	DATABAHN_REG(4 , _W_PRIORITY, 0x8),
	DATABAHN_REG(5 , _W_PRIORITY, 0x4),
	DATABAHN_REG(6 , _W_PRIORITY, 0x3),
	DATABAHN_REG(7 , _W_PRIORITY, 0x8),
	DATABAHN_REG(8 , _W_PRIORITY, 0x3),
	DATABAHN_REG(9 , _W_PRIORITY, 0x5),
	DATABAHN_REG(10, _W_PRIORITY, 0x3),
	DATABAHN_REG(11, _W_PRIORITY, 0x8),
	DATABAHN_REG(12, _W_PRIORITY, 0x8),
	DATABAHN_REG(13, _W_PRIORITY, 0x8),
	DATABAHN_REG(14, _W_PRIORITY, 0x8),
	DATABAHN_REG(15, _W_PRIORITY, 0x8),

	{DATABAHN_REG_SWAP_EN_ADDR, DATABAHN_REG_SWAP_EN_OFFSET, DATABAHN_REG_SWAP_EN_WIDTH, 0x0},

	// Databahn start enable
	//{DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1}
};

#if defined(CONFIG_EXTERN_PARAM) || defined(CONFIG_ARCH_CKMMU_GEMINI)
static struct reg_param gemini_diff_param_table[] = {
	DATABAHN_REG(3 , _R_PRIORITY, 0x2),     //dvb
	DATABAHN_REG(5 , _R_PRIORITY, 0x1),     //vpu
	DATABAHN_REG(14, _R_PRIORITY, 0x5),     //usb
	DATABAHN_REG(10, _R_PRIORITY, 0x2),     //apu

	DATABAHN_REG(3 , _W_PRIORITY, 0x2),
	DATABAHN_REG(5 , _W_PRIORITY, 0x1),     //vpu
	DATABAHN_REG(14, _W_PRIORITY, 0x5),     //usb
	DATABAHN_REG(10, _W_PRIORITY, 0x2),     //apu
};
#endif

/* routine.c */
static void SetRegisterField(unsigned int reg, unsigned int offset, unsigned int width, unsigned int value)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int value_masked;

	original = *(volatile unsigned int *)reg;

	if (width == 32)
		mask = 0xffffffff;
	else
		mask = (1 << width) - 1;
	value_masked = value & mask;
	result = (original & (~(mask << offset))) | (value_masked << offset);

	*(volatile unsigned int *)reg = result;
}

static unsigned int GetRegisterField(unsigned int reg, unsigned int offset, unsigned int width)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int mask_shifted;

	original = *(volatile unsigned int *)reg;
	if(width==32)
		mask = 0xffffffff;
	else
		mask = (1 << width)-1;
	mask_shifted = mask << offset;
	result = (original & mask_shifted) >> offset;

	return result;
}

#ifdef CHIP_BOARD_6703X5
extern unsigned char is_6701(void);
#endif

/* databahn.c */
void Databahn_Init(void)
{
	unsigned int i;
	unsigned int ddr_version;
	unsigned int tsel_feed;
	unsigned int data_e_sel;
	unsigned int ocd_pu;
	unsigned int ocd_pd;
	unsigned int dfi_cmd_control;
	unsigned int vref_set;
	unsigned int clk_div_out;
	unsigned int cwl;
	unsigned int encry_delay;

#ifdef DDR_SEC_PAR_INCLUDE
#ifdef CONFIG_ARCH_CKMMU_TAURUS
	unsigned char ddr_info = DDR_INFO_GET_NO_MMU();
#endif
#endif

#ifdef CONFIG_EXTERN_PARAM
	if (board_param->chip == TAURUS_CHIP_ID) {
		*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<25);
		*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT_NORM) &= ~((1<<27)|(1<<28));
	} else { /* gemini */
		*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<21);
		*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT2_NORM) &= ~((1<<2)|(1<<3));
	}
#else
#ifdef CONFIG_ARCH_CKMMU_TAURUS
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL) |= (1<<25);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT_NORM) &= ~((1<<27)|(1<<28));
#else /* gemini */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_SOURCE_SEL2) |= (1<<21);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLK_INHIBIT2_NORM) &= ~((1<<2)|(1<<3));
#endif
#endif
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DENALI_CONFIG0)=0xffffffff;

	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) |= (0x1);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_MPEG_CLD_RST_NORM) &= ~(0x1);

	//============set dram_config0-3: begin===================
	//clear config0-3
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2)=0x0;
#ifdef CONFIG_EXTERN_PARAM
	if (board_param->chip == GEMINI_CHIP_ID)
		*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3)=0x0;
#else
#ifdef CONFIG_ARCH_CKMMU_GEMINI
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3)=0x0;
#endif
#endif

	//#1: config1[30], select dram class
#ifdef CONFIG_EXTERN_PARAM
	if (board_param->ddr_type == 3)
		ddr_version = 0x2;
	else if (board_param->ddr_type == 2)
		ddr_version = 0x0;
#else
#ifdef CONFIG_DDR3
	ddr_version = 0x2;
#elif defined(CONFIG_DDR2)
	ddr_version = 0x0;
#endif
#ifdef DDR_SEC_PAR_INCLUDE
#ifdef CONFIG_ARCH_CKMMU_TAURUS
	/* only taurus DDR3 1GB should do follow work */
	if ((ddr_info & 0xF) == DDR2) {
		serial_put_no_mmu('2');
		ddr_version = 0x0;
	}
#endif
#endif
#endif

	//#2: config0[2:0], tsel_feed
	tsel_feed = 0x1;

	//#3: config0[15], data_e_sel, choose the switch of the receiver in DDRIO
	//data_e_sel=0 means switch is controlled by DRAM_CONFIG0[14:11]
	data_e_sel = 0x0;

	//#4: ocd_pu&ocd_pd. taurus: 8 gemini: 2
#ifdef CONFIG_EXTERN_PARAM
	ocd_pu = 8;
	ocd_pd = 8;
	if (board_param->chip == GEMINI_CHIP_ID) {
		ocd_pu = 2;
		ocd_pd = 2;
	}
#else
#ifdef CONFIG_ARCH_CKMMU_TAURUS
	ocd_pu = 8;
	ocd_pd = 8;
#else /* gemini */
	ocd_pu = 2;
	ocd_pd = 2;
#endif
#endif

	//#5: set output driver_strength of DDRIO in board_init.c
	ddr_config_patch();

	//#6: config0[31], dfi_cmd_control
	dfi_cmd_control = 0x1;

	//#7: config2[19:16], set Vref
	vref_set = 0x0;

	//#8: config3[1:0], set encry_delay
#ifdef CONFIG_EXTERN_PARAM
	cwl = (board_param->DENALI_CONFIG_CTL[5] >> 16) & 0x1F;
	encry_delay = (cwl - 4) / 2;
#else
#ifdef CONFIG_ARCH_CKMMU_GEMINI
	cwl = (DENALI_CONFIG_CTL[5] >> 16) & 0x1F;
	encry_delay = (cwl - 4) / 2;
#endif
#endif

	//#9: config3[18], clk_div_out
#ifdef CONFIG_EXTERN_PARAM
	if (board_param->chip == GEMINI_CHIP_ID) {
		if (board_param->ddr_frequency <= DDR_FREQUENCY_533M)
			clk_div_out=0x1;
	}
#else
#ifdef CONFIG_ARCH_CKMMU_GEMINI
#ifdef CHIP_BOARD_6703X5
	/* 6701 ddr fre is 533 MHz */
	if (is_6701()) {
		serial_put_no_mmu('1');
		clk_div_out=0x1;
	}
#else
	if (DDR_FREQUENCY_CONFIG <= DDR_FREQUENCY_533M)
		clk_div_out=0x1;
#endif
#endif
#endif

	//set DRAM_CONFIG
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0) |= (tsel_feed<<0) | (data_e_sel<<15) | (ocd_pu<<16) | (ocd_pd<<20) | (dfi_cmd_control<<31);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1) |= (ddr_version<<29) | (ocd_pu<<3) | (ocd_pd<<7) | (ocd_pu<<14) | (ocd_pd<<18);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2) |= (ocd_pu<<3) | (ocd_pd<<7) | (vref_set<<16);
#ifdef CONFIG_EXTERN_PARAM
	if (board_param->chip == GEMINI_CHIP_ID)
		*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3) |= (clk_div_out<<18) | (encry_delay<<0);
#else
#ifdef CONFIG_ARCH_CKMMU_GEMINI
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3) |= (clk_div_out<<18) | (encry_delay<<0);
#endif
#endif
	//============set dram_config0-3: end===========

#ifdef CONFIG_EXTERN_PARAM
	for(i = 0;i < DENALI_CONFIG_CTL_NUM; i++)
		*(volatile unsigned int *)Databahn_Reg(i) = board_param->DENALI_CONFIG_CTL[i];

	for(i = 0; i < DENALI_CONFIG_PHY_NUM; i++)
		*(volatile unsigned int *)Databahn_Reg((i + 256)) = board_param->DENALI_CONFIG_PHY[i];
#else
#ifdef CONFIG_ARCH_CKMMU_TAURUS
#if defined(CONFIG_DDR3)
	if (otp_read_simple(0x12B) == 0x4D) {
		serial_put_no_mmu('M');
		DENALI_CONFIG_CTL[81] = 0x00002c2c;
		DENALI_CONFIG_PHY[4] = 0x60035858;
	}
#endif
#endif

	for(i = 0;i < sizeof(DENALI_CONFIG_CTL)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg(i) = DENALI_CONFIG_CTL[i];

	for(i = 0; i < sizeof(DENALI_CONFIG_PHY)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg((i + 256)) = DENALI_CONFIG_PHY[i];
#ifdef DDR_SEC_PAR_INCLUDE
#ifdef CONFIG_ARCH_CKMMU_TAURUS
	/* only taurus DDR3 1GB should do follow work */
	if ((ddr_info & 0xF) == DDR2) {
		for(i = 0;i < sizeof(DENALI_CONFIG_CTL_2)/sizeof(unsigned int); i++)
			*(volatile unsigned int *)Databahn_Reg(i) = DENALI_CONFIG_CTL_2[i];

		for(i = 0; i < sizeof(DENALI_CONFIG_PHY_2)/sizeof(unsigned int); i++)
			*(volatile unsigned int *)Databahn_Reg((i + 256)) = DENALI_CONFIG_PHY_2[i];
	}
#endif /* CONFIG_ARCH_CKMMU_TAURUS */
#ifdef CONFIG_ARCH_CKMMU_GEMINI
#ifdef CHIP_BOARD_6703X5
	if (is_6701()) {
		for(i = 0;i < sizeof(DENALI_CONFIG_CTL_2)/sizeof(unsigned int); i++)
			*(volatile unsigned int *)Databahn_Reg(i) = DENALI_CONFIG_CTL_2[i];

		for(i = 0; i < sizeof(DENALI_CONFIG_PHY_2)/sizeof(unsigned int); i++)
			*(volatile unsigned int *)Databahn_Reg((i + 256)) = DENALI_CONFIG_PHY_2[i];
	}

#endif /* CHIP_BOARD_6703X5 */
#endif /* CONFIG_ARCH_CKMMU_GEMINI */
#endif /* DDR_SEC_PAR_INCLUDE */
#endif /* CONFIG_EXTERN_PARAM */

	Databahn_Config();

	while(!Databahn_isReady());
}

void Databahn_SetParameters(struct reg_param *regs, int count)
{
	int i;

	for (i=0; i < count; i++)
		SetRegisterField(Databahn_Reg(regs[i].reg), regs[i].offset, regs[i].width, regs[i].value);
}

static struct otp_dram_param param_mode0[] =
{
	/* ds_double */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0,  3,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1, 11,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1,  0,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0,  6,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0, 24,  3, 0, 5},
	/* ocd_pu */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0, 16,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1,  3,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1, 14,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG2,  3,  4, 1, 0},
	/* ocd_pd */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0, 20,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1,  7,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1, 18,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG2,  7,  4, 1, 4},
	/* mem_ds */
	{Databahn_Reg(28),                 1,  1, 2, 0},
	/* mem_odt */
	{Databahn_Reg(28),                 2,  1, 2, 1},
	{Databahn_Reg(28),                 6,  1, 2, 2},
	{Databahn_Reg(28),                 9,  1, 2, 3},
	/* ctlr_odt */
	{Databahn_Reg(25 + 256),          16,  3, 2, 4},
	{Databahn_Reg(25 + 256),           8,  3, 2, 4},
	{Databahn_Reg(25 + 256),           0,  3, 2, 4},
	/* read_dqs_phase */
	{Databahn_Reg(81),                 0,  8, 3, 0},
	/* write_dq_phase */
	{Databahn_Reg(4 + 256),            8,  8, 4, 0},
	/* rd_low_dq_delay */
	{Databahn_Reg(26 + 256),           0,  3, 5, 0},
	/* rd_high_dq_delay */
	{Databahn_Reg(27 + 256),           0,  3, 5, 3},
#ifdef CONFIG_ARCH_CKMMU_GEMINI
	/* dcap_vref_set */
	{CONFIG_BASE+0x208,                0,  2, 5, 6},
	{CONFIG_BASE+0x208,                2,  1, 6, 0},
#endif
	/* rd_dly_sel */
	{Databahn_Reg(2 + 256),           19,  3, 6, 1},
	/* ds_single */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG2, 11,  3, 6, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG2,  0,  3, 6, 4}
};

void Databahn_ConfigOTPParam(void)
{
	unsigned char otp_data[OTP_DRAM_PARAM_LEN];
	int i = 0;
	int otp_start_addr = 0x154;

	/* 0x154 ~ 0x157 and 0x15d ~ 0x15f */
	for (i = 0; i < OTP_DRAM_PARAM_LEN; i++) {
		otp_data[i] = otp_read_simple(otp_start_addr);
		otp_start_addr++;
		if (otp_start_addr == 0x158)
			otp_start_addr = 0x15d;
	}

	if ((otp_data[0] & 1) == 1 &&
	    ((otp_data[0] >> 1) & 0xF) == 0) {
		for (i = 0; i < sizeof(param_mode0) / sizeof(struct otp_dram_param); i++) {
			unsigned char val = 0;
			if (param_mode0[i].otp_data_byte_index > OTP_DRAM_PARAM_LEN - 1) {
				serial_put_no_mmu('e');
				while (1);
			}
			val = otp_data[param_mode0[i].otp_data_byte_index] >> param_mode0[i].otp_data_bit_offset;
			val &= (1 << param_mode0[i].reg_bit_width) - 1;
			SetRegisterField(param_mode0[i].reg_addr, param_mode0[i].reg_offset, \
					 param_mode0[i].reg_bit_width, val);
		}
		/* pvref_set */
		SetRegisterField(CONFIG_BASE+CONFIG_DRAM_CONFIG2, 16, 4, (otp_data[2] & 0x80) == 0x80 ? 0xa : 0x0);
	}
}

void Databahn_Config(void)
{
	Databahn_SetParameters(param_table, sizeof(param_table) / sizeof(struct reg_param));
#ifdef CONFIG_EXTERN_PARAM
	if (board_param->chip == GEMINI_CHIP_ID)
		Databahn_SetParameters(gemini_diff_param_table, sizeof(gemini_diff_param_table) / sizeof(struct reg_param));
#else
#ifdef CONFIG_ARCH_CKMMU_GEMINI
	Databahn_SetParameters(gemini_diff_param_table, sizeof(gemini_diff_param_table) / sizeof(struct reg_param));
#endif
#endif

	Databahn_ConfigOTPParam();
	// Databahn start enable
	SetRegisterField(Databahn_Reg(DATABAHN_REG_START_ADDR), DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1);
}

unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width)
{
	return GetRegisterField(Databahn_Reg(reg), offset, width);
}

unsigned int Databahn_GetIntStatus(void)
{
	return Databahn_GetParameter(DATABAHN_REG_INT_STATUS_ADDR, DATABAHN_REG_INT_STATUS_OFFSET, DATABAHN_REG_INT_STATUS_WIDTH);
}

unsigned int Databahn_isReady(void)
{
	return (Databahn_GetIntStatus() & 0x20) ? 1 : 0;
}

/* taurus_sdram.c */
void gx_setup_sdram_controller(void)
{
	Databahn_Init();
	serial_put_no_mmu('N');

	/* used for gemini secure align */
#ifdef CONFIG_ARCH_CKMMU_GEMINI
#ifdef ENABLE_SECURE_ALIGN
	volatile unsigned int i = 0x10000;
	*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_CTRL) = 1;
	while(*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_CTRL) != 0x02);
	*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_DATA);
	while (i--) //delay 30 ms
		__asm__ volatile ("nop");
#endif
#endif
}

