SET( CONFIG_GIF  1 )
SET( CONFIG_PNG  1 )
SET( CONFIG_JPEG 1 )
SET( I18N_IN_REALTIME 1)
SET( JPEG_SIZE 1)
#SET( CONFIG_TTF 1)
#SET( CONFIG_SOFT_JPEG 1)
#SET( GUI_SCRIPT JSON)
#SET(CONFIG_T9 1)
#SET(CONFIG_JPEG_ENCODING 1)
#SET(CONFIG_KEY_RECEIVE 1)
SET( GUI_SCRIPT XML)


