#ifndef _CPU_CONFIG_H_
#define _CPU_CONFIG_H_

#include "version_autogenerated.h"

#define CONFIG_BASE			0x0030a000
#define CONFIG_BASE_MMU			(GX_REG_VIRTUAL_BASE1 + CONFIG_BASE)

#define CONFIG_MPEG_CLD_RST_NORM	0x0
#define CONFIG_MPEG_CLD_RST_1SET	0x4
#define CONFIG_MPEG_CLD_RST_1CLR	0x8

#define CONFIG_MPEG_HOT_RST_NORM	0xc
#define CONFIG_MPEG_HOT_RST_1SET	0x10
#define CONFIG_MPEG_HOT_RST_1CLR	0x14

#define CONFIG_MPEG_CLK_INHIBIT_NORM	0x18
#define CONFIG_MPEG_CLK_INHIBIT_1SET	0x1c
#define CONFIG_MPEG_CLK_INHIBIT_1CLR	0x20

#define CONFIG_CLOCK_DIV_CONFIG		0x24

#define CONFIG_DTO_BASE			0x00601000
#define CONFIG_DTO_BASE_MMU		(GX_REG_VIRTUAL_BASE1 + CONFIG_DTO_BASE)
#define CONFIG_DTO1_CONFIG		0x000
#define CONFIG_DTO2_CONFIG		0x004
#define CONFIG_DTO3_CONFIG		0x008
#define CONFIG_DTO4_CONFIG		0x00c
#define CONFIG_DTO5_CONFIG		0x010
#define CONFIG_DTO6_CONFIG		0x014
#define CONFIG_DTO7_CONFIG		0x018
#define CONFIG_DTO8_CONFIG		0x01c
#define CONFIG_DTO9_CONFIG		0x020
#define CONFIG_DTO10_CONFIG		0x024
#define CONFIG_DTO11_CONFIG		0x028
#define CONFIG_DTO12_CONFIG		0x02c
#define CONFIG_DTO13_CONFIG		0x030
#define CONFIG_DTO14_CONFIG		0x034
#define CONFIG_DTO15_CONFIG		0x038
#define CONFIG_DTO16_CONFIG		0x03c

#define CONFIG_MPEG_CLK_INHIBIT2_NORM	0x68
#define CONFIG_MPEG_CLK_INHIBIT2_1SET	0x6C
#define CONFIG_MPEG_CLK_INHIBIT2_1CLR	0x70

#define CONFIG_PLL1_CONFIG              0xC0
#define CONFIG_PLL2_CONFIG              0xC4
#define CONFIG_PLL3_CONFIG              0xC8
#define CONFIG_PLL4_CONFIG              0xCC

#define CONFIG_PLL_CONFIG_IN            0xE8

#define CONFIG_USB_CONFIG               0x000
#define CONFIG_USB1_CONFIG              0x004
#define CONFIG_USB2_CONFIG              0x008
#define CONFIG_USB3_CONFIG              0x00C
#define CONFIG_USB4_CONFIG              0x010

#define CONFIG_DVB_CONFIG               0x110
#define CONFIG_EPHY_CONFIG              0x114

#define CONFIG_DRAM_CONFIG0		0x120
#define CONFIG_DRAM_CONFIG1		0x124
#define CONFIG_DRAM_CONFIG2		0x128
#define CONFIG_DRAM_CONFIG3		0x12c
#define CONFIG_DRAM_STATUS0		0x130
#define CONFIG_DRAM_STATUS1		0x134
#define CONFIG_DRAM_STATUS2		0x138

#define CONFIG_PIN_FUNCTION_SEL0	0x13C
#define CONFIG_PIN_FUNCTION_SEL1	0x140
#define CONFIG_PIN_FUNCTION_SEL2	0x144
#define CONFIG_PIN_FUNCTION_SEL3	0x148
#define CONFIG_PIN_FUNCTION_SEL4	0x14C
#define CONFIG_PIN_FUNCTION_SEL5	0x150

#define CONFIG_LOW_POWER                0x154
#define CONFIG_DDR_STATUS               0x158

#define CONFIG_SOURCE_SEL               0x170
#define CONFIG_SOURCE_SEL2              0x174

#define CONFIG_CLOCK_DIV_CONFIG2        0x178
#define CONFIG_CLOCK_DIV_CONFIG3        0x17C

#define CONFIG_CHIP_INFO                0x180
#define CONFIG_CHIP_ID                  0x184
#define CONFIG_CHIP_NAME0               0x190
#define CONFIG_CHIP_NAME1               0x194
#define CONFIG_CHIP_NAME2               0x198

#define CONFIG_AUDIO_CODEC_DATA         0x1A0
#define CONFIG_AUDIO_CODEC_CONTROL      0x1A4
#define CONFIG_AUDIO_LODEC_CONFIG1      0x1A8
#define CONFIG_AUDIO_LODEC_CONFIG2      0x1AC

#define CONFIG_ETH_CONFIG               0x1B0

#define CONFIG_MPEG_CLD_RST2_NORM	0x1C0
#define CONFIG_MPEG_CLD_RST2_1SET	0x1C4
#define CONFIG_MPEG_CLD_RST2_1CLR	0x1C8

#define CONFIG_MPEG_HOT_RST2_NORM	0x1D0
#define CONFIG_MPEG_HOT_RST2_1SET	0x1D4
#define CONFIG_MPEG_HOT_RST2_1CLR	0x1D8


#define CONFIG_HDMI_REG_DATA		0x1E0
#define CONFIG_HDMI_REG_CONTROL		0x1E4
#define CONFIG_HDMI_KEY			0x1E8

#define CONFIG_VOLTAGE_DETECT_STATUS	0x1EC

#define CONFIG_DAC_CONFIG_0             0x1F0
#define CONFIG_ADC_CONFIG_0             0x200
#define CONFIG_ADC_STA                  0x204

#define CONFIG_RNG_CTRL                 0x300
#define CONFIG_RNG_DATA                 0x304

#define CONFIG_PUBLIC_ID_L		0x560
#define CONFIG_PUBLIC_ID_H		0x674
#define CONFIG_DENALI_CONFIG0		0x580
#define CONFIG_DENALI_CONFIG1		0x584

#define CONFIG_CPU_SDC_AXI_8_62		0x600
#define CONFIG_CPU_SOFT_RESET		0x700
#define CONFIG_TS_OUT_SEL		0x704
#define CONFIG_LDO_DEBUG_SEL		0x780
#define CONFIG_LDO_CONFIG		0x784

#define CONFIG_HDMI_ESD_DEBUG_SEC	0x790
#define CONFIG_HDMI_ESD_CONFIG		0x794

#define CONFIG_IO_DRIVE_CTL             0xA00
#define CONFIG_IO_DRIVE_CTL1            0xA04
#define CONFIG_IO_DRIVE_CTL2            0xA08

#define MACROVISION_CTRL0       0x048040cc
#define MACROVISION_CTRL1       0x048040dc
#define MACROVISION_CTRL2       0x049040cc
#define MACROVISION_CTRL3       0x049040dc

#define DAC_GAIN_CONTROL	(0xa4800130)

#define PLL_DTO_CLK		(1188000000)
#define PLL_DVB_CLK		(1080000000)

#define PLL_DTO_CONFIG_BASE	(0x0030a0c0)
#define PLL_DDR_CONFIG_BASE	(0x0030a0c4)
#define PLL_DVB_CONFIG_BASE	(0x0030a0c8)

#define DDR_RESET_BIT           (0)
#define VDEC_RESET_BIT          (1)
#define ADEC_RESET_BIT          (4)

struct pll_param{
	unsigned int freq ;
	unsigned char refdiv ;
	unsigned char postdiv2 ;
	unsigned char postdiv1 ;
	unsigned int FBdiv ;
};

struct dto_param {
	unsigned char dto;
	unsigned char source_sel;
	unsigned int div;
	unsigned int source_sel_bit;
};

struct div_param {
	unsigned char div_cfg_id;
	unsigned char value_cfg_id;
	unsigned int bit_width;
	unsigned int rstn;
	unsigned int load;
	unsigned int ratio;
	unsigned int value;
};

void PLL_Config(unsigned int pll, unsigned int freq);
void DTO_Config(struct dto_param *param, unsigned char mmu_flag);
void DIV_Config(struct div_param *param, unsigned char mmu_flag);
void source_config(unsigned int source_id, unsigned int value, unsigned int mmu_flag);
void SDelay(unsigned int delay_by);
void ClockSourceSel_Config(unsigned int clock, unsigned int source);
void CPU_Bus_Ratio(unsigned int ratio);

void gx_setup_pll_mini_controller(void);
void gx_setup_pll_full_controller(void);

#endif
