#include "version_autogenerated.h"
#include "cpu_config.h"
#include "stdio.h"
#include "gxhwlib_registers.h"

static void USB_SetSuspendM(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<26);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) &= ~(1<<26);
}

static void USB_ClrSuspendM(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<26);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) |= (1<<26);
}

static void USB_SetPhyReset(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<12);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) |= (1<<28);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) |= (1<<28);
}

static void USB_ClrPhyReset(void)
{
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<12);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB1_CONFIG) &= ~(1<<28);
	*(volatile unsigned int *)(CONFIG_BASE_MMU+CONFIG_USB2_CONFIG) &= ~(1<<28);
}

/* usb.c */
void USB_Init(void)
{
	DTO_Config(12, 10845877, 1);

	//*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_DIV_CONFIG2) |= (1<<4)|(1<<5);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL2) |= 1 | (1<<1) | (1<<2) | (1<<3) | (1<<4) | (1<<5);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB_CONFIG)  |= (1<<25) | (1<<31) | (0x20<<8) | (0x20<<20) | (0x20<<26) | (0xf<<16);
	*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_USB3_CONFIG) |= (1<<25) | (0x20<<20);

	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();
	USB_ClrSuspendM();
	USB_SetSuspendM();
	USB_SetPhyReset();
	USB_ClrPhyReset();
}

static struct pll_dto {
	unsigned int dto;
	unsigned int div;
	unsigned int value;
} dto_table[] = {
	{0  , 0          , 1 << 26} ,  // Ethernet clock
	{7  , 0x07f91ab8 , 1 << 16} ,  // GA 		148MHZ
	{6  , 0x0cc48677 , 1 << 15} ,  // Audio decoder 237MHZ
//	{8  , 0x07f91ab8 , 1 << 17} ,  // DemuxSys 	148MHz
	{8  , 0x091ab875 , 1 << 17} ,  // DemuxSys 	169MHz
	{9  , 0x05d1745d , 1 << 18} ,  // DemuxStc 	108MHz
//	{3  , 0x07f91ab8 , 1 << 12} ,  // Video 	141Mhz
	{3  , 0x0a9ce01c , 1 << 12} ,  // Video  	197Mhz
	{4  , 0x07f91ab8 , 1 << 13} ,  // JPEG	 	148MHZ
	{5  , 0x07f91ab8 , 1 << 14} ,  // PP		148MHZ
	{10 , 0x01745d17 , 1 << 19} ,  // APB2_0 	27MHZ
};

/* only for hardware usb test */
void EHCI_Test(void)
{
#define EHCI_OPBASE	(REG_BASE_USB_EHCI+0x10)

#define EHCI_OPREG_USBCMD		(EHCI_OPBASE+0x0)
#define EHCI_OPREG_USBSTS		(EHCI_OPBASE+0x4)
#define EHCI_OPREG_USBINTR		(EHCI_OPBASE+0x8)
#define EHCI_OPREG_FRINDEX		(EHCI_OPBASE+0xc)
#define EHCI_OPREG_CTRLDSSEGMENT	(EHCI_OPBASE+0x10)
#define EHCI_OPREG_PERIODICLISTBASE	(EHCI_OPBASE+0x14)
#define EHCI_OPREG_ASYNCLISTADDR	(EHCI_OPBASE+0x18)
#define EHCI_OPREG_CONFIGFLAG		(EHCI_OPBASE+0x40)
#define EHCI_OPREG_PORTSC1		(EHCI_OPBASE+0x44)
#define EHCI_OPREG_PORTSC2		(EHCI_OPBASE+0x48)
#define EHCI_OPREG_PORTSC3		(EHCI_OPBASE+0x4c)
	printf("enter echi test, hardware engineer can test after this printf.\n");
	*(volatile unsigned int *)(EHCI_OPREG_USBCMD) &= ~((1<<5)|(1<<4));
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC1) |= (1<<7);
	*(volatile unsigned int *)(EHCI_OPREG_USBCMD) &= ~0x1;	//ehci stop
	while(((*(volatile unsigned int *)(EHCI_OPREG_USBSTS)) & (1<<12)) == 0);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC1) |= (4<<16);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC2) |= (4<<16);
	*(volatile unsigned int *)(EHCI_OPREG_PORTSC3) |= (4<<16);
	while(1);
}

void gx_setup_pll_full_controller(void)
{
	int i;

	/* dvb channel */
#ifdef DVB_CHANNEL_S2
	PLL_Config(PLL_DVB_CONFIG_BASE + GX_REG_VIRTUAL_BASE1, 728000000);
#endif
#ifdef DVB_CHANNEL_C
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<20);
	//PLL_Config(PLL_DVB_CONFIG_BASE + GX_REG_VIRTUAL_BASE1, 57600000);
#endif

	/* audio */
	PLL_Config(PLL_AUD_CONFIG_BASE + GX_REG_VIRTUAL_BASE1, 98304000);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) &= ~(1);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<1);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) &=~(1<<31);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<31);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<31)|(0<<24);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<31)|(0<<24)|(1<<30);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_CLOCK_DIV_CONFIG) |= (1<<31)|(0<<24);

	for (i=0; i < sizeof(dto_table) / sizeof(struct pll_dto); i++) {
		if (dto_table[i].dto != 0)
			DTO_Config(dto_table[i].dto, dto_table[i].div, 1);
		*(volatile unsigned int*)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL) |= dto_table[i].value;
	}

#ifdef DVB_CHANNEL_S2
	// DVB S2
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL2) |= (1<<16);

	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG2) |=  (6 << 8) | (4<<16) | (2<<24);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG2) |=  (1 << 15);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG2) &= ~(1 << 15);

	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG ) |=  (1 << 23);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG)  &= ~(1 << 23);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG)  |=  (1 << 23);

	//ADC
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_ADC) = (4<<8) | (3<<11) | (1<<4) | (1<<6) | (1<<5);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_ADC) = (4<<8) | (3<<11) | (1<<4) | (1<<6) | (1<<5) | 3;
	SDelay(10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_ADC) = (4<<8) | (3<<11) | (1<<4) | (1<<6) | (1<<5) | 3 | (1<<7);

	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_MPEG_HOT_RST_NORM) |= (1<<12);
	SDelay(10);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_MPEG_HOT_RST_NORM) &=~(1<<12);
#endif
#ifdef DVB_CHANNEL_C
	// DVB C
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL) |= (1<<27);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) |= (1<<17);
	*(volatile unsigned int*)(CONFIG_BASE_MMU+CONFIG_SOURCE_SEL2) &=~(1<<18);

	/* close dvb-s2*/
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_SOURCE_SEL2) |= (1<<16);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_CLOCK_DIV_CONFIG)  &= ~(1 << 23);

	//ADC
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_ADC) = (4<<8)|(3<<11)|(1<<4)|(1<<6)|(1<<5)|(1<<14);
	*(volatile unsigned int *)(CONFIG_BASE_MMU + CONFIG_ADC) = (4<<8)|(3<<11)|(1<<4)|(1<<6)|(1<<5)|3|(1<<14);
	SDelay(10);
	//*(volatile unsigned int *)(CONFIG_BASE+CONFIG_ADC) = (4<<8)|(3<<11)|(1<<4)|(1<<6)|(1<<5)|3|(1<<7);
#endif

	// USB
	USB_Init();
#ifdef CONFIG_USB_EYE_DIAGRAM_TEST
	EHCI_Test();
#endif

	//FIXME
//	while(!((*(volatile unsigned int*)0x00400004) & 0x80));
//	*(volatile unsigned int*)0x00400008 = 'U';
}

