#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <ctype.h>
#include <stdbool.h>
#include <getopt.h>
#include <string.h>
#include <sys/stat.h>
#include "version_autogenerated.h"
#ifdef CONFIG_ARCH_ARM_VEGA
#include "vega_param.h"
#endif

extern spl_boot_info spl_boot;
extern spl_clock_info spl_clock;
extern spl_dram_info spl_dram;
extern spl_flash_info spl_flash;
extern security_cfg_t ree_secure_cfg[REE_SECURITY_CFG_SIZE / 12];

char chip_name[128];
unsigned int stage2_size;

struct param_list {
	const char *param_file_name;
	unsigned int param_len;
	void *data;
	unsigned int data_len;
};

struct param_list vega_list[] =
{
	{"spl_boot_param.bin",    8,   &spl_boot,       sizeof(spl_boot_info)},
	{"spl_clock_param.bin",   128, &spl_clock,      sizeof(spl_clock_info)},
	{"spl_dram_param.bin",    2048,&spl_dram,       sizeof(spl_dram_info)},
	{"spl_flash_param.bin",   128, &spl_flash,      sizeof(spl_flash_info)},
	{"ree_security_cfg.bin",  384, &ree_secure_cfg, sizeof(ree_secure_cfg)},
};

static void process_options(int argc, char * const argv[])
{
	int error = 0;
	bool oob_default = true;

	for (;;) {
		int option_index = 0;
		static const char short_options[] = "c:";
		static const struct option long_options[] = {
			{"chip",  required_argument, 0, 'c'},
			{"stage2_size",  required_argument, 0, 0},
			{0, 0, 0, 0},
		};

		int c = getopt_long(argc, argv, short_options,
				long_options, &option_index);
		if (c == EOF) {
			break;
		}

		switch (c) {
			case 0:
				if (!strcmp(long_options[option_index].name, "stage2_size"))
					stage2_size = atoi(optarg);
				break;
			case 'c':
				memcpy(chip_name, optarg, strlen(optarg));
				break;
			default:
				break;
		}
	}
}

int main(int argc, char **argv)
{
	FILE *file_w;
	int write_len;
	int i;
	struct param_list *p_param_list;
	int list_count;
	unsigned char *buf = NULL;

	process_options(argc, argv);

	if (strcmp(chip_name, "vega") == 0) {
		p_param_list = vega_list;
		list_count = sizeof(vega_list) / sizeof(struct param_list);
	} else {
		printf("don't support this chip\n");
		return -1;
	}

extern void pll_mini_init(void);
extern void sdram_init(void);
extern void flash_init(void);
	pll_mini_init();
	sdram_init();
	flash_init();

	if (stage2_size != 0)
		spl_boot.stage2_flash_size = stage2_size;
	for (i = 0; i < list_count; i++) {
		char param_file_name[128+1] = {0};
		buf = NULL;

		snprintf(param_file_name, 128, "output/%s", p_param_list[i].param_file_name);
		file_w = fopen(param_file_name, "wb");
		if (file_w == 0) {
			printf("%s open err.\n", param_file_name);
			goto error_exit;
		}
		if (p_param_list[i].data_len > p_param_list[i].param_len) {
			printf("%s open err.\n", param_file_name);
			goto error_exit;
		}
		buf = malloc(p_param_list[i].param_len);
		if (buf == NULL) {
			printf("malloc buf failed\n");
			goto error_exit;
		}
		memset(buf, 0x00, p_param_list[i].param_len);
		memcpy(buf, p_param_list[i].data, p_param_list[i].data_len);
		write_len = fwrite(buf, 1, p_param_list[i].param_len, file_w);
		if (write_len != p_param_list[i].param_len) {
			printf("write_len != p_param_list[i].data_len\n");
			goto error_exit;
		}

		fclose(file_w);
		free(buf);
	}

	return 0;
error_exit:
	if (buf)
		free(buf);
	fclose(file_w);

	return -1;
}
