//This .c is generated by python script tool.
//Please do not edit it by yourself.
//sources: main_menu.ini mainmenu-config.json
//process: scripts/parse_mainmenu.py

#include "app.h"
#include "app_main_menu.h"

#include "app_main_menu_exapi.h"
#include "app_main_menu_style.h"

extern void app_tv_channel_menu_exec(void);
extern void app_radio_channel_menu_exec(void);
extern void app_deleteall_menu_exec(void);
extern void app_time_setting_menu_exec(void);
extern void app_timer_setting_menu_exec(void);
extern void app_lang_setting_menu_exec(void);
extern void app_av_setting_menu_exec(void);
extern void app_lock_setting_menu_exec(void);
extern void app_osd_setting_menu_exec(void);
extern void app_color_setting_menu_exec(void);
extern void app_network_menu_exec(void);
extern void app_antenna_setting_menu_exec(void);
extern void app_positioner_setting_menu_exec(void);
extern void app_sat_list_menu_exec(void);
extern void app_tp_list_menu_exec(void);
extern void app_sysinfo_menu_exec(void);
extern void app_reset_menu_exec(void);
extern void app_upgrade_menu_exec(void);
extern void app_create_dlna_dmr_menu(void);
extern void app_create_dlna_dmp_menu(void);
extern void app_create_dlna_sat2ip_menu(void);
extern void app_create_dlna_dms_menu(void);
extern void app_create_gxiptv_menu(void);
extern void app_create_stalker_menu(void);
extern void app_create_xtream_menu(void);
extern void app_create_freeiptv_menu(void);
extern void app_media_file_menu_exec(void);
extern void app_media_video_menu_exec(void);
extern void app_media_music_menu_exec(void);
extern void app_media_picture_menu_exec(void);
extern void app_create_pvr_media_menu(void);
extern void app_pvr_set_menu_exec(void);

int mainmenu_item_offset_get(void)
{
	return 80;
}

int mainmenu_item_length_get(void)
{
	return 144;
}

int mainmenu_item_move_level_get(void)
{
	return 6;
}

int mainmenu_item_listview_visual_get(void)
{
	return 6;
}

int mainmenu_item_arrow_exist_get(void)
{
	return 1;
}

int mainmenu_item_move_step_get(void)
{
	return 24;
}

static MainMenuStyle s_MainMenuStyle = {
	.default_last_sub = false,
	.default_sub = 2,
	.item_move = true
};

static int s_ClassificationChange[2] = {STBK_LEFT, STBK_RIGHT};

static char *s_MainMenuMainTitle[] =
{
	STR_ID_CH_EDIT,
	STR_ID_SYS_SET,
	STR_ID_INSTALLATION,
	STR_ID_UTILITY,
	STR_ID_MEDIA_CENTER
};

static OperationLadder s_OperationLadder[] =
{
	{.focus_widget = "wnd_main_menu_item_listview", .next_key_num = 1, .next_ladder_key = {STBK_OK}, .back_key_num = 2, .back_ladder_key = {STBK_MENU, STBK_EXIT}}
};

static unsigned int s_MainMenuSubSize[] = {3, 8, 4, 11, 6};
typedef enum
{
	// Channel Edit Index: 0
	MM_TV_CHANNEL,
	MM_RADIO_CHANNEL,
	MM_DELETE_ALL,

	// System Setting Index: 3
	MM_TIME_SETTING,
	MM_TIMER_SETTING,
	MM_LANGUAGE,
	MM_AV_SETTING,
	MM_LOCK_CONTROL,
	MM_OSD_SETTING,
	MM_COLOR_SETTING,
	MM_NETWORK_SETTING,

	// Installation Index: 11
	MM_ANTENNA,
	MM_POSITIONER,
	MM_SAT_LIST,
	MM_TP_LIST,

	// Utility Index: 15
	MM_SYSTEM_INFO,
	MM_FACTORY_RESET,
	MM_SOFTWARE_UPGRADE,
	MM_DLNA_DMR,
	MM_DLNA_DMP,
	MM_DLNA_SAT2IP,
	MM_DLNA_DMS,
	MM_IPTV,
	MM_STALKER,
	MM_XTREAM,
	MM_FREEIPTV,

	// Media Centre Index: 26
	MM_MEDIA_FILE,
	MM_MEDIA_VIDEO,
	MM_MEDIA_MUSIC,
	MM_MEDIA_PIC,
	MM_PVR_MEDIA,
	MM_PVR_MANAGEMENT,
} MainMenuItemID;

static char *s_MainMenuSubTitle[] =
{
	// Channel Edit Index: 0
	STR_ID_TV_CH,
	STR_ID_RADIO_CH,
	STR_ID_DEL_ALL,

	// System Setting Index: 3
	STR_ID_TIME_SET,
	STR_ID_TIMER_SET,
	STR_ID_LANG,
	STR_ID_AV_SET,
	STR_ID_LOCK_CTRL,
	STR_ID_OSD_SET,
	STR_ID_COLOR_SET,
	STR_ID_NETWORK,

	// Installation Index: 11
	STR_ID_ATNE_SET,
	STR_ID_POSI_SET,
	STR_ID_SAT_LIST,
	STR_ID_TP_LIST,

	// Utility Index: 15
	STR_ID_SYSTEM_INFO,
	STR_ID_FACTORY_RESET,
	STR_ID_FIRMWARE_UPGRADE,
	"DLNA Render",
	"DLNA Player",
	"SAT2IP Player",
	"DLNA DMS",
	STR_ID_NET_IPTV,
	"Stalker",
	"Xtream",
	"Free IPTV",

	// Media Centre Index: 26
	STR_ID_FILE,
	STR_ID_VIDEO,
	STR_ID_MUSIC,
	STR_ID_PICTURE,
	STR_ID_PVR_MEDIA,
	STR_ID_PVR_MANAGE,
};

static MainMenuSetting s_MainMenuSetting[] =
{
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_tv_channel_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_radio_channel_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_deleteall_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_time_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_timer_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_lang_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_av_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_FORCE, app_lock_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_osd_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_color_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_network_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_antenna_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_positioner_setting_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_sat_list_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_tp_list_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_sysinfo_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_FORCE, app_reset_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_LOCK_CHECK, app_upgrade_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NETWORK_CHECK, app_create_dlna_dmr_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NETWORK_CHECK, app_create_dlna_dmp_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NETWORK_CHECK, app_create_dlna_sat2ip_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NETWORK_CHECK, app_create_dlna_dms_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_create_gxiptv_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NETWORK_CHECK, app_create_stalker_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NETWORK_CHECK, app_create_xtream_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_create_freeiptv_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_media_file_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_media_video_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_media_music_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_media_picture_menu_exec, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_create_pvr_media_menu, NULL, 0}},
	{MAIN_MENU_ENTRY, 	.u.item_e = {MENU_NONE_ATTR, app_pvr_set_menu_exec, NULL, 0}}
};

MainMenuStyle* MainMenuStyle_DataGet(void)
{
	return &s_MainMenuStyle;
}

int* ClassificationChange_DataGet(int sel)
{
	return &s_ClassificationChange[sel];
}

int ClassificationChange_SizeGet(void)
{
	return sizeof(s_ClassificationChange) / sizeof(int);
}

char** MainMenuMainTitle_DataGet(int sel)
{
	return &s_MainMenuMainTitle[sel];
}

int MainMenuMainTitle_SizeGet(void)
{
	return sizeof(s_MainMenuMainTitle) / sizeof(char *);
}

OperationLadder* OperationLadder_DataGet(int sel)
{
	return &s_OperationLadder[sel];
}

int OperationLadder_SizeGet(void)
{
	return sizeof(s_OperationLadder) / sizeof(OperationLadder);
}

unsigned int* MainMenuSubSize_DataGet(int sel)
{
	return &s_MainMenuSubSize[sel];
}

int MainMenuSubSize_SizeGet(void)
{
	return sizeof(s_MainMenuSubSize) / sizeof(unsigned int);
}

char** MainMenuSubTitle_DataGet(int sel)
{
	return &s_MainMenuSubTitle[sel];
}

int MainMenuSubTitle_SizeGet(void)
{
	return sizeof(s_MainMenuSubTitle) / sizeof(char *);
}

MainMenuSetting* MainMenuSetting_DataGet(int sel)
{
	return &s_MainMenuSetting[sel];
}

int MainMenuSetting_SizeGet(void)
{
	return sizeof(s_MainMenuSetting) / sizeof(MainMenuSetting);
}

void MainMenuStyleItem_Init(void)
{
	extern MainmenuStyleOps classicops;
	app_mainmenu_style_register(&classicops);
	return;
}

