//create signal_connect_cplus.cpp by bash!!
#include "gui_core.h"
 
 
extern "C" status_t signal_connect_handler(void);
__BEGIN_DECLS
extern int app_cst_box_change(const char* widgetname, void *usrdata);
extern int app_cst_box_keypress(const char* widgetname, void *usrdata);
extern int app_cst_cmb1_change(const char* widgetname, void *usrdata);
extern int app_cst_cmb2_change(const char* widgetname, void *usrdata);
extern int app_cst_cmb3_change(const char* widgetname, void *usrdata);
extern int app_cst_cmb4_change(const char* widgetname, void *usrdata);
extern int app_cst_cmb5_change(const char* widgetname, void *usrdata);
extern int app_cst_cmb6_change(const char* widgetname, void *usrdata);
extern int app_cst_cmb7_change(const char* widgetname, void *usrdata);
extern int app_cst_create(const char* widgetname, void *usrdata);
extern int app_cst_destroy(const char* widgetname, void *usrdata);
extern int app_cst_got_focus(const char* widgetname, void *usrdata);
extern int app_cst_keypress(const char* widgetname, void *usrdata);
extern int app_cst_lost_focus(const char* widgetname, void *usrdata);
extern int app_edit_cst_item1_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_cst_item2_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_cst_item3_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_cst_item4_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_cst_item5_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_cst_item6_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_cst_item7_reach_end(const char* widgetname, void *usrdata);
extern int app_antenna_setting_create(const char* widgetname, void *usrdata);
extern int app_antenna_setting_destroy(const char* widgetname, void *usrdata);
extern int app_antenna_setting_got_focus(const char* widgetname, void *usrdata);
extern int app_antenna_setting_keypress(const char* widgetname, void *usrdata);
extern int app_antenna_setting_lost_focus(const char* widgetname, void *usrdata);
extern int app_atn_box_keypress(const char* widgetname, void *usrdata);
extern int app_atn_cmb_22k_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_diseqc10_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_diseqc11_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_lnb_freq_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_lnb_power_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_sat_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_tp_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_tuner_change(const char* widgetname, void *usrdata);
extern int app_atn_cmb_tuner_keypress(const char* widgetname, void *usrdata);
extern int app_book_popdlg_create(const char* widgetname, void *usrdata);
extern int app_book_popdlg_destroy(const char* widgetname, void *usrdata);
extern int app_book_popdlg_got_focus(const char* widgetname, void *usrdata);
extern int app_book_popdlg_keypress(const char* widgetname, void *usrdata);
extern int app_book_popdlg_lost_focus(const char* widgetname, void *usrdata);
extern int app_book_popdlg_set_service(const char* widgetname, void *usrdata);
extern int app_box_plsn_root_keypress(const char* widgetname, void *usrdata);
extern int app_channel_edit_create(const char* widgetname, void *usrdata);
extern int app_channel_edit_destroy(const char* widgetname, void *usrdata);
extern int app_channel_edit_got_focus(const char* widgetname, void *usrdata);
extern int app_channel_edit_keypress(const char* widgetname, void *usrdata);
extern int app_channel_edit_list_change(const char* widgetname, void *usrdata);
extern int app_channel_edit_list_create(const char* widgetname, void *usrdata);
extern int app_channel_edit_list_get_data(const char* widgetname, void *usrdata);
extern int app_channel_edit_list_get_total(const char* widgetname, void *usrdata);
extern int app_channel_edit_list_keypress(const char* widgetname, void *usrdata);
extern int app_channel_edit_show(const char* widgetname, void *usrdata);
extern int app_channel_info_create(const char* widgetname, void *usrdata);
extern int app_channel_info_destroy(const char* widgetname, void *usrdata);
extern int app_channel_info_got_focus(const char* widgetname, void *usrdata);
extern int app_channel_info_keypress(const char* widgetname, void *usrdata);
extern int app_channel_info_lost_focus(const char* widgetname, void *usrdata);
extern int app_channel_info_signal_create(const char* widgetname, void *usrdata);
extern int app_channel_info_signal_destroy(const char* widgetname, void *usrdata);
extern int app_channel_info_signal_got_focus(const char* widgetname, void *usrdata);
extern int app_channel_info_signal_keypress(const char* widgetname, void *usrdata);
extern int app_channel_info_signal_lost_focus(const char* widgetname, void *usrdata);
extern int app_channel_list_create(const char* widgetname, void *usrdata);
extern int app_channel_list_destroy(const char* widgetname, void *usrdata);
extern int app_channel_list_got_focus(const char* widgetname, void *usrdata);
extern int app_channel_list_group_change(const char* widgetname, void *usrdata);
extern int app_channel_list_keypress(const char* widgetname, void *usrdata);
extern int app_channel_list_list_change(const char* widgetname, void *usrdata);
extern int app_channel_list_list_get_data(const char* widgetname, void *usrdata);
extern int app_channel_list_list_get_total(const char* widgetname, void *usrdata);
extern int app_channel_list_list_keypress(const char* widgetname, void *usrdata);
extern int app_channel_list_lost_focus(const char* widgetname, void *usrdata);
extern int app_ch_pid_box_keypress(const char* widgetname, void *usrdata);
extern int app_common_2nd_menu_create(const char* widgetname, void *usrdata);
extern int app_common_2nd_menu_destroy(const char* widgetname, void *usrdata);
extern int app_common_2nd_menu_keypress(const char* widgetname, void *usrdata);
extern int app_common_select_create(const char* widgetname, void *usrdata);
extern int app_common_select_destroy(const char* widgetname, void *usrdata);
extern int app_common_select_got_focus(const char* widgetname, void *usrdata);
extern int app_common_select_group_change1(const char* widgetname, void *usrdata);
extern int app_common_select_group_change2(const char* widgetname, void *usrdata);
extern int app_common_select_keypress(const char* widgetname, void *usrdata);
extern int app_common_select_list_change(const char* widgetname, void *usrdata);
extern int app_common_select_list_get_data(const char* widgetname, void *usrdata);
extern int app_common_select_list_get_total(const char* widgetname, void *usrdata);
extern int app_common_select_list_keypress(const char* widgetname, void *usrdata);
extern int app_common_select_lost_focus(const char* widgetname, void *usrdata);
extern int app_common_text_keypress(const char* widgetname, void *usrdata);
extern int app_common_view_create(const char* widgetname, void *usrdata);
extern int app_common_view_destroy(const char* widgetname, void *usrdata);
extern int app_common_view_got_focus(const char* widgetname, void *usrdata);
extern int app_common_view_group_list_change(const char* widgetname, void *usrdata);
extern int app_common_view_group_list_get_data(const char* widgetname, void *usrdata);
extern int app_common_view_group_list_get_total(const char* widgetname, void *usrdata);
extern int app_common_view_group_list_keypress(const char* widgetname, void *usrdata);
extern int app_common_view_item_list_change(const char* widgetname, void *usrdata);
extern int app_common_view_item_list_get_data(const char* widgetname, void *usrdata);
extern int app_common_view_item_list_get_total(const char* widgetname, void *usrdata);
extern int app_common_view_item_list_keypress(const char* widgetname, void *usrdata);
extern int app_common_view_keypress(const char* widgetname, void *usrdata);
extern int app_common_view_lost_focus(const char* widgetname, void *usrdata);
extern int app_common_view_service(const char* widgetname, void *usrdata);
extern int app_cryptoguard_baseinfo_keypress(const char* widgetname, void *usrdata);
extern int app_dlna_dmp_create(const char* widgetname, void *usrdata);
extern int app_dlna_dmp_destroy(const char* widgetname, void *usrdata);
extern int app_dlna_dmp_got_focus(const char* widgetname, void *usrdata);
extern int app_dlna_dmp_keypress(const char* widgetname, void *usrdata);
extern int app_dlna_dmp_lost_focus(const char* widgetname, void *usrdata);
extern int app_dlna_dmr_create(const char* widgetname, void *usrdata);
extern int app_dlna_dmr_destroy(const char* widgetname, void *usrdata);
extern int app_dlna_dmr_got_focus(const char* widgetname, void *usrdata);
extern int app_dlna_dmr_keypress(const char* widgetname, void *usrdata);
extern int app_dlna_dmr_lost_focus(const char* widgetname, void *usrdata);
extern int app_dlna_dms_create(const char* widgetname, void *usrdata);
extern int app_dlna_dms_destroy(const char* widgetname, void *usrdata);
extern int app_dlna_dms_got_focus(const char* widgetname, void *usrdata);
extern int app_dlna_dms_keypress(const char* widgetname, void *usrdata);
extern int app_dlna_dms_lost_focus(const char* widgetname, void *usrdata);
extern int app_dm_destroy(const char* widgetname, void *usrdata);
extern int app_dm_got_focus(const char* widgetname, void *usrdata);
extern int app_dm_keypress(const char* widgetname, void *usrdata);
extern int app_dm_list_get_data(const char* widgetname, void *usrdata);
extern int app_dm_list_get_total(const char* widgetname, void *usrdata);
extern int app_dm_list_keypress(const char* widgetname, void *usrdata);
extern int app_dm_lost_focus(const char* widgetname, void *usrdata);
extern int app_dm_setting_create(const char* widgetname, void *usrdata);
extern int app_duration_set_create(const char* widgetname, void *usrdata);
extern int app_duration_set_destroy(const char* widgetname, void *usrdata);
extern int app_duration_set_keypress(const char* widgetname, void *usrdata);
extern int app_edit_ch_pid_a_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_ch_pid_pcr_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_ch_pid_v_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_duration_set_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_network_dns1_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_network_dns2_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_network_gate_way_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_network_ip_address_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_network_mask_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_plsn_root_value_keypress(const char* widgetname, void *usrdata);
extern int app_edit_plsn_root_value_n_keypress(const char* widgetname, void *usrdata);
extern int app_edit_tplist_popup_freq_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_tplist_popup_s2l3_reach_end(const char* widgetname, void *usrdata);
extern int app_edit_tplist_popup_sym_reach_end(const char* widgetname, void *usrdata);
extern int app_epg_create(const char* widgetname, void *usrdata);
extern int app_epg_destroy(const char* widgetname, void *usrdata);
extern int app_epg_got_focus(const char* widgetname, void *usrdata);
extern int app_epg_keypress(const char* widgetname, void *usrdata);
extern int app_epg_lost_focus(const char* widgetname, void *usrdata);
extern int app_epg_lvlist_change(const char* widgetname, void *usrdata);
extern int app_epg_lvlist_get_data(const char* widgetname, void *usrdata);
extern int app_epg_lvlist_get_total(const char* widgetname, void *usrdata);
extern int app_epg_lvlist_keypress(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_change(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_get_data(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_get_total(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_keypress(const char* widgetname, void *usrdata);
extern int app_epg_tmlist_change(const char* widgetname, void *usrdata);
extern int app_epg_tmlist_get_data(const char* widgetname, void *usrdata);
extern int app_epg_tmlist_keypress(const char* widgetname, void *usrdata);
extern int app_epg_video_show(const char* widgetname, void *usrdata);
extern int app_file_list_create(const char* widgetname, void *usrdata);
extern int app_file_list_destroy(const char* widgetname, void *usrdata);
extern int app_file_list_list_change(const char* widgetname, void *usrdata);
extern int app_file_list_list_create(const char* widgetname, void *usrdata);
extern int app_file_list_list_destroy(const char* widgetname, void *usrdata);
extern int app_file_list_list_get_data(const char* widgetname, void *usrdata);
extern int app_file_list_list_get_total(const char* widgetname, void *usrdata);
extern int app_file_list_list_keypress(const char* widgetname, void *usrdata);
extern int app_file_list_service(const char* widgetname, void *usrdata);
extern int app_full_screen_create(const char* widgetname, void *usrdata);
extern int app_full_screen_destroy(const char* widgetname, void *usrdata);
extern int app_full_screen_got_focus(const char* widgetname, void *usrdata);
extern int app_full_screen_keypress(const char* widgetname, void *usrdata);
extern int app_iptv_browser_create(const char* widgetname, void *usrdata);
extern int app_iptv_browser_destroy(const char* widgetname, void *usrdata);
extern int app_iptv_browser_keypress(const char* widgetname, void *usrdata);
extern int app_iptv_epg_create(const char* widgetname, void *usrdata);
extern int app_iptv_epg_days_list_change(const char* widgetname, void *usrdata);
extern int app_iptv_epg_days_list_get_data(const char* widgetname, void *usrdata);
extern int app_iptv_epg_days_list_get_total(const char* widgetname, void *usrdata);
extern int app_iptv_epg_days_list_keypress(const char* widgetname, void *usrdata);
extern int app_iptv_epg_destroy(const char* widgetname, void *usrdata);
extern int app_iptv_epg_events_list_change(const char* widgetname, void *usrdata);
extern int app_iptv_epg_events_list_get_data(const char* widgetname, void *usrdata);
extern int app_iptv_epg_events_list_get_total(const char* widgetname, void *usrdata);
extern int app_iptv_epg_events_list_keypress(const char* widgetname, void *usrdata);
extern int app_iptv_epg_keypress(const char* widgetname, void *usrdata);
extern int app_lang_edit_keyboard_keypress(const char* widgetname, void *usrdata);
extern int app_language_keyboard_create(const char* widgetname, void *usrdata);
extern int app_language_keyboard_destroy(const char* widgetname, void *usrdata);
extern int app_language_keyboard_keypress(const char* widgetname, void *usrdata);
extern int app_main_item_canvas_show(const char* widgetname, void *usrdata);
extern int app_main_menu_create(const char* widgetname, void *usrdata);
extern int app_main_menu_destroy(const char* widgetname, void *usrdata);
extern int app_main_menu_got_focus(const char* widgetname, void *usrdata);
extern int app_main_menu_item_create(const char* widgetname, void *usrdata);
extern int app_main_menu_item_got_focus(const char* widgetname, void *usrdata);
extern int app_main_menu_item_keypress(const char* widgetname, void *usrdata);
extern int app_main_menu_keypress(const char* widgetname, void *usrdata);
extern int app_main_menu_lost_focus(const char* widgetname, void *usrdata);
extern int app_mainmenu_tip_create(const char* widgetname, void *usrdata);
extern int app_mainmenu_tip_destroy(const char* widgetname, void *usrdata);
extern int app_mainmenu_tip_keypress(const char* widgetname, void *usrdata);
extern int app_movie_set_edit_seek_reach_end(const char* widgetname, void *usrdata);
extern int app_netapps_gui_create(const char* widgetname, void *usrdata);
extern int app_netapps_gui_destroy(const char* widgetname, void *usrdata);
extern int app_netapps_gui_got_focus(const char* widgetname, void *usrdata);
extern int app_netapps_gui_lost_focus(const char* widgetname, void *usrdata);
extern int app_netvideo_play_create(const char* widgetname, void *usrdata);
extern int app_netvideo_play_destroy(const char* widgetname, void *usrdata);
extern int app_netvideo_play_got_focus(const char* widgetname, void *usrdata);
extern int app_netvideo_play_keypress(const char* widgetname, void *usrdata);
extern int app_netvideo_play_lost_focus(const char* widgetname, void *usrdata);
extern int app_netvideo_play_number_create(const char* widgetname, void *usrdata);
extern int app_netvideo_play_number_destroy(const char* widgetname, void *usrdata);
extern int app_netvideo_play_number_keypress(const char* widgetname, void *usrdata);
extern int app_netvideo_subt_setting_create(const char* widgetname, void *usrdata);
extern int app_netvideo_subt_setting_destroy(const char* widgetname, void *usrdata);
extern int app_netvideo_subt_setting_keypress(const char* widgetname, void *usrdata);
extern int app_network_box_keypress(const char* widgetname, void *usrdata);
extern int app_network_btn_save_keypress(const char* widgetname, void *usrdata);
extern int app_network_cmb_device_change(const char* widgetname, void *usrdata);
extern int app_network_cmb_device_keypress(const char* widgetname, void *usrdata);
extern int app_network_cmb_mode_change(const char* widgetname, void *usrdata);
extern int app_network_cmb_type_change(const char* widgetname, void *usrdata);
extern int app_network_create(const char* widgetname, void *usrdata);
extern int app_network_destroy(const char* widgetname, void *usrdata);
extern int app_network_got_focus(const char* widgetname, void *usrdata);
extern int app_network_keypress(const char* widgetname, void *usrdata);
extern int app_network_lost_focus(const char* widgetname, void *usrdata);
extern int app_number_create(const char* widgetname, void *usrdata);
extern int app_number_destroy(const char* widgetname, void *usrdata);
extern int app_number_keypress(const char* widgetname, void *usrdata);
extern int app_passwd_dlg_create(const char* widgetname, void *usrdata);
extern int app_passwd_dlg_destroy(const char* widgetname, void *usrdata);
extern int app_passwd_dlg_keypress(const char* widgetname, void *usrdata);
extern int app_plugin_play_info_create(const char* widgetname, void *usrdata);
extern int app_plugin_play_info_cursor_keypress(const char* widgetname, void *usrdata);
extern int app_plugin_play_info_destroy(const char* widgetname, void *usrdata);
extern int app_plugin_play_info_got_focus(const char* widgetname, void *usrdata);
extern int app_plugin_play_info_keypress(const char* widgetname, void *usrdata);
extern int app_plugin_play_info_lost_focus(const char* widgetname, void *usrdata);
extern int app_pop_ch_pid_create(const char* widgetname, void *usrdata);
extern int app_pop_ch_pid_destroy(const char* widgetname, void *usrdata);
extern int app_pop_ch_pid_keypress(const char* widgetname, void *usrdata);
extern int app_pop_dialog_create(const char* widgetname, void *usrdata);
extern int app_pop_dialog_destroy(const char* widgetname, void *usrdata);
extern int app_pop_dialog_keypress(const char* widgetname, void *usrdata);
extern int app_pop_dialog_set_service(const char* widgetname, void *usrdata);
extern int app_popdlg_create(const char* widgetname, void *usrdata);
extern int app_popdlg_destroy(const char* widgetname, void *usrdata);
extern int app_popdlg_keypress(const char* widgetname, void *usrdata);
extern int app_popdlg_set_service(const char* widgetname, void *usrdata);
extern int app_pop_fav_keypress(const char* widgetname, void *usrdata);
extern int app_pop_fav_list_create(const char* widgetname, void *usrdata);
extern int app_pop_fav_list_destroy(const char* widgetname, void *usrdata);
extern int app_pop_fav_list_get_data(const char* widgetname, void *usrdata);
extern int app_pop_fav_list_get_total(const char* widgetname, void *usrdata);
extern int app_pop_fav_list_keypress(const char* widgetname, void *usrdata);
extern int app_pop_option_create(const char* widgetname, void *usrdata);
extern int app_pop_option_destroy(const char* widgetname, void *usrdata);
extern int app_pop_option_keypress(const char* widgetname, void *usrdata);
extern int app_pop_option_list_get_data(const char* widgetname, void *usrdata);
extern int app_pop_option_list_get_total(const char* widgetname, void *usrdata);
extern int app_pop_option_list_keypress(const char* widgetname, void *usrdata);
extern int app_pop_sort_list_create(const char* widgetname, void *usrdata);
extern int app_pop_sort_list_destroy(const char* widgetname, void *usrdata);
extern int app_pop_sort_list_get_data(const char* widgetname, void *usrdata);
extern int app_pop_sort_list_get_total(const char* widgetname, void *usrdata);
extern int app_pop_sort_list_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_cmb_tuner_change(const char* widgetname, void *usrdata);
extern int app_positioner_cmb_tuner_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_diseqc12_goto_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_fine_drive_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_latitude_edit_change(const char* widgetname, void *usrdata);
extern int app_positioner_latitude_edit_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_latitude_edit_reachend(const char* widgetname, void *usrdata);
extern int app_positioner_limit_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_local_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_longitude_edit_change(const char* widgetname, void *usrdata);
extern int app_positioner_longitude_edit_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_longitude_edit_reachend(const char* widgetname, void *usrdata);
extern int app_positioner_motor_type_change(const char* widgetname, void *usrdata);
extern int app_positioner_off_save_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_on_save_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_recalc_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_sat_change(const char* widgetname, void *usrdata);
extern int app_positioner_setting_create(const char* widgetname, void *usrdata);
extern int app_positioner_setting_destroy(const char* widgetname, void *usrdata);
extern int app_positioner_setting_got_focus(const char* widgetname, void *usrdata);
extern int app_positioner_setting_keypress(const char* widgetname, void *usrdata);
extern int app_positioner_setting_lost_focus(const char* widgetname, void *usrdata);
extern int app_positioner_tp_change(const char* widgetname, void *usrdata);
extern int app_positioner_usals_goto_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_bar_create(const char* widgetname, void *usrdata);
extern int app_pvr_bar_destroy(const char* widgetname, void *usrdata);
extern int app_pvr_bar_got_focus(const char* widgetname, void *usrdata);
extern int app_pvr_bar_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_bar_lost_focus(const char* widgetname, void *usrdata);
extern int app_pvr_media_create(const char* widgetname, void *usrdata);
extern int app_pvr_media_destroy(const char* widgetname, void *usrdata);
extern int app_pvr_media_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_change(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_get_data(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_get_total(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_seek_slider_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_sliderbar_keypress(const char* widgetname, void *usrdata);
extern int app_satellite_search_box_keypress(const char* widgetname, void *usrdata);
extern int app_satellite_search_create(const char* widgetname, void *usrdata);
extern int app_sat_list_create(const char* widgetname, void *usrdata);
extern int app_sat_list_destroy(const char* widgetname, void *usrdata);
extern int app_sat_list_got_focus(const char* widgetname, void *usrdata);
extern int app_sat_list_keypress(const char* widgetname, void *usrdata);
extern int app_sat_list_list_change(const char* widgetname, void *usrdata);
extern int app_sat_list_list_create(const char* widgetname, void *usrdata);
extern int app_sat_list_list_get_data(const char* widgetname, void *usrdata);
extern int app_sat_list_list_get_total(const char* widgetname, void *usrdata);
extern int app_sat_list_list_keypress(const char* widgetname, void *usrdata);
extern int app_sat_list_lost_focus(const char* widgetname, void *usrdata);
extern int app_satlist_popup_box_keypress(const char* widgetname, void *usrdata);
extern int app_satlist_popup_create(const char* widgetname, void *usrdata);
extern int app_satlist_popup_destroy(const char* widgetname, void *usrdata);
extern int app_satlist_popup_keypress(const char* widgetname, void *usrdata);
extern int app_satlist_popup_longitude_edit_change(const char* widgetname, void *usrdata);
extern int app_satlist_popup_longitude_edit_reachend(const char* widgetname, void *usrdata);
extern int app_search_cmbox_change(const char* widgetname, void *usrdata);
extern int app_search_create(const char* widgetname, void *usrdata);
extern int app_search_destroy(const char* widgetname, void *usrdata);
extern int app_search_keypress(const char* widgetname, void *usrdata);
extern int app_search_service(const char* widgetname, void *usrdata);
extern int app_search_tip_create(const char* widgetname, void *usrdata);
extern int app_search_tip_destroy(const char* widgetname, void *usrdata);
extern int app_search_tip_keypress(const char* widgetname, void *usrdata);
extern int app_system_info_box_keypress(const char* widgetname, void *usrdata);
extern int app_system_info_got_focus(const char* widgetname, void *usrdata);
extern int app_system_info_keypress(const char* widgetname, void *usrdata);
extern int app_system_info_lost_focus(const char* widgetname, void *usrdata);
extern int app_system_set_btn1_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_btn2_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_btn3_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_btn4_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_btn5_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_btn6_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_btn7_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb1_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb1_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb2_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb2_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb3_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb3_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb4_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb4_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb5_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb5_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb6_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb6_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_cmb7_change(const char* widgetname, void *usrdata);
extern int app_system_set_cmb7_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit1_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit1_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_edit2_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit2_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_edit3_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit3_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_edit4_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit4_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_edit5_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit5_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_edit6_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit6_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_edit7_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_edit7_reach_end(const char* widgetname, void *usrdata);
extern int app_system_set_got_focus(const char* widgetname, void *usrdata);
extern int app_system_set_keypress(const char* widgetname, void *usrdata);
extern int app_system_set_lost_focus(const char* widgetname, void *usrdata);
extern int app_system_set_real_destroy(const char* widgetname, void *usrdata);
extern int app_timer_channel_list_create(const char* widgetname, void *usrdata);
extern int app_timer_channel_list_destroy(const char* widgetname, void *usrdata);
extern int app_timer_channel_list_get_data(const char* widgetname, void *usrdata);
extern int app_timer_channel_list_get_total(const char* widgetname, void *usrdata);
extern int app_timer_channel_list_keypress(const char* widgetname, void *usrdata);
extern int app_timer_list_get_data(const char* widgetname, void *usrdata);
extern int app_timer_list_get_total(const char* widgetname, void *usrdata);
extern int app_timer_setting_create(const char* widgetname, void *usrdata);
extern int app_timer_setting_destroy(const char* widgetname, void *usrdata);
extern int app_timer_setting_got_focus(const char* widgetname, void *usrdata);
extern int app_timer_setting_keypress(const char* widgetname, void *usrdata);
extern int app_timer_setting_lost_focus(const char* widgetname, void *usrdata);
extern int app_tp_list_cmb_sat_change(const char* widgetname, void *usrdata);
extern int app_tp_list_cmb_sat_keypress(const char* widgetname, void *usrdata);
extern int app_tp_list_create(const char* widgetname, void *usrdata);
extern int app_tp_list_destroy(const char* widgetname, void *usrdata);
extern int app_tp_list_got_focus(const char* widgetname, void *usrdata);
extern int app_tp_list_keypress(const char* widgetname, void *usrdata);
extern int app_tp_list_list_change(const char* widgetname, void *usrdata);
extern int app_tp_list_list_create(const char* widgetname, void *usrdata);
extern int app_tp_list_list_get_data(const char* widgetname, void *usrdata);
extern int app_tp_list_list_get_total(const char* widgetname, void *usrdata);
extern int app_tp_list_list_keypress(const char* widgetname, void *usrdata);
extern int app_tp_list_lost_focus(const char* widgetname, void *usrdata);
extern int app_tp_list_plsn_root_create(const char* widgetname, void *usrdata);
extern int app_tp_list_plsn_root_keypress(const char* widgetname, void *usrdata);
extern int app_tplist_popup_box_keypress(const char* widgetname, void *usrdata);
extern int app_tplist_popup_box_s2l3_rec_keypress(const char* widgetname, void *usrdata);
extern int app_tplist_popup_create(const char* widgetname, void *usrdata);
extern int app_tplist_popup_destroy(const char* widgetname, void *usrdata);
extern int app_tplist_popup_keypress(const char* widgetname, void *usrdata);
extern int app_tp_list_prog_radio_get_data(const char* widgetname, void *usrdata);
extern int app_tp_list_prog_radio_get_total(const char* widgetname, void *usrdata);
extern int app_tp_list_prog_radio_keypress(const char* widgetname, void *usrdata);
extern int app_tp_list_prog_tv_get_data(const char* widgetname, void *usrdata);
extern int app_tp_list_prog_tv_get_total(const char* widgetname, void *usrdata);
extern int app_tp_list_prog_tv_keypress(const char* widgetname, void *usrdata);
extern int app_tp_search_box_keypress(const char* widgetname, void *usrdata);
extern int app_tp_search_create(const char* widgetname, void *usrdata);
extern int app_upgrade_progcess_create(const char* widgetname, void *usrdata);
extern int app_upgrade_progcess_destroy(const char* widgetname, void *usrdata);
extern int app_upgrade_progcess_keypress(const char* widgetname, void *usrdata);
extern int app_usb_speed_box_keypress(const char* widgetname, void *usrdata);
extern int app_usb_speed_btn1_keypress(const char* widgetname, void *usrdata);
extern int app_usb_speed_create(const char* widgetname, void *usrdata);
extern int app_usb_speed_destroy(const char* widgetname, void *usrdata);
extern int app_usb_speed_keypress(const char* widgetname, void *usrdata);
extern int app_volume_value_create(const char* widgetname, void *usrdata);
extern int app_volume_value_destroy(const char* widgetname, void *usrdata);
extern int app_volume_value_keypress(const char* widgetname, void *usrdata);
extern int app_volume_value_service(const char* widgetname, void *usrdata);
extern int app_wifi_button_cancel_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_button_connect_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_button_essid_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_button_psk_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_cmb_encryption_change(const char* widgetname, void *usrdata);
extern int app_wifi_cmb_encryption_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_create(const char* widgetname, void *usrdata);
extern int app_wifi_destroy(const char* widgetname, void *usrdata);
extern int app_wifi_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_list_create(const char* widgetname, void *usrdata);
extern int app_wifi_list_get_data(const char* widgetname, void *usrdata);
extern int app_wifi_list_get_total(const char* widgetname, void *usrdata);
extern int app_wifi_list_keypress(const char* widgetname, void *usrdata);
extern int app_wifi_list_list_change(const char* widgetname, void *usrdata);
extern int app_wnd_tp_detail_info_create(const char* widgetname, void *usrdata);
extern int app_wnd_tp_detail_info_keypress(const char* widgetname, void *usrdata);
extern int app_wnd_tp_proglist_create(const char* widgetname, void *usrdata);
extern int app_wnd_tp_proglist_destroy(const char* widgetname, void *usrdata);
extern int app_wnd_tp_proglist_keypress(const char* widgetname, void *usrdata);
extern int app_zoom_canvas_create(const char* widgetname, void *usrdata);
extern int app_zoom_create(const char* widgetname, void *usrdata);
extern int app_zoom_destroy(const char* widgetname, void *usrdata);
extern int app_zoom_keypress(const char* widgetname, void *usrdata);
extern int file_browser_destroy(const char* widgetname, void *usrdata);
extern int file_browser_got_focus(const char* widgetname, void *usrdata);
extern int file_browser_init(const char* widgetname, void *usrdata);
extern int file_browser_keypress(const char* widgetname, void *usrdata);
extern int file_browser_listview_change(const char* widgetname, void *usrdata);
extern int file_browser_listview_get_count(const char* widgetname, void *usrdata);
extern int file_browser_listview_get_data(const char* widgetname, void *usrdata);
extern int file_browser_listview_keypress(const char* widgetname, void *usrdata);
extern int file_browser_lost_focus(const char* widgetname, void *usrdata);
extern int file_browser_service(const char* widgetname, void *usrdata);
extern int listview_common_2nd_menu_get_data(const char* widgetname, void *usrdata);
extern int listview_common_2nd_menu_get_total(const char* widgetname, void *usrdata);
extern int listview_common_2nd_menu_keypress(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_change(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_filter_change(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_filter_get_count(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_filter_get_data(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_filter_keypress(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_get_count(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_get_data(const char* widgetname, void *usrdata);
extern int listview_dlna_dmp_keypress(const char* widgetname, void *usrdata);
extern int listview_main_menu_opt_change(const char* widgetname, void *usrdata);
extern int listview_main_menu_opt_get_data(const char* widgetname, void *usrdata);
extern int listview_main_menu_opt_get_total(const char* widgetname, void *usrdata);
extern int listview_main_menu_opt_keypress(const char* widgetname, void *usrdata);
extern int media_centre_box_keypress(const char* widgetname, void *usrdata);
extern int media_centre_button_file_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_music_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_picture_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_text_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_video_clicked(const char* widgetname, void *usrdata);
extern int media_centre_destroy(const char* widgetname, void *usrdata);
extern int media_centre_init(const char* widgetname, void *usrdata);
extern int media_centre_item_change(const char* widgetname, void *usrdata);
extern int media_centre_keypress(const char* widgetname, void *usrdata);
extern int media_info_destroy(const char* widgetname, void *usrdata);
extern int media_info_init(const char* widgetname, void *usrdata);
extern int media_info_keypress(const char* widgetname, void *usrdata);
extern int media_info_service(const char* widgetname, void *usrdata);
extern int movie_info_destroy(const char* widgetname, void *usrdata);
extern int movie_info_init(const char* widgetname, void *usrdata);
extern int movie_info_keypress(const char* widgetname, void *usrdata);
extern int movie_info_service(const char* widgetname, void *usrdata);
extern int movie_media_service(const char* widgetname, void *usrdata);
extern int movie_media_view_keypress(const char* widgetname, void *usrdata);
extern int movie_set_destroy(const char* widgetname, void *usrdata);
extern int movie_set_init(const char* widgetname, void *usrdata);
extern int movie_set_keypress(const char* widgetname, void *usrdata);
extern int movie_set_service(const char* widgetname, void *usrdata);
extern int movie_subt_destroy(const char* widgetname, void *usrdata);
extern int movie_subt_init(const char* widgetname, void *usrdata);
extern int movie_subt_keypress(const char* widgetname, void *usrdata);
extern int movie_subt_service(const char* widgetname, void *usrdata);
extern int movie_view_box_keypress(const char* widgetname, void *usrdata);
extern int movie_view_cursor_keypress(const char* widgetname, void *usrdata);
extern int movie_view_destroy(const char* widgetname, void *usrdata);
extern int movie_view_got_focus(const char* widgetname, void *usrdata);
extern int movie_view_init(const char* widgetname, void *usrdata);
extern int movie_view_keypress(const char* widgetname, void *usrdata);
extern int movie_view_lost_focus(const char* widgetname, void *usrdata);
extern int movie_view_service(const char* widgetname, void *usrdata);
extern int movie_view_sliderbar_keypress(const char* widgetname, void *usrdata);
extern int music_set_destroy(const char* widgetname, void *usrdata);
extern int music_set_init(const char* widgetname, void *usrdata);
extern int music_set_keypress(const char* widgetname, void *usrdata);
extern int music_set_service(const char* widgetname, void *usrdata);
extern int music_view_box_keypress(const char* widgetname, void *usrdata);
extern int music_view_canvas_init(const char* widgetname, void *usrdata);
extern int music_view_cursor_keypress(const char* widgetname, void *usrdata);
extern int music_view_destroy(const char* widgetname, void *usrdata);
extern int music_view_got_focus(const char* widgetname, void *usrdata);
extern int music_view_init(const char* widgetname, void *usrdata);
extern int music_view_keypress(const char* widgetname, void *usrdata);
extern int music_view_lost_focus(const char* widgetname, void *usrdata);
extern int music_view_service(const char* widgetname, void *usrdata);
extern int music_view_sliderbar_keypress(const char* widgetname, void *usrdata);
extern int On_3g_btn_ok_keypress(const char* widgetname, void *usrdata);
extern int On_3g_create(const char* widgetname, void *usrdata);
extern int On_3g_destroy(const char* widgetname, void *usrdata);
extern int On_3g_got_focus(const char* widgetname, void *usrdata);
extern int On_3g_keypress(const char* widgetname, void *usrdata);
extern int On_3g_lost_focus(const char* widgetname, void *usrdata);
extern int On_3g_set_cmb_area_change(const char* widgetname, void *usrdata);
extern int On_3g_set_cmb_operator_change(const char* widgetname, void *usrdata);
extern int On_3g_set_cmb_type_change(const char* widgetname, void *usrdata);
extern int On_box_3g_set_para_keypress(const char* widgetname, void *usrdata);
extern int On_btn_3g_set_apn_keypress(const char* widgetname, void *usrdata);
extern int On_btn_3g_set_passwd_keypress(const char* widgetname, void *usrdata);
extern int On_btn_3g_set_phone_keypress(const char* widgetname, void *usrdata);
extern int On_btn_3g_set_username_keypress(const char* widgetname, void *usrdata);
extern int On_wnd_cg_maturity_destroy(const char* widgetname, void *usrdata);
extern int On_wnd_cg_maturity_got_focus(const char* widgetname, void *usrdata);
extern int On_wnd_cg_maturity_keypress(const char* widgetname, void *usrdata);
extern int On_wnd_cg_maturity_lost_focus(const char* widgetname, void *usrdata);
extern int On_wnd_cg_strict_rating_destroy(const char* widgetname, void *usrdata);
extern int On_wnd_cg_strict_rating_got_focus(const char* widgetname, void *usrdata);
extern int On_wnd_cg_strict_rating_keypress(const char* widgetname, void *usrdata);
extern int On_wnd_cg_strict_rating_lost_focus(const char* widgetname, void *usrdata);
extern int pic_info_init(const char* widgetname, void *usrdata);
extern int pic_info_keypress(const char* widgetname, void *usrdata);
extern int pic_info_service(const char* widgetname, void *usrdata);
extern int pic_set_destroy(const char* widgetname, void *usrdata);
extern int pic_set_init(const char* widgetname, void *usrdata);
extern int pic_set_keypress(const char* widgetname, void *usrdata);
extern int pic_set_service(const char* widgetname, void *usrdata);
extern int pic_view_box_keypress(const char* widgetname, void *usrdata);
extern int pic_view_destroy(const char* widgetname, void *usrdata);
extern int pic_view_got_focus(const char* widgetname, void *usrdata);
extern int pic_view_init(const char* widgetname, void *usrdata);
extern int pic_view_keypress(const char* widgetname, void *usrdata);
extern int pic_view_lost_focus(const char* widgetname, void *usrdata);
extern int pic_view_service(const char* widgetname, void *usrdata);
extern int text_set_destroy(const char* widgetname, void *usrdata);
extern int text_set_init(const char* widgetname, void *usrdata);
extern int text_set_keypress(const char* widgetname, void *usrdata);
extern int text_set_service(const char* widgetname, void *usrdata);
extern int text_view_destroy(const char* widgetname, void *usrdata);
extern int text_view_got_focus(const char* widgetname, void *usrdata);
extern int text_view_init(const char* widgetname, void *usrdata);
extern int text_view_keypress(const char* widgetname, void *usrdata);
extern int text_view_lost_focus(const char* widgetname, void *usrdata);
extern int text_view_service(const char* widgetname, void *usrdata);
extern int top(const char* widgetname, void *usrdata);
 
 
__END_DECLS
status_t signal_connect_handler(void)
{
	status_t ret = GXCORE_SUCCESS;
	ret |= SIGNAL_CONNECT(app_cst_box_change);
	ret |= SIGNAL_CONNECT(app_cst_box_keypress);
	ret |= SIGNAL_CONNECT(app_cst_cmb1_change);
	ret |= SIGNAL_CONNECT(app_cst_cmb2_change);
	ret |= SIGNAL_CONNECT(app_cst_cmb3_change);
	ret |= SIGNAL_CONNECT(app_cst_cmb4_change);
	ret |= SIGNAL_CONNECT(app_cst_cmb5_change);
	ret |= SIGNAL_CONNECT(app_cst_cmb6_change);
	ret |= SIGNAL_CONNECT(app_cst_cmb7_change);
	ret |= SIGNAL_CONNECT(app_cst_create);
	ret |= SIGNAL_CONNECT(app_cst_destroy);
	ret |= SIGNAL_CONNECT(app_cst_got_focus);
	ret |= SIGNAL_CONNECT(app_cst_keypress);
	ret |= SIGNAL_CONNECT(app_cst_lost_focus);
	ret |= SIGNAL_CONNECT(app_edit_cst_item1_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_cst_item2_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_cst_item3_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_cst_item4_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_cst_item5_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_cst_item6_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_cst_item7_reach_end);
	ret |= SIGNAL_CONNECT(app_antenna_setting_create);
	ret |= SIGNAL_CONNECT(app_antenna_setting_destroy);
	ret |= SIGNAL_CONNECT(app_antenna_setting_got_focus);
	ret |= SIGNAL_CONNECT(app_antenna_setting_keypress);
	ret |= SIGNAL_CONNECT(app_antenna_setting_lost_focus);
	ret |= SIGNAL_CONNECT(app_atn_box_keypress);
	ret |= SIGNAL_CONNECT(app_atn_cmb_22k_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_diseqc10_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_diseqc11_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_lnb_freq_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_lnb_power_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_sat_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_tp_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_tuner_change);
	ret |= SIGNAL_CONNECT(app_atn_cmb_tuner_keypress);
	ret |= SIGNAL_CONNECT(app_book_popdlg_create);
	ret |= SIGNAL_CONNECT(app_book_popdlg_destroy);
	ret |= SIGNAL_CONNECT(app_book_popdlg_got_focus);
	ret |= SIGNAL_CONNECT(app_book_popdlg_keypress);
	ret |= SIGNAL_CONNECT(app_book_popdlg_lost_focus);
	ret |= SIGNAL_CONNECT(app_book_popdlg_set_service);
	ret |= SIGNAL_CONNECT(app_box_plsn_root_keypress);
	ret |= SIGNAL_CONNECT(app_channel_edit_create);
	ret |= SIGNAL_CONNECT(app_channel_edit_destroy);
	ret |= SIGNAL_CONNECT(app_channel_edit_got_focus);
	ret |= SIGNAL_CONNECT(app_channel_edit_keypress);
	ret |= SIGNAL_CONNECT(app_channel_edit_list_change);
	ret |= SIGNAL_CONNECT(app_channel_edit_list_create);
	ret |= SIGNAL_CONNECT(app_channel_edit_list_get_data);
	ret |= SIGNAL_CONNECT(app_channel_edit_list_get_total);
	ret |= SIGNAL_CONNECT(app_channel_edit_list_keypress);
	ret |= SIGNAL_CONNECT(app_channel_edit_show);
	ret |= SIGNAL_CONNECT(app_channel_info_create);
	ret |= SIGNAL_CONNECT(app_channel_info_destroy);
	ret |= SIGNAL_CONNECT(app_channel_info_got_focus);
	ret |= SIGNAL_CONNECT(app_channel_info_keypress);
	ret |= SIGNAL_CONNECT(app_channel_info_lost_focus);
	ret |= SIGNAL_CONNECT(app_channel_info_signal_create);
	ret |= SIGNAL_CONNECT(app_channel_info_signal_destroy);
	ret |= SIGNAL_CONNECT(app_channel_info_signal_got_focus);
	ret |= SIGNAL_CONNECT(app_channel_info_signal_keypress);
	ret |= SIGNAL_CONNECT(app_channel_info_signal_lost_focus);
	ret |= SIGNAL_CONNECT(app_channel_list_create);
	ret |= SIGNAL_CONNECT(app_channel_list_destroy);
	ret |= SIGNAL_CONNECT(app_channel_list_got_focus);
	ret |= SIGNAL_CONNECT(app_channel_list_group_change);
	ret |= SIGNAL_CONNECT(app_channel_list_keypress);
	ret |= SIGNAL_CONNECT(app_channel_list_list_change);
	ret |= SIGNAL_CONNECT(app_channel_list_list_get_data);
	ret |= SIGNAL_CONNECT(app_channel_list_list_get_total);
	ret |= SIGNAL_CONNECT(app_channel_list_list_keypress);
	ret |= SIGNAL_CONNECT(app_channel_list_lost_focus);
	ret |= SIGNAL_CONNECT(app_ch_pid_box_keypress);
	ret |= SIGNAL_CONNECT(app_common_2nd_menu_create);
	ret |= SIGNAL_CONNECT(app_common_2nd_menu_destroy);
	ret |= SIGNAL_CONNECT(app_common_2nd_menu_keypress);
	ret |= SIGNAL_CONNECT(app_common_select_create);
	ret |= SIGNAL_CONNECT(app_common_select_destroy);
	ret |= SIGNAL_CONNECT(app_common_select_got_focus);
	ret |= SIGNAL_CONNECT(app_common_select_group_change1);
	ret |= SIGNAL_CONNECT(app_common_select_group_change2);
	ret |= SIGNAL_CONNECT(app_common_select_keypress);
	ret |= SIGNAL_CONNECT(app_common_select_list_change);
	ret |= SIGNAL_CONNECT(app_common_select_list_get_data);
	ret |= SIGNAL_CONNECT(app_common_select_list_get_total);
	ret |= SIGNAL_CONNECT(app_common_select_list_keypress);
	ret |= SIGNAL_CONNECT(app_common_select_lost_focus);
	ret |= SIGNAL_CONNECT(app_common_text_keypress);
	ret |= SIGNAL_CONNECT(app_common_view_create);
	ret |= SIGNAL_CONNECT(app_common_view_destroy);
	ret |= SIGNAL_CONNECT(app_common_view_got_focus);
	ret |= SIGNAL_CONNECT(app_common_view_group_list_change);
	ret |= SIGNAL_CONNECT(app_common_view_group_list_get_data);
	ret |= SIGNAL_CONNECT(app_common_view_group_list_get_total);
	ret |= SIGNAL_CONNECT(app_common_view_group_list_keypress);
	ret |= SIGNAL_CONNECT(app_common_view_item_list_change);
	ret |= SIGNAL_CONNECT(app_common_view_item_list_get_data);
	ret |= SIGNAL_CONNECT(app_common_view_item_list_get_total);
	ret |= SIGNAL_CONNECT(app_common_view_item_list_keypress);
	ret |= SIGNAL_CONNECT(app_common_view_keypress);
	ret |= SIGNAL_CONNECT(app_common_view_lost_focus);
	ret |= SIGNAL_CONNECT(app_common_view_service);
	ret |= SIGNAL_CONNECT(app_cryptoguard_baseinfo_keypress);
	ret |= SIGNAL_CONNECT(app_dlna_dmp_create);
	ret |= SIGNAL_CONNECT(app_dlna_dmp_destroy);
	ret |= SIGNAL_CONNECT(app_dlna_dmp_got_focus);
	ret |= SIGNAL_CONNECT(app_dlna_dmp_keypress);
	ret |= SIGNAL_CONNECT(app_dlna_dmp_lost_focus);
	ret |= SIGNAL_CONNECT(app_dlna_dmr_create);
	ret |= SIGNAL_CONNECT(app_dlna_dmr_destroy);
	ret |= SIGNAL_CONNECT(app_dlna_dmr_got_focus);
	ret |= SIGNAL_CONNECT(app_dlna_dmr_keypress);
	ret |= SIGNAL_CONNECT(app_dlna_dmr_lost_focus);
	ret |= SIGNAL_CONNECT(app_dlna_dms_create);
	ret |= SIGNAL_CONNECT(app_dlna_dms_destroy);
	ret |= SIGNAL_CONNECT(app_dlna_dms_got_focus);
	ret |= SIGNAL_CONNECT(app_dlna_dms_keypress);
	ret |= SIGNAL_CONNECT(app_dlna_dms_lost_focus);
	ret |= SIGNAL_CONNECT(app_dm_destroy);
	ret |= SIGNAL_CONNECT(app_dm_got_focus);
	ret |= SIGNAL_CONNECT(app_dm_keypress);
	ret |= SIGNAL_CONNECT(app_dm_list_get_data);
	ret |= SIGNAL_CONNECT(app_dm_list_get_total);
	ret |= SIGNAL_CONNECT(app_dm_list_keypress);
	ret |= SIGNAL_CONNECT(app_dm_lost_focus);
	ret |= SIGNAL_CONNECT(app_dm_setting_create);
	ret |= SIGNAL_CONNECT(app_duration_set_create);
	ret |= SIGNAL_CONNECT(app_duration_set_destroy);
	ret |= SIGNAL_CONNECT(app_duration_set_keypress);
	ret |= SIGNAL_CONNECT(app_edit_ch_pid_a_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_ch_pid_pcr_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_ch_pid_v_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_duration_set_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_network_dns1_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_network_dns2_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_network_gate_way_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_network_ip_address_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_network_mask_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_plsn_root_value_keypress);
	ret |= SIGNAL_CONNECT(app_edit_plsn_root_value_n_keypress);
	ret |= SIGNAL_CONNECT(app_edit_tplist_popup_freq_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_tplist_popup_s2l3_reach_end);
	ret |= SIGNAL_CONNECT(app_edit_tplist_popup_sym_reach_end);
	ret |= SIGNAL_CONNECT(app_epg_create);
	ret |= SIGNAL_CONNECT(app_epg_destroy);
	ret |= SIGNAL_CONNECT(app_epg_got_focus);
	ret |= SIGNAL_CONNECT(app_epg_keypress);
	ret |= SIGNAL_CONNECT(app_epg_lost_focus);
	ret |= SIGNAL_CONNECT(app_epg_lvlist_change);
	ret |= SIGNAL_CONNECT(app_epg_lvlist_get_data);
	ret |= SIGNAL_CONNECT(app_epg_lvlist_get_total);
	ret |= SIGNAL_CONNECT(app_epg_lvlist_keypress);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_change);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_get_data);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_get_total);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_keypress);
	ret |= SIGNAL_CONNECT(app_epg_tmlist_change);
	ret |= SIGNAL_CONNECT(app_epg_tmlist_get_data);
	ret |= SIGNAL_CONNECT(app_epg_tmlist_keypress);
	ret |= SIGNAL_CONNECT(app_epg_video_show);
	ret |= SIGNAL_CONNECT(app_file_list_create);
	ret |= SIGNAL_CONNECT(app_file_list_destroy);
	ret |= SIGNAL_CONNECT(app_file_list_list_change);
	ret |= SIGNAL_CONNECT(app_file_list_list_create);
	ret |= SIGNAL_CONNECT(app_file_list_list_destroy);
	ret |= SIGNAL_CONNECT(app_file_list_list_get_data);
	ret |= SIGNAL_CONNECT(app_file_list_list_get_total);
	ret |= SIGNAL_CONNECT(app_file_list_list_keypress);
	ret |= SIGNAL_CONNECT(app_file_list_service);
	ret |= SIGNAL_CONNECT(app_full_screen_create);
	ret |= SIGNAL_CONNECT(app_full_screen_destroy);
	ret |= SIGNAL_CONNECT(app_full_screen_got_focus);
	ret |= SIGNAL_CONNECT(app_full_screen_keypress);
	ret |= SIGNAL_CONNECT(app_iptv_browser_create);
	ret |= SIGNAL_CONNECT(app_iptv_browser_destroy);
	ret |= SIGNAL_CONNECT(app_iptv_browser_keypress);
	ret |= SIGNAL_CONNECT(app_iptv_epg_create);
	ret |= SIGNAL_CONNECT(app_iptv_epg_days_list_change);
	ret |= SIGNAL_CONNECT(app_iptv_epg_days_list_get_data);
	ret |= SIGNAL_CONNECT(app_iptv_epg_days_list_get_total);
	ret |= SIGNAL_CONNECT(app_iptv_epg_days_list_keypress);
	ret |= SIGNAL_CONNECT(app_iptv_epg_destroy);
	ret |= SIGNAL_CONNECT(app_iptv_epg_events_list_change);
	ret |= SIGNAL_CONNECT(app_iptv_epg_events_list_get_data);
	ret |= SIGNAL_CONNECT(app_iptv_epg_events_list_get_total);
	ret |= SIGNAL_CONNECT(app_iptv_epg_events_list_keypress);
	ret |= SIGNAL_CONNECT(app_iptv_epg_keypress);
	ret |= SIGNAL_CONNECT(app_lang_edit_keyboard_keypress);
	ret |= SIGNAL_CONNECT(app_language_keyboard_create);
	ret |= SIGNAL_CONNECT(app_language_keyboard_destroy);
	ret |= SIGNAL_CONNECT(app_language_keyboard_keypress);
	ret |= SIGNAL_CONNECT(app_main_item_canvas_show);
	ret |= SIGNAL_CONNECT(app_main_menu_create);
	ret |= SIGNAL_CONNECT(app_main_menu_destroy);
	ret |= SIGNAL_CONNECT(app_main_menu_got_focus);
	ret |= SIGNAL_CONNECT(app_main_menu_item_create);
	ret |= SIGNAL_CONNECT(app_main_menu_item_got_focus);
	ret |= SIGNAL_CONNECT(app_main_menu_item_keypress);
	ret |= SIGNAL_CONNECT(app_main_menu_keypress);
	ret |= SIGNAL_CONNECT(app_main_menu_lost_focus);
	ret |= SIGNAL_CONNECT(app_mainmenu_tip_create);
	ret |= SIGNAL_CONNECT(app_mainmenu_tip_destroy);
	ret |= SIGNAL_CONNECT(app_mainmenu_tip_keypress);
	ret |= SIGNAL_CONNECT(app_movie_set_edit_seek_reach_end);
	ret |= SIGNAL_CONNECT(app_netapps_gui_create);
	ret |= SIGNAL_CONNECT(app_netapps_gui_destroy);
	ret |= SIGNAL_CONNECT(app_netapps_gui_got_focus);
	ret |= SIGNAL_CONNECT(app_netapps_gui_lost_focus);
	ret |= SIGNAL_CONNECT(app_netvideo_play_create);
	ret |= SIGNAL_CONNECT(app_netvideo_play_destroy);
	ret |= SIGNAL_CONNECT(app_netvideo_play_got_focus);
	ret |= SIGNAL_CONNECT(app_netvideo_play_keypress);
	ret |= SIGNAL_CONNECT(app_netvideo_play_lost_focus);
	ret |= SIGNAL_CONNECT(app_netvideo_play_number_create);
	ret |= SIGNAL_CONNECT(app_netvideo_play_number_destroy);
	ret |= SIGNAL_CONNECT(app_netvideo_play_number_keypress);
	ret |= SIGNAL_CONNECT(app_netvideo_subt_setting_create);
	ret |= SIGNAL_CONNECT(app_netvideo_subt_setting_destroy);
	ret |= SIGNAL_CONNECT(app_netvideo_subt_setting_keypress);
	ret |= SIGNAL_CONNECT(app_network_box_keypress);
	ret |= SIGNAL_CONNECT(app_network_btn_save_keypress);
	ret |= SIGNAL_CONNECT(app_network_cmb_device_change);
	ret |= SIGNAL_CONNECT(app_network_cmb_device_keypress);
	ret |= SIGNAL_CONNECT(app_network_cmb_mode_change);
	ret |= SIGNAL_CONNECT(app_network_cmb_type_change);
	ret |= SIGNAL_CONNECT(app_network_create);
	ret |= SIGNAL_CONNECT(app_network_destroy);
	ret |= SIGNAL_CONNECT(app_network_got_focus);
	ret |= SIGNAL_CONNECT(app_network_keypress);
	ret |= SIGNAL_CONNECT(app_network_lost_focus);
	ret |= SIGNAL_CONNECT(app_number_create);
	ret |= SIGNAL_CONNECT(app_number_destroy);
	ret |= SIGNAL_CONNECT(app_number_keypress);
	ret |= SIGNAL_CONNECT(app_passwd_dlg_create);
	ret |= SIGNAL_CONNECT(app_passwd_dlg_destroy);
	ret |= SIGNAL_CONNECT(app_passwd_dlg_keypress);
	ret |= SIGNAL_CONNECT(app_plugin_play_info_create);
	ret |= SIGNAL_CONNECT(app_plugin_play_info_cursor_keypress);
	ret |= SIGNAL_CONNECT(app_plugin_play_info_destroy);
	ret |= SIGNAL_CONNECT(app_plugin_play_info_got_focus);
	ret |= SIGNAL_CONNECT(app_plugin_play_info_keypress);
	ret |= SIGNAL_CONNECT(app_plugin_play_info_lost_focus);
	ret |= SIGNAL_CONNECT(app_pop_ch_pid_create);
	ret |= SIGNAL_CONNECT(app_pop_ch_pid_destroy);
	ret |= SIGNAL_CONNECT(app_pop_ch_pid_keypress);
	ret |= SIGNAL_CONNECT(app_pop_dialog_create);
	ret |= SIGNAL_CONNECT(app_pop_dialog_destroy);
	ret |= SIGNAL_CONNECT(app_pop_dialog_keypress);
	ret |= SIGNAL_CONNECT(app_pop_dialog_set_service);
	ret |= SIGNAL_CONNECT(app_popdlg_create);
	ret |= SIGNAL_CONNECT(app_popdlg_destroy);
	ret |= SIGNAL_CONNECT(app_popdlg_keypress);
	ret |= SIGNAL_CONNECT(app_popdlg_set_service);
	ret |= SIGNAL_CONNECT(app_pop_fav_keypress);
	ret |= SIGNAL_CONNECT(app_pop_fav_list_create);
	ret |= SIGNAL_CONNECT(app_pop_fav_list_destroy);
	ret |= SIGNAL_CONNECT(app_pop_fav_list_get_data);
	ret |= SIGNAL_CONNECT(app_pop_fav_list_get_total);
	ret |= SIGNAL_CONNECT(app_pop_fav_list_keypress);
	ret |= SIGNAL_CONNECT(app_pop_option_create);
	ret |= SIGNAL_CONNECT(app_pop_option_destroy);
	ret |= SIGNAL_CONNECT(app_pop_option_keypress);
	ret |= SIGNAL_CONNECT(app_pop_option_list_get_data);
	ret |= SIGNAL_CONNECT(app_pop_option_list_get_total);
	ret |= SIGNAL_CONNECT(app_pop_option_list_keypress);
	ret |= SIGNAL_CONNECT(app_pop_sort_list_create);
	ret |= SIGNAL_CONNECT(app_pop_sort_list_destroy);
	ret |= SIGNAL_CONNECT(app_pop_sort_list_get_data);
	ret |= SIGNAL_CONNECT(app_pop_sort_list_get_total);
	ret |= SIGNAL_CONNECT(app_pop_sort_list_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_cmb_tuner_change);
	ret |= SIGNAL_CONNECT(app_positioner_cmb_tuner_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_diseqc12_goto_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_fine_drive_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_latitude_edit_change);
	ret |= SIGNAL_CONNECT(app_positioner_latitude_edit_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_latitude_edit_reachend);
	ret |= SIGNAL_CONNECT(app_positioner_limit_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_local_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_longitude_edit_change);
	ret |= SIGNAL_CONNECT(app_positioner_longitude_edit_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_longitude_edit_reachend);
	ret |= SIGNAL_CONNECT(app_positioner_motor_type_change);
	ret |= SIGNAL_CONNECT(app_positioner_off_save_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_on_save_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_recalc_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_sat_change);
	ret |= SIGNAL_CONNECT(app_positioner_setting_create);
	ret |= SIGNAL_CONNECT(app_positioner_setting_destroy);
	ret |= SIGNAL_CONNECT(app_positioner_setting_got_focus);
	ret |= SIGNAL_CONNECT(app_positioner_setting_keypress);
	ret |= SIGNAL_CONNECT(app_positioner_setting_lost_focus);
	ret |= SIGNAL_CONNECT(app_positioner_tp_change);
	ret |= SIGNAL_CONNECT(app_positioner_usals_goto_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_bar_create);
	ret |= SIGNAL_CONNECT(app_pvr_bar_destroy);
	ret |= SIGNAL_CONNECT(app_pvr_bar_got_focus);
	ret |= SIGNAL_CONNECT(app_pvr_bar_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_bar_lost_focus);
	ret |= SIGNAL_CONNECT(app_pvr_media_create);
	ret |= SIGNAL_CONNECT(app_pvr_media_destroy);
	ret |= SIGNAL_CONNECT(app_pvr_media_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_change);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_get_data);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_get_total);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_seek_slider_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_sliderbar_keypress);
	ret |= SIGNAL_CONNECT(app_satellite_search_box_keypress);
	ret |= SIGNAL_CONNECT(app_satellite_search_create);
	ret |= SIGNAL_CONNECT(app_sat_list_create);
	ret |= SIGNAL_CONNECT(app_sat_list_destroy);
	ret |= SIGNAL_CONNECT(app_sat_list_got_focus);
	ret |= SIGNAL_CONNECT(app_sat_list_keypress);
	ret |= SIGNAL_CONNECT(app_sat_list_list_change);
	ret |= SIGNAL_CONNECT(app_sat_list_list_create);
	ret |= SIGNAL_CONNECT(app_sat_list_list_get_data);
	ret |= SIGNAL_CONNECT(app_sat_list_list_get_total);
	ret |= SIGNAL_CONNECT(app_sat_list_list_keypress);
	ret |= SIGNAL_CONNECT(app_sat_list_lost_focus);
	ret |= SIGNAL_CONNECT(app_satlist_popup_box_keypress);
	ret |= SIGNAL_CONNECT(app_satlist_popup_create);
	ret |= SIGNAL_CONNECT(app_satlist_popup_destroy);
	ret |= SIGNAL_CONNECT(app_satlist_popup_keypress);
	ret |= SIGNAL_CONNECT(app_satlist_popup_longitude_edit_change);
	ret |= SIGNAL_CONNECT(app_satlist_popup_longitude_edit_reachend);
	ret |= SIGNAL_CONNECT(app_search_cmbox_change);
	ret |= SIGNAL_CONNECT(app_search_create);
	ret |= SIGNAL_CONNECT(app_search_destroy);
	ret |= SIGNAL_CONNECT(app_search_keypress);
	ret |= SIGNAL_CONNECT(app_search_service);
	ret |= SIGNAL_CONNECT(app_search_tip_create);
	ret |= SIGNAL_CONNECT(app_search_tip_destroy);
	ret |= SIGNAL_CONNECT(app_search_tip_keypress);
	ret |= SIGNAL_CONNECT(app_system_info_box_keypress);
	ret |= SIGNAL_CONNECT(app_system_info_got_focus);
	ret |= SIGNAL_CONNECT(app_system_info_keypress);
	ret |= SIGNAL_CONNECT(app_system_info_lost_focus);
	ret |= SIGNAL_CONNECT(app_system_set_btn1_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_btn2_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_btn3_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_btn4_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_btn5_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_btn6_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_btn7_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb1_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb1_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb2_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb2_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb3_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb3_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb4_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb4_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb5_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb5_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb6_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb6_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_cmb7_change);
	ret |= SIGNAL_CONNECT(app_system_set_cmb7_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit1_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit1_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_edit2_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit2_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_edit3_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit3_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_edit4_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit4_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_edit5_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit5_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_edit6_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit6_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_edit7_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_edit7_reach_end);
	ret |= SIGNAL_CONNECT(app_system_set_got_focus);
	ret |= SIGNAL_CONNECT(app_system_set_keypress);
	ret |= SIGNAL_CONNECT(app_system_set_lost_focus);
	ret |= SIGNAL_CONNECT(app_system_set_real_destroy);
	ret |= SIGNAL_CONNECT(app_timer_channel_list_create);
	ret |= SIGNAL_CONNECT(app_timer_channel_list_destroy);
	ret |= SIGNAL_CONNECT(app_timer_channel_list_get_data);
	ret |= SIGNAL_CONNECT(app_timer_channel_list_get_total);
	ret |= SIGNAL_CONNECT(app_timer_channel_list_keypress);
	ret |= SIGNAL_CONNECT(app_timer_list_get_data);
	ret |= SIGNAL_CONNECT(app_timer_list_get_total);
	ret |= SIGNAL_CONNECT(app_timer_setting_create);
	ret |= SIGNAL_CONNECT(app_timer_setting_destroy);
	ret |= SIGNAL_CONNECT(app_timer_setting_got_focus);
	ret |= SIGNAL_CONNECT(app_timer_setting_keypress);
	ret |= SIGNAL_CONNECT(app_timer_setting_lost_focus);
	ret |= SIGNAL_CONNECT(app_tp_list_cmb_sat_change);
	ret |= SIGNAL_CONNECT(app_tp_list_cmb_sat_keypress);
	ret |= SIGNAL_CONNECT(app_tp_list_create);
	ret |= SIGNAL_CONNECT(app_tp_list_destroy);
	ret |= SIGNAL_CONNECT(app_tp_list_got_focus);
	ret |= SIGNAL_CONNECT(app_tp_list_keypress);
	ret |= SIGNAL_CONNECT(app_tp_list_list_change);
	ret |= SIGNAL_CONNECT(app_tp_list_list_create);
	ret |= SIGNAL_CONNECT(app_tp_list_list_get_data);
	ret |= SIGNAL_CONNECT(app_tp_list_list_get_total);
	ret |= SIGNAL_CONNECT(app_tp_list_list_keypress);
	ret |= SIGNAL_CONNECT(app_tp_list_lost_focus);
	ret |= SIGNAL_CONNECT(app_tp_list_plsn_root_create);
	ret |= SIGNAL_CONNECT(app_tp_list_plsn_root_keypress);
	ret |= SIGNAL_CONNECT(app_tplist_popup_box_keypress);
	ret |= SIGNAL_CONNECT(app_tplist_popup_box_s2l3_rec_keypress);
	ret |= SIGNAL_CONNECT(app_tplist_popup_create);
	ret |= SIGNAL_CONNECT(app_tplist_popup_destroy);
	ret |= SIGNAL_CONNECT(app_tplist_popup_keypress);
	ret |= SIGNAL_CONNECT(app_tp_list_prog_radio_get_data);
	ret |= SIGNAL_CONNECT(app_tp_list_prog_radio_get_total);
	ret |= SIGNAL_CONNECT(app_tp_list_prog_radio_keypress);
	ret |= SIGNAL_CONNECT(app_tp_list_prog_tv_get_data);
	ret |= SIGNAL_CONNECT(app_tp_list_prog_tv_get_total);
	ret |= SIGNAL_CONNECT(app_tp_list_prog_tv_keypress);
	ret |= SIGNAL_CONNECT(app_tp_search_box_keypress);
	ret |= SIGNAL_CONNECT(app_tp_search_create);
	ret |= SIGNAL_CONNECT(app_upgrade_progcess_create);
	ret |= SIGNAL_CONNECT(app_upgrade_progcess_destroy);
	ret |= SIGNAL_CONNECT(app_upgrade_progcess_keypress);
	ret |= SIGNAL_CONNECT(app_usb_speed_box_keypress);
	ret |= SIGNAL_CONNECT(app_usb_speed_btn1_keypress);
	ret |= SIGNAL_CONNECT(app_usb_speed_create);
	ret |= SIGNAL_CONNECT(app_usb_speed_destroy);
	ret |= SIGNAL_CONNECT(app_usb_speed_keypress);
	ret |= SIGNAL_CONNECT(app_volume_value_create);
	ret |= SIGNAL_CONNECT(app_volume_value_destroy);
	ret |= SIGNAL_CONNECT(app_volume_value_keypress);
	ret |= SIGNAL_CONNECT(app_volume_value_service);
	ret |= SIGNAL_CONNECT(app_wifi_button_cancel_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_button_connect_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_button_essid_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_button_psk_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_cmb_encryption_change);
	ret |= SIGNAL_CONNECT(app_wifi_cmb_encryption_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_create);
	ret |= SIGNAL_CONNECT(app_wifi_destroy);
	ret |= SIGNAL_CONNECT(app_wifi_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_list_create);
	ret |= SIGNAL_CONNECT(app_wifi_list_get_data);
	ret |= SIGNAL_CONNECT(app_wifi_list_get_total);
	ret |= SIGNAL_CONNECT(app_wifi_list_keypress);
	ret |= SIGNAL_CONNECT(app_wifi_list_list_change);
	ret |= SIGNAL_CONNECT(app_wnd_tp_detail_info_create);
	ret |= SIGNAL_CONNECT(app_wnd_tp_detail_info_keypress);
	ret |= SIGNAL_CONNECT(app_wnd_tp_proglist_create);
	ret |= SIGNAL_CONNECT(app_wnd_tp_proglist_destroy);
	ret |= SIGNAL_CONNECT(app_wnd_tp_proglist_keypress);
	ret |= SIGNAL_CONNECT(app_zoom_canvas_create);
	ret |= SIGNAL_CONNECT(app_zoom_create);
	ret |= SIGNAL_CONNECT(app_zoom_destroy);
	ret |= SIGNAL_CONNECT(app_zoom_keypress);
	ret |= SIGNAL_CONNECT(file_browser_destroy);
	ret |= SIGNAL_CONNECT(file_browser_got_focus);
	ret |= SIGNAL_CONNECT(file_browser_init);
	ret |= SIGNAL_CONNECT(file_browser_keypress);
	ret |= SIGNAL_CONNECT(file_browser_listview_change);
	ret |= SIGNAL_CONNECT(file_browser_listview_get_count);
	ret |= SIGNAL_CONNECT(file_browser_listview_get_data);
	ret |= SIGNAL_CONNECT(file_browser_listview_keypress);
	ret |= SIGNAL_CONNECT(file_browser_lost_focus);
	ret |= SIGNAL_CONNECT(file_browser_service);
	ret |= SIGNAL_CONNECT(listview_common_2nd_menu_get_data);
	ret |= SIGNAL_CONNECT(listview_common_2nd_menu_get_total);
	ret |= SIGNAL_CONNECT(listview_common_2nd_menu_keypress);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_change);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_filter_change);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_filter_get_count);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_filter_get_data);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_filter_keypress);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_get_count);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_get_data);
	ret |= SIGNAL_CONNECT(listview_dlna_dmp_keypress);
	ret |= SIGNAL_CONNECT(listview_main_menu_opt_change);
	ret |= SIGNAL_CONNECT(listview_main_menu_opt_get_data);
	ret |= SIGNAL_CONNECT(listview_main_menu_opt_get_total);
	ret |= SIGNAL_CONNECT(listview_main_menu_opt_keypress);
	ret |= SIGNAL_CONNECT(media_centre_box_keypress);
	ret |= SIGNAL_CONNECT(media_centre_button_file_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_music_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_picture_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_text_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_video_clicked);
	ret |= SIGNAL_CONNECT(media_centre_destroy);
	ret |= SIGNAL_CONNECT(media_centre_init);
	ret |= SIGNAL_CONNECT(media_centre_item_change);
	ret |= SIGNAL_CONNECT(media_centre_keypress);
	ret |= SIGNAL_CONNECT(media_info_destroy);
	ret |= SIGNAL_CONNECT(media_info_init);
	ret |= SIGNAL_CONNECT(media_info_keypress);
	ret |= SIGNAL_CONNECT(media_info_service);
	ret |= SIGNAL_CONNECT(movie_info_destroy);
	ret |= SIGNAL_CONNECT(movie_info_init);
	ret |= SIGNAL_CONNECT(movie_info_keypress);
	ret |= SIGNAL_CONNECT(movie_info_service);
	ret |= SIGNAL_CONNECT(movie_media_service);
	ret |= SIGNAL_CONNECT(movie_media_view_keypress);
	ret |= SIGNAL_CONNECT(movie_set_destroy);
	ret |= SIGNAL_CONNECT(movie_set_init);
	ret |= SIGNAL_CONNECT(movie_set_keypress);
	ret |= SIGNAL_CONNECT(movie_set_service);
	ret |= SIGNAL_CONNECT(movie_subt_destroy);
	ret |= SIGNAL_CONNECT(movie_subt_init);
	ret |= SIGNAL_CONNECT(movie_subt_keypress);
	ret |= SIGNAL_CONNECT(movie_subt_service);
	ret |= SIGNAL_CONNECT(movie_view_box_keypress);
	ret |= SIGNAL_CONNECT(movie_view_cursor_keypress);
	ret |= SIGNAL_CONNECT(movie_view_destroy);
	ret |= SIGNAL_CONNECT(movie_view_got_focus);
	ret |= SIGNAL_CONNECT(movie_view_init);
	ret |= SIGNAL_CONNECT(movie_view_keypress);
	ret |= SIGNAL_CONNECT(movie_view_lost_focus);
	ret |= SIGNAL_CONNECT(movie_view_service);
	ret |= SIGNAL_CONNECT(movie_view_sliderbar_keypress);
	ret |= SIGNAL_CONNECT(music_set_destroy);
	ret |= SIGNAL_CONNECT(music_set_init);
	ret |= SIGNAL_CONNECT(music_set_keypress);
	ret |= SIGNAL_CONNECT(music_set_service);
	ret |= SIGNAL_CONNECT(music_view_box_keypress);
	ret |= SIGNAL_CONNECT(music_view_canvas_init);
	ret |= SIGNAL_CONNECT(music_view_cursor_keypress);
	ret |= SIGNAL_CONNECT(music_view_destroy);
	ret |= SIGNAL_CONNECT(music_view_got_focus);
	ret |= SIGNAL_CONNECT(music_view_init);
	ret |= SIGNAL_CONNECT(music_view_keypress);
	ret |= SIGNAL_CONNECT(music_view_lost_focus);
	ret |= SIGNAL_CONNECT(music_view_service);
	ret |= SIGNAL_CONNECT(music_view_sliderbar_keypress);
	ret |= SIGNAL_CONNECT(On_3g_btn_ok_keypress);
	ret |= SIGNAL_CONNECT(On_3g_create);
	ret |= SIGNAL_CONNECT(On_3g_destroy);
	ret |= SIGNAL_CONNECT(On_3g_got_focus);
	ret |= SIGNAL_CONNECT(On_3g_keypress);
	ret |= SIGNAL_CONNECT(On_3g_lost_focus);
	ret |= SIGNAL_CONNECT(On_3g_set_cmb_area_change);
	ret |= SIGNAL_CONNECT(On_3g_set_cmb_operator_change);
	ret |= SIGNAL_CONNECT(On_3g_set_cmb_type_change);
	ret |= SIGNAL_CONNECT(On_box_3g_set_para_keypress);
	ret |= SIGNAL_CONNECT(On_btn_3g_set_apn_keypress);
	ret |= SIGNAL_CONNECT(On_btn_3g_set_passwd_keypress);
	ret |= SIGNAL_CONNECT(On_btn_3g_set_phone_keypress);
	ret |= SIGNAL_CONNECT(On_btn_3g_set_username_keypress);
	ret |= SIGNAL_CONNECT(On_wnd_cg_maturity_destroy);
	ret |= SIGNAL_CONNECT(On_wnd_cg_maturity_got_focus);
	ret |= SIGNAL_CONNECT(On_wnd_cg_maturity_keypress);
	ret |= SIGNAL_CONNECT(On_wnd_cg_maturity_lost_focus);
	ret |= SIGNAL_CONNECT(On_wnd_cg_strict_rating_destroy);
	ret |= SIGNAL_CONNECT(On_wnd_cg_strict_rating_got_focus);
	ret |= SIGNAL_CONNECT(On_wnd_cg_strict_rating_keypress);
	ret |= SIGNAL_CONNECT(On_wnd_cg_strict_rating_lost_focus);
	ret |= SIGNAL_CONNECT(pic_info_init);
	ret |= SIGNAL_CONNECT(pic_info_keypress);
	ret |= SIGNAL_CONNECT(pic_info_service);
	ret |= SIGNAL_CONNECT(pic_set_destroy);
	ret |= SIGNAL_CONNECT(pic_set_init);
	ret |= SIGNAL_CONNECT(pic_set_keypress);
	ret |= SIGNAL_CONNECT(pic_set_service);
	ret |= SIGNAL_CONNECT(pic_view_box_keypress);
	ret |= SIGNAL_CONNECT(pic_view_destroy);
	ret |= SIGNAL_CONNECT(pic_view_got_focus);
	ret |= SIGNAL_CONNECT(pic_view_init);
	ret |= SIGNAL_CONNECT(pic_view_keypress);
	ret |= SIGNAL_CONNECT(pic_view_lost_focus);
	ret |= SIGNAL_CONNECT(pic_view_service);
	ret |= SIGNAL_CONNECT(text_set_destroy);
	ret |= SIGNAL_CONNECT(text_set_init);
	ret |= SIGNAL_CONNECT(text_set_keypress);
	ret |= SIGNAL_CONNECT(text_set_service);
	ret |= SIGNAL_CONNECT(text_view_destroy);
	ret |= SIGNAL_CONNECT(text_view_got_focus);
	ret |= SIGNAL_CONNECT(text_view_init);
	ret |= SIGNAL_CONNECT(text_view_keypress);
	ret |= SIGNAL_CONNECT(text_view_lost_focus);
	ret |= SIGNAL_CONNECT(text_view_service);
	ret |= SIGNAL_CONNECT(top);
 
	return ret;
}
