#include "version_autogenerated.h"
#include "chip_info.h"

int aout_spdif_powercfg(void)
{
#if defined(CONFIG_ARCH_ARM_CANOPUS)
	volatile unsigned int *spdif_reg = (volatile unsigned int *)0x89400448;
	unsigned int vpcfg = 0x2;
	unsigned int nmask = 0x3; //2bit: 00:6.6mA, 01:13.3mA, 10:19.9mA 11:26.5mA
	unsigned int noffs =  28; //12-13 bit

	*(volatile unsigned int *)spdif_reg &= ~(nmask << noffs);
	*(volatile unsigned int *)spdif_reg |=  (vpcfg << noffs);
#elif defined(CONFIG_ARCH_ARM_VEGA)
	unsigned int vpcfg = 0x2;
#ifdef CONFIG_QFN88
	volatile unsigned int *spdif_reg = (volatile unsigned int *)0x89D00058;
	unsigned int nmask = 0x3; //2bit: 000:6.6mA, 01:13.3mA, 10:19.9mA 11:26.5mA
	unsigned int noffs =  20; //20-21 bit
#else
	volatile unsigned int *spdif_reg = (volatile unsigned int *)0x89D00048;
	unsigned int nmask = 0x3; //2bit: 000:6.6mA, 01:13.3mA, 10:19.9mA 11:26.5mA
	unsigned int noffs =  28; //28-29 bit
#endif

	*(volatile unsigned int *)spdif_reg &= ~(nmask << noffs);
	*(volatile unsigned int *)spdif_reg |=  (vpcfg << noffs);
#elif defined(CONFIG_ARCH_CKMMU_SCORPIO)
	unsigned int vpcfg = 0x3;
	volatile unsigned int *spdif_reg = (volatile unsigned int *)0xA030A418;
	unsigned int nmask = 0x3; //2bit: 000:6.6mA, 01:13.3mA, 10:19.9mA 11:26.5mA
	unsigned int noffs =  12; //12-13 bit

	*(volatile unsigned int *)spdif_reg &= ~(nmask << noffs);
	*(volatile unsigned int *)spdif_reg |=  (vpcfg << noffs);
#elif defined(CONFIG_ARCH_CKMMU_SCORPIO_TAURUS)
	unsigned int vpcfg = 0x3;
	volatile unsigned int *spdif_reg = (volatile unsigned int *)0xA030A418;
	unsigned int nmask = 0x3; //2bit: 000:6.6mA, 01:13.3mA, 10:19.9mA 11:26.5mA
	unsigned int noffs =  12; //12-13 bit

	if (gxcore_chip_probe() == 0x3113) {
		*(volatile unsigned int *)spdif_reg &= ~(nmask << noffs);
		*(volatile unsigned int *)spdif_reg |=  (vpcfg << noffs);
	}
#else
	printf("chip spdif powercfg not config\n");
#endif
}
