#include "interrupt.h"
#include "time.h"
#include "stdio.h"
#include "string.h"
#include "linux/errno.h"
#include "gx_mtc_core.h"
#include "cpu/cpu.h"
#include "version_autogenerated.h"
#include "gx_mtc.h"

static volatile MTC_Regs_t *p_mtc_reg = (volatile MTC_Regs_t *)0xa0fc0000;	//to do
static int nds_wait_flag = 0;

#define KEY_ORDER_CHANGE
#ifdef KEY_ORDER_CHANGE
static unsigned int swap32(unsigned int x)
{
	unsigned int r = 0;

	r |= (x>>24)&0xFF;
	r |= ((x>>16)&0xFF)<<8;
	r |= ((x>>8)&0xFF)<<16;
	r |= ((x)&0xFF)<<24;

	return r;
}
#else
#define swap32(x) ((unsigned int)(x))
#endif

static int gx_mtc_set_key(struct mtc_data_s *mp)
{
	int *p_key;
	int key_len;
	enum mtc_algorithm algo;

	p_key = (int *)mp->mtc_key.key_value;
	key_len = mp->mtc_key.key_len;
	algo = mp->algorithm;

	switch (algo) {
	case GXMTC_DES:
	case GXMTC_3DES:
		{
			switch (key_len) {
			case 8:
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[0]));
				break;
			case 16:
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[0]));
				MTC_SET_KEY_95_64(p_mtc_reg, swap32(p_key[3]));
				MTC_SET_KEY_127_96(p_mtc_reg, swap32(p_key[2]));
				break;
			case 24:
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[0]));
				MTC_SET_KEY_95_64(p_mtc_reg, swap32(p_key[3]));
				MTC_SET_KEY_127_96(p_mtc_reg, swap32(p_key[2]));
				MTC_SET_KEY_159_128(p_mtc_reg, swap32(p_key[5]));
				MTC_SET_KEY_191_160(p_mtc_reg, swap32(p_key[4]));
				break;
			case 32:
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[0]));
				MTC_SET_KEY_95_64(p_mtc_reg, swap32(p_key[3]));
				MTC_SET_KEY_127_96(p_mtc_reg, swap32(p_key[2]));
				MTC_SET_KEY_159_128(p_mtc_reg, swap32(p_key[5]));
				MTC_SET_KEY_191_160(p_mtc_reg, swap32(p_key[4]));
				MTC_SET_KEY_223_192(p_mtc_reg, swap32(p_key[7]));
				MTC_SET_KEY_255_224(p_mtc_reg, swap32(p_key[6]));
				break;
			default:
				break;
			}
		}
		break;
	case GXMTC_AES128:
	case GXMTC_AES192:
	case GXMTC_AES256:
		{
			switch (key_len) {
			case 16:
				MTC_SET_KEY_127_96(p_mtc_reg, swap32(p_key[0]));
				MTC_SET_KEY_95_64(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[2]));
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[3]));
				break;
			case 24:
				MTC_SET_KEY_191_160(p_mtc_reg, swap32(p_key[0]));
				MTC_SET_KEY_159_128(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_127_96(p_mtc_reg, swap32(p_key[2]));
				MTC_SET_KEY_95_64(p_mtc_reg, swap32(p_key[3]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[4]));
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[5]));
				break;
			case 32:
				MTC_SET_KEY_255_224(p_mtc_reg, swap32(p_key[0]));
				MTC_SET_KEY_223_192(p_mtc_reg, swap32(p_key[1]));
				MTC_SET_KEY_191_160(p_mtc_reg, swap32(p_key[2]));
				MTC_SET_KEY_159_128(p_mtc_reg, swap32(p_key[3]));
				MTC_SET_KEY_127_96(p_mtc_reg, swap32(p_key[4]));
				MTC_SET_KEY_95_64(p_mtc_reg, swap32(p_key[5]));
				MTC_SET_KEY_63_32(p_mtc_reg, swap32(p_key[6]));
				MTC_SET_KEY_31_0(p_mtc_reg, swap32(p_key[7]));
				break;
			default :
				break;
			}
		}
		break;
	default :
		break;
	}

	MTC_SET_KEY_READY(p_mtc_reg);
	return 0;
}

static int gx_mtc_set_mode(enum mtc_algorithm algorithm, enum mtc_sub_mode sub_mode)
{
	switch (algorithm) {
	case GXMTC_DES :
		break;
	case GXMTC_3DES:
		MTC_SET_ALGO_DES_3DES(p_mtc_reg);
		break;
	case GXMTC_AES128:
		MTC_SET_ALGO_AES128(p_mtc_reg);
		break;
	case GXMTC_AES192:
		MTC_SET_ALGO_AES192(p_mtc_reg);
		break;
	case GXMTC_AES256:
		MTC_SET_ALGO_AES256(p_mtc_reg);
		break;
	case GXMTC_MULTI2:
		MTC_SET_ALGO_MULTI2(p_mtc_reg);
		break;
	case GXMTC_SMS4:
		MTC_SET_ALGO_SMS4(p_mtc_reg);
		break;
	default:
		return -1;
	}

	if (sub_mode > GXMTC_CTR)
		return -1;
	else
		MTC_SET_SUB_MODE(p_mtc_reg, sub_mode);

	return 0;
}

static int gx_mtc_set_buf(unsigned int src_buf_addr, int src_buf_len, unsigned int dst_buf_addr)
{
	MTC_SET_READ_BUF_ADDR(p_mtc_reg, src_buf_addr);
	MTC_SET_READ_BUF_LEN(p_mtc_reg, src_buf_len);
	MTC_SET_WRITE_BUF_ADDR(p_mtc_reg, dst_buf_addr);
	return 0;
}

static int gx_mtc_finish_operate(void)
{
	MTC_CLR_CTRL1(p_mtc_reg);
	MTC_CLR_CTRL2(p_mtc_reg);
	MTC_ALL_INT_DISABLE(p_mtc_reg);
	MTC_CLR_ALL_INT_STATUS(p_mtc_reg);
	MTC_CLR_CA_MODE_REG(p_mtc_reg);
	MTC_CLR_CW_SELECT_REG(p_mtc_reg);
	MTC_NDS_KEY_GEN_CLR(p_mtc_reg);
	MTC_NDS_CONTROL_SET_CLR(p_mtc_reg);
	return 0;
}

static int gx_mtc_set_core_ready(enum mtc_algorithm algorithm)
{
	switch (algorithm) {
	case GXMTC_DES:
	case GXMTC_3DES:
		MTC_SET_DES_READY(p_mtc_reg);
		break;
	case GXMTC_AES128:
	case GXMTC_AES192:
	case GXMTC_AES256:
		MTC_SET_AES_READY(p_mtc_reg);
		break;
	case GXMTC_MULTI2:
		MTC_SET_MULTI2_READY(p_mtc_reg);
		break;
	case GXMTC_SMS4:
		MTC_SET_SMS4_READY(p_mtc_reg);
		break;
	default :
		return -1;
	}

	return 0;
}

static int gx_mtc_set_iv(struct mtc_data_s *mtc_data)
{
	int *iv = (int *)mtc_data->mtc_iv.iv_value;
	int iv_len = mtc_data->mtc_iv.iv_len;
	enum mtc_sub_mode sub_mode = mtc_data->sub_mode;
	enum mtc_algorithm algo = mtc_data->algorithm;

	if (sub_mode == GXMTC_CBC || sub_mode == GXMTC_OFB || sub_mode == GXMTC_CFB) {
		switch (algo) {
		case GXMTC_DES:
		case GXMTC_3DES:
			{
				switch (iv_len) {
				case 8:
					p_mtc_reg->MTC_IV0 = swap32(iv[1]);
					p_mtc_reg->MTC_IV1 = swap32(iv[0]);
					break;
				case 16:
					p_mtc_reg->MTC_IV0 = swap32(iv[1]);
					p_mtc_reg->MTC_IV1 = swap32(iv[0]);
					p_mtc_reg->MTC_IV2 = swap32(iv[3]);
					p_mtc_reg->MTC_IV3 = swap32(iv[2]);
					break;
				default :
					MTC_DBG ("iv size not right\n");
					return -1;
				}
			}
			break;
		case GXMTC_AES128:
		case GXMTC_AES192:
		case GXMTC_AES256:
			{
				switch (iv_len) {
				case 8:
					p_mtc_reg->MTC_IV0 = swap32(iv[1]);
					p_mtc_reg->MTC_IV1 = swap32(iv[0]);
					break;
				case 16:
					p_mtc_reg->MTC_IV0 = swap32(iv[3]);
					p_mtc_reg->MTC_IV1 = swap32(iv[2]);
					p_mtc_reg->MTC_IV2 = swap32(iv[1]);
					p_mtc_reg->MTC_IV3 = swap32(iv[0]);
					break;
				default :
					MTC_DBG ("iv size not right\n");
					return -1;
				}
			}
			break;
		default :
			break;
		}
	}

	return 0;
}

static int gx_mtc_set_ca_data(unsigned int base_addr, unsigned char *buf, int size)
{

	switch (size) {
	case 8:
		MTC_SET_CA_DATA_4(base_addr, (buf[3] | (buf[2] << 8) | (buf[1] << 16) | (buf[0] << 24)));
		MTC_SET_CA_DATA_5(base_addr, (buf[7] | (buf[6] << 8) | (buf[5] << 16) | (buf[4] << 24)));
		break;
	case 16:
		MTC_SET_CA_DATA_2(base_addr, ( buf[3] |  (buf[2] << 8) |  (buf[1] << 16) |  (buf[0] << 24)));
		MTC_SET_CA_DATA_3(base_addr, ( buf[7] |  (buf[6] << 8) |  (buf[5] << 16) |  (buf[4] << 24)));
		MTC_SET_CA_DATA_4(base_addr, (buf[11] | (buf[10] << 8) |  (buf[9] << 16) |  (buf[8] << 24)));
		MTC_SET_CA_DATA_5(base_addr, (buf[15] | (buf[14] << 8) | (buf[13] << 16) | (buf[12] << 24)));
		break;
	case 24:
		MTC_SET_CA_DATA_0(base_addr, ( buf[3] |  (buf[2] << 8) |  (buf[1] << 16) |  (buf[0] << 24)));
		MTC_SET_CA_DATA_1(base_addr, ( buf[7] |  (buf[6] << 8) |  (buf[5] << 16) |  (buf[4] << 24)));
		MTC_SET_CA_DATA_2(base_addr, (buf[11] | (buf[10] << 8) |  (buf[9] << 16) |  (buf[8] << 24)));
		MTC_SET_CA_DATA_3(base_addr, (buf[15] | (buf[14] << 8) | (buf[13] << 16) | (buf[12] << 24)));
		MTC_SET_CA_DATA_4(base_addr, (buf[19] | (buf[18] << 8) | (buf[17] << 16) | (buf[16] << 24)));
		MTC_SET_CA_DATA_5(base_addr, (buf[23] | (buf[22] << 8) | (buf[21] << 16) | (buf[20] << 24)));
		break;
	default:
		return -1;
	}

	return 0;
}

//set dsk/dck/dcw/vcw/mcw dcw字节序规则奇+偶
//1 : dcw
//2 : dck / dcw
//3 : dsk / dck / dcw
//4 : dsk / dck / dcw / vcw
//5 : dsk / dck / dcw / vcw / mcw
static int gx_mtc_set_round_and_data(struct mtc_input_s *input)
{

	switch (input->num) {
	case 1:
		MTC_SET_ONE_ROUND(p_mtc_reg);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCW_5, input->buf[0], input->size[0]);
		break;
	case 2:
		MTC_SET_TWO_ROUND(p_mtc_reg);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCK_5, input->buf[0], input->size[0]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCW_5, input->buf[1], input->size[1]);
		break;
	case 3:
		MTC_SET_THREE_ROUND(p_mtc_reg);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DSK_5, input->buf[0], input->size[0]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCK_5, input->buf[1], input->size[1]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCW_5, input->buf[2], input->size[2]);
		break;
	case 4:
		MTC_SET_FOUR_ROUND(p_mtc_reg);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DSK_5, input->buf[0], input->size[0]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCK_5, input->buf[1], input->size[1]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCW_5, input->buf[2], input->size[2]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_VCW_5, input->buf[3], input->size[3]);
		break;
	case 5:
		MTC_SET_FIVE_ROUND(p_mtc_reg);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DSK_5, input->buf[0], input->size[0]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCK_5, input->buf[1], input->size[1]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_DCW_5, input->buf[2], input->size[2]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_VCW_5, input->buf[3], input->size[3]);
		gx_mtc_set_ca_data((unsigned int)&p_mtc_reg->MTC_CA_MCW_5, input->buf[4], input->size[4]);
		break;
	default:
		return -1;
	}

	return 0;
}

static int gx_mtc_set_ca_mode_ready(int round)
{

	switch (round) {
	case 1:
		MTC_SET_ONE_ROUND_READY(p_mtc_reg);
		break;
	case 2:
		MTC_SET_TWO_ROUND_READY(p_mtc_reg);
		break;
	case 3:
		MTC_SET_THREE_ROUND_READY(p_mtc_reg);
		break;
	case 4:
		MTC_SET_FOUR_ROUND_READY(p_mtc_reg);
		break;
	case 5:
		MTC_SET_FIVE_ROUND_READY(p_mtc_reg);
		break;
	default:
		return -1;
	}

	return 0;
}

static int gx_mtc_set_counter(struct mtc_data_s *mtc_data)
{
	if (mtc_data->algorithm != GXMTC_DES && \
			mtc_data->algorithm != GXMTC_3DES)
		return 0;

	if (mtc_data->sub_mode != GXMTC_CTR)
		return 0;

	int *p_counter = (int *)mtc_data->mtc_counter.value;
	int counter_len = mtc_data->mtc_counter.len;
	// below config value need To be confirmed when CTR not right, that is to say the configure below may not right
	switch (counter_len) {
		case 8:
			MTC_SET_COUNTER_63_32(p_mtc_reg, swap32(p_counter[0]));
			MTC_SET_COUNTER_31_0(p_mtc_reg, swap32(p_counter[1]));
			break;
		default:
			break;
	}

	return 0;
}

void reg_info_print(struct mtc_data_s *mtc_data)
{
	MTC_DBG("------ debug info :---------\n");
	MTC_DBG("0x000 %x\n", p_mtc_reg->MTC_CTRL1);
	MTC_DBG("0x004 %x\n", p_mtc_reg->MTC_KEY1_L);
	MTC_DBG("0x008 %x\n", p_mtc_reg->MTC_KEY1_H);
	MTC_DBG("0x00c %x\n", p_mtc_reg->MTC_KEY2_L);
	MTC_DBG("0x010 %x\n", p_mtc_reg->MTC_KEY2_H);
	MTC_DBG("0x014 %x\n", p_mtc_reg->MTC_KEY3_L);
	MTC_DBG("0x018 %x\n", p_mtc_reg->MTC_KEY3_H);
	MTC_DBG("0x02c %x\n", p_mtc_reg->MTC_KEY4_L);
	MTC_DBG("0x030 %x\n", p_mtc_reg->MTC_KEY4_H);
	MTC_DBG("0x01c %x\n", p_mtc_reg->MTCR_SDR_START_ADDR);
	MTC_DBG("0x020 %x\n", p_mtc_reg->MTCW_SDR_START_ADDR);
	MTC_DBG("0x028 %x\n", p_mtc_reg->MTC_CTRL2);
	MTC_DBG("0x044 %x\n", p_mtc_reg->MTC_IV3);
	MTC_DBG("0x048 %x\n", p_mtc_reg->MTC_IV2);
	MTC_DBG("0x04c %x\n", p_mtc_reg->MTC_IV1);
	MTC_DBG("0x050 %x\n", p_mtc_reg->MTC_IV0);
	MTC_DBG("0x160 %x\n", p_mtc_reg->MTC_INT_EN);
	MTC_DBG("0x164 %x\n", p_mtc_reg->MTC_INT);
}

// 因硬件在调用AES加解密时存在出错的情况，所以每次使用前最好重置一下，调用如下接口
// 3211中存在 AES 连续解密出错问题，需 MTC_RST_CONTRL(0X60) 寄存器的第5bit需重置(硬件bug)
static void gx_mtc_core_rst_ctl(struct mtc_data_s *mtc_data)
{
#if defined(CONFIG_ARCH_CKMMU_GX3211)
	volatile int delay = 50;
	enum mtc_algorithm algo = mtc_data->algorithm;

	if (algo == GXMTC_AES128 || algo == GXMTC_AES192 || algo == GXMTC_AES256) {
		MTC_RST_CTL_5_SET(p_mtc_reg);
		while (delay--);
		MTC_RST_CTL_5_CLR(p_mtc_reg);
	}
#endif
}

//3211 等硬件中对于数据源地址目的地址对其有要求(64字节对齐硬件bug)，而传入数据长度检测不是bug
static int check_alignment(struct mtc_data_s *mtc_data)
{
	int i;

#if defined(CONFIG_ARCH_CKMMU_GX3211) || defined(CONFIG_ARCH_CKMMU_GX6605S)
	unsigned int addr_check;

	for (i = 0; i < mtc_data->input.num; i++) {
		addr_check = (int)mtc_data->input.buf[i];
		if (addr_check % 64 != 0)
			return -EIO;
	}
	addr_check = (int)mtc_data->output.buf;
	if (addr_check % 64 != 0)
		return -EIO;
#endif

	switch (mtc_data->algorithm) {
		case GXMTC_DES:
		case GXMTC_3DES:
			{
				for (i = 0; i < mtc_data->input.num; i++)
					if (mtc_data->input.size[i] % 8 != 0)
						return -EIO;
			}
			break;
		case GXMTC_AES128:
		case GXMTC_AES192:
		case GXMTC_AES256:
			{
				for (i = 0; i < mtc_data->input.num; i++)
					if (mtc_data->input.size[i] % 16 != 0)
						return -EIO;
			}
			break;
		default :
			break;
	}

	return 0;
}

static void gx_mtc_nds_key_write_done(void)
{
	while (!MTC_NDS_KEY_WRITE_DONE_STATUS(p_mtc_reg));
}

int gx_mtc_nds_key_generate(struct mtc_data_s *mtc_data)
{
	int addr = *(int *)mtc_data->mtc_key.key_value;

	if (nds_wait_flag) {
		gx_mtc_nds_key_write_done();
		nds_wait_flag = 0;
	}

	if (MTC_READ_NDS_KEY_FULL(p_mtc_reg))
		MTC_CLR_NDS_KEY_FULL(p_mtc_reg);
	MTC_NDS_UPDATE_KEY_CLR(p_mtc_reg);
	MTC_NDS_KEY_ADDR_CLR(p_mtc_reg);
	MTC_NDS_KEY_ADDR_WRITE(p_mtc_reg, addr);
	MTC_NDS_UPDATE_KEY_SET(p_mtc_reg);

	nds_wait_flag = 1;
	return 0;
}

static int gx_mtc_nds_tool_config_algo(struct mtc_data_s *mtc_data)
{
	switch (mtc_data->algorithm) {
	case GXMTC_DES:
		MTC_NDS_CONTROL_CONFIG_ALGO(p_mtc_reg, 2);
		break;
	case GXMTC_3DES:
		MTC_NDS_CONTROL_CONFIG_ALGO(p_mtc_reg, 1);
		break;
	case GXMTC_AES128:
	case GXMTC_AES192:
	case GXMTC_AES256:
		MTC_NDS_CONTROL_CONFIG_ALGO(p_mtc_reg, 0);
		break;
	case GXMTC_MULTI2:
	case GXMTC_SMS4:
		MTC_DBG("nds decrypt or encrypt not support this algorithm --%d\n", mtc_data->algorithm);
		return -1;
	default :
		MTC_NDS_CONTROL_CONFIG_ALGO(p_mtc_reg, 0);
		break;
	}

	return 0;
}

static int gx_mtc_nds_tool_config_submode(struct mtc_data_s *mtc_data)
{
	switch (mtc_data->sub_mode) {
	case GXMTC_ECB:
		MTC_NDS_CONTROL_CONFIG_SUBMODE(p_mtc_reg, 0);
		break;
	case GXMTC_CBC:
		MTC_NDS_CONTROL_CONFIG_SUBMODE(p_mtc_reg, 1);
		break;
	case GXMTC_CTR:
		MTC_NDS_CONTROL_CONFIG_SUBMODE(p_mtc_reg, 2);
		break;
	case GXMTC_CFB:
	case GXMTC_OFB:
		MTC_DBG("nds decrypt or encrypt not support this sub mode --%d\n", mtc_data->sub_mode);
		return -1;
	default :
		MTC_NDS_CONTROL_CONFIG_SUBMODE(p_mtc_reg, 0);
		break;
	}

	return 0;
}

static int gx_mtc_nds_tool_config_residue_msg(struct mtc_data_s *mtc_data)
{
	switch (mtc_data->res_msg) {
	case MTC_RES_CLEAR:
		MTC_NDS_CONTROL_CONFIG_RESIDE(p_mtc_reg, 0);
		break;
	case MTC_RES_CTS:
		MTC_NDS_CONTROL_CONFIG_RESIDE(p_mtc_reg, 1);
		break;
	case MTC_RES_RBT:
		MTC_NDS_CONTROL_CONFIG_RESIDE(p_mtc_reg, 2);
		break;
	default :
		MTC_NDS_CONTROL_CONFIG_RESIDE(p_mtc_reg, 0);
		break;
	}

	return 0;
}

static int gx_mtc_nds_tool_config_short_msg(struct mtc_data_s *mtc_data)
{
	switch (mtc_data->sht_msg) {
		case MTC_SHO_CLEAR:
			MTC_NDS_CONTROL_CONFIG_SHORT(p_mtc_reg, 0);
			break;
		case MTC_SHO_IV:
			MTC_NDS_CONTROL_CONFIG_SHORT(p_mtc_reg, 1);
			break;
		case MTC_SHO_IV2:
			MTC_NDS_CONTROL_CONFIG_SHORT(p_mtc_reg, 2);
			break;
		default:
			MTC_NDS_CONTROL_CONFIG_SHORT(p_mtc_reg, 0);
			break;
	}

	return 0;
}

enum interrupt_return mtc_interrupt_isr(unsigned int vector, void *pdata)
{
	gx_mask_interrupt(vector);
	gx_mtc_extra *extra = (gx_mtc_extra *)pdata;

	extra->result = MTC_ALL_INT_STATUS_GET(p_mtc_reg);
	extra->sync_flag = 1;
	MTC_CLR_ALL_INT_STATUS(p_mtc_reg);

	gx_unmask_interrupt(vector);
	return HANDLED;
}

static int flag_timed_wait(uint32_t timeout)
{
	uint32_t start = 0;
	uint32_t end = 0;
	gx_mtc_extra *extra = &mtc_extra;

	start = gx_time_get_ms();
	do {
		if (extra->sync_flag) {
			extra->sync_flag = 0;
			return 1;
		}
		end = gx_time_get_ms();
	} while((end - start) < timeout);

	return 0;
}

static void gx_mtc_wait_finish(struct mtc_data_s *mtc_data)
{
	gx_mtc_extra *extra = &mtc_extra;
	uint32_t start = 0;
	uint32_t end = 0;
	uint32_t ret = GXMTC_DEFAULT_STATUS;

	extra->result = GXMTC_NOERR;
	if (mtc_data->wait_mode == GXMTC_QUERY_MODE) {
		start = gx_time_get_ms();
		do {
			ret = MTC_ALL_INT_STATUS_GET(p_mtc_reg);
			if (ret)
				break;
			end = gx_time_get_ms();
		} while ((end - start) < MTC_WAIT_TIMEOUT_MS);

		if (!ret) {
			extra->result = GXMTC_TIMEOUT;
			MTC_DBG("mtc time out , in  %s %d \n", __FILE__, __LINE__);
			return ;
		}
	} else {
		ret = flag_timed_wait(MTC_WAIT_TIMEOUT_MS);
		if (ret == 0) {
			extra->result = GXMTC_TIMEOUT;
			MTC_DBG("mtc time out , in  %s %d \n", __FILE__, __LINE__);
			return ;
		}
		ret = extra->result;
		extra->result = GXMTC_NOERR;
	}

	// 优先判断错误
	if (ret & GXMTC_NDS_OPERATE_ERROR) {
		extra->result = GXMTC_ERROR;
		MTC_DBG("mtc nds operate error\n");
		return ;
	} else if (ret & GXMTC_M2MKEY_RW_SPACE_ERROR) {
		extra->result = GXMTC_ERROR;
		MTC_DBG("mtc m2mkey read or write space error\n");
		return ;
	} else if (ret & GXMTC_MEMORY_KEY_RD_SPACE_ERROR) {
		extra->result = GXMTC_ERROR;
		MTC_DBG("mtc memory key read space error\n");
		return ;
	} else if (ret & GXMTC_DATA_FINISH) {
		return ;
	} else if (ret & GXMTC_K3_FINISH) {
		return ;
	} else if (ret & GXMTC_AES_ROUND_FINISH) {
		return ;
	} else if (ret & GXMTC_TDES_ROUND_FINISH) {
		return ;
	} else if (ret & GXMTC_MEMORY_KEY_RD_FINISH) {
		return ;
	}

	extra->result = GXMTC_ERROR;
	return ;
}
static void gx_mtc_int_ctl(struct mtc_data_s *mtc_data)
{
	if (mtc_data->wait_mode == GXMTC_QUERY_MODE)
		MTC_ALL_INT_DISABLE(p_mtc_reg);
	else
		MTC_ALL_INT_ENABLE(p_mtc_reg);
}

static int gx_mtc_get_max_buf_len(void)
{
#if defined(CONFIG_ARCH_CKMMU_GX3211) || defined(CONFIG_ARCH_CKMMU_GX6605S)
	// 3211 & 6605s need 64 Bytes align
	return (MTC_MAX_BUF_LEN / 64) * 64;
#else
	return -1;
#endif
}

static int gx_mtc_core_nds_en_or_decrypt(struct mtc_data_s *mtc_data, int is_encrypt, struct mtc_input_s  *ip,
		struct mtc_output_s *op)
{
	gx_mtc_extra *extra = &mtc_extra;
	int key_index;

	gx_mtc_core_rst_ctl(mtc_data);

	if (nds_wait_flag) {
		gx_mtc_nds_key_write_done();
		nds_wait_flag = 0;
	}

	key_index = *(int *)mtc_data->mtc_key.key_value;
	gx_mtc_int_ctl(mtc_data);
	MTC_NDS_CONTROL_UNITWRITE_CLR(p_mtc_reg);

	if (is_encrypt)
		MTC_NDS_CONTROL_SET_ENCRYPT(p_mtc_reg);
	else
		MTC_NDS_CONTROL_SET_DECRYPT(p_mtc_reg);

	if (gx_mtc_nds_tool_config_algo(mtc_data) != 0)
		return -EIO;
	if (gx_mtc_nds_tool_config_submode(mtc_data) != 0)
		return -EIO;
	if (gx_mtc_nds_tool_config_residue_msg(mtc_data) != 0)
		return -EIO;
	if (gx_mtc_nds_tool_config_short_msg(mtc_data) != 0)
		return -EIO;
	MTC_NDS_CONTROL_UNITWRITE_ADDR_SET(p_mtc_reg, key_index);
	MTC_NDS_CONTROL_UNITWRITE_SET(p_mtc_reg);

	MTC_NDS_KEY_TABLE_SELECT_CLR(p_mtc_reg);
	MTC_NDS_KEY_TABLE_SELECT(p_mtc_reg, key_index);
	MTC_NDS_KEY_TABLE_SELECT_SET(p_mtc_reg);

	gx_mtc_set_counter(mtc_data);
	gx_mtc_set_iv(mtc_data);
	MTC_SET_KEY_SELECT(p_mtc_reg, 2);                    // nds key
	gx_mtc_set_buf((unsigned int)ip->buf[0], ip->size[0], (unsigned int)op->buf);
	MTC_SET_KEY_READY(p_mtc_reg);
	MTC_SET_NDS_READY(p_mtc_reg);
	dcache_flush();
	gx_mtc_wait_finish(mtc_data);
	gx_mtc_finish_operate();
	dcache_flush();

	HANDLE_ERROR(extra->result);
}

static int gx_mtc_core_data_en_or_decrypt(struct mtc_data_s *mtc_data, int is_encrypt, struct mtc_input_s *ip,
		struct mtc_output_s *op)
{
	gx_mtc_extra *extra = &mtc_extra;

	gx_mtc_core_rst_ctl(mtc_data);
	gx_mtc_int_ctl(mtc_data);
	if (is_encrypt)
		MTC_SET_ENCRYPT(p_mtc_reg);
	else
		MTC_SET_DECRYPT(p_mtc_reg);
	MTC_SET_KEY_SELECT(p_mtc_reg, KEY_SELECT_KEY_IPBUS_SET);
	gx_mtc_set_mode(mtc_data->algorithm, mtc_data->sub_mode);
	gx_mtc_set_counter(mtc_data);
	gx_mtc_set_iv(mtc_data);
	gx_mtc_set_key(mtc_data);
	gx_mtc_set_buf((unsigned int)ip->buf[0], ip->size[0], (unsigned int)op->buf);
	dcache_flush();
	gx_mtc_set_core_ready(mtc_data->algorithm);
	gx_mtc_wait_finish(mtc_data);
	gx_mtc_finish_operate();
	dcache_flush();

	HANDLE_ERROR(extra->result);
}

static int gx_mtc_core_otp_en_or_decrypt(struct mtc_data_s *mtc_data, int is_encrypt, struct mtc_input_s *ip,
		struct mtc_output_s *op)
{
	gx_mtc_extra *extra = &mtc_extra;

	gx_mtc_core_rst_ctl(mtc_data);
	gx_mtc_int_ctl(mtc_data);
	if (is_encrypt)
		MTC_SET_ENCRYPT(p_mtc_reg);
	else
		MTC_SET_DECRYPT(p_mtc_reg);
	MTC_SET_KEY_SELECT(p_mtc_reg, KEY_SELECT_FROM_OTP);
	gx_mtc_set_mode(mtc_data->algorithm, mtc_data->sub_mode);
	gx_mtc_set_counter(mtc_data);
	gx_mtc_set_iv(mtc_data);
	MTC_SET_KEY_READY(p_mtc_reg);
	gx_mtc_set_buf((unsigned int)ip->buf[0], ip->size[0], (unsigned int)op->buf);
	dcache_flush();
	gx_mtc_set_core_ready(mtc_data->algorithm);
	gx_mtc_wait_finish(mtc_data);
	gx_mtc_finish_operate();
	dcache_flush();

	HANDLE_ERROR(extra->result);
}

static int gx_mtc_core_encrypt_or_decrypt(struct mtc_data_s *mtc_data, int is_encrypt, enum mtc_key_from from)
{
	int max_size_each_time, total_size, offset;
	struct mtc_input_s ip;
	struct mtc_output_s op;
	int ret = -1;

	ret = check_alignment(mtc_data);
	if (ret != 0)
		return ret;

	offset = 0;
	total_size = mtc_data->input.size[0];
	max_size_each_time = gx_mtc_get_max_buf_len();

	while (total_size > 0) {
		ip.size[0] = total_size < max_size_each_time ? total_size : max_size_each_time;
		ip.buf[0]  = mtc_data->input.buf[0] + offset;
		op.buf     = mtc_data->output.buf   + offset;

		if (from == GXMTC_KEY_FROM_SOFT)
			ret = gx_mtc_core_data_en_or_decrypt(mtc_data, is_encrypt, &ip, &op);
		else if (from == GXMTC_KEY_FROM_NDS)
			ret = gx_mtc_core_nds_en_or_decrypt(mtc_data, is_encrypt, &ip, &op);
		else if (from == GXMTC_KEY_FROM_OTP)
			ret = gx_mtc_core_otp_en_or_decrypt(mtc_data, is_encrypt, &ip, &op);
		else
			ret = -1;

		if (ret != 0)
			break;

		total_size -= ip.size[0];
		offset     += ip.size[0];
	}

	return ret;
}

static int gx_mtc_set_ca_addr(struct mtc_data_s *mtc_data)
{
	enum mtc_cw_odd_even cw_odd_even;
	int addr = *(int *)mtc_data->output.buf;
	cw_odd_even = mtc_data->odd_even;

#if defined(CONFIG_ARCH_CKMMU_GX3211)
	if (cw_odd_even == GXMTC_CW_ODD_FIRST)
		MTC_SET_CA_ADDR_3211_ODD_FIRST(p_mtc_reg, addr);
	else
		MTC_SET_CA_ADDR_3211_EVEN_FIRST(p_mtc_reg, addr);
#elif defined(CONFIG_ARCH_CKMMU_GX6605S)
	if (mtc_data->desc_type == GXMTC_DESC_TYPE_CAS2) {
		if (cw_odd_even == GXMTC_CW_ODD_FIRST)
			MTC_SET_CA_ADDR_6605S_CAS2_ODD_FIRST(p_mtc_reg, addr);
		else
			MTC_SET_CA_ADDR_6605S_CAS2_EVEN_FIRST(p_mtc_reg, addr);
	} else if (mtc_data->desc_type == GXMTC_DESC_TYPE_DES) {
		if (cw_odd_even == GXMTC_CW_ODD_FIRST)
			MTC_SET_CA_ADDR_6605S_DES_ODD_FIRST(p_mtc_reg, addr);
		else
			MTC_SET_CA_ADDR_6605S_DES_EVEN_FIRST(p_mtc_reg, addr);
	}
#endif
	return 0;
}

int gx_mtc_core_data_decrypt(struct mtc_data_s *mtc_data)
{
	return gx_mtc_core_encrypt_or_decrypt(mtc_data, DO_DECRYPT, GXMTC_KEY_FROM_SOFT);
}

int gx_mtc_core_data_encrypt(struct mtc_data_s *mtc_data)
{
	return gx_mtc_core_encrypt_or_decrypt(mtc_data, DO_ENCRYPT, GXMTC_KEY_FROM_SOFT);
}

int gx_mtc_core_otp_decrypt(struct mtc_data_s *mtc_data)
{
	return gx_mtc_core_encrypt_or_decrypt(mtc_data, DO_DECRYPT, GXMTC_KEY_FROM_OTP);
}

int gx_mtc_core_otp_encrypt(struct mtc_data_s *mtc_data)
{
	return gx_mtc_core_encrypt_or_decrypt(mtc_data, DO_ENCRYPT, GXMTC_KEY_FROM_OTP);
}

int gx_mtc_core_nds_decrypt(struct mtc_data_s *mtc_data)
{
	return gx_mtc_core_encrypt_or_decrypt(mtc_data, DO_DECRYPT, GXMTC_KEY_FROM_NDS);
}

int gx_mtc_core_nds_encrypt(struct mtc_data_s *mtc_data)
{
	return gx_mtc_core_encrypt_or_decrypt(mtc_data, DO_ENCRYPT, GXMTC_KEY_FROM_NDS);
}

int gx_mtc_core_cw_decrypt(struct mtc_data_s *mtc_data)
{
	gx_mtc_extra *extra = &mtc_extra;

	gx_mtc_int_ctl(mtc_data);
	MTC_SET_DECRYPT(p_mtc_reg);
	MTC_SET_CA_MODE(p_mtc_reg);
	MTC_SET_KEY_SELECT(p_mtc_reg, KEY_SELECT_CDCAS_KEY_AES_CP);
	gx_mtc_set_mode(mtc_data->algorithm, mtc_data->sub_mode);
	gx_mtc_set_iv(mtc_data);
	gx_mtc_set_round_and_data(&mtc_data->input);
	gx_mtc_set_ca_addr(mtc_data);
	dcache_flush();
	MTC_SET_KEY_READY(p_mtc_reg);
	gx_mtc_set_core_ready(mtc_data->algorithm);
	gx_mtc_set_ca_mode_ready(mtc_data->input.num);
	MTC_SET_CW_ENABLE(p_mtc_reg);
	gx_mtc_wait_finish(mtc_data);
	gx_mtc_finish_operate();
	dcache_flush();

	HANDLE_ERROR(extra->result);
}
