#include "version_autogenerated.h"
#include "cpu_config.h"
#include "databahn.h"

/* denali_config.c / h5tq2g63bfr_h9.c */
extern unsigned int DENALI_CONFIG_CTL[159];
extern unsigned int DENALI_CONFIG_PHY[31];
#ifdef DDR_SEC_PAR_INCLUDE
extern unsigned int DENALI_CONFIG_CTL_2[159];
extern unsigned int DENALI_CONFIG_PHY_2[31];
#endif
#ifdef DDR_THR_PAR_INCLUDE
extern unsigned int DENALI_CONFIG_CTL_3[159];
extern unsigned int DENALI_CONFIG_PHY_3[31];
#endif
extern void ddr_config_patch(void);
extern void serial_put_no_mmu(char);
extern unsigned char otp_read_simple(unsigned int address);

static void Databahn_Init(void);
static void Databahn_SetParameters(struct reg_param *regs, int count);
static unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width);
static unsigned int Databahn_GetIntStatus(void);
static unsigned int Databahn_isReady(void);
static void Databahn_Config(void);

#define DATABAHN_REG_FULL(i, name, addr, offset, width, v) \
	{DATABAHN_REG_AXI##i##name##addr,  DATABAHN_REG_AXI##i##name##offset,  DATABAHN_REG_AXI##i##name##width, v}

#define DATABAHN_REG(i, name, v) \
	DATABAHN_REG_FULL(i, name, _ADDR, _OFFSET, _WIDTH, v)

static struct reg_param param_table[] = {
	// Lvl
	{DATABAHN_REG_WRLVL_REG_EN_ADDR, DATABAHN_REG_WRLVL_REG_EN_OFFSET, DATABAHN_REG_WRLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_REG_EN_ADDR, DATABAHN_REG_RDLVL_REG_EN_OFFSET, DATABAHN_REG_RDLVL_REG_EN_WIDTH, 1},
	{DATABAHN_REG_RDLVL_GATE_EN_ADDR, DATABAHN_REG_RDLVL_GATE_EN_OFFSET, DATABAHN_REG_RDLVL_GATE_EN_WIDTH, 1},

	DATABAHN_REG(0 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(1 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(2 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(3 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),
	DATABAHN_REG(4 , _EN_SIZE_LT_WIDTH_INSTR, 0xffff),

	DATABAHN_REG(0 , _R_PRIORITY, 0x5),  // gp/gse/jpeg/vpu
	DATABAHN_REG(1 , _R_PRIORITY, 0x7),  // apu/filter/ga/gc300/pp/usb
	DATABAHN_REG(2 , _R_PRIORITY, 0x6),  // audio/gmac/nfc/vedio_decoder
	DATABAHN_REG(3 , _R_PRIORITY, 0x7),  // cortexA7/rcc/secure_hash
	DATABAHN_REG(4 , _R_PRIORITY, 0x6),  // sdio/spi/demux/secure_m2m

	DATABAHN_REG(0 , _W_PRIORITY, 0x5),
	DATABAHN_REG(1 , _W_PRIORITY, 0x7),
	DATABAHN_REG(2 , _W_PRIORITY, 0x6),
	DATABAHN_REG(3 , _W_PRIORITY, 0x7),
	DATABAHN_REG(4 , _W_PRIORITY, 0x6),

	{DATABAHN_REG_SWAP_EN_ADDR, DATABAHN_REG_SWAP_EN_OFFSET, DATABAHN_REG_SWAP_EN_WIDTH, 0x0},

	// Databahn start enable
	//{DATABAHN_REG_START_ADDR, DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1}
};

/* routine.c */
static void SetRegisterField(unsigned int reg, unsigned int offset, unsigned int width, unsigned int value)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int value_masked;

	original = *(volatile unsigned int *)reg;

	if (width == 32)
		mask = 0xffffffff;
	else
		mask = (1 << width) - 1;
	value_masked = value & mask;
	result = (original & (~(mask << offset))) | (value_masked << offset);

	*(volatile unsigned int *)reg = result;
}

static unsigned int GetRegisterField(unsigned int reg, unsigned int offset, unsigned int width)
{
	unsigned int result;
	unsigned int original;
	unsigned int mask;
	unsigned int mask_shifted;

	original = *(volatile unsigned int *)reg;
	if(width==32)
		mask = 0xffffffff;
	else
		mask = (1 << width)-1;
	mask_shifted = mask << offset;
	result = (original & mask_shifted) >> offset;

	return result;
}

static void Databahn_SetModeRegister6(unsigned int reg)
{
        //MRSINGLE_DATA_0
        SetRegisterField(Databahn_Reg(DATABAHN_REG_MRSINGLE_DATA_0_ADDR), DATABAHN_REG_MRSINGLE_DATA_0_OFFSET, 8, reg);
        //WRITE_MODEREG6
        SetRegisterField(Databahn_Reg(DATABAHN_REG_WRITE_MODEREG_ADDR), DATABAHN_REG_WRITE_MODEREG_OFFSET, DATABAHN_REG_WRITE_MODEREG_WIDTH, 0x02800006);
}

static void Databahn_SetDDR4Vref(void)
{
	/* ROM has init Counter1, so directly invoke stage1_delay_us */
	unsigned char vref_value = 0x08; //只需要vref_value的[5:0]

	//#1: enter vref calibration mode
	Databahn_SetModeRegister6(0x80);
	stage1_delay_us(1); //150ns is enough

	//#2: set vref
	Databahn_SetModeRegister6(0x80|(vref_value & 0x3F));
	stage1_delay_us(1); //150ns is enough

	//#3: quit vref calibration mode
	Databahn_SetModeRegister6(0x0);
	stage1_delay_us(1); //150ns is enough
}

/* databahn.c */
void Databahn_Init(void)
{
	unsigned int i;
	unsigned int ddr_version;
	unsigned int tsel_feed;
	unsigned int data_e_sel;
	unsigned int ocd_pu_clk;
	unsigned int ocd_pd_clk;
	unsigned int ocd_pu_cmd;
	unsigned int ocd_pd_cmd;
	unsigned int dfi_cmd_control;
	unsigned int vref_set;
	unsigned int ddr_vref_en;
	unsigned int cwl;
	unsigned int encry_delay;
	unsigned int ddr_vref_cfg;
	unsigned int phy_ddrp_vref_cfg;
	unsigned int phy_ddrb_vref_cfg;
	unsigned int phy_ddrb_vref_en;
	unsigned int phy_ddrp_vref_en;
#ifdef CHIP_BOARD_6631SHXD
	unsigned char ddr_info = otp_read_simple(0x1B8);
#endif
	unsigned int *p_DENALI_CONFIG_CTL;
	unsigned int *p_DENALI_CONFIG_PHY;

	p_DENALI_CONFIG_CTL = DENALI_CONFIG_CTL;
	p_DENALI_CONFIG_PHY = DENALI_CONFIG_PHY;
#ifdef CHIP_BOARD_6631SHXD
	if ((ddr_info & 0xF) == 0x3) {
		if ((ddr_info & 0xF0) == 0x80) {
			/* DDR3-128 */
			serial_put_no_mmu('1');
			p_DENALI_CONFIG_CTL = DENALI_CONFIG_CTL_2;
			p_DENALI_CONFIG_PHY = DENALI_CONFIG_PHY_2;
		} else {
			/* DDR3-256 */
			serial_put_no_mmu('2');
			p_DENALI_CONFIG_CTL = DENALI_CONFIG_CTL_3;
			p_DENALI_CONFIG_PHY = DENALI_CONFIG_PHY_3;
		}
	} else {
			serial_put_no_mmu('5');
	}
#endif
	//===========clk&rst use sec_config!!!=====================
	/* set ddrc_clk */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_SOURCE_SEC) |= (1<<17);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_CLOCK_GATE_REG_SEC) &= ~((1<<27)|(1<<28));

	/* reset ddrc */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_COLD_RESET_REG_SEC) |= (0x1);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_COLD_RESET_REG_SEC) &= ~(0x1);

	/* set ddrc_ports */
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DENALI_CONFIG0)=0xffffffff;

	//============set dram_config0-7: begin===================
	//clear config0-7
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG4)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG5)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG6)=0x0;
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG7)=0x0;

	//#1: config1[31:29], set ddr_version
#ifdef CONFIG_DDR3
#ifdef DDR_SIP
	ddr_version = 0x2;
#else
	ddr_version = 0x3;
#endif
#elif defined(CONFIG_DDR2)
	ddr_version = 0x1;
#elif defined(CONFIG_DDR4)
	ddr_version = 0x4;
#else
#error "DDR_POS error"
#endif


#ifdef CHIP_BOARD_6631SHXD
	/* set DDR3 */
	if ((ddr_info & 0xF) == 0x3) {
		ddr_version = 0x2;
	}
#endif

	//#2: config0[2:0], tsel_feed
	tsel_feed = 0x1;

	//#3: config0[15], data_e_sel, choose the switch of the receiver in DDRIO
	//data_e_sel=0 means switch is controlled by DRAM_CONFIG0[14:11]
	data_e_sel = 0x0;

	//#4: ocd_pu&ocd_pd
	ocd_pu_clk = 0x8;
	ocd_pd_clk = 0x8;
	ocd_pu_cmd = 0x8;
	ocd_pd_cmd = 0x8;

	//#5: set output driver_strength of DDRIO in board_init.c
	ddr_config_patch();

	//#6: config0[31], dfi_cmd_control
	dfi_cmd_control = 0x1;

	//#7: config2[19:16], set SMIC_DDRIO's Vref
	vref_set = 0x0;

	//#8: config3[1:0], set encry_delay
	cwl = (p_DENALI_CONFIG_CTL[5] >> 16) & 0x1F;
	encry_delay = (cwl - 4) / 2;

	//#9: config7, set reserved vref on decap
	ddr_vref_cfg      = 0;
	phy_ddrp_vref_cfg = 0;
	phy_ddrb_vref_cfg = 0;
	phy_ddrb_vref_en  = 0;
	phy_ddrp_vref_en  = 0;
	ddr_vref_en       = 0;

	//set DRAM_CONFIG
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG0) |= (tsel_feed<<0) | (data_e_sel<<15) | (dfi_cmd_control<<31);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG1) |= (ocd_pu_clk<<3) | (ocd_pd_clk<<7) | (ocd_pu_clk<<14) | (ocd_pd_clk<<18) | (ddr_version<<29);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG2) |= (ocd_pu_cmd<<3) | (ocd_pd_cmd<<7) | (vref_set<<16);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG3) |= (encry_delay<<0);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG4) |= (ocd_pu_clk<<0) | (ocd_pd_clk<<4) | (ocd_pu_clk<<8) | (ocd_pd_clk<<12) | (ocd_pu_clk<<16) | (ocd_pd_clk<<20) | (ocd_pu_clk<<24) | (ocd_pd_clk<<28);
	*(volatile unsigned int*)(CONFIG_BASE+CONFIG_DRAM_CONFIG7) |= (ddr_vref_cfg<<0) | (phy_ddrp_vref_cfg<<8) | (phy_ddrb_vref_cfg<<16) | (phy_ddrb_vref_en<<29) | (phy_ddrp_vref_en<<30) | (ddr_vref_en<<31);
	//============set dram_config0-7: end===========

	for(i = 0;i < sizeof(DENALI_CONFIG_CTL)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg(i) = p_DENALI_CONFIG_CTL[i];

	for(i = 0; i < sizeof(DENALI_CONFIG_PHY)/sizeof(unsigned int); i++)
		*(volatile unsigned int *)Databahn_Reg((i + 256)) = p_DENALI_CONFIG_PHY[i];

	Databahn_Config();

	if (ddr_version == 0x4)
		Databahn_SetDDR4Vref();

	while(!Databahn_isReady());
}

void Databahn_SetParameters(struct reg_param *regs, int count) {
	int i;

	for (i=0; i < count; i++)
		SetRegisterField(Databahn_Reg(regs[i].reg), regs[i].offset, regs[i].width, regs[i].value);
}

#ifdef DDR_SIP
static const struct otp_dram_param param_mode0[] =
{
	/* reg_addr | reg_offset | reg_bit_width | otp_data_byte_index | otp_data_bit_offset */
	/* ds_double */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0,  3,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1, 11,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1,  0,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG3, 16,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG3, 20,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG3, 24,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG3, 28,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0, 16,  3, 0, 5},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG0, 19,  3, 0, 5},
	/* ocd_pu */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4,  0,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4,  8,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4, 16,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4, 24,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1,  3,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1, 14,  4, 1, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG2,  3,  4, 1, 0},
	/* ocd_pd */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4,  4,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4, 12,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4, 20,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG4, 28,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1,  7,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG1, 18,  4, 1, 4},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG2,  7,  4, 1, 4},
	/* mem_ds */
	{Databahn_Reg(28),                 1,  1, 2, 0},
	/* mem_odt */
	{Databahn_Reg(28),                 2,  1, 2, 1},
	{Databahn_Reg(28),                 6,  1, 2, 2},
	{Databahn_Reg(28),                 9,  1, 2, 3},
	/* ctlr_odt */
	{Databahn_Reg(25 + 256),          16,  3, 2, 4},
	{Databahn_Reg(25 + 256),           8,  3, 2, 4},
	{Databahn_Reg(25 + 256),           0,  3, 2, 4},
	/* read_dqs_phase */
	{Databahn_Reg(81),                 0,  8, 3, 0},
	/* write_dq_phase */
	{Databahn_Reg(4 + 256),            8,  8, 4, 0},
	/* rd_low_dq_delay */
	{Databahn_Reg(26 + 256),           0,  3, 5, 0},
	{Databahn_Reg(26 + 256),           4,  3, 5, 0},
	{Databahn_Reg(26 + 256),           8,  3, 5, 0},
	{Databahn_Reg(26 + 256),          12,  3, 5, 0},
	{Databahn_Reg(26 + 256),          16,  3, 5, 0},
	{Databahn_Reg(26 + 256),          20,  3, 5, 0},
	{Databahn_Reg(26 + 256),          24,  3, 5, 0},
	{Databahn_Reg(26 + 256),          28,  3, 5, 0},
	/* rd_high_dq_delay */
	{Databahn_Reg(27 + 256),           0,  3, 5, 3},
	{Databahn_Reg(27 + 256),           4,  3, 5, 3},
	{Databahn_Reg(27 + 256),           8,  3, 5, 3},
	{Databahn_Reg(27 + 256),          12,  3, 5, 3},
	{Databahn_Reg(27 + 256),          16,  3, 5, 3},
	{Databahn_Reg(27 + 256),          20,  3, 5, 3},
	{Databahn_Reg(27 + 256),          24,  3, 5, 3},
	{Databahn_Reg(27 + 256),          28,  3, 5, 3},
	/* dcap_vref_set */
	{CONFIG_BASE+0x208,                0,  2, 5, 6},
	{CONFIG_BASE+0x208,                2,  1, 6, 0},
	/* rd_dly_sel */
	{Databahn_Reg(2 + 256),           19,  3, 6, 1},
	/* decap_ddr_vref_set */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG7, 31,  1, 7, 6},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG7,  0,  6, 7, 0},
	/* decap_phy_vref_set */
	{CONFIG_BASE+CONFIG_DRAM_CONFIG7, 30,  1, 8, 6},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG7,  8,  6, 8, 0},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG7, 29,  1, 8, 6},
	{CONFIG_BASE+CONFIG_DRAM_CONFIG7, 16,  6, 8, 0}
};

static void Databahn_ConfigOTPParam(void)
{
	unsigned char otp_data[OTP_DRAM_PARAM_LEN];
	int i = 0;
	int otp_start_addr = 0x1B9;

	/* 0x1B9 ~ 0x1BF and 0x1CC ~ 0x1CD */
	for (i = 0; i < OTP_DRAM_PARAM_LEN; i++) {
		otp_data[i] = otp_read_simple(otp_start_addr);
		otp_start_addr++;
		if (otp_start_addr == 0x1C0)
			otp_start_addr = 0x1CC;
	}

	if ((otp_data[0] & 1) == 1 &&
	    ((otp_data[0] >> 1) & 0xF) == 0) {
		for (i = 0; i < sizeof(param_mode0) / sizeof(struct otp_dram_param); i++) {
			unsigned char val = 0;
			if (param_mode0[i].otp_data_byte_index > OTP_DRAM_PARAM_LEN - 1) {
				serial_put_no_mmu('e');
				while (1);
			}
			val = otp_data[param_mode0[i].otp_data_byte_index] >> param_mode0[i].otp_data_bit_offset;
			val &= (1 << param_mode0[i].reg_bit_width) - 1;
			SetRegisterField(param_mode0[i].reg_addr, param_mode0[i].reg_offset, \
					 param_mode0[i].reg_bit_width, val);
		}
		/* pvref_set */
		SetRegisterField(CONFIG_BASE+CONFIG_DRAM_CONFIG2, 16, 4, (otp_data[2] & 0x80) == 0x80 ? 0xa : 0x0);
	}
}
#endif

void Databahn_Config(void)
{
	Databahn_SetParameters(param_table, sizeof(param_table) / sizeof(struct reg_param));

#ifdef DDR_SIP
	Databahn_ConfigOTPParam();
#endif
	// Databahn start enable
	SetRegisterField(Databahn_Reg(DATABAHN_REG_START_ADDR), DATABAHN_REG_START_OFFSET, DATABAHN_REG_START_WIDTH, 1);
}

unsigned int Databahn_GetParameter(unsigned int reg, unsigned int offset, unsigned int width)
{
	return GetRegisterField(Databahn_Reg(reg), offset, width);
}

unsigned int Databahn_GetIntStatus(void)
{
	return Databahn_GetParameter(DATABAHN_REG_INT_STATUS_ADDR, DATABAHN_REG_INT_STATUS_OFFSET, DATABAHN_REG_INT_STATUS_WIDTH);
}

unsigned int Databahn_isReady(void)
{
	return (Databahn_GetIntStatus() & 0x20) ? 1 : 0;
}

static void wait_rng_ready(void)
{
	*(volatile unsigned int*)(CONFIG_BASE + CONFIG_RNG_CTRL) |= 1;
	while (!((*(volatile unsigned int*)(CONFIG_BASE + CONFIG_RNG_CTRL)) & 0x2));
	*(volatile unsigned int*)(CONFIG_BASE + CONFIG_RNG_CTRL) &= ~1;
}

void gx_setup_sdram_controller(void)
{
#ifdef CONFIG_FPGA_BOARD
	serial_put_no_mmu('N');
	return;
#endif
	Databahn_Init();
	serial_put_no_mmu('N');

//#ifdef ENABLE_SECURE_ALIGN
	if ((*(volatile unsigned int*)(REG_BASE_OTP+0x0C)) & (0x1 << 10))//bit 10 to indicate ddr_content_scramble_enable
	{
		volatile unsigned int i = 0x10000;
		*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_CTRL) = 1;
		while(*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_CTRL) != 0x02);
		*(volatile unsigned int *)(CONFIG_BASE + CONFIG_RNG_DATA);
		while (i--) //delay 30 ms
			__asm__ volatile ("nop");
	}
//#endif

}

