#include "stdio.h"
#include "version_autogenerated.h"
#include "gxhwlib_registers.h"

#define GX3113C_CHIP_ID0          (0x0030a560)
#define GX3113C_CHIP_ID1          (0x0030a564)

#define BETWEEN(value, min, max)  ((unsigned int)value < (unsigned int)min ? 0 : \
                ((unsigned int)value > (unsigned int)max ? 0 : 1))

static int gx3113c_otp_read_register_one_byte(unsigned int start_addr, unsigned char *data)
{
    const unsigned int *id   = (const unsigned int *)GX3113C_CHIP_ID0;
    unsigned int number = 0;
    unsigned int fir, sec;

	// public id addr
    if (BETWEEN(start_addr, 0x368, 0x36f)) {
        number = (unsigned int)(start_addr - 0x368);
        fir = number / 4;
        sec = number % 4;
        *data = ((*(id + fir)) >> (sec * 8)) & 0xff;
    } else
        return 0;

    return 1;
}

int gx_otp_read(unsigned int start_addr, int rd_num, unsigned char *data)
{
	int i;
	unsigned int otp_con_reg;

#ifdef ENABLE_BOOT_TOOL
	// do nothing
#else
	GX_OTP_CFG_REG |= 2;  //config otp fre to 210M
#endif

	start_addr  = start_addr << 3;
	while (!(GX_OTP_STA_REG & (1<<10))); // check if OTP Controller is ready
	otp_con_reg = 0x43000000 | (0x1fff & start_addr);  // start address
	for (i = 0; i < rd_num; i++)
	{
		if (gx3113c_otp_read_register_one_byte(0x7ff & ((start_addr >> 3) + i), &data[i])) {
			otp_con_reg = 0x43000000 | (0x1fff & (start_addr + ((i + 1) << 3)));
			continue;
		}

		while (GX_OTP_STA_REG & 0x100); // check if OTP Controller is busy now; 1 for busy
		GX_OTP_CON_REG = otp_con_reg | (0x1 << 14); // set READEN
		GX_OTP_CON_REG = otp_con_reg; // clear READEN
		while (!(GX_OTP_STA_REG & 0x200)); // chekc if OTP data is ready
		data[i] = (unsigned char)(GX_OTP_STA_REG & 0xFF);
		otp_con_reg = otp_con_reg + 8;
	}

	return rd_num;
}

#ifdef CONFIG_ENABLE_OTP_FULLFUNCTION
int gx_otp_write(unsigned int start_addr, int wr_num, unsigned char *data)
{
	int i;
	unsigned int otp_con_reg;

	start_addr  = start_addr << 3;
	while (!(GX_OTP_STA_REG & (1<<10))); // check if OTP Controller is ready
	otp_con_reg = 0x43000000 | (0x1fff & start_addr);  // start address
	for (i = 0; i < wr_num; i++)
	{
		otp_con_reg &= ~(0xff<<16);
		otp_con_reg |= data[i] << 16;
		while (GX_OTP_STA_REG & 0x100); // check if OTP Controller is busy now; 1 for busy
		GX_OTP_CON_REG = otp_con_reg | (0x1 << 15); // set BURN
		GX_OTP_CON_REG = otp_con_reg;         // clear READEN
		otp_con_reg = otp_con_reg + 8;
	}

	return wr_num;
}
#endif
